export const documentBaseType = {
	GLJournal: 'GLJ',
	GLDocument: 'GLD',
	APInvoice: 'API',
	APPayment: 'APP',
	ARInvoice: 'ARI',
	ARReceipt: 'ARR',
	SalesOrder: 'SOO',
	ARProFormaInvoice: 'ARF',
	MaterialDelivery: 'MMS',
	MaterialReceipt: 'MMR',
	MaterialMovement: 'MMM',
	PurchaseOrder: 'POO',
	PurchaseRequisition: 'POR',
	MaterialPhysicalInventory: 'MMI',
	APCreditMemo: 'APC',
	ARCreditMemo: 'ARC',
	BankStatement: 'CMB',
	CashJournal: 'CMC',
	PaymentAllocation: 'CMA',
	MaterialProduction: 'MMP',
	MatchInvoice: 'MXI',
	MatchPO: 'MXP',
	ProjectIssue: 'PJI',
	MaintenanceOrder: 'MOF',
	ManufacturingOrder: 'MOP',
	QualityOrder: 'MQO',
	Payroll: 'HRP',
	DistributionOrder: 'DOO',
	ManufacturingCostCollector: 'MCC',
	FixedAssetsAddition: 'FAA',
	FixedAssetsDisposal: 'FAD',
	FixedAssetsDepreciation: 'FDP',
} as const;

export type DocumentBaseType = typeof documentBaseType[keyof typeof documentBaseType];
