package org.bandahealth.idempiere.graphql;

import graphql.kickstart.tools.SchemaParserBuilder;

public class BandaSchemaFileComposer {
	public static void addAll(SchemaParserBuilder builder) {
		builder
				.files(
						"WEB-INF/resources/Authentication.graphqls",
						"WEB-INF/resources/ForeignEntity.graphqls",
						"WEB-INF/resources/InventoryTransaction.graphqls",
//						"WEB-INF/resources/MAccessLog.graphqls",
						"WEB-INF/resources/MAccount.graphqls",
						"WEB-INF/resources/MAcctProcessor.graphqls",
//						"WEB-INF/resources/MAcctProcessorLog.graphqls",
						"WEB-INF/resources/MAcctSchema.graphqls",
//						"WEB-INF/resources/MAcctSchemaDefault.graphqls",
//						"WEB-INF/resources/MAcctSchemaElement.graphqls",
//						"WEB-INF/resources/MAcctSchemaGL.graphqls",
//						"WEB-INF/resources/MAchievement.graphqls",
//						"WEB-INF/resources/MActivity.graphqls",
//						"WEB-INF/resources/MAddressTransaction.graphqls",
//						"WEB-INF/resources/MAddressValidation.graphqls",
//						"WEB-INF/resources/MAging.graphqls",
						"WEB-INF/resources/MAlert.graphqls",
						"WEB-INF/resources/MAlertProcessor.graphqls",
//						"WEB-INF/resources/MAlertProcessorLog.graphqls",
//						"WEB-INF/resources/MAlertRecipient.graphqls",
//						"WEB-INF/resources/MAlertRule.graphqls",
						"WEB-INF/resources/MAllocationHdr.graphqls",
//						"WEB-INF/resources/MAllocationLine.graphqls",
//						"WEB-INF/resources/MArchive.graphqls",
//						"WEB-INF/resources/MAsset.graphqls",
//						"WEB-INF/resources/MAssetAcct.graphqls",
//						"WEB-INF/resources/MAssetAddition.graphqls",
//						"WEB-INF/resources/MAssetChange.graphqls",
//						"WEB-INF/resources/MAssetClass.graphqls",
//						"WEB-INF/resources/MAssetDelivery.graphqls",
//						"WEB-INF/resources/MAssetDisposed.graphqls",
//						"WEB-INF/resources/MAssetGroup.graphqls",
//						"WEB-INF/resources/MAssetGroupAcct.graphqls",
//						"WEB-INF/resources/MAssetProduct.graphqls",
//						"WEB-INF/resources/MAssetReval.graphqls",
//						"WEB-INF/resources/MAssetTransfer.graphqls",
//						"WEB-INF/resources/MAssetType.graphqls",
//						"WEB-INF/resources/MAssetUse.graphqls",
//						"WEB-INF/resources/MAttachment.graphqls",
//						"WEB-INF/resources/MAttachmentNote.graphqls",
						"WEB-INF/resources/MAttribute.graphqls",
//						"WEB-INF/resources/MAttributeInstance.graphqls",
						"WEB-INF/resources/MAttributeSet.graphqls",
//						"WEB-INF/resources/MAttributeSetExclude.graphqls",
						"WEB-INF/resources/MAttributeSetInstance.graphqls",
//						"WEB-INF/resources/MAttributeUse.graphqls",
//						"WEB-INF/resources/MAttributeValue.graphqls",
//						"WEB-INF/resources/MAuthorizationAccount.graphqls",
//						"WEB-INF/resources/MAuthorizationCredential.graphqls",
//						"WEB-INF/resources/MAuthorizationProvider.graphqls",
//						"WEB-INF/resources/MBank.graphqls",
//						"WEB-INF/resources/MBankAccount.graphqls",
//						"WEB-INF/resources/MBankAccountProcessor.graphqls",
						"WEB-INF/resources/MBankStatement.graphqls",
//						"WEB-INF/resources/MBankStatementLine.graphqls",
//						"WEB-INF/resources/MBankStatementLoader.graphqls",
//						"WEB-INF/resources/MBankStatementMatcher.graphqls",
//						"WEB-INF/resources/MBankTransfer.graphqls",
//						"WEB-INF/resources/MBHBPGeneralPayerInfo.graphqls",
						"WEB-INF/resources/MBHBPPayerInfo.graphqls",
//						"WEB-INF/resources/MBHBPSpecificPayerInfo.graphqls",
//						"WEB-INF/resources/MBHCodedDiagnosis.graphqls",
//						"WEB-INF/resources/MBHCodedDiagnosisMapping.graphqls",
						"WEB-INF/resources/MBHConcept.graphqls",
						"WEB-INF/resources/MBHConceptMapping.graphqls",
//						"WEB-INF/resources/MBHDefaultDocActionAccess.graphqls",
//						"WEB-INF/resources/MBHDefaultIncludedRole.graphqls",
						"WEB-INF/resources/MBHEncounter.graphqls",
//						"WEB-INF/resources/MBHEncounterDiagnosis.graphqls",
//						"WEB-INF/resources/MBHEncounterTypeWindow.graphqls",
//						"WEB-INF/resources/MBHObservation.graphqls",
						"WEB-INF/resources/MBHPayerInfoFld.graphqls",
						"WEB-INF/resources/MBHPayerInfoFldSug.graphqls",
//						"WEB-INF/resources/MBHPayerInfoFldVal.graphqls",
//						"WEB-INF/resources/MBHPayerInfoFldValSug.graphqls",
//						"WEB-INF/resources/MBHPaymentRef.graphqls",
//						"WEB-INF/resources/MBHPaymentRefBankAccount.graphqls",
//						"WEB-INF/resources/MBHProductCategoryDefault.graphqls",
//						"WEB-INF/resources/MBHRoleWarehouseAccess.graphqls",
						"WEB-INF/resources/MBHVisit.graphqls",
//						"WEB-INF/resources/MBHVoidedReason.graphqls",
						"WEB-INF/resources/MBPartner.graphqls",
//						"WEB-INF/resources/MBPartnerInfo.graphqls",
//						"WEB-INF/resources/MBPartnerLocation.graphqls",
//						"WEB-INF/resources/MBPartnerProduct.graphqls",
//						"WEB-INF/resources/MBPBankAccount.graphqls",
						"WEB-INF/resources/MBPGroup.graphqls",
//						"WEB-INF/resources/MCalendar.graphqls",
//						"WEB-INF/resources/MCampaign.graphqls",
//						"WEB-INF/resources/MCash.graphqls",
//						"WEB-INF/resources/MCashBook.graphqls",
//						"WEB-INF/resources/MCashLine.graphqls",
						"WEB-INF/resources/MCashPlan.graphqls",
//						"WEB-INF/resources/MCashPlanLine.graphqls",
//						"WEB-INF/resources/MChangeLog.graphqls",
//						"WEB-INF/resources/MChangeNotice.graphqls",
//						"WEB-INF/resources/MChangeRequest.graphqls",
						"WEB-INF/resources/MCharge.graphqls",
//						"WEB-INF/resources/MChargeType.graphqls",
						"WEB-INF/resources/MChart.graphqls",
//						"WEB-INF/resources/MChartDatasource.graphqls",
						"WEB-INF/resources/MChat.graphqls",
//						"WEB-INF/resources/MChatEntry.graphqls",
//						"WEB-INF/resources/MChatType.graphqls",
//						"WEB-INF/resources/MCity.graphqls",
						"WEB-INF/resources/MClient.graphqls",
//						"WEB-INF/resources/MClientInfo.graphqls",
//						"WEB-INF/resources/MClientShare.graphqls",
//						"WEB-INF/resources/MColor.graphqls",
//						"WEB-INF/resources/MColorSchema.graphqls",
//						"WEB-INF/resources/MColumn.graphqls",
//						"WEB-INF/resources/MColumnAccess.graphqls",
						"WEB-INF/resources/MCommission.graphqls",
						"WEB-INF/resources/MCommissionAmt.graphqls",
//						"WEB-INF/resources/MCommissionDetail.graphqls",
//						"WEB-INF/resources/MCommissionLine.graphqls",
						"WEB-INF/resources/MCommissionRun.graphqls",
//						"WEB-INF/resources/MContactInterest.graphqls",
//						"WEB-INF/resources/MConversionRate.graphqls",
//						"WEB-INF/resources/MConversionType.graphqls",
//						"WEB-INF/resources/MCost.graphqls",
//						"WEB-INF/resources/MCostDetail.graphqls",
//						"WEB-INF/resources/MCostElement.graphqls",
//						"WEB-INF/resources/MCostQueue.graphqls",
//						"WEB-INF/resources/MCostType.graphqls",
						"WEB-INF/resources/MCountry.graphqls",
//						"WEB-INF/resources/MCountryGroup.graphqls",
//						"WEB-INF/resources/MCountryGroupCountry.graphqls",
//						"WEB-INF/resources/MCtxHelp.graphqls",
//						"WEB-INF/resources/MCtxHelpMsg.graphqls",
//						"WEB-INF/resources/MCtxHelpSuggestion.graphqls",
//						"WEB-INF/resources/MCurrency.graphqls",
//						"WEB-INF/resources/MCurrencyAcct.graphqls",
//						"WEB-INF/resources/MDashboardContent.graphqls",
//						"WEB-INF/resources/MDashboardContentAccess.graphqls",
//						"WEB-INF/resources/MDashboardPreference.graphqls",
						"WEB-INF/resources/MDDOrder.graphqls",
//						"WEB-INF/resources/MDDOrderLine.graphqls",
						"WEB-INF/resources/MDepositBatch.graphqls",
//						"WEB-INF/resources/MDepositBatchLine.graphqls",
//						"WEB-INF/resources/MDepreciation.graphqls",
//						"WEB-INF/resources/MDepreciationBuild.graphqls",
//						"WEB-INF/resources/MDepreciationConvention.graphqls",
//						"WEB-INF/resources/MDepreciationEntry.graphqls",
//						"WEB-INF/resources/MDepreciationExp.graphqls",
//						"WEB-INF/resources/MDepreciationMethod.graphqls",
//						"WEB-INF/resources/MDepreciationWorkfile.graphqls",
						"WEB-INF/resources/MDiscountSchema.graphqls",
//						"WEB-INF/resources/MDiscountSchemaBreak.graphqls",
//						"WEB-INF/resources/MDiscountSchemaLine.graphqls",
						"WEB-INF/resources/MDistribution.graphqls",
//						"WEB-INF/resources/MDistributionLine.graphqls",
						"WEB-INF/resources/MDistributionList.graphqls",
//						"WEB-INF/resources/MDistributionListLine.graphqls",
						"WEB-INF/resources/MDistributionRun.graphqls",
//						"WEB-INF/resources/MDistributionRunDetail.graphqls",
//						"WEB-INF/resources/MDistributionRunLine.graphqls",
//						"WEB-INF/resources/MDocType.graphqls",
//						"WEB-INF/resources/MDocTypeCounter.graphqls",
//						"WEB-INF/resources/MDocumentStatus.graphqls",
//						"WEB-INF/resources/MDunning.graphqls",
//						"WEB-INF/resources/MDunningLevel.graphqls",
						"WEB-INF/resources/MDunningRun.graphqls",
						"WEB-INF/resources/MDunningRunEntry.graphqls",
//						"WEB-INF/resources/MDunningRunLine.graphqls",
//						"WEB-INF/resources/MElement.graphqls",
//						"WEB-INF/resources/MElementValue.graphqls",
//						"WEB-INF/resources/MEntityType.graphqls",
//						"WEB-INF/resources/MExpenseType.graphqls",
						"WEB-INF/resources/MEXPFormat.graphqls",
//						"WEB-INF/resources/MEXPFormatLine.graphqls",
						"WEB-INF/resources/MEXPProcessor.graphqls",
//						"WEB-INF/resources/MEXPProcessorParameter.graphqls",
//						"WEB-INF/resources/MEXPProcessorType.graphqls",
//						"WEB-INF/resources/MFactAcct.graphqls",
//						"WEB-INF/resources/MFactReconciliation.graphqls",
//						"WEB-INF/resources/MField.graphqls",
//						"WEB-INF/resources/MFieldGroup.graphqls",
//						"WEB-INF/resources/MFieldSuggestion.graphqls",
//						"WEB-INF/resources/MForecast.graphqls",
//						"WEB-INF/resources/MForecastLine.graphqls",
//						"WEB-INF/resources/MForm.graphqls",
//						"WEB-INF/resources/MFormAccess.graphqls",
//						"WEB-INF/resources/MFreight.graphqls",
//						"WEB-INF/resources/MFreightCategory.graphqls",
//						"WEB-INF/resources/MGLCategory.graphqls",
						"WEB-INF/resources/MGoal.graphqls",
//						"WEB-INF/resources/MGoalRestriction.graphqls",
//						"WEB-INF/resources/MGroup.graphqls",
//						"WEB-INF/resources/MHierarchy.graphqls",
//						"WEB-INF/resources/MHouseKeeping.graphqls",
//						"WEB-INF/resources/MIFixedAsset.graphqls",
//						"WEB-INF/resources/MImage.graphqls",
//						"WEB-INF/resources/MImportTemplate.graphqls",
//						"WEB-INF/resources/MIndexColumn.graphqls",
//						"WEB-INF/resources/MInfoColumn.graphqls",
						"WEB-INF/resources/MInfoWindow.graphqls",
//						"WEB-INF/resources/MInfoWindowAccess.graphqls",
						"WEB-INF/resources/MInOut.graphqls",
						"WEB-INF/resources/MInOutConfirm.graphqls",
						"WEB-INF/resources/MInOutLine.graphqls",
//						"WEB-INF/resources/MInOutLineConfirm.graphqls",
//						"WEB-INF/resources/MInOutLineMA.graphqls",
//						"WEB-INF/resources/MInterestArea.graphqls",
						"WEB-INF/resources/MInventory.graphqls",
						"WEB-INF/resources/MInventoryLine.graphqls",
//						"WEB-INF/resources/MInventoryLineMA.graphqls",
						"WEB-INF/resources/MInvoice.graphqls",
						"WEB-INF/resources/MInvoiceBatch.graphqls",
//						"WEB-INF/resources/MInvoiceBatchLine.graphqls",
						"WEB-INF/resources/MInvoiceLine.graphqls",
//						"WEB-INF/resources/MInvoicePaySchedule.graphqls",
//						"WEB-INF/resources/MInvoiceSchedule.graphqls",
//						"WEB-INF/resources/MInvoiceTax.graphqls",
//						"WEB-INF/resources/MIssue.graphqls",
//						"WEB-INF/resources/MIssueProject.graphqls",
//						"WEB-INF/resources/MIssueSystem.graphqls",
//						"WEB-INF/resources/MIssueUser.graphqls",
						"WEB-INF/resources/MJournal.graphqls",
						"WEB-INF/resources/MJournalBatch.graphqls",
						"WEB-INF/resources/MJournalGenerator.graphqls",
						"WEB-INF/resources/MJournalGeneratorLine.graphqls",
//						"WEB-INF/resources/MJournalGeneratorSource.graphqls",
//						"WEB-INF/resources/MJournalLine.graphqls",
//						"WEB-INF/resources/MLandedCost.graphqls",
//						"WEB-INF/resources/MLandedCostAllocation.graphqls",
//						"WEB-INF/resources/MLanguage.graphqls",
//						"WEB-INF/resources/MLdapAccess.graphqls",
						"WEB-INF/resources/MLdapProcessor.graphqls",
//						"WEB-INF/resources/MLdapProcessorLog.graphqls",
//						"WEB-INF/resources/MLocation.graphqls",
//						"WEB-INF/resources/MLocator.graphqls",
//						"WEB-INF/resources/MLocatorType.graphqls",
//						"WEB-INF/resources/MLot.graphqls",
//						"WEB-INF/resources/MLotCtl.graphqls",
//						"WEB-INF/resources/MLotCtlExclude.graphqls",
//						"WEB-INF/resources/MMailText.graphqls",
//						"WEB-INF/resources/MMatchInv.graphqls",
//						"WEB-INF/resources/MMatchPO.graphqls",
//						"WEB-INF/resources/MMeasure.graphqls",
//						"WEB-INF/resources/MMeasureCalc.graphqls",
						"WEB-INF/resources/MMenu.graphqls",
//						"WEB-INF/resources/MMessage.graphqls",
						"WEB-INF/resources/MMovement.graphqls",
						"WEB-INF/resources/MMovementConfirm.graphqls",
						"WEB-INF/resources/MMovementLine.graphqls",
//						"WEB-INF/resources/MMovementLineConfirm.graphqls",
//						"WEB-INF/resources/MMovementLineMA.graphqls",
//						"WEB-INF/resources/MNote.graphqls",
//						"WEB-INF/resources/MOnlineTrxHistory.graphqls",
//						"WEB-INF/resources/MOpportunity.graphqls",
						"WEB-INF/resources/MOrder.graphqls",
						"WEB-INF/resources/MOrderLandedCost.graphqls",
//						"WEB-INF/resources/MOrderLandedCostAllocation.graphqls",
						"WEB-INF/resources/MOrderLine.graphqls",
//						"WEB-INF/resources/MOrderPaySchedule.graphqls",
//						"WEB-INF/resources/MOrderTax.graphqls",
						"WEB-INF/resources/MOrg.graphqls",
//						"WEB-INF/resources/MOrgInfo.graphqls",
//						"WEB-INF/resources/MPackage.graphqls",
						"WEB-INF/resources/MPackageExp.graphqls",
//						"WEB-INF/resources/MPackageExpDetail.graphqls",
//						"WEB-INF/resources/MPackageLine.graphqls",
//						"WEB-INF/resources/MPackageMPS.graphqls",
//						"WEB-INF/resources/MPasswordHistory.graphqls",
//						"WEB-INF/resources/MPasswordRule.graphqls",
						"WEB-INF/resources/MPayment.graphqls",
//						"WEB-INF/resources/MPaymentAllocate.graphqls",
//						"WEB-INF/resources/MPaymentBatch.graphqls",
//						"WEB-INF/resources/MPaymentProcessor.graphqls",
						"WEB-INF/resources/MPaymentTerm.graphqls",
//						"WEB-INF/resources/MPaymentTransaction.graphqls",
//						"WEB-INF/resources/MPaySchedule.graphqls",
						"WEB-INF/resources/MPaySelection.graphqls",
						"WEB-INF/resources/MPaySelectionCheck.graphqls",
//						"WEB-INF/resources/MPaySelectionLine.graphqls",
						"WEB-INF/resources/MPeriod.graphqls",
//						"WEB-INF/resources/MPeriodControl.graphqls",
						"WEB-INF/resources/MPInstance.graphqls",
//						"WEB-INF/resources/MPInstancePara.graphqls",
//						"WEB-INF/resources/MPOS.graphqls",
//						"WEB-INF/resources/MPOSKey.graphqls",
						"WEB-INF/resources/MPOSKeyLayout.graphqls",
//						"WEB-INF/resources/MPOSTerminal.graphqls",
//						"WEB-INF/resources/MPostIt.graphqls",
						"WEB-INF/resources/MPPProductBOM.graphqls",
//						"WEB-INF/resources/MPPProductBOMLine.graphqls",
//						"WEB-INF/resources/MPPProductPlanning.graphqls",
//						"WEB-INF/resources/MPreference.graphqls",
						"WEB-INF/resources/MPriceList.graphqls",
						"WEB-INF/resources/MPriceListVersion.graphqls",
//						"WEB-INF/resources/MPrivateAccess.graphqls",
						"WEB-INF/resources/MProcess.graphqls",
//						"WEB-INF/resources/MProcessAccess.graphqls",
//						"WEB-INF/resources/MProcessPara.graphqls",
						"WEB-INF/resources/MProduct.graphqls",
//						"WEB-INF/resources/MProductBOM.graphqls",
//						"WEB-INF/resources/MProductCategory.graphqls",
//						"WEB-INF/resources/MProductCategoryAcct.graphqls",
//						"WEB-INF/resources/MProductDownload.graphqls",
						"WEB-INF/resources/MProduction.graphqls",
						"WEB-INF/resources/MProductionLine.graphqls",
//						"WEB-INF/resources/MProductionLineMA.graphqls",
						"WEB-INF/resources/MProductionPlan.graphqls",
//						"WEB-INF/resources/MProductPO.graphqls",
//						"WEB-INF/resources/MProductPrice.graphqls",
						"WEB-INF/resources/MProject.graphqls",
//						"WEB-INF/resources/MProjectIssue.graphqls",
//						"WEB-INF/resources/MProjectLine.graphqls",
						"WEB-INF/resources/MProjectPhase.graphqls",
//						"WEB-INF/resources/MProjectTask.graphqls",
						"WEB-INF/resources/MProjectType.graphqls",
						"WEB-INF/resources/MProjectTypePhase.graphqls",
//						"WEB-INF/resources/MProjectTypeTask.graphqls",
//						"WEB-INF/resources/MQualityTest.graphqls",
//						"WEB-INF/resources/MQualityTestResult.graphqls",
//						"WEB-INF/resources/MRecentItem.graphqls",
//						"WEB-INF/resources/MRecordAccess.graphqls",
//						"WEB-INF/resources/MRecurring.graphqls",
//						"WEB-INF/resources/MRecurringRun.graphqls",
						"WEB-INF/resources/MReference.graphqls",
						"WEB-INF/resources/MRefList.graphqls",
//						"WEB-INF/resources/MRefTable.graphqls",
//						"WEB-INF/resources/MRegion.graphqls",
//						"WEB-INF/resources/MRegistration.graphqls",
//						"WEB-INF/resources/MRegistrationAttribute.graphqls",
//						"WEB-INF/resources/MRegistrationValue.graphqls",
//						"WEB-INF/resources/MReplenish.graphqls",
//						"WEB-INF/resources/MReplication.graphqls",
//						"WEB-INF/resources/MReplicationLog.graphqls",
//						"WEB-INF/resources/MReplicationRun.graphqls",
						"WEB-INF/resources/MReplicationStrategy.graphqls",
//						"WEB-INF/resources/MReportCube.graphqls",
//						"WEB-INF/resources/MReportView.graphqls",
//						"WEB-INF/resources/MRequest.graphqls",
//						"WEB-INF/resources/MRequestAction.graphqls",
//						"WEB-INF/resources/MRequestCategory.graphqls",
						"WEB-INF/resources/MRequestProcessor.graphqls",
//						"WEB-INF/resources/MRequestProcessorLog.graphqls",
//						"WEB-INF/resources/MRequestProcessorRoute.graphqls",
//						"WEB-INF/resources/MRequestType.graphqls",
//						"WEB-INF/resources/MRequestUpdate.graphqls",
						"WEB-INF/resources/MRequisition.graphqls",
//						"WEB-INF/resources/MRequisitionLine.graphqls",
//						"WEB-INF/resources/MResolution.graphqls",
//						"WEB-INF/resources/MResource.graphqls",
//						"WEB-INF/resources/MResourceAssignment.graphqls",
//						"WEB-INF/resources/MResourceType.graphqls",
//						"WEB-INF/resources/MResourceUnAvailable.graphqls",
//						"WEB-INF/resources/MRevenueRecognition.graphqls",
//						"WEB-INF/resources/MRevenueRecognitionPlan.graphqls",
//						"WEB-INF/resources/MRevenueRecognitionRun.graphqls",
//						"WEB-INF/resources/MRevenueRecogService.graphqls",
						"WEB-INF/resources/MRfQ.graphqls",
						"WEB-INF/resources/MRfQLine.graphqls",
						"WEB-INF/resources/MRfQLineQty.graphqls",
						"WEB-INF/resources/MRfQResponse.graphqls",
						"WEB-INF/resources/MRfQResponseLine.graphqls",
//						"WEB-INF/resources/MRfQResponseLineQty.graphqls",
						"WEB-INF/resources/MRfQTopic.graphqls",
						"WEB-INF/resources/MRfQTopicSubscriber.graphqls",
//						"WEB-INF/resources/MRfQTopicSubscriberOnly.graphqls",
						"WEB-INF/resources/MRMA.graphqls",
						"WEB-INF/resources/MRMALine.graphqls",
//						"WEB-INF/resources/MRMATax.graphqls",
						"WEB-INF/resources/MRole.graphqls",
//						"WEB-INF/resources/MRoleIncluded.graphqls",
//						"WEB-INF/resources/MRoleMenu.graphqls",
//						"WEB-INF/resources/MRoleOrgAccess.graphqls",
//						"WEB-INF/resources/MRule.graphqls",
//						"WEB-INF/resources/MSalesRegion.graphqls",
//						"WEB-INF/resources/MSchedule.graphqls",
						"WEB-INF/resources/MScheduler.graphqls",
//						"WEB-INF/resources/MSchedulerLog.graphqls",
//						"WEB-INF/resources/MSchedulerPara.graphqls",
//						"WEB-INF/resources/MSchedulerRecipient.graphqls",
//						"WEB-INF/resources/MSearchDefinition.graphqls",
//						"WEB-INF/resources/MSequence.graphqls",
						"WEB-INF/resources/MSerNoCtl.graphqls",
//						"WEB-INF/resources/MSerNoCtlExclude.graphqls",
//						"WEB-INF/resources/MSession.graphqls",
//						"WEB-INF/resources/MShipper.graphqls",
//						"WEB-INF/resources/MShipperLabels.graphqls",
//						"WEB-INF/resources/MShipperPackaging.graphqls",
//						"WEB-INF/resources/MShipperPickupTypes.graphqls",
//						"WEB-INF/resources/MShippingProcessor.graphqls",
						"WEB-INF/resources/MShippingTransaction.graphqls",
//						"WEB-INF/resources/MShippingTransactionLine.graphqls",
//						"WEB-INF/resources/MSLACriteria.graphqls",
//						"WEB-INF/resources/MSLAGoal.graphqls",
//						"WEB-INF/resources/MSLAMeasure.graphqls",
//						"WEB-INF/resources/MStatus.graphqls",
						"WEB-INF/resources/MStatusCategory.graphqls",
//						"WEB-INF/resources/MStatusLine.graphqls",
//						"WEB-INF/resources/MStatusLineUsedIn.graphqls",
//						"WEB-INF/resources/MStorageOnHand.graphqls",
//						"WEB-INF/resources/MStorageProvider.graphqls",
//						"WEB-INF/resources/MStorageReservation.graphqls",
//						"WEB-INF/resources/MStyle.graphqls",
//						"WEB-INF/resources/MStyleLine.graphqls",
//						"WEB-INF/resources/MSysConfig.graphqls",
//						"WEB-INF/resources/MSystem.graphqls",
						"WEB-INF/resources/MTab.graphqls",
						"WEB-INF/resources/MTable.graphqls",
//						"WEB-INF/resources/MTableAccess.graphqls",
						"WEB-INF/resources/MTableIndex.graphqls",
//						"WEB-INF/resources/MTableScriptValidator.graphqls",
//						"WEB-INF/resources/MTask.graphqls",
						"WEB-INF/resources/MTax.graphqls",
//						"WEB-INF/resources/MTaxCategory.graphqls",
//						"WEB-INF/resources/MTaxDeclaration.graphqls",
//						"WEB-INF/resources/MTaxDeclarationAcct.graphqls",
//						"WEB-INF/resources/MTaxDeclarationLine.graphqls",
//						"WEB-INF/resources/MTaxPostal.graphqls",
//						"WEB-INF/resources/MTaxProvider.graphqls",
//						"WEB-INF/resources/MTest.graphqls",
						"WEB-INF/resources/MTimeExpense.graphqls",
//						"WEB-INF/resources/MTimeExpenseLine.graphqls",
//						"WEB-INF/resources/MToolBarButton.graphqls",
//						"WEB-INF/resources/MToolBarButtonRestrict.graphqls",
//						"WEB-INF/resources/MTransaction.graphqls",
//						"WEB-INF/resources/MTree.graphqls",
//						"WEB-INF/resources/MTreeFavorite.graphqls",
//						"WEB-INF/resources/MTreeFavoriteNode.graphqls",
//						"WEB-INF/resources/MTree_Node.graphqls",
//						"WEB-INF/resources/MTree_NodeBP.graphqls",
//						"WEB-INF/resources/MTree_NodeCMC.graphqls",
//						"WEB-INF/resources/MTree_NodeCMS.graphqls",
						"WEB-INF/resources/MTree_NodeMM.graphqls",
//						"WEB-INF/resources/MTree_NodePR.graphqls",
						"WEB-INF/resources/MUOM.graphqls",
//						"WEB-INF/resources/MUOMConversion.graphqls",
						"WEB-INF/resources/MUser.graphqls",
//						"WEB-INF/resources/MUserBPAccess.graphqls",
//						"WEB-INF/resources/MUserDefField.graphqls",
//						"WEB-INF/resources/MUserDefInfo.graphqls",
//						"WEB-INF/resources/MUserDefInfoColumn.graphqls",
//						"WEB-INF/resources/MUserDefInfoRelated.graphqls",
//						"WEB-INF/resources/MUserDefProc.graphqls",
//						"WEB-INF/resources/MUserDefProcParameter.graphqls",
//						"WEB-INF/resources/MUserDefTab.graphqls",
//						"WEB-INF/resources/MUserDefWin.graphqls",
//						"WEB-INF/resources/MUserMail.graphqls",
//						"WEB-INF/resources/MUserOrgAccess.graphqls",
//						"WEB-INF/resources/MUserQuery.graphqls",
//						"WEB-INF/resources/MUserRoles.graphqls",
//						"WEB-INF/resources/MValRule.graphqls",
//						"WEB-INF/resources/MViewColumn.graphqls",
						"WEB-INF/resources/MViewComponent.graphqls",
						"WEB-INF/resources/MWarehouse.graphqls",
//						"WEB-INF/resources/MWarehousePrice.graphqls",
//						"WEB-INF/resources/MWebMenu.graphqls",
//						"WEB-INF/resources/MWebProperties.graphqls",
//						"WEB-INF/resources/MWFActivityApprover.graphqls",
						"WEB-INF/resources/MWindow.graphqls",
//						"WEB-INF/resources/MWindowAccess.graphqls",
//						"WEB-INF/resources/MWithholding.graphqls",
//						"WEB-INF/resources/MXIFAJournal.graphqls",
//						"WEB-INF/resources/MYear.graphqls",
//						"WEB-INF/resources/MZoomCondition.graphqls",
//						"WEB-INF/resources/M_Element.graphqls",
//						"WEB-INF/resources/M_Registration.graphqls",
						"WEB-INF/resources/PagingInfo.graphqls",
						"WEB-INF/resources/ProcessInfoParameter.graphqls",
						"WEB-INF/resources/ReportOutput.graphqls",
						"WEB-INF/resources/schema.graphqls",
						"WEB-INF/resources/X_AD_AccessLog.graphqls",
						"WEB-INF/resources/X_AD_Alert.graphqls",
						"WEB-INF/resources/X_AD_AlertProcessor.graphqls",
						"WEB-INF/resources/X_AD_AlertProcessorLog.graphqls",
						"WEB-INF/resources/X_AD_AlertRecipient.graphqls",
						"WEB-INF/resources/X_AD_AlertRule.graphqls",
						"WEB-INF/resources/X_AD_AllClients_V.graphqls",
						"WEB-INF/resources/X_AD_AllUsers_V.graphqls",
						"WEB-INF/resources/X_AD_Archive.graphqls",
						"WEB-INF/resources/X_AD_Attachment.graphqls",
						"WEB-INF/resources/X_AD_AttachmentNote.graphqls",
						"WEB-INF/resources/X_AD_Attribute.graphqls",
						"WEB-INF/resources/X_AD_Attribute_Value.graphqls",
						"WEB-INF/resources/X_AD_AuthorizationAccount.graphqls",
						"WEB-INF/resources/X_AD_AuthorizationCredential.graphqls",
						"WEB-INF/resources/X_AD_AuthorizationProvider.graphqls",
						"WEB-INF/resources/X_AD_BroadcastMessage.graphqls",
						"WEB-INF/resources/X_AD_ChangeLog.graphqls",
						"WEB-INF/resources/X_AD_Chart.graphqls",
						"WEB-INF/resources/X_AD_ChartDatasource.graphqls",
						"WEB-INF/resources/X_AD_Client.graphqls",
						"WEB-INF/resources/X_AD_ClientInfo.graphqls",
						"WEB-INF/resources/X_AD_ClientShare.graphqls",
						"WEB-INF/resources/X_AD_Color.graphqls",
						"WEB-INF/resources/X_AD_Column.graphqls",
						"WEB-INF/resources/X_AD_Column_Access.graphqls",
						"WEB-INF/resources/X_AD_CtxHelp.graphqls",
						"WEB-INF/resources/X_AD_CtxHelpMsg.graphqls",
						"WEB-INF/resources/X_AD_CtxHelpSuggestion.graphqls",
						"WEB-INF/resources/X_AD_Document_Action_Access.graphqls",
						"WEB-INF/resources/X_AD_Element.graphqls",
						"WEB-INF/resources/X_AD_EntityType.graphqls",
						"WEB-INF/resources/X_AD_Error.graphqls",
						"WEB-INF/resources/X_AD_Field.graphqls",
						"WEB-INF/resources/X_AD_FieldGroup.graphqls",
						"WEB-INF/resources/X_AD_FieldSuggestion.graphqls",
						"WEB-INF/resources/X_AD_Find.graphqls",
						"WEB-INF/resources/X_AD_Form.graphqls",
						"WEB-INF/resources/X_AD_Form_Access.graphqls",
						"WEB-INF/resources/X_AD_HouseKeeping.graphqls",
						"WEB-INF/resources/X_AD_Image.graphqls",
						"WEB-INF/resources/X_AD_ImpFormat.graphqls",
						"WEB-INF/resources/X_AD_ImpFormat_Row.graphqls",
						"WEB-INF/resources/X_AD_ImportTemplate.graphqls",
						"WEB-INF/resources/X_AD_ImportTemplateAccess.graphqls",
						"WEB-INF/resources/X_AD_IndexColumn.graphqls",
						"WEB-INF/resources/X_AD_InfoColumn.graphqls",
						"WEB-INF/resources/X_AD_InfoProcess.graphqls",
						"WEB-INF/resources/X_AD_InfoRelated.graphqls",
						"WEB-INF/resources/X_AD_InfoWindow.graphqls",
						"WEB-INF/resources/X_AD_InfoWindow_Access.graphqls",
						"WEB-INF/resources/X_AD_Issue.graphqls",
						"WEB-INF/resources/X_AD_LabelPrinter.graphqls",
						"WEB-INF/resources/X_AD_LabelPrinterFunction.graphqls",
						"WEB-INF/resources/X_AD_Language.graphqls",
						"WEB-INF/resources/X_AD_LdapAccess.graphqls",
						"WEB-INF/resources/X_AD_LdapProcessor.graphqls",
						"WEB-INF/resources/X_AD_LdapProcessorLog.graphqls",
						"WEB-INF/resources/X_AD_Menu.graphqls",
						"WEB-INF/resources/X_AD_Message.graphqls",
						"WEB-INF/resources/X_AD_MigrationScript.graphqls",
						"WEB-INF/resources/X_AD_ModelValidator.graphqls",
						"WEB-INF/resources/X_AD_Modification.graphqls",
						"WEB-INF/resources/X_AD_Note.graphqls",
						"WEB-INF/resources/X_AD_Org.graphqls",
						"WEB-INF/resources/X_AD_OrgInfo.graphqls",
						"WEB-INF/resources/X_AD_OrgType.graphqls",
						"WEB-INF/resources/X_AD_Package_Exp.graphqls",
						"WEB-INF/resources/X_AD_Package_Exp_Detail.graphqls",
						"WEB-INF/resources/X_AD_Package_Imp.graphqls",
						"WEB-INF/resources/X_AD_Package_Imp_Backup.graphqls",
						"WEB-INF/resources/X_AD_Package_Imp_Detail.graphqls",
						"WEB-INF/resources/X_AD_Package_Imp_Inst.graphqls",
						"WEB-INF/resources/X_AD_Package_Imp_Proc.graphqls",
						"WEB-INF/resources/X_AD_Package_UUID_Map.graphqls",
						"WEB-INF/resources/X_AD_PasswordRule.graphqls",
						"WEB-INF/resources/X_AD_Password_History.graphqls",
						"WEB-INF/resources/X_AD_PInstance.graphqls",
						"WEB-INF/resources/X_AD_PInstance_Log.graphqls",
						"WEB-INF/resources/X_AD_PInstance_Para.graphqls",
						"WEB-INF/resources/X_AD_PostIt.graphqls",
						"WEB-INF/resources/X_AD_Preference.graphqls",
						"WEB-INF/resources/X_AD_PrintColor.graphqls",
						"WEB-INF/resources/X_AD_PrintFont.graphqls",
						"WEB-INF/resources/X_AD_PrintForm.graphqls",
						"WEB-INF/resources/X_AD_PrintFormat.graphqls",
						"WEB-INF/resources/X_AD_PrintFormatItem.graphqls",
						"WEB-INF/resources/X_AD_PrintGraph.graphqls",
						"WEB-INF/resources/X_AD_PrintHeaderFooter.graphqls",
						"WEB-INF/resources/X_AD_PrintLabel.graphqls",
						"WEB-INF/resources/X_AD_PrintLabelLine.graphqls",
						"WEB-INF/resources/X_AD_PrintPaper.graphqls",
						"WEB-INF/resources/X_AD_PrintTableFormat.graphqls",
						"WEB-INF/resources/X_AD_Private_Access.graphqls",
						"WEB-INF/resources/X_AD_Process.graphqls",
						"WEB-INF/resources/X_AD_Process_Access.graphqls",
						"WEB-INF/resources/X_AD_Process_Para.graphqls",
						"WEB-INF/resources/X_AD_RecentItem.graphqls",
						"WEB-INF/resources/X_AD_Record_Access.graphqls",
						"WEB-INF/resources/X_AD_Reference.graphqls",
						"WEB-INF/resources/X_AD_Ref_List.graphqls",
						"WEB-INF/resources/X_AD_Ref_Table.graphqls",
						"WEB-INF/resources/X_AD_Registration.graphqls",
						"WEB-INF/resources/X_AD_RelationType.graphqls",
						"WEB-INF/resources/X_AD_Replication.graphqls",
						"WEB-INF/resources/X_AD_ReplicationDocument.graphqls",
						"WEB-INF/resources/X_AD_ReplicationStrategy.graphqls",
						"WEB-INF/resources/X_AD_ReplicationTable.graphqls",
						"WEB-INF/resources/X_AD_Replication_Log.graphqls",
						"WEB-INF/resources/X_AD_Replication_Run.graphqls",
						"WEB-INF/resources/X_AD_ReportView.graphqls",
						"WEB-INF/resources/X_AD_ReportView_Col.graphqls",
						"WEB-INF/resources/X_AD_ReportView_Column.graphqls",
						"WEB-INF/resources/X_AD_Role.graphqls",
						"WEB-INF/resources/X_AD_Role_Included.graphqls",
						"WEB-INF/resources/X_AD_Role_OrgAccess.graphqls",
						"WEB-INF/resources/X_AD_Rule.graphqls",
						"WEB-INF/resources/X_AD_Schedule.graphqls",
						"WEB-INF/resources/X_AD_Scheduler.graphqls",
						"WEB-INF/resources/X_AD_SchedulerLog.graphqls",
						"WEB-INF/resources/X_AD_SchedulerRecipient.graphqls",
						"WEB-INF/resources/X_AD_Scheduler_Para.graphqls",
						"WEB-INF/resources/X_AD_SearchDefinition.graphqls",
						"WEB-INF/resources/X_AD_Sequence.graphqls",
						"WEB-INF/resources/X_AD_Sequence_Audit.graphqls",
						"WEB-INF/resources/X_AD_Sequence_No.graphqls",
						"WEB-INF/resources/X_AD_Session.graphqls",
						"WEB-INF/resources/X_AD_StatusLine.graphqls",
						"WEB-INF/resources/X_AD_StatusLineUsedIn.graphqls",
						"WEB-INF/resources/X_AD_StorageProvider.graphqls",
						"WEB-INF/resources/X_AD_Style.graphqls",
						"WEB-INF/resources/X_AD_StyleLine.graphqls",
						"WEB-INF/resources/X_AD_SysConfig.graphqls",
						"WEB-INF/resources/X_AD_System.graphqls",
						"WEB-INF/resources/X_AD_Tab.graphqls",
						"WEB-INF/resources/X_AD_Table.graphqls",
						"WEB-INF/resources/X_AD_TableIndex.graphqls",
						"WEB-INF/resources/X_AD_Table_Access.graphqls",
						"WEB-INF/resources/X_AD_Table_ScriptValidator.graphqls",
						"WEB-INF/resources/X_AD_Tab_Customization.graphqls",
						"WEB-INF/resources/X_AD_Task.graphqls",
						"WEB-INF/resources/X_AD_TaskInstance.graphqls",
						"WEB-INF/resources/X_AD_Task_Access.graphqls",
						"WEB-INF/resources/X_AD_ToolBarButton.graphqls",
						"WEB-INF/resources/X_AD_ToolBarButtonRestrict.graphqls",
						"WEB-INF/resources/X_AD_Tree.graphqls",
						"WEB-INF/resources/X_AD_TreeNode.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeBP.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeCMC.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeCMM.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeCMS.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeCMT.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeMM.graphqls",
						"WEB-INF/resources/X_AD_TreeNodePR.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeU1.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeU2.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeU3.graphqls",
						"WEB-INF/resources/X_AD_TreeNodeU4.graphqls",
						"WEB-INF/resources/X_AD_Tree_Favorite.graphqls",
						"WEB-INF/resources/X_AD_Tree_Favorite_Node.graphqls",
						"WEB-INF/resources/X_AD_User.graphqls",
						"WEB-INF/resources/X_AD_UserBPAccess.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Field.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Info.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Info_Column.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Info_Related.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Proc.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Proc_Parameter.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Tab.graphqls",
						"WEB-INF/resources/X_AD_UserDef_Win.graphqls",
						"WEB-INF/resources/X_AD_UserMail.graphqls",
						"WEB-INF/resources/X_AD_UserPreference.graphqls",
						"WEB-INF/resources/X_AD_UserQuery.graphqls",
						"WEB-INF/resources/X_AD_User_OrgAccess.graphqls",
						"WEB-INF/resources/X_AD_User_Roles.graphqls",
						"WEB-INF/resources/X_AD_User_Substitute.graphqls",
						"WEB-INF/resources/X_AD_Val_Rule.graphqls",
						"WEB-INF/resources/X_AD_ViewColumn.graphqls",
						"WEB-INF/resources/X_AD_ViewComponent.graphqls",
						"WEB-INF/resources/X_AD_WF_Activity.graphqls",
						"WEB-INF/resources/X_AD_WF_ActivityApprover.graphqls",
						"WEB-INF/resources/X_AD_WF_ActivityResult.graphqls",
						"WEB-INF/resources/X_AD_WF_Block.graphqls",
						"WEB-INF/resources/X_AD_WF_EventAudit.graphqls",
						"WEB-INF/resources/X_AD_WF_NextCondition.graphqls",
						"WEB-INF/resources/X_AD_WF_Node.graphqls",
						"WEB-INF/resources/X_AD_WF_NodeNext.graphqls",
						"WEB-INF/resources/X_AD_WF_Node_Para.graphqls",
						"WEB-INF/resources/X_AD_WF_Process.graphqls",
						"WEB-INF/resources/X_AD_WF_ProcessData.graphqls",
						"WEB-INF/resources/X_AD_WF_Responsible.graphqls",
						"WEB-INF/resources/X_AD_Window.graphqls",
						"WEB-INF/resources/X_AD_Window_Access.graphqls",
						"WEB-INF/resources/X_AD_WizardProcess.graphqls",
						"WEB-INF/resources/X_AD_Workflow.graphqls",
						"WEB-INF/resources/X_AD_Workflow_Access.graphqls",
						"WEB-INF/resources/X_AD_WorkflowProcessor.graphqls",
						"WEB-INF/resources/X_AD_WorkflowProcessorLog.graphqls",
						"WEB-INF/resources/X_AD_ZoomCondition.graphqls",
						"WEB-INF/resources/X_ASP_ClientException.graphqls",
						"WEB-INF/resources/X_ASP_ClientLevel.graphqls",
						"WEB-INF/resources/X_ASP_Field.graphqls",
						"WEB-INF/resources/X_ASP_Form.graphqls",
						"WEB-INF/resources/X_ASP_Level.graphqls",
						"WEB-INF/resources/X_ASP_Module.graphqls",
						"WEB-INF/resources/X_ASP_Process.graphqls",
						"WEB-INF/resources/X_ASP_Process_Para.graphqls",
						"WEB-INF/resources/X_ASP_Ref_List.graphqls",
						"WEB-INF/resources/X_ASP_Tab.graphqls",
						"WEB-INF/resources/X_ASP_Task.graphqls",
						"WEB-INF/resources/X_ASP_Window.graphqls",
						"WEB-INF/resources/X_ASP_Workflow.graphqls",
						"WEB-INF/resources/X_A_Asset.graphqls",
						"WEB-INF/resources/X_A_Asset_Acct.graphqls",
						"WEB-INF/resources/X_A_Asset_Addition.graphqls",
						"WEB-INF/resources/X_A_Asset_Change.graphqls",
						"WEB-INF/resources/X_A_Asset_Class.graphqls",
						"WEB-INF/resources/X_A_Asset_Delivery.graphqls",
						"WEB-INF/resources/X_A_Asset_Disposed.graphqls",
						"WEB-INF/resources/X_A_Asset_Group.graphqls",
						"WEB-INF/resources/X_A_Asset_Group_Acct.graphqls",
						"WEB-INF/resources/X_A_Asset_Info_Fin.graphqls",
						"WEB-INF/resources/X_A_Asset_Info_Ins.graphqls",
						"WEB-INF/resources/X_A_Asset_Info_Lic.graphqls",
						"WEB-INF/resources/X_A_Asset_Info_Oth.graphqls",
						"WEB-INF/resources/X_A_Asset_Info_Tax.graphqls",
						"WEB-INF/resources/X_A_Asset_Product.graphqls",
						"WEB-INF/resources/X_A_Asset_Retirement.graphqls",
						"WEB-INF/resources/X_A_Asset_Reval.graphqls",
						"WEB-INF/resources/X_A_Asset_Reval_Entry.graphqls",
						"WEB-INF/resources/X_A_Asset_Reval_Index.graphqls",
						"WEB-INF/resources/X_A_Asset_Split.graphqls",
						"WEB-INF/resources/X_A_Asset_Transfer.graphqls",
						"WEB-INF/resources/X_A_Asset_Type.graphqls",
						"WEB-INF/resources/X_A_Asset_Use.graphqls",
						"WEB-INF/resources/X_A_Depreciation.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Build.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Convention.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Entry.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Exp.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Forecast.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Method.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Table_Detail.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Table_Header.graphqls",
						"WEB-INF/resources/X_A_Depreciation_Workfile.graphqls",
						"WEB-INF/resources/X_A_FundingMode.graphqls",
						"WEB-INF/resources/X_A_FundingMode_Acct.graphqls",
						"WEB-INF/resources/X_A_Registration.graphqls",
						"WEB-INF/resources/X_A_RegistrationAttribute.graphqls",
						"WEB-INF/resources/X_A_RegistrationProduct.graphqls",
						"WEB-INF/resources/X_A_RegistrationValue.graphqls",
						"WEB-INF/resources/X_BH_BP_General_Payer_Info.graphqls",
						"WEB-INF/resources/X_BH_BP_Payer_Info.graphqls",
						"WEB-INF/resources/X_BH_BP_Specific_Payer_Info.graphqls",
						"WEB-INF/resources/X_BH_Client_Concept.graphqls",
						"WEB-INF/resources/X_BH_Coded_Diagnosis.graphqls",
						"WEB-INF/resources/X_BH_Coded_Diagnosis_Mapping.graphqls",
						"WEB-INF/resources/X_BH_Concept_Description.graphqls",
						"WEB-INF/resources/X_BH_Concept_Extra.graphqls",
						"WEB-INF/resources/X_BH_Concept_Mapping.graphqls",
						"WEB-INF/resources/X_BH_Concept_Name.graphqls",
						"WEB-INF/resources/X_BH_Concept.graphqls",
						"WEB-INF/resources/X_BH_DefaultIncludedRole.graphqls",
						"WEB-INF/resources/X_BH_Default_DocAction_Access.graphqls",
						"WEB-INF/resources/X_BH_Encounter.graphqls",
						"WEB-INF/resources/X_BH_Encounter_Diagnosis.graphqls",
						"WEB-INF/resources/X_BH_Encounter_Type_Window.graphqls",
						"WEB-INF/resources/X_BH_I_Product_Quantity.graphqls",
						"WEB-INF/resources/X_BH_Observation.graphqls",
						"WEB-INF/resources/X_BH_Payer_Info_Fld.graphqls",
						"WEB-INF/resources/X_BH_Payer_Info_Fld_Sug.graphqls",
						"WEB-INF/resources/X_BH_Payer_Info_Fld_Val.graphqls",
						"WEB-INF/resources/X_BH_Payer_Info_Fld_Val_Sug.graphqls",
						"WEB-INF/resources/X_BH_PaymentRef.graphqls",
						"WEB-INF/resources/X_BH_PaymentRef_BankAcct.graphqls",
						"WEB-INF/resources/X_BH_Product_CategoryDefault.graphqls",
						"WEB-INF/resources/X_BH_Role_WarehouseAccess.graphqls",
						"WEB-INF/resources/X_BH_Visit.graphqls",
						"WEB-INF/resources/X_BH_Voided_Reason.graphqls",
						"WEB-INF/resources/X_B_Bid.graphqls",
						"WEB-INF/resources/X_B_BidComment.graphqls",
						"WEB-INF/resources/X_B_Buyer.graphqls",
						"WEB-INF/resources/X_B_BuyerFunds.graphqls",
						"WEB-INF/resources/X_B_Offer.graphqls",
						"WEB-INF/resources/X_B_Seller.graphqls",
						"WEB-INF/resources/X_B_SellerFunds.graphqls",
						"WEB-INF/resources/X_B_Topic.graphqls",
						"WEB-INF/resources/X_B_TopicCategory.graphqls",
						"WEB-INF/resources/X_B_TopicType.graphqls",
						"WEB-INF/resources/X_CM_Chat.graphqls",
						"WEB-INF/resources/X_CM_ChatEntry.graphqls",
						"WEB-INF/resources/X_CM_ChatType.graphqls",
						"WEB-INF/resources/X_CM_ChatTypeUpdate.graphqls",
						"WEB-INF/resources/X_CM_ChatUpdate.graphqls",
						"WEB-INF/resources/X_C_1099Box.graphqls",
						"WEB-INF/resources/X_C_AcctProcessor.graphqls",
						"WEB-INF/resources/X_C_AcctProcessorLog.graphqls",
						"WEB-INF/resources/X_C_AcctSchema.graphqls",
						"WEB-INF/resources/X_C_AcctSchema_Default.graphqls",
						"WEB-INF/resources/X_C_AcctSchema_Element.graphqls",
						"WEB-INF/resources/X_C_AcctSchema_GL.graphqls",
						"WEB-INF/resources/X_C_Activity.graphqls",
						"WEB-INF/resources/X_C_AddressTransaction.graphqls",
						"WEB-INF/resources/X_C_AddressValidation.graphqls",
						"WEB-INF/resources/X_C_AddressValidationCfg.graphqls",
						"WEB-INF/resources/X_C_AllocationHdr.graphqls",
						"WEB-INF/resources/X_C_AllocationLine.graphqls",
						"WEB-INF/resources/X_C_Bank.graphqls",
						"WEB-INF/resources/X_C_BankAccount.graphqls",
						"WEB-INF/resources/X_C_BankAccountDoc.graphqls",
						"WEB-INF/resources/X_C_BankAccount_Acct.graphqls",
						"WEB-INF/resources/X_C_BankAccount_Processor.graphqls",
						"WEB-INF/resources/X_C_BankStatement.graphqls",
						"WEB-INF/resources/X_C_BankStatementLine.graphqls",
						"WEB-INF/resources/X_C_BankStatementLoader.graphqls",
						"WEB-INF/resources/X_C_BankStatementMatcher.graphqls",
						"WEB-INF/resources/X_C_BankTransfer.graphqls",
						"WEB-INF/resources/X_C_BPartner.graphqls",
						"WEB-INF/resources/X_C_BPartner_Location.graphqls",
						"WEB-INF/resources/X_C_BPartner_Product.graphqls",
						"WEB-INF/resources/X_C_BP_BankAccount.graphqls",
						"WEB-INF/resources/X_C_BP_Customer_Acct.graphqls",
						"WEB-INF/resources/X_C_BP_EDI.graphqls",
						"WEB-INF/resources/X_C_BP_Employee_Acct.graphqls",
						"WEB-INF/resources/X_C_BP_Group.graphqls",
						"WEB-INF/resources/X_C_BP_Group_Acct.graphqls",
						"WEB-INF/resources/X_C_BP_Relation.graphqls",
						"WEB-INF/resources/X_C_BP_ShippingAcct.graphqls",
						"WEB-INF/resources/X_C_BP_Vendor_Acct.graphqls",
						"WEB-INF/resources/X_C_BP_Withholding.graphqls",
						"WEB-INF/resources/X_C_Calendar.graphqls",
						"WEB-INF/resources/X_C_Campaign.graphqls",
						"WEB-INF/resources/X_C_Cash.graphqls",
						"WEB-INF/resources/X_C_CashBook.graphqls",
						"WEB-INF/resources/X_C_CashBook_Acct.graphqls",
						"WEB-INF/resources/X_C_CashLine.graphqls",
						"WEB-INF/resources/X_C_CashPlan.graphqls",
						"WEB-INF/resources/X_C_CashPlanLine.graphqls",
						"WEB-INF/resources/X_C_Channel.graphqls",
						"WEB-INF/resources/X_C_Charge.graphqls",
						"WEB-INF/resources/X_C_ChargeType.graphqls",
						"WEB-INF/resources/X_C_ChargeType_DocType.graphqls",
						"WEB-INF/resources/X_C_Charge_Acct.graphqls",
						"WEB-INF/resources/X_C_City.graphqls",
						"WEB-INF/resources/X_C_Commission.graphqls",
						"WEB-INF/resources/X_C_CommissionAmt.graphqls",
						"WEB-INF/resources/X_C_CommissionDetail.graphqls",
						"WEB-INF/resources/X_C_CommissionLine.graphqls",
						"WEB-INF/resources/X_C_CommissionRun.graphqls",
						"WEB-INF/resources/X_C_ContactActivity.graphqls",
						"WEB-INF/resources/X_C_ConversionType.graphqls",
						"WEB-INF/resources/X_C_Conversion_Rate.graphqls",
						"WEB-INF/resources/X_C_Country.graphqls",
						"WEB-INF/resources/X_C_CountryGroup.graphqls",
						"WEB-INF/resources/X_C_CountryGroupCountry.graphqls",
						"WEB-INF/resources/X_C_Currency.graphqls",
						"WEB-INF/resources/X_C_Currency_Acct.graphqls",
						"WEB-INF/resources/X_C_Cycle.graphqls",
						"WEB-INF/resources/X_C_CyclePhase.graphqls",
						"WEB-INF/resources/X_C_CycleStep.graphqls",
						"WEB-INF/resources/X_C_DepositBatch.graphqls",
						"WEB-INF/resources/X_C_DepositBatchLine.graphqls",
						"WEB-INF/resources/X_C_DocType.graphqls",
						"WEB-INF/resources/X_C_DocTypeCounter.graphqls",
						"WEB-INF/resources/X_C_Dunning.graphqls",
						"WEB-INF/resources/X_C_DunningLevel.graphqls",
						"WEB-INF/resources/X_C_DunningRun.graphqls",
						"WEB-INF/resources/X_C_DunningRunEntry.graphqls",
						"WEB-INF/resources/X_C_DunningRunLine.graphqls",
						"WEB-INF/resources/X_C_Element.graphqls",
						"WEB-INF/resources/X_C_ElementValue.graphqls",
						"WEB-INF/resources/X_C_Greeting.graphqls",
						"WEB-INF/resources/X_C_InterOrg_Acct.graphqls",
						"WEB-INF/resources/X_C_Invoice.graphqls",
						"WEB-INF/resources/X_C_InvoiceBatch.graphqls",
						"WEB-INF/resources/X_C_InvoiceBatchLine.graphqls",
						"WEB-INF/resources/X_C_InvoiceLine.graphqls",
						"WEB-INF/resources/X_C_InvoicePaySchedule.graphqls",
						"WEB-INF/resources/X_C_InvoiceSchedule.graphqls",
						"WEB-INF/resources/X_C_InvoiceTax.graphqls",
						"WEB-INF/resources/X_C_Job.graphqls",
						"WEB-INF/resources/X_C_JobAssignment.graphqls",
						"WEB-INF/resources/X_C_JobCategory.graphqls",
						"WEB-INF/resources/X_C_JobRemuneration.graphqls",
						"WEB-INF/resources/X_C_LandedCost.graphqls",
						"WEB-INF/resources/X_C_LandedCostAllocation.graphqls",
						"WEB-INF/resources/X_C_Location.graphqls",
						"WEB-INF/resources/X_C_NonBusinessDay.graphqls",
						"WEB-INF/resources/X_C_OnlineTrxHistory.graphqls",
						"WEB-INF/resources/X_C_Opportunity.graphqls",
						"WEB-INF/resources/X_C_Order.graphqls",
						"WEB-INF/resources/X_C_OrderLandedCost.graphqls",
						"WEB-INF/resources/X_C_OrderLandedCostAllocation.graphqls",
						"WEB-INF/resources/X_C_OrderLine.graphqls",
						"WEB-INF/resources/X_C_OrderPaySchedule.graphqls",
						"WEB-INF/resources/X_C_OrderSource.graphqls",
						"WEB-INF/resources/X_C_OrderTax.graphqls",
						"WEB-INF/resources/X_C_OrgAssignment.graphqls",
						"WEB-INF/resources/X_C_Payment.graphqls",
						"WEB-INF/resources/X_C_PaymentAllocate.graphqls",
						"WEB-INF/resources/X_C_PaymentBatch.graphqls",
						"WEB-INF/resources/X_C_PaymentProcessor.graphqls",
						"WEB-INF/resources/X_C_PaymentTerm.graphqls",
						"WEB-INF/resources/X_C_PaymentTransaction.graphqls",
						"WEB-INF/resources/X_C_PaySchedule.graphqls",
						"WEB-INF/resources/X_C_PaySelection.graphqls",
						"WEB-INF/resources/X_C_PaySelectionCheck.graphqls",
						"WEB-INF/resources/X_C_PaySelectionLine.graphqls",
						"WEB-INF/resources/X_C_Period.graphqls",
						"WEB-INF/resources/X_C_PeriodControl.graphqls",
						"WEB-INF/resources/X_C_Phase.graphqls",
						"WEB-INF/resources/X_C_POS.graphqls",
						"WEB-INF/resources/X_C_POSKey.graphqls",
						"WEB-INF/resources/X_C_POSKeyLayout.graphqls",
						"WEB-INF/resources/X_C_POSPayment.graphqls",
						"WEB-INF/resources/X_C_POSTenderType.graphqls",
						"WEB-INF/resources/X_C_Project.graphqls",
						"WEB-INF/resources/X_C_ProjectIssue.graphqls",
						"WEB-INF/resources/X_C_ProjectIssueMA.graphqls",
						"WEB-INF/resources/X_C_ProjectLine.graphqls",
						"WEB-INF/resources/X_C_ProjectPhase.graphqls",
						"WEB-INF/resources/X_C_ProjectTask.graphqls",
						"WEB-INF/resources/X_C_ProjectType.graphqls",
						"WEB-INF/resources/X_C_Project_Acct.graphqls",
						"WEB-INF/resources/X_C_Recurring.graphqls",
						"WEB-INF/resources/X_C_RecurringGroup.graphqls",
						"WEB-INF/resources/X_C_Recurring_Run.graphqls",
						"WEB-INF/resources/X_C_Region.graphqls",
						"WEB-INF/resources/X_C_Remuneration.graphqls",
						"WEB-INF/resources/X_C_RevenueRecognition.graphqls",
						"WEB-INF/resources/X_C_RevenueRecognition_Plan.graphqls",
						"WEB-INF/resources/X_C_RevenueRecognition_Run.graphqls",
						"WEB-INF/resources/X_C_RevenueRecog_Service.graphqls",
						"WEB-INF/resources/X_C_RfQ.graphqls",
						"WEB-INF/resources/X_C_RfQLine.graphqls",
						"WEB-INF/resources/X_C_RfQLineQty.graphqls",
						"WEB-INF/resources/X_C_RfQResponse.graphqls",
						"WEB-INF/resources/X_C_RfQResponseLine.graphqls",
						"WEB-INF/resources/X_C_RfQResponseLineQty.graphqls",
						"WEB-INF/resources/X_C_RfQ_Topic.graphqls",
						"WEB-INF/resources/X_C_RfQ_TopicSubscriber.graphqls",
						"WEB-INF/resources/X_C_RfQ_TopicSubscriberOnly.graphqls",
						"WEB-INF/resources/X_C_SalesRegion.graphqls",
						"WEB-INF/resources/X_C_SalesStage.graphqls",
						"WEB-INF/resources/X_C_ServiceLevel.graphqls",
						"WEB-INF/resources/X_C_ServiceLevelLine.graphqls",
						"WEB-INF/resources/X_C_SubAcct.graphqls",
						"WEB-INF/resources/X_C_Subscription.graphqls",
						"WEB-INF/resources/X_C_SubscriptionType.graphqls",
						"WEB-INF/resources/X_C_Subscription_Delivery.graphqls",
						"WEB-INF/resources/X_C_Task.graphqls",
						"WEB-INF/resources/X_C_Tax.graphqls",
						"WEB-INF/resources/X_C_TaxBase.graphqls",
						"WEB-INF/resources/X_C_TaxCategory.graphqls",
						"WEB-INF/resources/X_C_TaxDeclaration.graphqls",
						"WEB-INF/resources/X_C_TaxDeclarationAcct.graphqls",
						"WEB-INF/resources/X_C_TaxDeclarationLine.graphqls",
						"WEB-INF/resources/X_C_TaxDefinition.graphqls",
						"WEB-INF/resources/X_C_TaxGroup.graphqls",
						"WEB-INF/resources/X_C_TaxPostal.graphqls",
						"WEB-INF/resources/X_C_TaxProvider.graphqls",
						"WEB-INF/resources/X_C_TaxProviderCfg.graphqls",
						"WEB-INF/resources/X_C_TaxType.graphqls",
						"WEB-INF/resources/X_C_Tax_Acct.graphqls",
						"WEB-INF/resources/X_C_UOM.graphqls",
						"WEB-INF/resources/X_C_UOM_Conversion.graphqls",
						"WEB-INF/resources/X_C_UserRemuneration.graphqls",
						"WEB-INF/resources/X_C_ValidCombination.graphqls",
						"WEB-INF/resources/X_C_Withholding.graphqls",
						"WEB-INF/resources/X_C_Withholding_Acct.graphqls",
						"WEB-INF/resources/X_C_Year.graphqls",
						"WEB-INF/resources/X_DD_NetworkDistribution.graphqls",
						"WEB-INF/resources/X_DD_NetworkDistributionLine.graphqls",
						"WEB-INF/resources/X_DD_Order.graphqls",
						"WEB-INF/resources/X_DD_OrderLine.graphqls",
						"WEB-INF/resources/X_EXP_Format.graphqls",
						"WEB-INF/resources/X_EXP_FormatLine.graphqls",
						"WEB-INF/resources/X_EXP_Processor.graphqls",
						"WEB-INF/resources/X_EXP_ProcessorParameter.graphqls",
						"WEB-INF/resources/X_EXP_Processor_Type.graphqls",
						"WEB-INF/resources/X_Fact_Acct.graphqls",
						"WEB-INF/resources/X_Fact_Acct_Summary.graphqls",
						"WEB-INF/resources/X_Fact_Reconciliation.graphqls",
						"WEB-INF/resources/X_GL_Budget.graphqls",
						"WEB-INF/resources/X_GL_BudgetControl.graphqls",
						"WEB-INF/resources/X_GL_Category.graphqls",
						"WEB-INF/resources/X_GL_Distribution.graphqls",
						"WEB-INF/resources/X_GL_DistributionLine.graphqls",
						"WEB-INF/resources/X_GL_Fund.graphqls",
						"WEB-INF/resources/X_GL_FundRestriction.graphqls",
						"WEB-INF/resources/X_GL_Journal.graphqls",
						"WEB-INF/resources/X_GL_JournalBatch.graphqls",
						"WEB-INF/resources/X_GL_JournalGenerator.graphqls",
						"WEB-INF/resources/X_GL_JournalGeneratorLine.graphqls",
						"WEB-INF/resources/X_GL_JournalGeneratorSource.graphqls",
						"WEB-INF/resources/X_GL_JournalLine.graphqls",
						"WEB-INF/resources/X_HR_Attribute.graphqls",
						"WEB-INF/resources/X_HR_Concept.graphqls",
						"WEB-INF/resources/X_HR_Concept_Acct.graphqls",
						"WEB-INF/resources/X_HR_Concept_Category.graphqls",
						"WEB-INF/resources/X_HR_Contract.graphqls",
						"WEB-INF/resources/X_HR_Department.graphqls",
						"WEB-INF/resources/X_HR_Employee.graphqls",
						"WEB-INF/resources/X_HR_Job.graphqls",
						"WEB-INF/resources/X_HR_List.graphqls",
						"WEB-INF/resources/X_HR_ListLine.graphqls",
						"WEB-INF/resources/X_HR_ListType.graphqls",
						"WEB-INF/resources/X_HR_ListVersion.graphqls",
						"WEB-INF/resources/X_HR_Movement.graphqls",
						"WEB-INF/resources/X_HR_Payroll.graphqls",
						"WEB-INF/resources/X_HR_PayrollConcept.graphqls",
						"WEB-INF/resources/X_HR_Period.graphqls",
						"WEB-INF/resources/X_HR_Process.graphqls",
						"WEB-INF/resources/X_HR_Year.graphqls",
						"WEB-INF/resources/X_IMP_Processor.graphqls",
						"WEB-INF/resources/X_IMP_ProcessorLog.graphqls",
						"WEB-INF/resources/X_IMP_ProcessorParameter.graphqls",
						"WEB-INF/resources/X_IMP_Processor_Type.graphqls",
						"WEB-INF/resources/X_I_Asset.graphqls",
						"WEB-INF/resources/X_I_BankStatement.graphqls",
						"WEB-INF/resources/X_I_BPartner.graphqls",
						"WEB-INF/resources/X_I_Conversion_Rate.graphqls",
						"WEB-INF/resources/X_I_ElementValue.graphqls",
						"WEB-INF/resources/X_I_FAJournal.graphqls",
						"WEB-INF/resources/X_I_FixedAsset.graphqls",
						"WEB-INF/resources/X_I_GLJournal.graphqls",
						"WEB-INF/resources/X_I_HR_Movement.graphqls",
						"WEB-INF/resources/X_I_InOutLineConfirm.graphqls",
						"WEB-INF/resources/X_I_Inventory.graphqls",
						"WEB-INF/resources/X_I_Invoice.graphqls",
						"WEB-INF/resources/X_I_Movement.graphqls",
						"WEB-INF/resources/X_I_Order.graphqls",
						"WEB-INF/resources/X_I_Payment.graphqls",
						"WEB-INF/resources/X_I_PriceList.graphqls",
						"WEB-INF/resources/X_I_Product.graphqls",
						"WEB-INF/resources/X_I_ProductPlanning.graphqls",
						"WEB-INF/resources/X_I_ReportLine.graphqls",
						"WEB-INF/resources/X_M_Attribute.graphqls",
						"WEB-INF/resources/X_M_AttributeInstance.graphqls",
						"WEB-INF/resources/X_M_AttributeSearch.graphqls",
						"WEB-INF/resources/X_M_AttributeSet.graphqls",
						"WEB-INF/resources/X_M_AttributeSetExclude.graphqls",
						"WEB-INF/resources/X_M_AttributeSetInstance.graphqls",
						"WEB-INF/resources/X_M_AttributeUse.graphqls",
						"WEB-INF/resources/X_M_AttributeValue.graphqls",
						"WEB-INF/resources/X_M_BOMAlternative.graphqls",
						"WEB-INF/resources/X_M_BP_Price.graphqls",
						"WEB-INF/resources/X_M_ChangeNotice.graphqls",
						"WEB-INF/resources/X_M_ChangeRequest.graphqls",
						"WEB-INF/resources/X_M_CommodityShipment.graphqls",
						"WEB-INF/resources/X_M_Cost.graphqls",
						"WEB-INF/resources/X_M_CostDetail.graphqls",
						"WEB-INF/resources/X_M_CostElement.graphqls",
						"WEB-INF/resources/X_M_CostHistory.graphqls",
						"WEB-INF/resources/X_M_CostQueue.graphqls",
						"WEB-INF/resources/X_M_CostType.graphqls",
						"WEB-INF/resources/X_M_Demand.graphqls",
						"WEB-INF/resources/X_M_DemandDetail.graphqls",
						"WEB-INF/resources/X_M_DemandLine.graphqls",
						"WEB-INF/resources/X_M_DiscountSchema.graphqls",
						"WEB-INF/resources/X_M_DiscountSchemaBreak.graphqls",
						"WEB-INF/resources/X_M_DiscountSchemaLine.graphqls",
						"WEB-INF/resources/X_M_DistributionList.graphqls",
						"WEB-INF/resources/X_M_DistributionListLine.graphqls",
						"WEB-INF/resources/X_M_DistributionRun.graphqls",
						"WEB-INF/resources/X_M_DistributionRunLine.graphqls",
						"WEB-INF/resources/X_M_Forecast.graphqls",
						"WEB-INF/resources/X_M_ForecastLine.graphqls",
						"WEB-INF/resources/X_M_Freight.graphqls",
						"WEB-INF/resources/X_M_FreightCategory.graphqls",
						"WEB-INF/resources/X_M_InOut.graphqls",
						"WEB-INF/resources/X_M_InOutConfirm.graphqls",
						"WEB-INF/resources/X_M_InOutLine.graphqls",
						"WEB-INF/resources/X_M_InOutLineConfirm.graphqls",
						"WEB-INF/resources/X_M_InOutLineMA.graphqls",
						"WEB-INF/resources/X_M_Inventory.graphqls",
						"WEB-INF/resources/X_M_InventoryLine.graphqls",
						"WEB-INF/resources/X_M_InventoryLineMA.graphqls",
						"WEB-INF/resources/X_M_Locator.graphqls",
						"WEB-INF/resources/X_M_LocatorType.graphqls",
						"WEB-INF/resources/X_M_Lot.graphqls",
						"WEB-INF/resources/X_M_LotCtl.graphqls",
						"WEB-INF/resources/X_M_LotCtlExclude.graphqls",
						"WEB-INF/resources/X_M_MatchInv.graphqls",
						"WEB-INF/resources/X_M_MatchPO.graphqls",
						"WEB-INF/resources/X_M_Movement.graphqls",
						"WEB-INF/resources/X_M_MovementConfirm.graphqls",
						"WEB-INF/resources/X_M_MovementLine.graphqls",
						"WEB-INF/resources/X_M_MovementLineConfirm.graphqls",
						"WEB-INF/resources/X_M_MovementLineMA.graphqls",
						"WEB-INF/resources/X_M_OperationResource.graphqls",
						"WEB-INF/resources/X_M_Package.graphqls",
						"WEB-INF/resources/X_M_PackageLine.graphqls",
						"WEB-INF/resources/X_M_PackageMPS.graphqls",
						"WEB-INF/resources/X_M_PartType.graphqls",
						"WEB-INF/resources/X_M_PerpetualInv.graphqls",
						"WEB-INF/resources/X_M_PriceList.graphqls",
						"WEB-INF/resources/X_M_PriceList_Version.graphqls",
						"WEB-INF/resources/X_M_Product.graphqls",
						"WEB-INF/resources/X_M_ProductDownload.graphqls",
						"WEB-INF/resources/X_M_Production.graphqls",
						"WEB-INF/resources/X_M_ProductionLine.graphqls",
						"WEB-INF/resources/X_M_ProductionLineMA.graphqls",
						"WEB-INF/resources/X_M_ProductionPlan.graphqls",
						"WEB-INF/resources/X_M_ProductOperation.graphqls",
						"WEB-INF/resources/X_M_ProductPrice.graphqls",
						"WEB-INF/resources/X_M_ProductPriceVendorBreak.graphqls",
						"WEB-INF/resources/X_M_Product_Acct.graphqls",
						"WEB-INF/resources/X_M_Product_Category.graphqls",
						"WEB-INF/resources/X_M_Product_Category_Acct.graphqls",
						"WEB-INF/resources/X_M_Product_PO.graphqls",
						"WEB-INF/resources/X_M_Product_QualityTest.graphqls",
						"WEB-INF/resources/X_M_Promotion.graphqls",
						"WEB-INF/resources/X_M_PromotionDistribution.graphqls",
						"WEB-INF/resources/X_M_PromotionGroup.graphqls",
						"WEB-INF/resources/X_M_PromotionGroupLine.graphqls",
						"WEB-INF/resources/X_M_PromotionLine.graphqls",
						"WEB-INF/resources/X_M_PromotionPreCondition.graphqls",
						"WEB-INF/resources/X_M_PromotionReward.graphqls",
						"WEB-INF/resources/X_M_QualityTest.graphqls",
						"WEB-INF/resources/X_M_QualityTestResult.graphqls",
						"WEB-INF/resources/X_M_RelatedProduct.graphqls",
						"WEB-INF/resources/X_M_Replenish.graphqls",
						"WEB-INF/resources/X_M_Requisition.graphqls",
						"WEB-INF/resources/X_M_RequisitionLine.graphqls",
						"WEB-INF/resources/X_M_RMA.graphqls",
						"WEB-INF/resources/X_M_RMALine.graphqls",
						"WEB-INF/resources/X_M_RMATax.graphqls",
						"WEB-INF/resources/X_M_RMAType.graphqls",
						"WEB-INF/resources/X_M_SerNoCtl.graphqls",
						"WEB-INF/resources/X_M_SerNoCtlExclude.graphqls",
						"WEB-INF/resources/X_M_Shipper.graphqls",
						"WEB-INF/resources/X_M_ShipperCfg.graphqls",
						"WEB-INF/resources/X_M_ShipperLabels.graphqls",
						"WEB-INF/resources/X_M_ShipperLabelsCfg.graphqls",
						"WEB-INF/resources/X_M_ShipperPackaging.graphqls",
						"WEB-INF/resources/X_M_ShipperPackagingCfg.graphqls",
						"WEB-INF/resources/X_M_ShipperPickupTypes.graphqls",
						"WEB-INF/resources/X_M_ShipperPickupTypesCfg.graphqls",
						"WEB-INF/resources/X_M_ShippingProcessor.graphqls",
						"WEB-INF/resources/X_M_ShippingProcessorCfg.graphqls",
						"WEB-INF/resources/X_M_ShippingTransaction.graphqls",
						"WEB-INF/resources/X_M_ShippingTransactionLine.graphqls",
						"WEB-INF/resources/X_M_StorageOnHand.graphqls",
						"WEB-INF/resources/X_M_StorageReservation.graphqls",
						"WEB-INF/resources/X_M_Substitute.graphqls",
						"WEB-INF/resources/X_M_Transaction.graphqls",
						"WEB-INF/resources/X_M_TransactionAllocation.graphqls",
						"WEB-INF/resources/X_M_Warehouse.graphqls",
						"WEB-INF/resources/X_M_Warehouse_Acct.graphqls",
						"WEB-INF/resources/X_PA_Achievement.graphqls",
						"WEB-INF/resources/X_PA_Benchmark.graphqls",
						"WEB-INF/resources/X_PA_BenchmarkData.graphqls",
						"WEB-INF/resources/X_PA_ColorSchema.graphqls",
						"WEB-INF/resources/X_PA_DashboardContent.graphqls",
						"WEB-INF/resources/X_PA_DashboardContent_Access.graphqls",
						"WEB-INF/resources/X_PA_DashboardPreference.graphqls",
						"WEB-INF/resources/X_PA_DocumentStatus.graphqls",
						"WEB-INF/resources/X_PA_Goal.graphqls",
						"WEB-INF/resources/X_PA_GoalRestriction.graphqls",
						"WEB-INF/resources/X_PA_Hierarchy.graphqls",
						"WEB-INF/resources/X_PA_Measure.graphqls",
						"WEB-INF/resources/X_PA_MeasureCalc.graphqls",
						"WEB-INF/resources/X_PA_Ratio.graphqls",
						"WEB-INF/resources/X_PA_RatioElement.graphqls",
						"WEB-INF/resources/X_PA_Report.graphqls",
						"WEB-INF/resources/X_PA_ReportColumn.graphqls",
						"WEB-INF/resources/X_PA_ReportColumnSet.graphqls",
						"WEB-INF/resources/X_PA_ReportCube.graphqls",
						"WEB-INF/resources/X_PA_ReportLine.graphqls",
						"WEB-INF/resources/X_PA_ReportLineSet.graphqls",
						"WEB-INF/resources/X_PA_ReportSource.graphqls",
						"WEB-INF/resources/X_PA_SLA_Criteria.graphqls",
						"WEB-INF/resources/X_PA_SLA_Goal.graphqls",
						"WEB-INF/resources/X_PA_SLA_Measure.graphqls",
						"WEB-INF/resources/X_PP_Cost_Collector.graphqls",
						"WEB-INF/resources/X_PP_Cost_CollectorMA.graphqls",
						"WEB-INF/resources/X_PP_MRP.graphqls",
						"WEB-INF/resources/X_PP_Order.graphqls",
						"WEB-INF/resources/X_PP_Order_BOM.graphqls",
						"WEB-INF/resources/X_PP_Order_BOMLine.graphqls",
						"WEB-INF/resources/X_PP_Order_Cost.graphqls",
						"WEB-INF/resources/X_PP_Order_Node.graphqls",
						"WEB-INF/resources/X_PP_Order_NodeNext.graphqls",
						"WEB-INF/resources/X_PP_Order_Node_Asset.graphqls",
						"WEB-INF/resources/X_PP_Order_Node_Product.graphqls",
						"WEB-INF/resources/X_PP_Order_Workflow.graphqls",
						"WEB-INF/resources/X_PP_Product_BOM.graphqls",
						"WEB-INF/resources/X_PP_Product_BOMLine.graphqls",
						"WEB-INF/resources/X_PP_Product_Planning.graphqls",
						"WEB-INF/resources/X_PP_WF_Node_Asset.graphqls",
						"WEB-INF/resources/X_PP_WF_Node_Product.graphqls",
						"WEB-INF/resources/X_QM_Specification.graphqls",
						"WEB-INF/resources/X_QM_SpecificationLine.graphqls",
						"WEB-INF/resources/X_RV_BPartner.graphqls",
						"WEB-INF/resources/X_RV_WarehousePrice.graphqls",
						"WEB-INF/resources/X_R_Category.graphqls",
						"WEB-INF/resources/X_R_CategoryUpdates.graphqls",
						"WEB-INF/resources/X_R_ContactInterest.graphqls",
						"WEB-INF/resources/X_R_Group.graphqls",
						"WEB-INF/resources/X_R_GroupUpdates.graphqls",
						"WEB-INF/resources/X_R_InterestArea.graphqls",
						"WEB-INF/resources/X_R_IssueKnown.graphqls",
						"WEB-INF/resources/X_R_IssueProject.graphqls",
						"WEB-INF/resources/X_R_IssueRecommendation.graphqls",
						"WEB-INF/resources/X_R_IssueStatus.graphqls",
						"WEB-INF/resources/X_R_IssueSystem.graphqls",
						"WEB-INF/resources/X_R_IssueUser.graphqls",
						"WEB-INF/resources/X_R_MailText.graphqls",
						"WEB-INF/resources/X_R_Request.graphqls",
						"WEB-INF/resources/X_R_RequestAction.graphqls",
						"WEB-INF/resources/X_R_RequestProcessor.graphqls",
						"WEB-INF/resources/X_R_RequestProcessorLog.graphqls",
						"WEB-INF/resources/X_R_RequestProcessor_Route.graphqls",
						"WEB-INF/resources/X_R_RequestType.graphqls",
						"WEB-INF/resources/X_R_RequestTypeUpdates.graphqls",
						"WEB-INF/resources/X_R_RequestUpdate.graphqls",
						"WEB-INF/resources/X_R_RequestUpdates.graphqls",
						"WEB-INF/resources/X_R_Resolution.graphqls",
						"WEB-INF/resources/X_R_StandardResponse.graphqls",
						"WEB-INF/resources/X_R_Status.graphqls",
						"WEB-INF/resources/X_R_StatusCategory.graphqls",
						"WEB-INF/resources/X_S_ExpenseType.graphqls",
						"WEB-INF/resources/X_S_Resource.graphqls",
						"WEB-INF/resources/X_S_ResourceAssignment.graphqls",
						"WEB-INF/resources/X_S_ResourceType.graphqls",
						"WEB-INF/resources/X_S_ResourceUnAvailable.graphqls",
						"WEB-INF/resources/X_S_TimeExpense.graphqls",
						"WEB-INF/resources/X_S_TimeExpenseLine.graphqls",
						"WEB-INF/resources/X_S_TimeType.graphqls",
						"WEB-INF/resources/X_S_Training.graphqls",
						"WEB-INF/resources/X_S_Training_Class.graphqls",
						"WEB-INF/resources/X_Test.graphqls",
						"WEB-INF/resources/X_T_1099Extract.graphqls",
						"WEB-INF/resources/X_T_Aging.graphqls",
						"WEB-INF/resources/X_T_BankRegister.graphqls",
						"WEB-INF/resources/X_T_BOMLine.graphqls",
						"WEB-INF/resources/X_T_BOM_Indented.graphqls",
						"WEB-INF/resources/X_T_CashFlow.graphqls",
						"WEB-INF/resources/X_T_DistributionRunDetail.graphqls",
						"WEB-INF/resources/X_T_InventoryValue.graphqls",
						"WEB-INF/resources/X_T_InvoiceGL.graphqls",
						"WEB-INF/resources/X_T_MRP_CRP.graphqls",
						"WEB-INF/resources/X_T_Reconciliation.graphqls",
						"WEB-INF/resources/X_T_Replenish.graphqls",
						"WEB-INF/resources/X_T_Report.graphqls",
						"WEB-INF/resources/X_T_ReportStatement.graphqls",
						"WEB-INF/resources/X_T_Transaction.graphqls",
						"WEB-INF/resources/X_U_POSTerminal.graphqls",
						"WEB-INF/resources/X_U_RoleMenu.graphqls",
						"WEB-INF/resources/X_U_WebMenu.graphqls",
						"WEB-INF/resources/X_U_Web_Properties.graphqls"
				);
	}
}
