ALTER TABLE m_movement
 ADD IF NOT EXISTS BH_From_Warehouse_ID numeric(10) DEFAULT NULL;
 
ALTER TABLE m_movement 
 ADD IF NOT EXISTS BH_To_Warehouse_ID numeric(10) DEFAULT NULL;
 
 INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:31.093000', 100, '2021-10-13 16:36:31.093000', 100, 'BH_From_Warehouse_ID', 'U', 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', null, null, null, null, null, 'bfe459e4-4fe9-4ffa-ae5d-395379879d51', null);
 
 INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:39.633000', 100, '2021-10-13 16:36:39.633000', 100, 'BH_To_Warehouse_ID', 'U', 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', null, null, null, null, null, '483c2345-05f5-4d08-9927-f3520126fae8', null);
 
 INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-13 16:36:57.118000', '2021-10-13 16:36:57.118000', 100, 100, 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', null, 0, 'U', 'BH_From_Warehouse_ID', 323, 13, null, null, 50, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = 'bfe459e4-4fe9-4ffa-ae5d-395379879d51'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '1ff928cc-2b78-490d-b8a0-4c246d9ed0e5', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N');
 
 INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-13 16:42:47.023000', '2021-10-13 16:42:47.023000', 100, 100, 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', null, 0, 'U', 'BH_To_Warehouse_ID', 323, 13, null, null, 50, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = '483c2345-05f5-4d08-9927-f3520126fae8'), null, 'N', 'N', null, null, null, 'N', 'Y', null, 'e92cdafc-3691-4bc7-98bb-700ec86bccfb', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N'); 


SELECT register_migration_script('202110131559_GO-1806.sql') FROM dual;
