--Price Update reasons ref-list
INSERT INTO ad_ref_list (ad_ref_list_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, value, name, description, ad_reference_id, validfrom, validto, entitytype, ad_ref_list_uu, bh_update_existing, bh_add_all) VALUES ((SELECT max(ad_ref_list_id) + 1 FROM adempiere.ad_ref_list), 0, 0, 'Y', '2021-11-02 22:13:00.944000', 100, '2021-11-02 22:13:00.944000', 100, 'p_wer', 'Wrong expiration received', null, (SELECT ad_reference_id FROM ad_reference WHERE ad_reference_uu = 'dcdc79d7-8e55-428f-a8a5-e7a6f562404f'), null, null, 'U', '6936f0fa-bf26-4c24-a744-d398e458fd2e', null, null) ON CONFLICT DO NOTHING;

--add column to hold reason IDs for inventory updates
alter table m_attributesetinstance
add column if not exists bh_update_reason varchar(10);

INSERT INTO ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder) VALUES ((SELECT MAX(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-12-15 09:41:23.238000', '2021-12-15 09:41:23.238000', 100, 100, 'bh_update_reason', null, null, 0, 'U', 'bh_update_reason', 559, 17, (SELECT ad_reference_id FROM ad_reference WHERE ad_reference_uu = 'dcdc79d7-8e55-428f-a8a5-e7a6f562404f'), null, 10, null, 'N', 'N', 'N', 'Y', null, 'N', null, 'N', 'N', null, null, null, null, 'N', (SELECT ad_element_id FROM ad_element WHERE ad_element_uu = 'cf161a48-d2ff-4b2e-a45c-1a48f6ea88ef'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '099d8fd1-3489-4f07-aac3-d564f37d34be', 'Y', null, 'N', 'N', null, null, 'N', null, null) ON CONFLICT DO NOTHING;

SELECT register_migration_script('202112150931_GO-1993.sql') FROM dual;
