ALTER TABLE m_movement
 ADD IF NOT EXISTS BH_From_Warehouse_ID numeric(10) DEFAULT NULL;
 
ALTER TABLE m_movement 
 ADD IF NOT EXISTS BH_To_Warehouse_ID numeric(10) DEFAULT NULL;
 
 ALTER TABLE m_warehouse 
 ADD IF NOT EXISTS BH_DefaultWarehouse char default 'N'::bpchar;
 
 INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:31.093000', 100, '2021-10-13 16:36:31.093000', 100, 'BH_From_Warehouse_ID', 'U', 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', null, null, null, null, null, 'bfe459e4-4fe9-4ffa-ae5d-395379879d51', null);
 
 INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:39.633000', 100, '2021-10-13 16:36:39.633000', 100, 'BH_To_Warehouse_ID', 'U', 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', null, null, null, null, null, '483c2345-05f5-4d08-9927-f3520126fae8', null);
 
  INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:31.093000', 100, '2021-10-13 16:36:31.093000', 100, 'BH_DefaultWarehouse', 'U', 'Default Warehouse', 'Default Warehouse', 'Default Warehouse', null, null, null, null, null, 'a644ce55-ced1-4041-86fe-543adfc85609', null);
 
 INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-13 16:36:57.118000', '2021-10-13 16:36:57.118000', 100, 100, 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', null, 0, 'U', 'BH_From_Warehouse_ID', 323, 13, null, null, 50, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = 'bfe459e4-4fe9-4ffa-ae5d-395379879d51'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '1ff928cc-2b78-490d-b8a0-4c246d9ed0e5', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N');
 
 INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-13 16:42:47.023000', '2021-10-13 16:42:47.023000', 100, 100, 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', null, 0, 'U', 'BH_To_Warehouse_ID', 323, 13, null, null, 50, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = '483c2345-05f5-4d08-9927-f3520126fae8'), null, 'N', 'N', null, null, null, 'N', 'Y', null, 'e92cdafc-3691-4bc7-98bb-700ec86bccfb', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N');
 

  INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-18 18:30:27.701000', '2021-10-18 18:30:27.701000', 100, 100, 'BH_DefaultWarehouse', 'BH_DefaultWarehouse', null, 0, 'U', 'BH_DefaultWarehouse', 190, 20, null, null, 1, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = 'a644ce55-ced1-4041-86fe-543adfc85609'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '0ccc40a4-6b68-4a7a-a28d-224cbfb9a898', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N');
  
  INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT max(ad_field_id) + 1 FROM ad_field), 0, 0, 'Y', '2021-10-18 18:33:44.162000', 100, '2021-10-18 18:38:25.779000', 100, 'Default Warehouse', 'Default Warehouse', null, 'Y', (SELECT AD_TAB_ID FROM AD_Tab WHERE AD_TAB_UU = 'b6ec1b3e-e8d4-44e3-bb34-70062bea155c'), (SELECT AD_Column_ID FROM AD_Column where ad_column_uu = '0ccc40a4-6b68-4a7a-a28d-224cbfb9a898'), null, 'Y', null, 0, 'N', 140, 0, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, '4e2c2550-e94a-45ef-ab18-bd6bcb659f05', null, 140, 'Y', 2, 1, 1, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N');


SELECT register_migration_script('202110131559_GO-1806.sql') FROM dual;
