-- CREATE BH_Voided_Reason table
create table bh_voided_reason
(
    bh_voided_reason_id   numeric(10) not null
        constraint bh_voided_reason_key
            primary key,
    bh_voided_reason_uu   varchar(36)  default NULL::character varying
        constraint bh_voided_reason_uu_idx
            unique,
    ad_client_id            numeric(10) not null,
    ad_org_id               numeric(10) not null,
    created                 timestamp    default statement_timestamp(),
    createdby               numeric(10)  default NULL::numeric,
    name		     varchar(200) not null,
    description             text,
    isactive                char         default 'Y'::bpchar
        constraint bh_voided_reason_isactive_check
            check (isactive = ANY (ARRAY ['Y'::bpchar, 'N'::bpchar])),
    updated                 timestamp    default statement_timestamp(),
    updatedby               numeric(10)  default NULL::numeric,
    bh_window_id	     numeric(10) default null,
    lineno           numeric(10)  default NULL::numeric
);

-- ADD bh_voided_reason TO C_Order
ALTER TABLE c_order 
  ADD IF NOT EXISTS bh_voided_reason_id numeric(10) DEFAULT NULL;
  
  -- ADD to AD_Table
  INSERT INTO adempiere.ad_table (ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable, iscentrallymaintained, ad_table_uu, processing, databaseviewdrop, copycomponentsfromview, createwindowfromtable) VALUES ((SELECT MAX(ad_table_id) +1 FROM AD_Table), 0, 0, 'Y', '2021-06-30 16:45:13.341000', 100, '2021-06-30 16:45:13.341000', 100, 'Voided Reason', null, null, 'BH_Voided_Reason', 'N', '3', 'U', null, null, 0, 'N', 'Y', 'N', 'N', 'Y', 'L', null, 'N', 'Y', '81c76e12-8ee9-438f-a948-56bd2921f08b', 'N', 'N', 'N', 'N') ON CONFLICT DO NOTHING;
  
  -- Add ad_elements
  INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT MAX(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-06-30 16:45:45.654000', 100, '2021-06-30 16:45:45.654000', 100, 'bh_voided_reason_uu', 'U', 'bh_voided_reason_uu', 'bh_voided_reason_uu', null, null, null, null, null, null, '17226899-35c3-41d9-8b3a-79a78f3c4dbb', null) ON CONFLICT DO NOTHING;
  
  INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT MAX(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-06-30 17:10:31.465000', 100, '2021-06-30 17:10:31.465000', 100, 'bh_voided_reason_id', 'U', 'Voided Reason', 'Voided Reason', null, null, null, null, null, null, '9f1bb1b0-353c-4f5c-a034-e5faea969b35', null) ON CONFLICT DO NOTHING;
  
  INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT MAX(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-06-30 17:07:21.595000', 100, '2021-06-30 17:07:21.595000', 100, 'bh_window_id', 'U', 'Window ID', 'Window ID', null, null, null, null, null, null, 'f5f0496d-b58d-4b14-af89-cd2f2da43da3', null) ON CONFLICT DO NOTHING;
  
  -- ADD to AD_Columns
  INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:04:08.676000', '2021-06-30 17:04:08.676000', 100, 100, 'Client', 'Client/Tenant for this installation.', 'A Client is a company or a legal entity. You cannot share data between Clients. Tenant is a synonym for Client.', 0, 'U', 'AD_Client_ID', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 19, null, 129, 22, '@#AD_Client_ID@', 'N', 'N', 'N', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 102, null, 'N', 'N', null, null, null, 'N', 'Y', null, 'ae570d8b-c85b-400c-8fc2-bbf16f7739c1', 'N', 0, 'N', 'N', null, null, 'D', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:04:27.090000', '2021-06-30 17:04:27.090000', 100, 100, 'Organization', 'Organizational entity within client', 'An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.', 0, 'U', 'AD_Org_ID', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 19, null, 104, 22, '@#AD_Org_ID@', 'N', 'N', 'N', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 113, null, 'N', 'N', null, null, null, 'N', 'Y', null, 'cbe5a1c6-cf45-4fdf-8bc1-57c19fac8f30', 'N', 0, 'N', 'N', null, null, 'D', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:04:40.595000', '2021-06-30 17:04:40.595000', 100, 100, 'Created', 'Date this record was created', 'The Created field indicates the date that this record was created.', 0, 'U', 'Created', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 16, null, null, 7, 'SYSDATE', 'N', 'N', 'N', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 245, null, 'N', 'N', null, null, null, 'N', 'Y', null, '446ba4ef-e115-440b-8f01-2f336570d625', 'N', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:05:05.978000', '2021-06-30 17:05:05.978000', 100, 100, 'Created By', 'User who created this records', 'The Created By field indicates the user who created this record.', 0, 'U', 'CreatedBy', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 30, 110, null, 22, null, 'N', 'N', 'N', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 246, null, 'N', 'N', null, null, null, 'N', 'Y', null, 'cbd1d5ce-4b21-44e2-baf0-ac78172d91eb', 'N', 0, 'N', 'N', null, null, 'D', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:05:36.995000', '2021-06-30 17:05:36.995000', 100, 100, 'Description', 'Optional short description of the record', 'A description is limited to 255 characters.', 0, 'U', 'Description', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 10, null, null, 255, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'Y', 275, null, 'N', 'N', null, null, null, 'N', 'Y', null, 'da0709a5-c8a6-4efb-bdc7-cb2b60f27b50', 'Y', 20, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:06:25.621000', '2021-06-30 17:06:25.621000', 100, 100, 'Line', 'Line No', null, 0, 'U', 'LineNo', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 11, null, null, 10, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 2945, null, 'N', 'N', null, null, null, 'N', 'Y', null, '72d4f157-2f1f-4afa-8eea-dff194d59308', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:05:17.843000', '2021-06-30 17:05:17.843000', 100, 100, 'Name', 'Alphanumeric identifier of the entity', 'The name of an entity (record) is used as an default search option in addition to the search key. The name is up to 60 characters in length.', 0, 'U', 'Name', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 10, null, null, 60, null, 'N', 'N', 'N', 'Y', null, 'Y', 0, 'N', 'N', null, null, null, null, 'Y', 469, null, 'N', 'N', null, null, null, 'N', 'Y', null, 'af2fd4dc-1bc2-4b0f-bcc0-d72e2645a2e3', 'Y', 10, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:05:47.420000', '2021-06-30 17:05:47.420000', 100, 100, 'Active', 'The record is active in the system', 'There are two methods of making records unavailable in the system: One is to delete the record, the other is to de-activate the record. A de-activated record is not available for selection, but available for reports.
There are two reasons for de-activating and not deleting records:
(1) The system requires the record for audit purposes.
(2) The record is referenced by other records. E.g., you cannot delete a Business Partner, if there are invoices for this partner record existing. You de-activate the Business Partner and prevent that this record is used for future entries.', 0, 'U', 'IsActive', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 20, null, null, 1, 'Y', 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 348, null, 'N', 'N', null, null, null, 'N', 'Y', null, '202f8ba3-d593-4e37-a94b-1716f24a6e95', 'N', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:06:01.897000', '2021-06-30 17:06:01.897000', 100, 100, 'Updated', 'Date this record was updated', 'The Updated field indicates the date that this record was updated.', 0, 'U', 'Updated', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 16, null, null, 7, 'SYSDATE', 'N', 'N', 'N', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 607, null, 'N', 'N', null, null, null, 'N', 'Y', null, '5e1fcb5b-ba90-4f9b-a134-a6738cc39d6b', 'N', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:06:16.872000', '2021-06-30 17:06:16.872000', 100, 100, 'Updated By', 'User who updated this records', 'The Updated By field indicates the user who updated this record.', 0, 'U', 'UpdatedBy', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 30, 110, null, 22, null, 'N', 'N', 'N', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 608, null, 'N', 'N', null, null, null, 'N', 'Y', null, 'bb59af6c-68c5-4d26-a41f-5ac9d850ce6e', 'N', 0, 'N', 'N', null, null, 'D', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:07:36.755000', '2021-06-30 17:07:36.755000', 100, 100, 'Window ID', null, null, 0, 'U', 'bh_window_id', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 22, null, null, 10, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (SELECT ad_element_id FROM ad_element WHERE ad_element_uu = 'f5f0496d-b58d-4b14-af89-cd2f2da43da3'), null, 'N', 'N', null, null, null, 'N', 'Y', null, 'd49e1ddf-c3df-4c44-b06b-ed0d4bf31460', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:11:02.500000', '2021-06-30 17:11:02.500000', 100, 100, 'Voided Reason', null, null, 0, 'U', 'bh_voided_reason_id', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 13, null, null, 22, null, 'Y', 'N', 'Y', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (SELECT ad_element_id FROM ad_element WHERE ad_element_uu = '9f1bb1b0-353c-4f5c-a034-e5faea969b35'), null, 'N', 'N', null, null, null, 'N', 'Y', null, 'f5d395d3-6f91-4c0d-9102-d38b18ea95cf', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:12:00.642000', '2021-06-30 17:12:00.642000', 100, 100, 'bh_voided_reason_uu', null, null, 0, 'U', 'bh_voided_reason_uu', (SELECT ad_table_id FROM ad_table WHERE tablename='BH_Voided_Reason'), 10, null, null, 36, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (SELECT ad_element_id FROM ad_element WHERE ad_element_uu = '17226899-35c3-41d9-8b3a-79a78f3c4dbb'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '376e96e5-0b52-4daa-87f9-4d3a4dcd86d4', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
 
-- insert bh_voided_reason table
INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong payment type or amount paid entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = 'a1f3e45c-4a6f-4c05-af26-517b8e9cbb77' AND isActive = 'Y'), 1, '2de54da3-25f8-4f51-abe8-bccbd8171bcf', 10) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Prescribed drug is sold out', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = 'a1f3e45c-4a6f-4c05-af26-517b8e9cbb77' AND isActive = 'Y'), 2, 'e49a626f-7f64-4ec3-82d8-824a39e491d5', 20) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Patient could not pay for the bill', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = 'a1f3e45c-4a6f-4c05-af26-517b8e9cbb77' AND isActive = 'Y'), 3, '04ae1937-a98b-4813-9fc2-2e8f944aaeb3', 30) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Duplicated transaction', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = 'a1f3e45c-4a6f-4c05-af26-517b8e9cbb77' AND isActive = 'Y'), 4, 'ee791d50-450a-406c-b70a-18342bab95e9', 40) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Add or Edit clinical information', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = 'a1f3e45c-4a6f-4c05-af26-517b8e9cbb77' AND isActive = 'Y'), 5, 'd1796d94-083e-4dd5-9bb9-c79a434067a3', 50) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong supplier entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '78dd6f39-84f9-4e19-b08e-7a3441af15e5' AND isActive = 'Y'), 6, '84a44c0e-0e6c-4b15-a69e-bedd4a539248', 60) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong date entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '78dd6f39-84f9-4e19-b08e-7a3441af15e5' AND isActive = 'Y'), 7, '745a4b6e-3ff1-433d-b31b-10052b67dccd', 70) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong product/drug entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '78dd6f39-84f9-4e19-b08e-7a3441af15e5' AND isActive = 'Y'), 8, '83bbcca2-9769-4421-b071-15fe1015a8c9', 80) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong expiration date entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '78dd6f39-84f9-4e19-b08e-7a3441af15e5' AND isActive = 'Y'), 9, 'd3adb9d8-4811-419d-b1f5-a2ece7ab10b0', 90) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong supplier entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '37df7931-7d07-4812-b9d4-dec7a53bb70f' AND isActive = 'Y'), 10, '243c1b1e-da7c-48fc-902e-bc631d67561e', 100) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong date entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '37df7931-7d07-4812-b9d4-dec7a53bb70f' AND isActive = 'Y'), 11, 'fa6e4e5a-23a9-4767-9aae-dda3a4bc1b30', 110) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong payment method entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '37df7931-7d07-4812-b9d4-dec7a53bb70f' AND isActive = 'Y'), 12, '05629ac4-e7fc-4438-b0a4-f8f5e38756b5', 120) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong expense category entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '37df7931-7d07-4812-b9d4-dec7a53bb70f' AND isActive = 'Y'), 13, '3bfd9e13-53d6-47ea-b955-d7820c41fb17', 130) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.bh_voided_reason (ad_client_id, ad_org_id, created, createdby, name, description, isactive, updated, updatedby, bh_window_id, bh_voided_reason_id, bh_voided_reason_uu, lineno) VALUES (0, 0, '2021-06-30 14:35:25.982661', 100, 'Wrong Amount entered', null, 'Y', '2021-06-30 14:35:25.982661', 100, (SELECT ad_window_id FROM ad_window WHERE ad_window_uu = '37df7931-7d07-4812-b9d4-dec7a53bb70f' AND isActive = 'Y'), 14, '07d34285-e72c-4a1e-ac00-c3f2cc1a3f92', 140) ON CONFLICT DO NOTHING;

SELECT register_migration_script('202106301435_GO-1739.sql') FROM dual;
