import { menuApi } from '../api';
import { Menu } from '../types/org.bandahealth.idempiere.rest';

test('correct menu names are returned', async () => {
	await globalThis.__VALUE_OBJECT__.login();
	const menus = (await menuApi.get(globalThis.__VALUE_OBJECT__)).results;

	expect(menus).toBe(2);

	let menu: Menu | undefined;

	menu = menus.find((menu) => menu.name === 'Dashboard');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(1);
	menu = menus.find((menu) => menu.name === 'Visits/Bills');
	expect(menu).not.toBeUndefined();
	expect(menu?.sequenceNumber).toBe(2);
	menu = menus.find((menu) => menu.name === 'Patients');
	expect(menu).not.toBeUndefined();
	expect(menu?.sequenceNumber).toBe(4);
	menu = menus.find((menu) => menu.name === 'Pharmacy Sales (OTC)');
	expect(menu).not.toBeUndefined();
	expect(menu?.sequenceNumber).toBe(3);
	menu = menus.find((menu) => menu.name === 'Reports');
	expect(menu).not.toBeUndefined();
	expect(menu?.sequenceNumber).toBe(8);

	const inventoryMenu = menus.find((menu) => menu.name === 'Inventory');
	expect(inventoryMenu).not.toBeUndefined();
	expect(inventoryMenu?.sequenceNumber).toBe(5);
	menu = inventoryMenu?.subMenus.find((menu) => menu.name === 'Products & Prices');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(0);
	menu = inventoryMenu?.subMenus.find((menu) => menu.name === 'Services & Prices');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(1);
	menu = inventoryMenu?.subMenus.find((menu) => menu.name === 'Receive Products');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(2);
	menu = inventoryMenu?.subMenus.find((menu) => menu.name === 'Manage Inventory');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(3);
	menu = inventoryMenu?.subMenus.find((menu) => menu.name === 'Transfer Inventory');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(4);
	menu = inventoryMenu?.subMenus.find((menu) => menu.name === 'Suppliers');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(5);

	const accountingMenu = menus.find((menu) => menu.name === 'Accounting');
	expect(accountingMenu).not.toBeUndefined();
	expect(accountingMenu?.sequenceNumber).toBe(6);
	menu = accountingMenu?.subMenus.find((menu) => menu.name === 'Debt Payments');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(0);
	menu = accountingMenu?.subMenus.find((menu) => menu.name === 'Track Expenses');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(1);
	menu = accountingMenu?.subMenus.find((menu) => menu.name === 'Track Income');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(3);
	menu = accountingMenu?.subMenus.find((menu) => menu.name === 'Donors & Insurers');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(2);
	menu = accountingMenu?.subMenus.find((menu) => menu.name === 'Expense Categories');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(4);
	menu = accountingMenu?.subMenus.find((menu) => menu.name === 'Suppliers');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(5);

	const backEndMenu = menus.find((menu) => menu.name === 'Back-End');
	expect(backEndMenu).not.toBeUndefined();
	expect(backEndMenu?.sequenceNumber).toBe(7);
	menu = backEndMenu?.subMenus.find((menu) => menu.name === 'Diagnoses');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(0);
	menu = backEndMenu?.subMenus.find((menu) => menu.name === 'Suppliers');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(1);
	menu = backEndMenu?.subMenus.find((menu) => menu.name === 'Manage Users');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(3);
	menu = backEndMenu?.subMenus.find((menu) => menu.name === 'Facility Information');
	expect(menu).not.toBeUndefined();
	expect(menu?.window?.uuid).toBeTruthy();
	expect(menu?.sequenceNumber).toBe(2);
});
