services:
  test:
    build: .
    volumes:
      - ./rest-test/testing:/app/rest-test
      - /app/rest-test/node_modules
    environment:
      - IDEMPIERE_USER=${IDEMPIERE_USER}
      - IDEMPIERE_USER_PASSWORD=${IDEMPIERE_USER_PASSWORD}
      - IDEMPIERE_ENDPOINT=${IDEMPIERE_ENDPOINT}
      - IDEMPIERE_REST_TEST_CLIENT=${IDEMPIERE_REST_TEST_CLIENT}
      - PGHOST=${POSTGRES_HOST}
      - PGPORT=${POSTGRES_PORT}
      - PGDATABASE=${DB_NAME}
      - PGUSER=adempiere
      - PGPASSWORD=${IDEMPIERE_DATABASE_PASSWORD}
    entrypoint: [tail, -f, /dev/null]
