services:
  idempiere:
    image: ghcr.io/banda-health/banda-idempiere:${IDEMPIERE_VERSION}
    depends_on:
      - postgres
    volumes:
      - ./testing:${INSTALLATION_HOME}
    environment:
      - DB_ADMIN_PASS=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${IDEMPIERE_DATABASE_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
      - IDEMPIERE_FRESH_DB=${IDEMPIERE_FRESH_DB}
      - IDEMPIERE_VERSION=${IDEMPIERE_VERSION}
      - MIGRATE_EXISTING_DATABASE=${MIGRATE_EXISTING_DATABASE}
      - GENERATE_PLUGIN_BUNDLE_INFO=${GENERATE_PLUGIN_BUNDLE_INFO}
      - HEALTHY_AFTER_PLUGINS_START=${HEALTHY_AFTER_PLUGINS_START}
      - INSTALLATION_HOME=${INSTALLATION_HOME}
    ports:
      - ${IDEMPIERE_PORT}:8080
      - ${IDEMPIERE_SSL_PORT}:8443
      - ${TELNET_PORT}:12612

  tests:
    build: .
    depends_on:
      idempiere:
        condition: service_healthy
    environment:
      - IDEMPIERE_ENDPOINT=${IDEMPIERE_ENDPOINT}
      - IDEMPIERE_REST_TEST_CLIENT=${IDEMPIERE_REST_TEST_CLIENT}
      - IDEMPIERE_USER=${IDEMPIERE_USER}
      - IDEMPIERE_USER_PASSWORD=${IDEMPIERE_USER_PASSWORD}
      - PGHOST=${POSTGRES_HOST}
      - PGPORT=${POSTGRES_PORT}
      - PGDATABASE=${DB_NAME}
      - PGUSER=adempiere
      - PGPASSWORD=${IDEMPIERE_DATABASE_PASSWORD}

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
