export enum RoleName {
	Accounting = 'Accounting',
	Admin = 'Admin',
	CashierRegistrationAdvanced = 'Cashier/Registration Advanced',
	CashierRegistrationBasic = 'Cashier/Registration Basic',
	CashierRegistrationBasicPlus = 'Cashier/Registration Basic+',
	ClinicAdmin = 'Clinic Admin',
	ClinicianNurseAdvanced = 'Clinician/Nurse Advanced',
	ClinicianNurseBasic = 'Clinician/Nurse Basic',
	ClinicUser = 'Clinic User',
	Implementer = 'Implementer',
	InventoryPharmacyAdvanced = 'Inventory/Pharmacy Advanced',
	InventoryPharmacyBasic = 'Inventory/Pharmacy Basic',
	LabRadiologyAdvanced = 'Lab/Radiology Advanced',
	LabRadiologyBasic = 'Lab/Radiology Basic',
	OtcOnly = 'OTC Only',
	Registration = 'Registration',
	Triage = 'Triage',
}
