package org.bandahealth.idempiere.rest.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.bandahealth.idempiere.base.model.MAttributeSet_BH;

public class AttributeSet extends BaseEntity {
	@JsonProperty("isSerialNumber")
	private boolean isSerialNumber;
	@JsonIgnore
	private Integer serialNumberControlId;
	private SerialNumberControl serialNumberControl;
	@JsonProperty("isLot")
	private boolean isLot;
	//	private LotControl lotControl;
	@JsonProperty("isGuaranteeDate")
	private boolean isGuaranteeDate;
	private int guaranteeDays;
	@JsonProperty("isInstanceAttribute")
	private boolean isInstanceAttribute;
	@JsonIgnore
	private String mandatoryTypeValue;
	private ReferenceList mandatoryType;
	@JsonProperty("isGuaranteeDateMandatory")
	private boolean isGuaranteeDateMandatory;
	@JsonProperty("isLotMandatory")
	private boolean isLotMandatory;
	@JsonProperty("isSerialNumberMandatory")
	private boolean isSerialNumberMandatory;
	private String serialNumberStartCharacterOverwrite;
	private String serialNumberEndCharacterOverwrite;
	private String lotStartCharacterOverwrite;
	private String lotEndCharacterOverwrite;
	@JsonProperty("useGuaranteeDateForMaterialPolicy")
	private boolean useGuaranteeDateForMaterialPolicy;
	@JsonProperty("isAutoGeneratedLot")
	private boolean isAutoGeneratedLot;
	private String type;
	@JsonProperty("isLocked")
	private boolean isLocked;

	public AttributeSet() {}

	public AttributeSet(MAttributeSet_BH model) {
		super(model, model.getName(), model.getDescription(), null);
		this.isSerialNumber = model.isSerNo();
		this.isLot = model.isLot();
		this.isGuaranteeDate = model.isGuaranteeDate();
		this.guaranteeDays = model.getGuaranteeDays();
		this.isInstanceAttribute = model.isInstanceAttribute();
		this.isGuaranteeDateMandatory = model.isGuaranteeDateMandatory();
		this.isLotMandatory = model.isLotMandatory();
		this.isSerialNumberMandatory = model.isSerNoMandatory();
		this.serialNumberStartCharacterOverwrite = model.getSerNoCharSOverwrite();
		this.serialNumberEndCharacterOverwrite = model.getSerNoCharEOverwrite();
		this.lotStartCharacterOverwrite = model.getLotCharSOverwrite();
		this.lotEndCharacterOverwrite = model.getLotCharEOverwrite();
		this.useGuaranteeDateForMaterialPolicy = model.isUseGuaranteeDateForMPolicy();
		this.isAutoGeneratedLot = model.isAutoGenerateLot();
		// Only works in iDempiere v8.2+
		//this.type = model.getM_AttributeSet_Type();
		this.serialNumberControlId = model.getM_SerNoCtl_ID() == 0 ? null : model.getM_SerNoCtl_ID();
		this.mandatoryTypeValue = model.getMandatoryType();
		this.isLocked = model.isBH_Locked();
	}

	public boolean isSerialNumber() {
		return isSerialNumber;
	}

	public void setSerialNumber(boolean serialNumber) {
		isSerialNumber = serialNumber;
	}

	public SerialNumberControl getSerialNumberControl() {
		return serialNumberControl;
	}

	public void setSerialNumberControl(SerialNumberControl serialNumberControl) {
		this.serialNumberControl = serialNumberControl;
	}

	public boolean isLot() {
		return isLot;
	}

	public void setLot(boolean lot) {
		isLot = lot;
	}

	public boolean isGuaranteeDate() {
		return isGuaranteeDate;
	}

	public void setGuaranteeDate(boolean guaranteeDate) {
		isGuaranteeDate = guaranteeDate;
	}

	public int getGuaranteeDays() {
		return guaranteeDays;
	}

	public void setGuaranteeDays(int guaranteeDays) {
		this.guaranteeDays = guaranteeDays;
	}

	public boolean isInstanceAttribute() {
		return isInstanceAttribute;
	}

	public void setInstanceAttribute(boolean instanceAttribute) {
		isInstanceAttribute = instanceAttribute;
	}

	public ReferenceList getMandatoryType() {
		return mandatoryType;
	}

	public void setMandatoryType(ReferenceList mandatoryType) {
		this.mandatoryType = mandatoryType;
	}

	public boolean isGuaranteeDateMandatory() {
		return isGuaranteeDateMandatory;
	}

	public void setGuaranteeDateMandatory(boolean guaranteeDateMandatory) {
		isGuaranteeDateMandatory = guaranteeDateMandatory;
	}

	public boolean isLotMandatory() {
		return isLotMandatory;
	}

	public void setLotMandatory(boolean lotMandatory) {
		isLotMandatory = lotMandatory;
	}

	public boolean isSerialNumberMandatory() {
		return isSerialNumberMandatory;
	}

	public void setSerialNumberMandatory(boolean serialNumberMandatory) {
		isSerialNumberMandatory = serialNumberMandatory;
	}

	public String getSerialNumberStartCharacterOverwrite() {
		return serialNumberStartCharacterOverwrite;
	}

	public void setSerialNumberStartCharacterOverwrite(String serialNumberStartCharacterOverwrite) {
		this.serialNumberStartCharacterOverwrite = serialNumberStartCharacterOverwrite;
	}

	public String getSerialNumberEndCharacterOverwrite() {
		return serialNumberEndCharacterOverwrite;
	}

	public void setSerialNumberEndCharacterOverwrite(String serialNumberEndCharacterOverwrite) {
		this.serialNumberEndCharacterOverwrite = serialNumberEndCharacterOverwrite;
	}

	public String getLotStartCharacterOverwrite() {
		return lotStartCharacterOverwrite;
	}

	public void setLotStartCharacterOverwrite(String lotStartCharacterOverwrite) {
		this.lotStartCharacterOverwrite = lotStartCharacterOverwrite;
	}

	public String getLotEndCharacterOverwrite() {
		return lotEndCharacterOverwrite;
	}

	public void setLotEndCharacterOverwrite(String lotEndCharacterOverwrite) {
		this.lotEndCharacterOverwrite = lotEndCharacterOverwrite;
	}

	public boolean isUseGuaranteeDateForMaterialPolicy() {
		return useGuaranteeDateForMaterialPolicy;
	}

	public void setUseGuaranteeDateForMaterialPolicy(boolean useGuaranteeDateForMaterialPolicy) {
		this.useGuaranteeDateForMaterialPolicy = useGuaranteeDateForMaterialPolicy;
	}

	public boolean isAutoGeneratedLot() {
		return isAutoGeneratedLot;
	}

	public void setAutoGeneratedLot(boolean autoGeneratedLot) {
		isAutoGeneratedLot = autoGeneratedLot;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getSerialNumberControlId() {
		return serialNumberControlId;
	}

	public void setSerialNumberControlId(Integer serialNumberControlId) {
		this.serialNumberControlId = serialNumberControlId;
	}

	public String getMandatoryTypeValue() {
		return mandatoryTypeValue;
	}

	public void setMandatoryTypeValue(String mandatoryTypeValue) {
		this.mandatoryTypeValue = mandatoryTypeValue;
	}

	public boolean isLocked() {
		return isLocked;
	}

	public void setLocked(boolean locked) {
		isLocked = locked;
	}
}
