import { v4 } from 'uuid';
import { mutate, query } from '../api';
import { createBusinessPartner, createProduct, createVisit } from '../utils';

// Documents are generated by `pnpm run generate` after migrate + server restart.
import {
	Ad_Ref_ListGetDocument,
	Bh_Visit_Family_Planning_Larc_Removal_ReasonSaveDocument,
	Bh_Visit_Family_Planning_ProductSaveDocument,
	Bh_Visit_Family_PlanningSaveDocument,
	Bh_VisitWithFamilyPlanningDocument,
} from '../__generated__/graphql';

const refListByReferenceName = async (valueObject: typeof globalThis.__VALUE_OBJECT__, referenceName: string, value: string) => {
	const { data } = await query(valueObject)({
		query: Ad_Ref_ListGetDocument,
		variables: {
			Filter: JSON.stringify({
				ad_reference: { name: referenceName },
				value,
				isactive: true,
			}),
		},
	});
	return data.AD_Ref_ListGet.Results[0];
};

test('family planning visit save and load round-trip', async () => {
	const valueObject = globalThis.__VALUE_OBJECT__;
	await valueObject.login();

	await createBusinessPartner(valueObject);
	valueObject.salesStandardPrice = 10;
	valueObject.stepName = 'Create product 1';
	await createProduct(valueObject);
	const product1 = valueObject.product!;

	valueObject.stepName = 'Create product 2';
	valueObject.clearProduct();
	await createProduct(valueObject);
	const product2 = valueObject.product!;

	await createVisit(valueObject);
	const visitUU = valueObject.visit!.UU;
	const fpUU = v4();

	const yesRef = await refListByReferenceName(valueObject, 'BH_FP_YesNo', 'yes');
	const hivRef = await refListByReferenceName(valueObject, 'BH_FP_Hiv_Counseled_Tested', 'yes');
	const ipvRef = await refListByReferenceName(valueObject, 'BH_FP_Ipv', 'noGbv');
	const oralMethodRef = await refListByReferenceName(valueObject, 'BH_FP_Fp_Method', 'oralContraceptive');
	const injectableMethodRef = await refListByReferenceName(valueObject, 'BH_FP_Fp_Method', 'injectable');
	const maturityRef = await refListByReferenceName(valueObject, 'BH_FP_Larc_Removal_Reason', 'maturity');
	const methodSwitchRef = await refListByReferenceName(valueObject, 'BH_FP_Larc_Removal_Reason', 'methodSwitch');

	await mutate(valueObject)({
		mutation: Bh_Visit_Family_PlanningSaveDocument,
		variables: {
			Entity: {
				UU: fpUU,
				BH_Visit: { UU: visitUU },
				BH_Contraceptive_Oral: true,
				BH_Contraceptive_Injectable: true,
				BH_Screening_Tb: true,
				BH_Screening_Hiv: true,
				BH_First_Ever_Contraceptive_User: { UU: yesRef.UU },
				BH_Hiv_Counseled_Tested: { UU: hivRef.UU },
				BH_Ipv_Reproductive_Coercion: { UU: ipvRef.UU },
				BH_Emergency_Contraception_Notes: 'gave EC counseling',
				BH_Remarks: 'routine FP visit',
			},
		},
	});

	const productUU1 = product1.UU;
	const productUU2 = product2.UU;

	await mutate(valueObject)({
		mutation: Bh_Visit_Family_Planning_ProductSaveDocument,
		variables: {
			Entity: {
				UU: v4(),
				BH_Visit_Family_Planning: { UU: fpUU },
				M_Product: { UU: productUU1 },
				BH_Fp_Method: { UU: oralMethodRef.UU },
				QtyEntered: 2,
			},
		},
	});
	await mutate(valueObject)({
		mutation: Bh_Visit_Family_Planning_ProductSaveDocument,
		variables: {
			Entity: {
				UU: v4(),
				BH_Visit_Family_Planning: { UU: fpUU },
				M_Product: { UU: productUU2 },
				BH_Fp_Method: { UU: injectableMethodRef.UU },
				QtyEntered: 1,
			},
		},
	});

	await mutate(valueObject)({
		mutation: Bh_Visit_Family_Planning_Larc_Removal_ReasonSaveDocument,
		variables: {
			Entity: {
				UU: v4(),
				BH_Visit_Family_Planning: { UU: fpUU },
				BH_Larc_Removal_Reason: { UU: maturityRef.UU },
			},
		},
	});
	await mutate(valueObject)({
		mutation: Bh_Visit_Family_Planning_Larc_Removal_ReasonSaveDocument,
		variables: {
			Entity: {
				UU: v4(),
				BH_Visit_Family_Planning: { UU: fpUU },
				BH_Larc_Removal_Reason: { UU: methodSwitchRef.UU },
			},
		},
	});

	const visit = (await query(valueObject)({ query: Bh_VisitWithFamilyPlanningDocument, variables: { UU: visitUU } }))
		.data.BH_Visit!;
	const fp = visit.BH_Visit_Family_Planning!;

	expect(fp.UU).toBe(fpUU);
	expect(fp.BH_Contraceptive_Oral).toBe(true);
	expect(fp.BH_Contraceptive_Injectable).toBe(true);
	expect(fp.BH_Screening_Tb).toBe(true);
	expect(fp.BH_Screening_Hiv).toBe(true);
	expect(fp.BH_Hiv_Counseled_Tested?.Value).toBe('yes');
	expect(fp.BH_Ipv_Reproductive_Coercion?.Value).toBe('noGbv');
	expect(fp.BH_Emergency_Contraception_Notes).toBe('gave EC counseling');
	expect(fp.BH_Remarks).toBe('routine FP visit');
	expect(fp.BH_Visit_Family_Planning_Products).toHaveLength(2);
	expect(fp.BH_Larc_Removal_Reasons).toHaveLength(2);
});
