fragment AD_RoleFields on AD_Role {
	UUID
	IsMasterRole
	AD_Role_IncludedList {
		UUID
		Included_Role {
			UUID
		}
	}
	Name
}

fragment BH_VisitFields on BH_Visit {
	BH_VisitDate
	Description
	DocumentNo
	UUID
	Patient {
		UUID
		Name
	}
	BH_Encounters {
		UUID
		BH_Encounter_DiagnosisList {
			UUID
			BH_Coded_Diagnosis {
				UUID
			}
			BH_Uncoded_Diagnosis
		}
		BH_Observations {
			UUID
			BH_Value
		}
	}
	C_Orders {
		UUID
		DocStatus {
			UUID
			Value
		}
		C_OrderLines {
			UUID
		}
	}
	C_Invoices {
		UUID
		DocStatus {
			UUID
			Value
		}
		C_BPartner {
			UUID
		}
		C_InvoiceLines {
			UUID
			PriceActual
			C_OrderLine {
				UUID
			}
		}
	}
	C_Payments {
		UUID
		BH_tender_amount
		DocStatus {
			UUID
			Value
		}
		PayAmt
	}
}

fragment C_BPartnerFields on C_BPartner {
	BH_Birthday
	bh_gender {
		UUID
		Value
	}
	bh_occupation
	BH_Payer_Info_FldList {
		UUID
		BH_PayerInfoFieldDataType {
			UUID
			Value
		}
	}
	C_BP_Group {
		Name
		UUID
		AssociatedCustomerReceivablesCharge {
			UUID
		}
	}
	C_BPartner_Locations {
		UUID
		C_Location {
			Address1
		}
	}
	Description
	UUID
	IsCustomer
	IsVendor
	LastVisitDate
	Name
	NationalID
	NextOfKin_Contact
	NextOfKin_Name
	TotalOpenBalance
	TotalVisits
}

fragment C_LocationFields on C_Location {
	C_Country {
		UUID
	}
	C_Region {
		UUID
		Name
	}
	UUID
}

fragment C_InvoiceFields on C_Invoice {
	C_Currency {
		UUID
	}
	DocStatus {
		Value
	}
	GrandTotal
	UUID
}

fragment C_OrderFields on C_Order {
	C_Currency {
		UUID
	}
	DocStatus {
		Value
	}
	GrandTotal
	UUID
}

fragment C_PaymentFields on C_Payment {
	BH_tender_amount
	DocStatus {
		Value
	}
	PayAmt
	TenderType {
		UUID
		Name
		Value
	}
	UUID
}

fragment M_InventoryFields on M_Inventory {
	DocStatus {
		Value
	}
	UUID
}

fragment M_MovementFields on M_Movement {
	DocStatus {
		Value
	}
	UUID
}

fragment M_ProductFields on M_Product {
	BH_BuyPrice
	BH_SellPrice
	Description
	HasBeenPurchased
	LastPurchasePrice
	UUID
	Name
	M_Product_Category {
		UUID
	}
	TotalQuantity
}
