fragment AD_RoleFields on AD_Role {
	UUID
	IsMasterRole
	AD_Role_IncludedList {
		UUID
		Included_Role {
			UUID
		}
	}
	Name
}

fragment BH_VisitFields on BH_Visit {
	BH_VisitDate
	Description
	UUID
	Patient {
		UUID
		Name
	}
}

fragment C_BPartnerFields on C_BPartner {
	BH_Birthday
	bh_gender {
		UUID
		Value
	}
	bh_occupation
	C_BP_Group {
		Name
		UUID
	}
	C_BPartner_Locations {
		UUID
		C_Location {
			Address1
		}
	}
	Description
	UUID
	IsCustomer
	IsVendor
	LastVisitDate
	Name
	NationalID
	NextOfKin_Contact
	NextOfKin_Name
	TotalOpenBalance
	TotalVisits
}

fragment C_LocationFields on C_Location {
	C_Country {
		UUID
	}
	C_Region {
		UUID
		Name
	}
	UUID
}

fragment C_InvoiceFields on C_Invoice {
	C_Currency {
		UUID
	}
	DocStatus {
		Value
	}
	GrandTotal
	UUID
}

fragment C_OrderFields on C_Order {
	C_Currency {
		UUID
	}
	DocStatus {
		Value
	}
	GrandTotal
	UUID
}

fragment C_PaymentFields on C_Payment {
	BH_tender_amount
	DocStatus {
		Value
	}
	PayAmt
	TenderType {
		UUID
		Name
		Value
	}
	UUID
}

fragment M_InventoryFields on M_Inventory {
	DocStatus {
		Value
	}
	UUID
}

fragment M_MovementFields on M_Movement {
	DocStatus {
		Value
	}
	UUID
}

fragment M_ProductFields on M_Product {
	BH_BuyPrice
	BH_SellPrice
	Description
	HasBeenPurchased
	LastPurchasePrice
	UUID
	Name
	M_Product_Category {
		UUID
	}
	TotalQuantity
}
