mutation LogoAndAD_OrgInfoSave($logo: AD_ImageInput!, $AD_OrgInfo: AD_OrgInfoInput!) {
	AD_ImageSave(entity: $logo) {
		UUID
	}
	AD_OrgInfoSave(entity: $AD_OrgInfo) {
		UUID
	}
}

mutation AD_OrgInfoSave($AD_OrgInfo: AD_OrgInfoInput!) {
	AD_OrgInfoSave(entity: $AD_OrgInfo) {
		UUID
	}
}

mutation AD_ProcessRun($UUID: ID!, $ProcessInfoParameterList: [ProcessInfoParameterInput!]) {
	AD_ProcessRun(UUID: $UUID, ProcessInfoParameterList: $ProcessInfoParameterList)
}

mutation AD_ProcessRunAndExport(
	$UUID: ID!
	$ProcessInfoParameterList: [ProcessInfoParameterInput!]
	$ReportType: ReportOutput!
) {
	AD_ProcessRunAndExport(UUID: $UUID, ProcessInfoParameterList: $ProcessInfoParameterList, ReportType: $ReportType)
}

mutation AD_Role_IncludedSaveMany($entities: [AD_Role_IncludedInput!]!) {
	AD_Role_IncludedSaveMany(entities: $entities) {
		UUID
	}
}

mutation AD_Role_IncludedDelete($uuids: [String!]!) {
	AD_Role_IncludedDelete(uuids: $uuids)
}

mutation AD_RoleSave($entity: AD_RoleInput!) {
	AD_RoleSave(entity: $entity) {
		...AD_RoleFields
	}
}

mutation AD_RoleWithIncludedSave($AD_Role: AD_RoleInput!, $AD_Role_IncludedList: [AD_Role_IncludedInput!]!) {
	AD_RoleSave(entity: $AD_Role) {
		...AD_RoleFields
	}
	AD_Role_IncludedSaveMany(entities: $AD_Role_IncludedList) {
		UUID
	}
}

mutation AD_User_RolesDelete($uuids: [String!]!) {
	AD_User_RolesDelete(uuids: $uuids)
}

mutation AD_User_RolesSaveAndDeleteMany(
	$AD_User_Roles: [AD_User_RolesInput!]!
	$AD_User_Role_UUIDs_To_Delete: [String!]!
) {
	AD_User_RolesSaveMany(entities: $AD_User_Roles) {
		UUID
	}
	AD_User_RolesDelete(uuids: $AD_User_Role_UUIDs_To_Delete)
}

mutation AD_User_RolesSaveMany($AD_User_Roles: [AD_User_RolesInput!]!) {
	AD_User_RolesSaveMany(entities: $AD_User_Roles) {
		UUID
	}
}

mutation AD_UserWithRoleSave($AD_User: AD_UserInput!, $AD_User_Roles: [AD_User_RolesInput!]!) {
	AD_UserSave(entity: $AD_User) {
		UUID
		Name
		IsActive
		AD_User_Roles {
			UUID
		}
	}
	AD_User_RolesSaveMany(entities: $AD_User_Roles) {
		UUID
	}
}

mutation AD_UserWithRoleSaveAndDelete(
	$AD_User: AD_UserInput!
	$AD_User_Roles: [AD_User_RolesInput!]!
	$AD_User_RoleUUIDSToDelete: [String!]!
) {
	AD_UserSave(entity: $AD_User) {
		UUID
	}
	AD_User_RolesSaveMany(entities: $AD_User_Roles) {
		UUID
	}
	AD_User_RolesDelete(uuids: $AD_User_RoleUUIDSToDelete)
}

mutation BH_EncounterDelete($UUIDS: [String!]!) {
	BH_EncounterDelete(uuids: $UUIDS)
}

mutation BH_EncounterAndObservationsSaveMany(
	$BH_Encounters: [BH_EncounterInput!]!
	$BH_Observations: [BH_ObservationInput!]!
) {
	BH_EncounterSaveMany(entities: $BH_Encounters) {
		UUID
	}
	BH_ObservationSaveMany(entities: $BH_Observations) {
		UUID
	}
}

mutation BH_EncounterObservationsAndEncounterDiagnosesSaveMany(
	$BH_Encounters: [BH_EncounterInput!]!
	$BH_Observations: [BH_ObservationInput!]!
	$BH_EncounterDiagnoses: [BH_Encounter_DiagnosisInput!]!
) {
	BH_EncounterSaveMany(entities: $BH_Encounters) {
		UUID
	}
	BH_ObservationSaveMany(entities: $BH_Observations) {
		UUID
	}
	BH_Encounter_DiagnosisSaveMany(entities: $BH_EncounterDiagnoses) {
		UUID
	}
}

mutation BH_ObservationsDeleteAndSaveManyAndEncounterDiagnosesDelete(
	$BH_ObservationUuids: [String!]!
	$BH_EncounterDiagnosesUuids: [String!]!
	$BH_Observations: [BH_ObservationInput!]!
) {
	BH_ObservationDelete(uuids: $BH_ObservationUuids)
	BH_Encounter_DiagnosisDelete(uuids: $BH_EncounterDiagnosesUuids)
	BH_ObservationSaveMany(entities: $BH_Observations) {
		UUID
	}
}

mutation BH_ObservationsDeleteAndSaveManyAndEncounterDiagnosesSaveMany(
	$BH_ObservationUuids: [String!]!
	$BH_Observations: [BH_ObservationInput!]!
	$BH_EncounterDiagnoses: [BH_Encounter_DiagnosisInput!]!
) {
	BH_ObservationDelete(uuids: $BH_ObservationUuids)
	BH_ObservationSaveMany(entities: $BH_Observations) {
		UUID
	}
	BH_Encounter_DiagnosisSaveMany(entities: $BH_EncounterDiagnoses) {
		UUID
	}
}

mutation BH_VisitDeleteAll(
	$visitUuids: [String!]!
	$orderUuids: [String!]!
	$invoiceUuids: [String!]!
	$paymentUuids: [String!]!
) {
	C_PaymentDelete(uuids: $paymentUuids)
	C_InvoiceDelete(uuids: $invoiceUuids)
	C_OrderDelete(uuids: $orderUuids)
	BH_VisitDelete(uuids: $visitUuids)
}

mutation BH_VisitDelete($uuids: [String!]!) {
	BH_VisitDelete(uuids: $uuids)
}

mutation BH_VisitProcess($uuid: String!, $documentAction: String!) {
	BH_VisitProcess(uuid: $uuid, documentAction: $documentAction) {
		...BH_VisitFields
	}
}

mutation BH_VisitRemoveInsurancePayer(
	$C_Invoice_UUIDS: [String!]!
	$C_InvoiceLine_UUIDS: [String!]!
	$C_Payments: [C_PaymentInput!]!
) {
	C_InvoiceDelete(uuids: $C_Invoice_UUIDS)
	C_InvoiceLineDelete(uuids: $C_InvoiceLine_UUIDS)
	C_PaymentSaveMany(entities: $C_Payments) {
		UUID
	}
}

mutation BH_VisitSave($entity: BH_VisitInput!) {
	BH_VisitSave(entity: $entity) {
		...BH_VisitFields
	}
}

mutation BH_VisitSaveAndProcess($BH_Visit: BH_VisitInput!, $UUID: String!, $DocumentAction: String!) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	BH_VisitProcess(uuid: $UUID, documentAction: $DocumentAction) {
		UUID
	}
}

mutation BH_VisitSaveAndProcessWithOrders(
	$BH_Visit: BH_VisitInput!
	$C_Orders: [C_OrderInput!]!
	$UUID: String!
	$DocumentAction: String!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	BH_VisitProcess(uuid: $UUID, documentAction: $DocumentAction) {
		UUID
	}
}

mutation BH_VisitSaveAndProcessWithOrdersInvoicesAndPayments(
	$BH_Visit: BH_VisitInput!
	$C_Orders: [C_OrderInput!]!
	$C_OrderLines: [C_OrderLineInput!]!
	$C_Invoices: [C_InvoiceInput!]!
	$C_InvoiceLines: [C_InvoiceLineInput!]!
	$C_Payments: [C_PaymentInput!]!
	$UUID: String!
	$DocumentAction: String!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	C_OrderLineSaveMany(entities: $C_OrderLines) {
		UUID
	}
	C_InvoiceSaveMany(entities: $C_Invoices) {
		UUID
	}
	C_InvoiceLineSaveMany(entities: $C_InvoiceLines) {
		UUID
	}
	C_PaymentSaveMany(entities: $C_Payments) {
		UUID
	}
	BH_VisitProcess(uuid: $UUID, documentAction: $DocumentAction) {
		UUID
	}
}

mutation BH_VisitSaveWithEncountersObservationsOrdersInvoicesAndPayments(
	$BH_Visit: BH_VisitInput!
	$BH_Encounters: [BH_EncounterInput!]!
	$BH_EncounterDiagnoses: [BH_Encounter_DiagnosisInput!]!
	$BH_Observations: [BH_ObservationInput!]!
	$C_Orders: [C_OrderInput!]!
	$C_OrderLines: [C_OrderLineInput!]!
	$C_Invoices: [C_InvoiceInput!]!
	$C_InvoiceLines: [C_InvoiceLineInput!]!
	$C_Payments: [C_PaymentInput!]!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	BH_EncounterSaveMany(entities: $BH_Encounters) {
		UUID
	}
	BH_ObservationSaveMany(entities: $BH_Observations) {
		UUID
	}
	BH_Encounter_DiagnosisSaveMany(entities: $BH_EncounterDiagnoses) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	C_OrderLineSaveMany(entities: $C_OrderLines) {
		UUID
	}
	C_InvoiceSaveMany(entities: $C_Invoices) {
		UUID
	}
	C_InvoiceLineSaveMany(entities: $C_InvoiceLines) {
		UUID
	}
	C_PaymentSaveMany(entities: $C_Payments) {
		UUID
	}
}

mutation BH_VisitSaveWithEncountersOrdersAndInvoices(
	$BH_Visit: BH_VisitInput!
	$BH_Encounters: [BH_EncounterInput!]!
	$C_Orders: [C_OrderInput!]!
	$C_OrderLines: [C_OrderLineInput!]!
	$C_Invoices: [C_InvoiceInput!]!
	$C_InvoiceLines: [C_InvoiceLineInput!]!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	BH_EncounterSaveMany(entities: $BH_Encounters) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	C_OrderLineSaveMany(entities: $C_OrderLines) {
		UUID
	}
	C_InvoiceSaveMany(entities: $C_Invoices) {
		UUID
	}
	C_InvoiceLineSaveMany(entities: $C_InvoiceLines) {
		UUID
	}
}

mutation BH_VisitSaveWithEncountersObservationsOrdersInvoicesInsuranceAndPayments(
	$BH_Visit: BH_VisitInput!
	$BH_Encounters: [BH_EncounterInput!]!
	$BH_EncounterDiagnoses: [BH_Encounter_DiagnosisInput!]!
	$BH_Observations: [BH_ObservationInput!]!
	$C_Orders: [C_OrderInput!]!
	$C_OrderLines: [C_OrderLineInput!]!
	$C_Invoices: [C_InvoiceInput!]!
	$C_InvoiceLines: [C_InvoiceLineInput!]!
	$BH_BP_Specific_Payer_InfoList: [BH_BP_Specific_Payer_InfoInput!]!
	$C_Payments: [C_PaymentInput!]!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	BH_EncounterSaveMany(entities: $BH_Encounters) {
		UUID
	}
	BH_ObservationSaveMany(entities: $BH_Observations) {
		UUID
	}
	BH_Encounter_DiagnosisSaveMany(entities: $BH_EncounterDiagnoses) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	C_OrderLineSaveMany(entities: $C_OrderLines) {
		UUID
	}
	C_InvoiceSaveMany(entities: $C_Invoices) {
		UUID
	}
	C_InvoiceLineSaveMany(entities: $C_InvoiceLines) {
		UUID
	}
	BH_BP_Specific_Payer_InfoSaveMany(entities: $BH_BP_Specific_Payer_InfoList) {
		UUID
	}
	C_PaymentSaveMany(entities: $C_Payments) {
		UUID
	}
}

mutation BH_VisitSaveWithOrdersInvoicesAndPayments(
	$BH_Visit: BH_VisitInput!
	$C_Orders: [C_OrderInput!]!
	$C_OrderLines: [C_OrderLineInput!]!
	$C_Invoices: [C_InvoiceInput!]!
	$C_InvoiceLines: [C_InvoiceLineInput!]!
	$C_Payments: [C_PaymentInput!]!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	C_OrderLineSaveMany(entities: $C_OrderLines) {
		UUID
	}
	C_InvoiceSaveMany(entities: $C_Invoices) {
		UUID
	}
	C_InvoiceLineSaveMany(entities: $C_InvoiceLines) {
		UUID
	}
	C_PaymentSaveMany(entities: $C_Payments) {
		UUID
	}
}

mutation BH_VisitSaveWithOrdersInvoicesPayerInformationAndPayments(
	$BH_Visit: BH_VisitInput!
	$C_Orders: [C_OrderInput!]!
	$C_OrderLines: [C_OrderLineInput!]!
	$C_Invoices: [C_InvoiceInput!]!
	$C_InvoiceLines: [C_InvoiceLineInput!]!
	$BH_BP_Specific_Payer_InfoList: [BH_BP_Specific_Payer_InfoInput!]!
	$C_Payments: [C_PaymentInput!]!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	C_OrderLineSaveMany(entities: $C_OrderLines) {
		UUID
	}
	C_InvoiceSaveMany(entities: $C_Invoices) {
		UUID
	}
	C_InvoiceLineSaveMany(entities: $C_InvoiceLines) {
		UUID
	}
	BH_BP_Specific_Payer_InfoSaveMany(entities: $BH_BP_Specific_Payer_InfoList) {
		UUID
	}
	C_PaymentSaveMany(entities: $C_Payments) {
		UUID
	}
}

mutation BH_VisitSaveWithOrdersAndInvoices(
	$BH_Visit: BH_VisitInput!
	$C_Orders: [C_OrderInput!]!
	$C_Invoices: [C_InvoiceInput!]!
) {
	BH_VisitSave(entity: $BH_Visit) {
		UUID
	}
	C_OrderSaveMany(entities: $C_Orders) {
		UUID
	}
	C_InvoiceSaveMany(entities: $C_Invoices) {
		UUID
	}
}

mutation BH_VisitSaveWithPayments($BH_Visit: BH_VisitInput!, $C_Payments: [C_PaymentInput!]!) {
	BH_VisitSave(entity: $BH_Visit) {
		...BH_VisitFields
	}
	C_PaymentSaveMany(entities: $C_Payments) {
		...C_PaymentFields
	}
}

mutation C_BPartner_LocationSave($entity: C_BPartner_LocationInput!) {
	C_BPartner_LocationSave(entity: $entity) {
		UUID
	}
}

mutation C_BPartnerSave($entity: C_BPartnerInput!) {
	C_BPartnerSave(entity: $entity) {
		...C_BPartnerFields
	}
}

mutation C_BPartnerSaveWithLocation(
	$C_BPartner: C_BPartnerInput!
	$C_Location: C_LocationInput!
	$C_BPartner_Location: C_BPartner_LocationInput!
) {
	C_BPartnerSave(entity: $C_BPartner) {
		...C_BPartnerFields
	}
	C_LocationSave(entity: $C_Location) {
		...C_LocationFields
	}
	C_BPartner_LocationSave(entity: $C_BPartner_Location) {
		UUID
	}
}

mutation C_Charge_AcctSave($entity: C_Charge_AcctInput!) {
	C_Charge_AcctSave(entity: $entity) {
		UUID
	}
}

mutation C_ChargeSave($entity: C_ChargeInput!) {
	C_ChargeSave(entity: $entity) {
		Description
		UUID
		Name
		C_Charge_AcctList {
			UUID
			C_AcctSchema {
				UUID
			}
		}
	}
}

mutation C_LocationSave($entity: C_LocationInput!) {
	C_LocationSave(entity: $entity) {
		...C_LocationFields
	}
}

mutation C_LocationUpdateWithBPartner(
	$C_BPartner: C_BPartnerInput!
	$C_Location: C_LocationInput!
	$C_BPartner_Location: C_BPartner_LocationInput!
) {
	C_LocationSave(entity: $C_Location) {
		...C_LocationFields
	}
	C_BPartner_LocationSave(entity: $C_BPartner_Location) {
		UUID
	}
	C_BPartnerSave(entity: $C_BPartner) {
		...C_BPartnerFields
	}
}

mutation C_InvoiceAndOrderLineDelete($C_OrderLineUUIDS: [String!]!, $C_InvoiceLineUUIDS: [String!]!) {
	C_InvoiceLineDelete(uuids: $C_InvoiceLineUUIDS)
	C_OrderLineDelete(uuids: $C_OrderLineUUIDS)
}

mutation C_InvoiceDelete($uuids: [String!]!) {
	C_InvoiceDelete(uuids: $uuids)
}

mutation C_InvoiceSaveWithInvoiceLines($C_Invoice: C_InvoiceInput!, $C_InvoiceLine: C_InvoiceLineInput!) {
	C_InvoiceSave(entity: $C_Invoice) {
		...C_InvoiceFields
	}
	C_InvoiceLineSave(entity: $C_InvoiceLine) {
		UUID
	}
}

mutation C_InvoiceProcess($uuid: String!, $documentAction: String!) {
	C_InvoiceProcess(uuid: $uuid, documentAction: $documentAction) {
		...C_InvoiceFields
	}
}

mutation C_OrderLineDelete($UUIDS: [String!]!) {
	C_OrderLineDelete(uuids: $UUIDS)
}

mutation C_OrderLineSave($entity: C_OrderLineInput!) {
	C_OrderLineSave(entity: $entity) {
		UUID
	}
}

mutation C_OrderProcess($uuid: String!, $documentAction: String!) {
	C_OrderProcess(uuid: $uuid, documentAction: $documentAction) {
		...C_OrderFields
	}
}

mutation C_OrderSave($entity: C_OrderInput!) {
	C_OrderSave(entity: $entity) {
		...C_OrderFields
	}
}

mutation C_OrderSaveWithOrderLines($C_Order: C_OrderInput!, $C_OrderLine: C_OrderLineInput!) {
	C_OrderSave(entity: $C_Order) {
		...C_OrderFields
	}
	C_OrderLineSave(entity: $C_OrderLine) {
		UUID
	}
}

mutation C_PaymentProcess($uuid: String!, $documentAction: String!) {
	C_PaymentProcess(uuid: $uuid, documentAction: $documentAction) {
		...C_PaymentFields
	}
}

mutation C_PaymentDelete($uuids: [String!]!) {
	C_PaymentDelete(uuids: $uuids)
}

mutation C_PaymentSave($entity: C_PaymentInput!) {
	C_PaymentSave(entity: $entity) {
		...C_PaymentFields
	}
}

mutation C_PaymentSaveMany($entities: [C_PaymentInput!]!) {
	C_PaymentSaveMany(entities: $entities) {
		UUID
	}
}

mutation C_ValidCombinationGetOrCreate(
	$AD_Org_UU: String
	$C_AcctSchema_UU: String
	$Account_UU: String
	$C_SubAcct_UU: String
	$M_Product_UU: String
	$C_BPartner_UU: String
	$AD_OrgTrx_UU: String
	$C_LocFrom_UU: String
	$C_LocTo_UU: String
	$C_SalesRegion_UU: String
	$C_Project_UU: String
	$C_Campaign_UU: String
	$C_Activity_UU: String
	$User1_UU: String
	$User2_UU: String
	$UserElement1_UU: String
	$UserElement2_UU: String
) {
	C_ValidCombinationGetOrCreate(
		AD_Org_UU: $AD_Org_UU
		C_AcctSchema_UU: $C_AcctSchema_UU
		Account_UU: $Account_UU
		C_SubAcct_UU: $C_SubAcct_UU
		M_Product_UU: $M_Product_UU
		C_BPartner_UU: $C_BPartner_UU
		AD_OrgTrx_UU: $AD_OrgTrx_UU
		C_LocFrom_UU: $C_LocFrom_UU
		C_LocTo_UU: $C_LocTo_UU
		C_SalesRegion_UU: $C_SalesRegion_UU
		C_Project_UU: $C_Project_UU
		C_Campaign_UU: $C_Campaign_UU
		C_Activity_UU: $C_Activity_UU
		User1_UU: $User1_UU
		User2_UU: $User2_UU
		UserElement1_UU: $UserElement1_UU
		UserElement2_UU: $UserElement2_UU
	) {
		UUID
	}
}

mutation M_AttributeSetInstanceSave($entity: M_AttributeSetInstanceInput!) {
	M_AttributeSetInstanceSave(entity: $entity) {
		UUID
	}
}

mutation M_InventoryProcess($uuid: String!, $documentAction: String!) {
	M_InventoryProcess(uuid: $uuid, documentAction: $documentAction) {
		...M_InventoryFields
	}
}

mutation M_InventorySave($entity: M_InventoryInput!) {
	M_InventorySave(entity: $entity) {
		...M_InventoryFields
	}
}

mutation M_InventorySaveWithInventoryLines($M_Inventory: M_InventoryInput!, $M_InventoryLine: M_InventoryLineInput!) {
	M_InventorySave(entity: $M_Inventory) {
		...M_InventoryFields
	}
	M_InventoryLineSave(entity: $M_InventoryLine) {
		UUID
	}
}

mutation M_MovementProcess($uuid: String!, $documentAction: String!) {
	M_MovementProcess(uuid: $uuid, documentAction: $documentAction) {
		...M_MovementFields
	}
}

mutation M_MovementSave($entity: M_MovementInput!) {
	M_MovementSave(entity: $entity) {
		...M_MovementFields
	}
}

mutation M_MovementSaveWithMovementLinesAndProcess(
	$M_Movement: M_MovementInput!
	$M_MovementLine: M_MovementLineInput!
	$uuid: String!
	$documentAction: String!
) {
	M_MovementSave(entity: $M_Movement) {
		...M_MovementFields
	}
	M_MovementLineSave(entity: $M_MovementLine) {
		UUID
	}
	M_MovementProcess(uuid: $uuid, documentAction: $documentAction) {
		...M_MovementFields
	}
}

mutation M_ProductSave($entity: M_ProductInput!) {
	M_ProductSave(entity: $entity) {
		...M_ProductFields
	}
}

mutation M_ProductSaveMany($entities: [M_ProductInput!]!) {
	M_ProductSaveMany(entities: $entities) {
		BH_BuyPrice
		BH_SellPrice
		Description
		UUID
		Name
		M_Product_Category {
			UUID
		}
	}
}
