mutation LogoAndAD_OrgInfoSave($logo: AD_ImageInput!, $AD_OrgInfo: AD_OrgInfoInput!) {
	AD_ImageSave(entity: $logo) {
		UUID
	}
	AD_OrgInfoSave(entity: $AD_OrgInfo) {
		UUID
	}
}

mutation AD_OrgInfoSave($AD_OrgInfo: AD_OrgInfoInput!) {
	AD_OrgInfoSave(entity: $AD_OrgInfo) {
		UUID
	}
}

mutation AD_ProcessRun($UUID: ID!, $ProcessInfoParameterList: [ProcessInfoParameterInput!]) {
	AD_ProcessRun(UUID: $UUID, ProcessInfoParameterList: $ProcessInfoParameterList)
}

mutation AD_ProcessRunAndExport(
	$UUID: ID!
	$ProcessInfoParameterList: [ProcessInfoParameterInput!]
	$ReportType: ReportOutput!
) {
	AD_ProcessRunAndExport(UUID: $UUID, ProcessInfoParameterList: $ProcessInfoParameterList, ReportType: $ReportType)
}

mutation AD_Role_IncludedSaveMany($entities: [AD_Role_IncludedInput!]!) {
	AD_Role_IncludedSaveMany(entities: $entities) {
		UUID
	}
}

mutation AD_Role_IncludedDelete($uuids: [String!]!) {
	AD_Role_IncludedDelete(uuids: $uuids)
}

mutation AD_RoleSave($entity: AD_RoleInput!) {
	AD_RoleSave(entity: $entity) {
		...AD_RoleFields
	}
}

mutation AD_RoleWithIncludedSave($AD_Role: AD_RoleInput!, $AD_Role_IncludedList: [AD_Role_IncludedInput!]!) {
	AD_RoleSave(entity: $AD_Role) {
		...AD_RoleFields
	}
	AD_Role_IncludedSaveMany(entities: $AD_Role_IncludedList) {
		UUID
	}
}

mutation BH_VisitProcess($uuid: String!, $documentAction: String!) {
	BH_VisitProcess(uuid: $uuid, documentAction: $documentAction) {
		...BH_VisitFields
	}
}

mutation BH_VisitSave($entity: BH_VisitInput!) {
	BH_VisitSave(entity: $entity) {
		...BH_VisitFields
	}
}

mutation BH_VisitSaveWithPayments($BH_Visit: BH_VisitInput!, $C_Payments: [C_PaymentInput!]!) {
	BH_VisitSave(entity: $BH_Visit) {
		...BH_VisitFields
	}
	C_PaymentSaveMany(entities: $C_Payments) {
		...C_PaymentFields
	}
}

mutation C_BPartner_LocationSave($entity: C_BPartner_LocationInput!) {
	C_BPartner_LocationSave(entity: $entity) {
		UUID
	}
}

mutation C_BPartnerSave($entity: C_BPartnerInput!) {
	C_BPartnerSave(entity: $entity) {
		...C_BPartnerFields
	}
}

mutation C_BPartnerSaveWithLocation(
	$C_BPartner: C_BPartnerInput!
	$C_Location: C_LocationInput!
	$C_BPartner_Location: C_BPartner_LocationInput!
) {
	C_BPartnerSave(entity: $C_BPartner) {
		...C_BPartnerFields
	}
	C_LocationSave(entity: $C_Location) {
		...C_LocationFields
	}
	C_BPartner_LocationSave(entity: $C_BPartner_Location) {
		UUID
	}
}

mutation C_Charge_AcctSave($entity: C_Charge_AcctInput!) {
	C_Charge_AcctSave(entity: $entity) {
		UUID
	}
}

mutation C_ChargeSave($entity: C_ChargeInput!) {
	C_ChargeSave(entity: $entity) {
		Description
		UUID
		Name
		C_Charge_AcctList {
			UUID
			C_AcctSchema {
				UUID
			}
		}
	}
}

mutation C_LocationSave($entity: C_LocationInput!) {
	C_LocationSave(entity: $entity) {
		...C_LocationFields
	}
}

mutation C_LocationUpdateWithBPartner(
	$C_BPartner: C_BPartnerInput!
	$C_Location: C_LocationInput!
	$C_BPartner_Location: C_BPartner_LocationInput!
) {
	C_LocationSave(entity: $C_Location) {
		...C_LocationFields
	}
	C_BPartner_LocationSave(entity: $C_BPartner_Location) {
		UUID
	}
	C_BPartnerSave(entity: $C_BPartner) {
		...C_BPartnerFields
	}
}

mutation C_InvoiceDelete($uuids: [String!]!) {
	C_InvoiceDelete(uuids: $uuids)
}

mutation C_InvoiceSaveWithInvoiceLines($C_Invoice: C_InvoiceInput!, $C_InvoiceLine: C_InvoiceLineInput!) {
	C_InvoiceSave(entity: $C_Invoice) {
		...C_InvoiceFields
	}
	C_InvoiceLineSave(entity: $C_InvoiceLine) {
		UUID
	}
}

mutation C_InvoiceProcess($uuid: String!, $documentAction: String!) {
	C_InvoiceProcess(uuid: $uuid, documentAction: $documentAction) {
		...C_InvoiceFields
	}
}

mutation C_OrderLineSave($entity: C_OrderLineInput!) {
	C_OrderLineSave(entity: $entity) {
		UUID
	}
}

mutation C_OrderProcess($uuid: String!, $documentAction: String!) {
	C_OrderProcess(uuid: $uuid, documentAction: $documentAction) {
		...C_OrderFields
	}
}

mutation C_OrderSave($entity: C_OrderInput!) {
	C_OrderSave(entity: $entity) {
		...C_OrderFields
	}
}

mutation C_OrderSaveWithOrderLines($C_Order: C_OrderInput!, $C_OrderLine: C_OrderLineInput!) {
	C_OrderSave(entity: $C_Order) {
		...C_OrderFields
	}
	C_OrderLineSave(entity: $C_OrderLine) {
		UUID
	}
}

mutation C_PaymentProcess($uuid: String!, $documentAction: String!) {
	C_PaymentProcess(uuid: $uuid, documentAction: $documentAction) {
		...C_PaymentFields
	}
}

mutation C_PaymentSave($entity: C_PaymentInput!) {
	C_PaymentSave(entity: $entity) {
		...C_PaymentFields
	}
}

mutation C_ValidCombinationGetOrCreate(
	$AD_Org_UU: String
	$C_AcctSchema_UU: String
	$Account_UU: String
	$C_SubAcct_UU: String
	$M_Product_UU: String
	$C_BPartner_UU: String
	$AD_OrgTrx_UU: String
	$C_LocFrom_UU: String
	$C_LocTo_UU: String
	$C_SalesRegion_UU: String
	$C_Project_UU: String
	$C_Campaign_UU: String
	$C_Activity_UU: String
	$User1_UU: String
	$User2_UU: String
	$UserElement1_UU: String
	$UserElement2_UU: String
) {
	C_ValidCombinationGetOrCreate(
		AD_Org_UU: $AD_Org_UU
		C_AcctSchema_UU: $C_AcctSchema_UU
		Account_UU: $Account_UU
		C_SubAcct_UU: $C_SubAcct_UU
		M_Product_UU: $M_Product_UU
		C_BPartner_UU: $C_BPartner_UU
		AD_OrgTrx_UU: $AD_OrgTrx_UU
		C_LocFrom_UU: $C_LocFrom_UU
		C_LocTo_UU: $C_LocTo_UU
		C_SalesRegion_UU: $C_SalesRegion_UU
		C_Project_UU: $C_Project_UU
		C_Campaign_UU: $C_Campaign_UU
		C_Activity_UU: $C_Activity_UU
		User1_UU: $User1_UU
		User2_UU: $User2_UU
		UserElement1_UU: $UserElement1_UU
		UserElement2_UU: $UserElement2_UU
	) {
		UUID
	}
}

mutation M_AttributeSetInstanceSave($entity: M_AttributeSetInstanceInput!) {
	M_AttributeSetInstanceSave(entity: $entity) {
		UUID
	}
}

mutation M_InventoryProcess($uuid: String!, $documentAction: String!) {
	M_InventoryProcess(uuid: $uuid, documentAction: $documentAction) {
		...M_InventoryFields
	}
}

mutation M_InventorySave($entity: M_InventoryInput!) {
	M_InventorySave(entity: $entity) {
		...M_InventoryFields
	}
}

mutation M_InventorySaveWithInventoryLines($M_Inventory: M_InventoryInput!, $M_InventoryLine: M_InventoryLineInput!) {
	M_InventorySave(entity: $M_Inventory) {
		...M_InventoryFields
	}
	M_InventoryLineSave(entity: $M_InventoryLine) {
		UUID
	}
}

mutation M_MovementProcess($uuid: String!, $documentAction: String!) {
	M_MovementProcess(uuid: $uuid, documentAction: $documentAction) {
		...M_MovementFields
	}
}

mutation M_MovementSave($entity: M_MovementInput!) {
	M_MovementSave(entity: $entity) {
		...M_MovementFields
	}
}

mutation M_MovementSaveWithMovementLinesAndProcess(
	$M_Movement: M_MovementInput!
	$M_MovementLine: M_MovementLineInput!
	$uuid: String!
	$documentAction: String!
) {
	M_MovementSave(entity: $M_Movement) {
		...M_MovementFields
	}
	M_MovementLineSave(entity: $M_MovementLine) {
		UUID
	}
	M_MovementProcess(uuid: $uuid, documentAction: $documentAction) {
		...M_MovementFields
	}
}

mutation M_ProductSave($entity: M_ProductInput!) {
	M_ProductSave(entity: $entity) {
		...M_ProductFields
	}
}

mutation M_ProductSaveMany($entities: [M_ProductInput!]!) {
	M_ProductSaveMany(entities: $entities) {
		BH_BuyPrice
		BH_SellPrice
		Description
		UUID
		Name
		M_Product_Category {
			UUID
		}
	}
}
