query AD_MenuGet($page: Int, $size: Int, $sort: String, $filter: String) {
	AD_MenuGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			ChildrenTree_NodeMMList {
				Node {
					Name
					ChildrenTree_NodeMMList {
						Node {
							Name
							AD_Process {
								UUID
								Name
							}
							AD_Window {
								UUID
								Name
							}
						}
						SeqNo
					}
					AD_Process {
						UUID
						Name
					}
					AD_Window {
						UUID
						Name
					}
					UUID
				}
				SeqNo
			}
		}
	}
}

query AD_OrgGet($page: Int, $size: Int, $sort: String, $filter: String) {
	AD_OrgGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			Name
			AD_OrgInfo {
				UUID
				BH_FacilityNumber
				BH_Header
				ReceiptFooterMsg
			}
			M_Warehouses {
				UUID
				Name
				BH_DefaultWarehouse
				IsActive
				M_Locators {
					UUID
				}
			}
		}
	}
}

query AD_OrgInfoGet($page: Int, $size: Int, $sort: String, $filter: String) {
	AD_OrgInfoGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			C_Location {
				C_Country {
					UUID
				}
				C_Region {
					UUID
					Name
				}
				UUID
			}
			Logo {
				UUID
			}
			UUID
		}
	}
}

query AD_ProcessGet($page: Int, $size: Int, $sort: String, $filter: String) {
	AD_ProcessGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			AD_Process_ParaList {
				UUID
				Name
			}
			UUID
		}
	}
}

query AD_Ref_ListGet($page: Int, $size: Int, $sort: String, $filter: String) {
	AD_Ref_ListGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			Name
			UUID
			Value
		}
	}
}

query BH_Coded_DiagnosisGet($page: Int, $size: Int, $sort: String, $filter: String) {
	BH_Coded_DiagnosisGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			bh_cielname
			bh_icd10who
			bh_searchterms
		}
	}
}

query BH_Payer_Info_Fld_SugGet($page: Int, $size: Int, $sort: String, $filter: String) {
	BH_Payer_Info_Fld_SugGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			BH_SubType {
				UUID
				Value
			}
			BH_PayerInfoFieldDataType {
				UUID
				Value
			}
		}
	}
}

query C_AcctSchemaGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_AcctSchemaGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			C_Currency {
				UUID
			}
		}
	}
}

query C_BankAccountGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_BankAccountGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			Name
		}
	}
}

query C_BP_GroupGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_BP_GroupGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			Name
		}
	}
}

query C_BPartnerGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_BPartnerGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			...C_BPartnerFields
		}
	}
}

query C_Charge_AcctGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_Charge_AcctGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
		}
	}
}

query C_ChargeGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_ChargeGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			Name
			C_Charge_AcctList {
				UUID
				Ch_Expense_A {
					UUID
					Account {
						UUID
						Value
					}
				}
			}
			C_ChargeType {
				UUID
			}
		}
	}
}

query C_ChargeTypeGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_ChargeTypeGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			Name
		}
	}
}

query C_CurrencyGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_CurrencyGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
		}
	}
}

query C_DocTypeGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_DocTypeGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			IsSOTrx
		}
	}
}

query C_ElementValueGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_ElementValueGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
		}
	}
}

query C_InvoiceGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_InvoiceGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			...C_InvoiceFields
		}
	}
}

query C_LocationGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_LocationGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			...C_LocationFields
		}
	}
}

query C_OrderGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_OrderGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			...C_OrderFields
		}
	}
}

query C_PaymentGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_PaymentGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			...C_PaymentFields
		}
	}
}

query C_TaxCategoryGet($page: Int, $size: Int, $sort: String, $filter: String) {
	C_TaxCategoryGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
		}
	}
}

query C_UOMGetDefault {
	C_UOMGetDefault {
		UUID
	}
}

query ChangeAccess($credentials: ChangeAccessInput!) {
	changeAccess(credentials: $credentials) {
		token
	}
}

query M_AttributeSetInstanceGet($page: Int, $size: Int, $sort: String, $filter: String) {
	M_AttributeSetInstanceGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
		}
	}
}

query M_Product_CategoryGet($page: Int, $size: Int, $sort: String, $filter: String) {
	M_Product_CategoryGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			Name
		}
	}
}

query M_ProductGet($page: Int, $size: Int, $sort: String, $filter: String) {
	M_ProductGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			...M_ProductFields
		}
		pagingInfo {
			page
			totalPages
		}
	}
}

query M_StorageOnHandGet($page: Int, $size: Int, $sort: String, $filter: String) {
	M_StorageOnHandGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			QtyOnHand
		}
	}
}

query M_WarehouseGet($page: Int, $size: Int, $sort: String, $filter: String) {
	M_WarehouseGet(page: $page, size: $size, sort: $sort, filter: $filter) {
		results {
			UUID
			Name
			BH_DefaultWarehouse
			IsActive
			M_Locators {
				UUID
			}
		}
	}
}

query SignIn($credentials: AuthenticationInput!) {
	signIn(credentials: $credentials) {
		token
		AD_Clients {
			UUID
			Name
			AD_Orgs {
				UUID
				Name
				AD_Roles {
					UUID
					Name
				}
				M_Warehouses {
					UUID
					Name
					BH_DefaultWarehouse
					IsActive
					M_Locators {
						UUID
					}
				}
			}
		}
		AD_Role {
			IncludedRoles {
				UUID
			}
			AD_Window_AccessList {
				AD_Window {
					UUID
				}
				BH_CanDeactivate
				IsReadWrite
			}
		}
	}
}
