extend type Query {
	changeAccess(credentials: ChangeAccessInput!): ChangeAccessResponse!
	changePassword(credentials: AuthenticationInput!): AuthenticationResponse!
	signIn(credentials: AuthenticationInput!): AuthenticationResponse!
}

#extend type Mutation {
#	changePassword(credentials: AuthenticationData!): AuthenticationResponse!
#	signIn(credentials: AuthenticationData!): AuthenticationResponse!
#}

type AuthenticationResponse {
	token: String
	AD_Clients: [AD_Client!]!
	user: AD_User
	AD_Role: AD_Role
	securityQuestions: [String!]
}

input AuthenticationInput {
	username: String!
	password: String!
	newPassword: String
	securityQuestion: String
	answer: String
	clientUuid: String
	roleUuid: String
	organizationUuid: String
	warehouseUuid: String
	language: String
}

type ChangeAccessResponse {
	token: String!
}

input ChangeAccessInput {
	username: String!
	clientUuid: String
	roleUuid: String
	organizationUuid: String
	warehouseUuid: String
	language: String
}
