extend type Query {
	DashboardFinancialGeneralMetricsGet(BeginDate: DateTime!, EndDate: DateTime!): DashboardFinancialGeneralMetric!
	DashboardFinancialHistoricalGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardFinancialHistorical]!
	DashboardFinancialOpenBalancesGet(BeginDate: DateTime!, EndDate: DateTime!, Type: String!): [DashboardFinancialOpenBalance]!
	DashboardFinancialSourcesGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardFinancialSource]!
	DashboardFinancialTypesGet(BeginDate: DateTime!, EndDate: DateTime!, Type: String!): [DashboardFinancialType]!
	DashboardFinancialVisitChargesGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardFinancialVisitCharge]!
}

type DashboardFinancialGeneralMetric {
	RevenueSales: BigDecimal!
	TotalExpenses: BigDecimal!
	NetProfit: BigDecimal!
	TotalOwed: BigDecimal!
	InventoryValue: BigDecimal!
	TotalCharges: BigDecimal!
	CostOfGoodsSold: BigDecimal!
	GrossProfit: BigDecimal!
	GrossProfitMargin: BigDecimal!
}

type DashboardFinancialHistorical {
 	BucketValue: DateTime!
	TotalIncome: BigDecimal!
	TotalExpenses: BigDecimal!
	NetProfit: BigDecimal!
}

type DashboardFinancialOpenBalance {
	Name: String!
	TotalOpenBalance: BigDecimal!
}

type DashboardFinancialSource {
	Source: String!
	Frequency: Int!
}

type DashboardFinancialType {
	Name: String!
	Frequency: Int!
}

type DashboardFinancialVisitCharge {
	BucketValue: DateTime!
	PatientVisits: Int!
	AvgChargePatient: Int!
}