extend type Query {
	DashboardData(UU: String!, SqlQuery: String!): String
	DashboardGeneralDataGet(BeginDate: DateTime!, EndDate: DateTime!): DashboardGeneralData!
	DashboardDiagnosisUsageGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardDiagnosisUsage]!
	DashboardProductUsageGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardProductUsage]!
	DashboardLabUsageGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardLabUsage]!
	DashboardVisitHistoryStatGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardVisitHistoryStat]!

	DashboardInventoryGeneralMetricsGet(BeginDate: DateTime!, EndDate: DateTime!): DashboardInventoryGeneralMetrics!
	DashboardInventoryHistoricalChargeEarningGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardInventoryHistoricalChargeEarning]!
	DashboardInventoryHistoricalValueGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardInventoryHistoricalValue]!
	DashboardInventoryTopSellerEarnerGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardInventoryTopSellerEarner]!

	DashboardFinancialGeneralMetricsGet(BeginDate: DateTime!, EndDate: DateTime!): DashboardFinancialGeneralMetric!
	DashboardFinancialHistoricalGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardFinancialHistorical]!
	DashboardFinancialOpenBalancesGet(BeginDate: DateTime!, EndDate: DateTime!, Type: String!): [DashboardFinancialOpenBalance]!
	DashboardFinancialSourcesGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardFinancialSource]!
	DashboardFinancialTypesGet(BeginDate: DateTime!, EndDate: DateTime!, Type: String!): [DashboardFinancialType]!
	DashboardFinancialVisitChargesGet(BeginDate: DateTime!, EndDate: DateTime!): [DashboardFinancialVisitCharge]!
}

type DashboardGeneralData {
	TotalPatientsServed: Int!
	NewPatientsRegistered: Int!
	AverageNumberOfProductsDelivered: BigDecimal!
	AverageChargePerPatient: BigDecimal!
	AverageProductTurnover: BigDecimal!
	PercentVitalsTracked: BigDecimal!
	PercentDiagnosesCoded: BigDecimal!
	PercentNotes: BigDecimal!
	PercentCompletedLabs: BigDecimal!
	PercentVisitsCompleted: BigDecimal!
}

type DashboardInventoryGeneralMetrics {
	InventoryTurnoverRate: BigDecimal!
	DaysOnHand: BigDecimal!
	SalesToStockRatio: BigDecimal!
	GrossMargin: BigDecimal!
	ReturnOnInvestment: BigDecimal!
}

type DashboardInventoryHistoricalChargeEarning {
	BucketValue: DateTime!
	Charges: BigDecimal!
	Margins: BigDecimal!
}

type DashboardInventoryHistoricalValue {
	BucketValue: DateTime!
	InventoryValue: BigDecimal!
	InventoryReceived: BigDecimal!
}

type DashboardInventoryTopSellerEarner {
	Name: String!
	QuantitySold: BigDecimal!
	ValueGoodsSold: BigDecimal!
	IncomeGenerated: BigDecimal!
	MarginEarned: BigDecimal!
}

type DashboardDiagnosisUsage {
	BH_Concept: BH_Concept
	BH_Uncoded_Diagnosis: String
	Current: BigDecimal!
	Previous: BigDecimal
	CurrentTotal: BigDecimal
}

type DashboardFinancialGeneralMetric {
	RevenueSales: BigDecimal!
	TotalExpenses: BigDecimal!
	NetProfit: BigDecimal!
	TotalOwed: BigDecimal!
	InventoryValue: BigDecimal!
	TotalCharges: BigDecimal!
	CostOfGoodsSold: BigDecimal!
	GrossProfit: BigDecimal!
	GrossProfitMargin: BigDecimal!
}

type DashboardFinancialHistorical {
	BucketValue: DateTime!
	TotalIncome: BigDecimal!
	TotalExpenses: BigDecimal!
	NetProfit: BigDecimal!
}

type DashboardFinancialOpenBalance {
	Name: String!
	TotalOpenBalance: BigDecimal!
}

type DashboardFinancialSource {
	Source: String!
	Frequency: Int!
}

type DashboardFinancialType {
	Name: String!
	Frequency: Int!
}

type DashboardFinancialVisitCharge {
	BucketValue: DateTime!
	PatientVisits: Int!
	AvgChargePatient: Int!
}

type DashboardProductUsage {
	M_Product: M_Product
	Name: String!
	Current: BigDecimal!
	Previous: BigDecimal
}

type DashboardLabUsage {
	BH_Concept: BH_Concept
	Name: String!
	Current: BigDecimal!
	Previous: BigDecimal
}

type DashboardVisitHistoryStat {
	BucketValue: DateTime!
	BH_PatientType: AD_Ref_List
	AlternateVisitType: String
	Frequency: Int!
}
