extend type Mutation {
	M_ProductMerge(OldUU: String!, NewUU: String!): Boolean!
}

extend type M_Product {
	BH_Product_IncludedList: [BH_Product_Included!]
	HasBeenPurchased: Boolean!
	LastPurchaseDate: DateTime
	LastPurchasePrice: BigDecimal
	M_InOutLines: [M_InOutLine!]
	M_Lots: [M_Lot!]
	M_ProductPrices: [M_ProductPrice!]
	M_Product_POList: [M_Product_PO!]
	M_ReplenishList: [M_Replenish!]
	M_StorageOnHandList: [M_StorageOnHand!]
	M_StorageReservations: [M_StorageReservation!]
	TotalQuantity: BigDecimal!
}
