type Payment {
  id: ID!
  client: Client!
  organization: Organization!
  description: String
  isActive: Boolean!
  created: String @dateFormat
  createdBy: User!
  businessPartner: BusinessPartner
  charge: Charge
  payAmount: Float
  paymentType: ReferenceList
  docStatus: ReferenceList!
  transactionDate: String @dateFormat
  tenderAmount: Float
}

type PaymentConnection {
  results: [Payment!]!
  pagingInfo: PagingInfo!
}

input PaymentInput {
  id: ID
  description: String
  isActive: Boolean
  businessPartner: BusinessPartnerInput
  charge: ChargeInput
  payAmount: Float
  paymentType: ReferenceListInput
  transactionDate: String
  tenderAmount: Float
}