# All directives and scalars, custom or not, should be declared here
directive @dateFormat on FIELD_DEFINITION
directive @fixed on INPUT_FIELD_DEFINITION
scalar Object
scalar Date

# Per the GraphQL standard, Query types cannot be split amongst files, so all are defined here
type Query {
  # Authentication
  changePassword(credentials: AuthenticationData!): AuthenticationResponse
  signIn(credentials: AuthenticationData!): AuthenticationResponse
}

# Per the GraphQL standard, Mutation types cannot be split amongst files, so all are defined here
type Mutation {
#  # Authentication
#  changePassword(credentials: AuthenticationData!): AuthenticationResponse
#  signIn(credentials: AuthenticationData!): AuthenticationResponse
}

# This is the root definition for GraphQL
schema {
  query: Query
  mutation: Mutation
}
