extend type Query {
	VendorPaymentTrailGet(Page: Int, Size: Int, Sort: String, Filter: String): VendorPaymentTrailConnection!
}

type VendorPaymentTrailConnection {
	Results: [VendorPaymentTrail!]!
	PagingInfo: PagingInfo!
}

type VendorPaymentTrail {
	BH_Visit: BH_Visit
	Credits: BigDecimal
	C_BPartner: C_BPartner!
	C_Invoice: C_Invoice
	C_Order: C_Order
	C_Payment: C_Payment
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Date this record happened
	Date: DateTime!
	Debits: BigDecimal
	Item: String
	OpenBalance: BigDecimal
	# Date this record was updated
	Updated: DateTime!
}
