# Generated Schema for A_Asset_Group_Acct - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	A_Asset_Group_AcctGet(page: Int, size: Int, sort: String, filter: String): A_Asset_Group_AcctConnection!
}

extend type Mutation {
	A_Asset_Group_AcctSave(entity: A_Asset_Group_AcctInput!): A_Asset_Group_Acct!
	A_Asset_Group_AcctDelete(uuids: [String!]!): Boolean!
}

type A_Asset_Group_AcctConnection {
	results: [A_Asset_Group_Acct!]!
	pagingInfo: PagingInfo!
}

type A_Asset_Group_Acct {
	A_Accumdepreciation_Acct: C_ValidCombination!
	A_Asset_Acct: C_ValidCombination!
	ID: ID!
	# Group of Assets
	A_Asset_Group: A_Asset_Group!
	A_Depreciation_Acct: C_ValidCombination!
	A_Depreciation_Conv_F: A_Depreciation_Convention
	A_Depreciation_Conv: A_Depreciation_Convention
	A_Depreciation_F: A_Depreciation!
	A_Depreciation: A_Depreciation!
	A_Depreciation_Manual_Amount: Int
	A_Depreciation_Manual_Period: AD_Ref_List
	A_Depreciation_Method_F: A_Depreciation_Method
	A_Depreciation_Method: A_Depreciation_Method
	A_Depreciation_Table_Header: A_Depreciation_Table_Header
	A_Depreciation_Variable_Perc: Int
	A_Depreciation_Variable_Perc_F: Int
	A_Disposal_Gain_Acct: C_ValidCombination
	A_Disposal_Loss_Acct: C_ValidCombination!
	A_Disposal_Revenue_Acct: C_ValidCombination!
	A_Reval_Adep_Offset_Cur_Acct: C_ValidCombination
	A_Reval_Adep_Offset_Prior_Acct: C_ValidCombination
	A_Reval_Cal_Method: AD_Ref_List
	A_Reval_Cost_Offset_Acct: C_ValidCombination
	A_Reval_Cost_Offset_Prior_Acct: C_ValidCombination
	A_Reval_Depexp_Offset_Acct: C_ValidCombination
	A_Split_Percent: Int!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User
	# The record is active in the system
	IsActive: Boolean!
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List!
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User
	# Months of the usable life of the asset
	UseLifeMonths: Int
	UseLifeMonths_F: Int!
	# Years of the usable life of the asset
	UseLifeYears: Int
	UseLifeYears_F: Int!
}

input A_Asset_Group_AcctInput {
	A_Accumdepreciation_Acct: C_ValidCombinationInput
	A_Asset_Acct: C_ValidCombinationInput
	ID: ID
	# Group of Assets
	A_Asset_Group: A_Asset_GroupInput
	A_Depreciation_Acct: C_ValidCombinationInput
	A_Depreciation_Conv_F: A_Depreciation_ConventionInput
	A_Depreciation_Conv: A_Depreciation_ConventionInput
	A_Depreciation_F: A_DepreciationInput
	A_Depreciation: A_DepreciationInput
	A_Depreciation_Manual_Amount: Int
	A_Depreciation_Manual_Period: AD_Ref_ListInput
	A_Depreciation_Method_F: A_Depreciation_MethodInput
	A_Depreciation_Method: A_Depreciation_MethodInput
	A_Depreciation_Table_Header: A_Depreciation_Table_HeaderInput
	A_Depreciation_Variable_Perc: Int
	A_Depreciation_Variable_Perc_F: Int
	A_Disposal_Gain_Acct: C_ValidCombinationInput
	A_Disposal_Loss_Acct: C_ValidCombinationInput
	A_Disposal_Revenue_Acct: C_ValidCombinationInput
	A_Reval_Adep_Offset_Cur_Acct: C_ValidCombinationInput
	A_Reval_Adep_Offset_Prior_Acct: C_ValidCombinationInput
	A_Reval_Cal_Method: AD_Ref_ListInput
	A_Reval_Cost_Offset_Acct: C_ValidCombinationInput
	A_Reval_Cost_Offset_Prior_Acct: C_ValidCombinationInput
	A_Reval_Depexp_Offset_Acct: C_ValidCombinationInput
	A_Split_Percent: Int
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Rules for accounting
	C_AcctSchema: C_AcctSchemaInput
	# The record is active in the system
	IsActive: Boolean
	# The type of posted amount for the transaction
	PostingType: AD_Ref_ListInput
	Processing: Boolean
	# Months of the usable life of the asset
	UseLifeMonths: Int
	UseLifeMonths_F: Int
	# Years of the usable life of the asset
	UseLifeYears: Int
	UseLifeYears_F: Int
}
