# Generated Schema for A_Registration - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	A_Registration(UU: String!): A_Registration
	A_RegistrationGet(Page: Int, Size: Int, Sort: String, Filter: String): A_RegistrationConnection!
}

extend type Mutation {
	A_RegistrationSave(Entity: A_RegistrationInput!): A_Registration!
	A_RegistrationSaveMany(Entities: [A_RegistrationInput!]!): [A_Registration!]!
	A_RegistrationDelete(UUs: [String!]!): Boolean!
}

type A_RegistrationConnection {
	Results: [A_Registration!]!
	PagingInfo: PagingInfo!
}

type A_Registration {
	# Asset used internally or by customers
	A_Asset: A_Asset
	UU: ID!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Date when Asset was put into service
	AssetServiceDate: Date!
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# You allow to publish the information, not just statistical summary info
	IsAllowPublish: Boolean!
	# The system is in production
	IsInProduction: Boolean!
	# The application is registered.
	IsRegistered: Boolean!
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String!
	# Optional additional user defined information
	Note: String
	Processing: Boolean!
	# Remote Address
	Remote_Addr: String
	# Remote host Info
	Remote_Host: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input A_RegistrationInput {
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Date when Asset was put into service
	AssetServiceDate: Date
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# You allow to publish the information, not just statistical summary info
	IsAllowPublish: Boolean
	# The system is in production
	IsInProduction: Boolean
	# The application is registered.
	IsRegistered: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# Optional additional user defined information
	Note: String
	Processing: Boolean
	# Remote Address
	Remote_Addr: String
	# Remote host Info
	Remote_Host: String
}
