# Generated Schema for A_Depreciation_Exp - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	A_Depreciation_Exp(UU: String!): A_Depreciation_Exp
	A_Depreciation_ExpGet(Page: Int, Size: Int, Sort: String, Filter: String): A_Depreciation_ExpConnection!
}

extend type Mutation {
	A_Depreciation_ExpSave(Entity: A_Depreciation_ExpInput!): A_Depreciation_Exp!
	A_Depreciation_ExpSaveMany(Entities: [A_Depreciation_ExpInput!]!): [A_Depreciation_Exp!]!
	A_Depreciation_ExpDelete(UUs: [String!]!): Boolean!
}

type A_Depreciation_ExpConnection {
	Results: [A_Depreciation_Exp!]!
	PagingInfo: PagingInfo!
}

type A_Depreciation_Exp {
	A_Account_Number_A: C_ValidCombination
	A_Accumulated_Depr: BigDecimal
	A_Accumulated_Depr_Delta: BigDecimal!
	A_Accumulated_Depr_F: BigDecimal
	A_Accumulated_Depr_F_Delta: BigDecimal!
	A_Asset_Addition: A_Asset_Addition
	A_Asset_Cost: BigDecimal
	A_Asset_Cost_Delta: BigDecimal!
	A_Asset_Disposed: A_Asset_Disposed
	# Asset used internally or by customers
	A_Asset: A_Asset!
	A_Asset_Remaining: BigDecimal
	A_Asset_Remaining_F: BigDecimal
	A_Depreciation_Entry: A_Depreciation_Entry
	UU: ID!
	A_Entry_Type: AD_Ref_List!
	A_Period: Int!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema
	# Account used
	CR_Account: C_ValidCombination
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String!
	# Account used
	DR_Account: C_ValidCombination
	Expense: BigDecimal!
	Expense_F: BigDecimal!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# The asset will be depreciated
	IsDepreciated: Boolean!
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Months of the usable life of the asset
	UseLifeMonths: Int
	UseLifeMonths_F: Int
}

input A_Depreciation_ExpInput {
	A_Account_Number_A: ForeignEntityInput
	A_Accumulated_Depr: BigDecimal
	A_Accumulated_Depr_Delta: BigDecimal
	A_Accumulated_Depr_F: BigDecimal
	A_Accumulated_Depr_F_Delta: BigDecimal
	A_Asset_Addition: ForeignEntityInput
	A_Asset_Cost: BigDecimal
	A_Asset_Cost_Delta: BigDecimal
	A_Asset_Disposed: ForeignEntityInput
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	A_Asset_Remaining: BigDecimal
	A_Asset_Remaining_F: BigDecimal
	A_Depreciation_Entry: ForeignEntityInput
	UU: ID
	A_Entry_Type: ForeignEntityInput
	A_Period: Int
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# Account used
	CR_Account: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# Account used
	DR_Account: ForeignEntityInput
	Expense: BigDecimal
	Expense_F: BigDecimal
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# The asset will be depreciated
	IsDepreciated: Boolean
	# The type of posted amount for the transaction
	PostingType: ForeignEntityInput
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Months of the usable life of the asset
	UseLifeMonths: Int
	UseLifeMonths_F: Int
}
