# Generated Schema for A_RegistrationProduct - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	A_RegistrationProduct(UU: String!): A_RegistrationProduct
	A_RegistrationProductGet(Page: Int, Size: Int, Sort: String, Filter: String): A_RegistrationProductConnection!
}

extend type Mutation {
	A_RegistrationProductSave(Entity: A_RegistrationProductInput!): A_RegistrationProduct!
	A_RegistrationProductSaveMany(Entities: [A_RegistrationProductInput!]!): [A_RegistrationProduct!]!
	A_RegistrationProductDelete(UUs: [String!]!): Boolean!
}

type A_RegistrationProductConnection {
	Results: [A_RegistrationProduct!]!
	PagingInfo: PagingInfo!
}

type A_RegistrationProduct {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Asset Registration Attribute
	A_RegistrationAttribute: A_RegistrationAttribute!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input A_RegistrationProductInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Asset Registration Attribute
	A_RegistrationAttribute: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
}
