# Generated Schema for A_Asset_Change - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	A_Asset_Change(UU: String!): A_Asset_Change
	A_Asset_ChangeGet(Page: Int, Size: Int, Sort: String, Filter: String): A_Asset_ChangeConnection!
}

extend type Mutation {
	A_Asset_ChangeSave(Entity: A_Asset_ChangeInput!): A_Asset_Change!
	A_Asset_ChangeSaveMany(Entities: [A_Asset_ChangeInput!]!): [A_Asset_Change!]!
	A_Asset_ChangeDelete(UUs: [String!]!): Boolean!
}

type A_Asset_ChangeConnection {
	Results: [A_Asset_Change!]!
	PagingInfo: PagingInfo!
}

type A_Asset_Change {
	A_Accumdepreciation_A: C_ValidCombination
	A_Asset_A: C_ValidCombination
	A_Asset_Acct_ID: Int
	A_Asset_Addition: A_Asset_Addition
	UU: ID!
	A_Asset_CreateDate: Date
	# Asset used internally or by customers
	A_Asset: A_Asset!
	# Internally used asset is not longer used.
	A_Asset_Retirement: A_Asset_Retirement
	A_Asset_RevalDate: Date
	A_Depreciation_A: C_ValidCombination
	A_Depreciation_Manual_Amount: BigDecimal
	A_Depreciation_Manual_Period: AD_Ref_List
	A_Depreciation_Table_Header: A_Depreciation_Table_Header
	A_Depreciation_Variable_Perc: BigDecimal
	A_Disposal_Loss_A: C_ValidCombination
	A_Disposal_Revenue_A: C_ValidCombination
	A_Parent_Asset: A_Asset
	A_Period_End: Int
	A_Period_Start: Int
	A_QTY_Current: BigDecimal
	A_QTY_Original: BigDecimal
	A_Reval_Accumdep_Offset_Cur: Int
	A_Reval_Accumdep_Offset_Prior: Int
	A_Reval_Adep_Offset_Cur_Acct: Int
	A_Reval_Adep_Offset_Prior_Acct: Int
	A_Reval_Cal_Method: AD_Ref_List
	A_Reval_Cost_Offset: Int
	A_Reval_Cost_Offset_Acct: Int
	A_Reval_Cost_Offset_Prior: Int
	A_Reval_Cost_Offset_Prior_Acct: Int
	A_Reval_Depexp_Offset: Int
	A_Reval_Depexp_Offset_Acct: Int
	A_Salvage_Value: BigDecimal
	A_Split_Percent: BigDecimal
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	AssetAccumDepreciationAmt: BigDecimal
	AssetBookValueAmt: BigDecimal
	# Date of last depreciation
	AssetDepreciationDate: Date
	# Date when the asset is/was disposed
	AssetDisposalDate: Date
	# Market value of the asset
	AssetMarketValueAmt: BigDecimal
	# Date when Asset was put into service
	AssetServiceDate: Date
	# Book Value of the asset
	AssetValueAmt: BigDecimal!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: C_BPartner_Location
	# Location or Address
	C_Location: C_Location
	# Valid Account Combination
	C_ValidCombination: C_ValidCombination
	ChangeAmt: BigDecimal
	ChangeDate: DateTime
	ChangeType: AD_Ref_List!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date
	# The record is active in the system
	IsActive: Boolean!
	# The asset will be depreciated
	IsDepreciated: Boolean!
	# The asset is disposed
	IsDisposed: Boolean!
	# The asset is fully depreciated
	IsFullyDepreciated: Boolean!
	# The asset is in the possession of the organization
	IsInPosession: Boolean!
	# The asset is owned by the organization
	IsOwned: Boolean!
	# Units of use until the asset is not usable anymore
	LifeUseUnits: Int
	# Lot number (alphanumeric)
	Lot: String
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List
	# Product Serial Number 
	SerNo: String
	TextDetails: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Months of the usable life of the asset
	UseLifeMonths: Int
	# Years of the usable life of the asset
	UseLifeYears: BigDecimal
	# Currently used units of the assets
	UseUnits: Int
	# Version Number
	VersionNo: String
}

input A_Asset_ChangeInput {
	A_Accumdepreciation_A: ForeignEntityInput
	A_Asset_A: ForeignEntityInput
	A_Asset_Acct_ID: Int
	A_Asset_Addition: ForeignEntityInput
	UU: ID
	A_Asset_CreateDate: Date
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	# Internally used asset is not longer used.
	A_Asset_Retirement: ForeignEntityInput
	A_Asset_RevalDate: Date
	A_Depreciation_A: ForeignEntityInput
	A_Depreciation_Manual_Amount: BigDecimal
	A_Depreciation_Manual_Period: ForeignEntityInput
	A_Depreciation_Table_Header: ForeignEntityInput
	A_Depreciation_Variable_Perc: BigDecimal
	A_Disposal_Loss_A: ForeignEntityInput
	A_Disposal_Revenue_A: ForeignEntityInput
	A_Parent_Asset: ForeignEntityInput
	A_Period_End: Int
	A_Period_Start: Int
	A_QTY_Current: BigDecimal
	A_QTY_Original: BigDecimal
	A_Reval_Accumdep_Offset_Cur: Int
	A_Reval_Accumdep_Offset_Prior: Int
	A_Reval_Adep_Offset_Cur_Acct: Int
	A_Reval_Adep_Offset_Prior_Acct: Int
	A_Reval_Cal_Method: ForeignEntityInput
	A_Reval_Cost_Offset: Int
	A_Reval_Cost_Offset_Acct: Int
	A_Reval_Cost_Offset_Prior: Int
	A_Reval_Cost_Offset_Prior_Acct: Int
	A_Reval_Depexp_Offset: Int
	A_Reval_Depexp_Offset_Acct: Int
	A_Salvage_Value: BigDecimal
	A_Split_Percent: BigDecimal
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	AssetAccumDepreciationAmt: BigDecimal
	AssetBookValueAmt: BigDecimal
	# Date of last depreciation
	AssetDepreciationDate: Date
	# Date when the asset is/was disposed
	AssetDisposalDate: Date
	# Market value of the asset
	AssetMarketValueAmt: BigDecimal
	# Date when Asset was put into service
	AssetServiceDate: Date
	# Book Value of the asset
	AssetValueAmt: BigDecimal
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: ForeignEntityInput
	# Location or Address
	C_Location: ForeignEntityInput
	# Valid Account Combination
	C_ValidCombination: ForeignEntityInput
	ChangeAmt: BigDecimal
	ChangeDate: DateTime
	ChangeType: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# The record is active in the system
	IsActive: Boolean
	# The asset will be depreciated
	IsDepreciated: Boolean
	# The asset is disposed
	IsDisposed: Boolean
	# The asset is fully depreciated
	IsFullyDepreciated: Boolean
	# The asset is in the possession of the organization
	IsInPosession: Boolean
	# The asset is owned by the organization
	IsOwned: Boolean
	# Units of use until the asset is not usable anymore
	LifeUseUnits: Int
	# Lot number (alphanumeric)
	Lot: String
	# The type of posted amount for the transaction
	PostingType: ForeignEntityInput
	# Product Serial Number 
	SerNo: String
	TextDetails: String
	# Months of the usable life of the asset
	UseLifeMonths: Int
	# Years of the usable life of the asset
	UseLifeYears: BigDecimal
	# Currently used units of the assets
	UseUnits: Int
	# Version Number
	VersionNo: String
}
