# Generated Schema for A_Asset_Product - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	A_Asset_ProductGet(page: Int, size: Int, sort: String, filter: String): A_Asset_ProductConnection!
}

extend type Mutation {
	A_Asset_ProductSave(entity: A_Asset_ProductInput!): A_Asset_Product!
	A_Asset_ProductDelete(uuids: [String!]!): Boolean!
}

type A_Asset_ProductConnection {
	results: [A_Asset_Product!]!
	pagingInfo: PagingInfo!
}

type A_Asset_Product {
	# Asset used internally or by customers
	A_Asset: A_Asset!
	ID: ID!
	A_QTY_Current: Int!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance!
	# Warehouse Locator
	M_Locator: M_Locator
	# Product, Service, Item
	M_Product: M_Product!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input A_Asset_ProductInput {
	# Asset used internally or by customers
	A_Asset: A_AssetInput
	ID: ID
	A_QTY_Current: Int
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstanceInput
	# Warehouse Locator
	M_Locator: M_LocatorInput
	# Product, Service, Item
	M_Product: M_ProductInput
}
