# Generated Schema for A_Asset_Disposed - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	A_Asset_DisposedGet(Page: Int, Size: Int, Sort: String, Filter: String): A_Asset_DisposedConnection!
}

extend type Mutation {
	A_Asset_DisposedSave(Entity: A_Asset_DisposedInput!): A_Asset_Disposed!
	A_Asset_DisposedSaveMany(Entities: [A_Asset_DisposedInput!]!): [A_Asset_Disposed!]!
	A_Asset_DisposedDelete(UUs: [String!]!): Boolean!
}

type A_Asset_DisposedConnection {
	Results: [A_Asset_Disposed!]!
	PagingInfo: PagingInfo!
}

type A_Asset_Disposed {
	A_Accumulated_Depr: BigDecimal!
	A_Accumulated_Depr_Delta: BigDecimal!
	A_Activation_Method: AD_Ref_List!
	A_Asset_Cost: BigDecimal
	UU: ID!
	# Asset used internally or by customers
	A_Asset: A_Asset!
	A_Asset_Status: AD_Ref_List
	A_Asset_Trade: A_Asset
	A_Disposal_Amt: BigDecimal!
	A_Disposed_Date: Date!
	A_Disposed_Method: AD_Ref_List!
	A_Disposed_Reason: AD_Ref_List
	A_Proceeds: BigDecimal
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Document type or rules
	C_DocType: C_DocType
	# Invoice Identifier
	C_Invoice: C_Invoice
	# Invoice Detail Line
	C_InvoiceLine: C_InvoiceLine
	# Period of the Calendar
	C_Period: C_Period
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date!
	# Date of the Document
	DateDoc: Date!
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: AD_Ref_List
	# The current status of the document
	DocStatus: AD_Ref_List
	# Document sequence number of the document
	DocumentNo: String!
	Expense: BigDecimal!
	# The record is active in the system
	IsActive: Boolean!
	# Indicates if this document requires approval
	IsApproved: Boolean!
	# The asset is disposed
	IsDisposed: Boolean!
	# Posting status
	Posted: Boolean!
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List!
	# The document has been processed
	Processed: Boolean!
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input A_Asset_DisposedInput {
	A_Accumulated_Depr: BigDecimal
	A_Accumulated_Depr_Delta: BigDecimal
	A_Activation_Method: AD_Ref_ListInput
	A_Asset_Cost: BigDecimal
	UU: ID
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	A_Asset_Status: AD_Ref_ListInput
	A_Asset_Trade: ForeignEntityInput
	A_Disposal_Amt: BigDecimal
	A_Disposed_Date: Date
	A_Disposed_Method: AD_Ref_ListInput
	A_Disposed_Reason: AD_Ref_ListInput
	A_Proceeds: BigDecimal
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Document type or rules
	C_DocType: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# Invoice Detail Line
	C_InvoiceLine: ForeignEntityInput
	# Period of the Calendar
	C_Period: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Date of the Document
	DateDoc: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: AD_Ref_ListInput
	# The current status of the document
	DocStatus: AD_Ref_ListInput
	# Document sequence number of the document
	DocumentNo: String
	Expense: BigDecimal
	# The record is active in the system
	IsActive: Boolean
	# Indicates if this document requires approval
	IsApproved: Boolean
	# The asset is disposed
	IsDisposed: Boolean
	# Posting status
	Posted: Boolean
	# The type of posted amount for the transaction
	PostingType: AD_Ref_ListInput
	# The document has been processed
	Processed: Boolean
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean
}
