# Generated Schema for A_Depreciation_Workfile - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	A_Depreciation_WorkfileGet(page: Int, size: Int, sort: String, filter: String): A_Depreciation_WorkfileConnection!
}

extend type Mutation {
	A_Depreciation_WorkfileSave(entity: A_Depreciation_WorkfileInput!): A_Depreciation_Workfile!
	A_Depreciation_WorkfileDelete(uuids: [String!]!): Boolean!
}

type A_Depreciation_WorkfileConnection {
	results: [A_Depreciation_Workfile!]!
	pagingInfo: PagingInfo!
}

type A_Depreciation_Workfile {
	A_Accumulated_Depr: BigDecimal!
	A_Accumulated_Depr_F: BigDecimal!
	A_Asset_Cost: BigDecimal!
	# Asset used internally or by customers
	A_Asset: A_Asset!
	A_Asset_Life_Current_Year: BigDecimal!
	A_Asset_Life_Years: Int!
	A_Asset_Life_Years_F: Int!
	A_Asset_Remaining: BigDecimal
	A_Asset_Remaining_F: BigDecimal
	A_Base_Amount: BigDecimal
	A_Calc_Accumulated_Depr: BigDecimal
	A_Curr_Dep_Exp: BigDecimal!
	A_Current_Period: Int
	ID: ID!
	A_Expense_SL: BigDecimal
	A_Expense_SL_F: BigDecimal
	A_FundingMode: A_FundingMode
	A_Life_Period: Int!
	A_Life_Period_F: Int!
	A_Life_Period_Max: Int
	A_Life_Period_Min: Int
	A_Period_Forecast: BigDecimal
	A_Period_Posted: Int
	A_Prior_Year_Accumulated_Depr: BigDecimal
	A_QTY_Current: BigDecimal!
	A_Salvage_Value: BigDecimal!
	# Financing Type
	A_Tip_Finantare: AD_Ref_List!
	A_Valoare_Cofinantare: BigDecimal
	A_Valoare_Tert: BigDecimal
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date of last depreciation
	AssetDepreciationDate: Date
	# Rules for accounting
	C_AcctSchema: C_AcctSchema
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# The asset will be depreciated
	IsDepreciated: Boolean!
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Months of the usable life of the asset
	UseLifeMonths: Int!
	UseLifeMonths_F: Int!
	# Years of the usable life of the asset
	UseLifeYears: Int!
	UseLifeYears_F: Int!
}

input A_Depreciation_WorkfileInput {
	A_Accumulated_Depr: BigDecimal
	A_Accumulated_Depr_F: BigDecimal
	A_Asset_Cost: BigDecimal
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	A_Asset_Life_Current_Year: BigDecimal
	A_Asset_Life_Years: Int
	A_Asset_Life_Years_F: Int
	A_Asset_Remaining: BigDecimal
	A_Asset_Remaining_F: BigDecimal
	A_Base_Amount: BigDecimal
	A_Calc_Accumulated_Depr: BigDecimal
	A_Curr_Dep_Exp: BigDecimal
	A_Current_Period: Int
	ID: ID
	A_FundingMode: ForeignEntityInput
	A_Life_Period: Int
	A_Life_Period_F: Int
	A_Period_Forecast: BigDecimal
	A_Period_Posted: Int
	A_Prior_Year_Accumulated_Depr: BigDecimal
	A_QTY_Current: BigDecimal
	A_Salvage_Value: BigDecimal
	# Financing Type
	A_Tip_Finantare: AD_Ref_ListInput
	A_Valoare_Cofinantare: BigDecimal
	A_Valoare_Tert: BigDecimal
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Date of last depreciation
	AssetDepreciationDate: Date
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# The asset will be depreciated
	IsDepreciated: Boolean
	# The type of posted amount for the transaction
	PostingType: AD_Ref_ListInput
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Months of the usable life of the asset
	UseLifeMonths: Int
	UseLifeMonths_F: Int
	# Years of the usable life of the asset
	UseLifeYears: Int
	UseLifeYears_F: Int
}
