# Generated Schema for A_Asset_Reval_Entry - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	A_Asset_Reval_Entry(UU: String!): A_Asset_Reval_Entry
	A_Asset_Reval_EntryGet(Page: Int, Size: Int, Sort: String, Filter: String): A_Asset_Reval_EntryConnection!
}

extend type Mutation {
	A_Asset_Reval_EntrySave(Entity: A_Asset_Reval_EntryInput!): A_Asset_Reval_Entry!
	A_Asset_Reval_EntrySaveMany(Entities: [A_Asset_Reval_EntryInput!]!): [A_Asset_Reval_Entry!]!
	A_Asset_Reval_EntryDelete(UUs: [String!]!): Boolean!
}

type A_Asset_Reval_EntryConnection {
	Results: [A_Asset_Reval_Entry!]!
	PagingInfo: PagingInfo!
}

type A_Asset_Reval_Entry {
	UU: ID!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	A_Effective_Date: Date!
	A_Reval_Cal_Method: AD_Ref_List!
	A_Reval_Effective_Date: AD_Ref_List!
	A_Reval_Multiplier: AD_Ref_List!
	A_Rev_Code: AD_Ref_List!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema
	# The Currency for this record
	C_Currency: C_Currency!
	# Document type or rules
	C_DocType: C_DocType
	# Period of the Calendar
	C_Period: C_Period
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date
	# Date of the Document
	DateDoc: Date
	# Optional short description of the record
	Description: String!
	# Document sequence number of the document
	DocumentNo: String!
	# General Ledger Category
	GL_Category: GL_Category
	# The record is active in the system
	IsActive: Boolean!
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input A_Asset_Reval_EntryInput {
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	A_Effective_Date: Date
	A_Reval_Cal_Method: ForeignEntityInput
	A_Reval_Effective_Date: ForeignEntityInput
	A_Reval_Multiplier: ForeignEntityInput
	A_Rev_Code: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Document type or rules
	C_DocType: ForeignEntityInput
	# Period of the Calendar
	C_Period: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Date of the Document
	DateDoc: Date
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String
	# General Ledger Category
	GL_Category: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# The type of posted amount for the transaction
	PostingType: ForeignEntityInput
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
}
