# Generated Schema for A_Asset_Delivery - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	A_Asset_Delivery(UU: String!): A_Asset_Delivery
	A_Asset_DeliveryGet(Page: Int, Size: Int, Sort: String, Filter: String): A_Asset_DeliveryConnection!
}

extend type Mutation {
	A_Asset_DeliverySave(Entity: A_Asset_DeliveryInput!): A_Asset_Delivery!
	A_Asset_DeliverySaveMany(Entities: [A_Asset_DeliveryInput!]!): [A_Asset_Delivery!]!
	A_Asset_DeliveryDelete(UUs: [String!]!): Boolean!
}

type A_Asset_DeliveryConnection {
	Results: [A_Asset_Delivery!]!
	PagingInfo: PagingInfo!
}

type A_Asset_Delivery {
	UU: ID!
	# Asset used internally or by customers
	A_Asset: A_Asset!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# EMail Delivery confirmation
	DeliveryConfirmation: String
	# Optional short description of the record
	Description: String
	# Electronic Mail Address
	EMail: String
	# The record is active in the system
	IsActive: Boolean!
	# Lot number (alphanumeric)
	Lot: String
	# EMail Message ID
	MessageID: String
	# Line on Shipment or Receipt document
	M_InOutLine: M_InOutLine
	# Date a product was moved in or out of inventory
	MovementDate: DateTime!
	# Product downloads
	M_ProductDownload: M_ProductDownload
	# Referring web address
	Referrer: String
	# Remote Address
	Remote_Addr: String
	# Remote host Info
	Remote_Host: String
	# Product Serial Number 
	SerNo: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Full URL address - e.g. http://www.idempiere.org
	URL: String
	# Version Number
	VersionNo: String
}

input A_Asset_DeliveryInput {
	UU: ID
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# EMail Delivery confirmation
	DeliveryConfirmation: String
	# Optional short description of the record
	Description: String
	# Electronic Mail Address
	EMail: String
	# The record is active in the system
	IsActive: Boolean
	# Lot number (alphanumeric)
	Lot: String
	# EMail Message ID
	MessageID: String
	# Line on Shipment or Receipt document
	M_InOutLine: ForeignEntityInput
	# Date a product was moved in or out of inventory
	MovementDate: DateTime
	# Product downloads
	M_ProductDownload: ForeignEntityInput
	# Referring web address
	Referrer: String
	# Remote Address
	Remote_Addr: String
	# Remote host Info
	Remote_Host: String
	# Product Serial Number 
	SerNo: String
	# Full URL address - e.g. http://www.idempiere.org
	URL: String
	# Version Number
	VersionNo: String
}
