# Generated Schema for A_Asset_Info_Lic - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	A_Asset_Info_Lic(UU: String!): A_Asset_Info_Lic
	A_Asset_Info_LicGet(Page: Int, Size: Int, Sort: String, Filter: String): A_Asset_Info_LicConnection!
}

extend type Mutation {
	A_Asset_Info_LicSave(Entity: A_Asset_Info_LicInput!): A_Asset_Info_Lic!
	A_Asset_Info_LicSaveMany(Entities: [A_Asset_Info_LicInput!]!): [A_Asset_Info_Lic!]!
	A_Asset_Info_LicDelete(UUs: [String!]!): Boolean!
}

type A_Asset_Info_LicConnection {
	Results: [A_Asset_Info_Lic!]!
	PagingInfo: PagingInfo!
}

type A_Asset_Info_Lic {
	# Asset used internally or by customers
	A_Asset: A_Asset!
	UU: ID!
	A_Issuing_Agency: String
	A_License_Fee: BigDecimal
	A_License_No: String
	A_Renewal_Date: Date
	# State of the Credit Card or Account holder
	A_State: String
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# The document has been processed
	Processed: Boolean!
	Text: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input A_Asset_Info_LicInput {
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	UU: ID
	A_Issuing_Agency: String
	A_License_Fee: BigDecimal
	A_License_No: String
	A_Renewal_Date: Date
	# State of the Credit Card or Account holder
	A_State: String
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# The document has been processed
	Processed: Boolean
	Text: String
}
