# Generated Schema for A_Asset_Reval_Index - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	A_Asset_Reval_IndexGet(page: Int, size: Int, sort: String, filter: String): A_Asset_Reval_IndexConnection!
}

extend type Mutation {
	A_Asset_Reval_IndexSave(entity: A_Asset_Reval_IndexInput!): A_Asset_Reval_Index!
	A_Asset_Reval_IndexDelete(uuids: [String!]!): Boolean!
}

type A_Asset_Reval_IndexConnection {
	results: [A_Asset_Reval_Index!]!
	pagingInfo: PagingInfo!
}

type A_Asset_Reval_Index {
	ID: ID!
	A_Effective_Date: Date!
	A_Reval_Code: AD_Ref_List!
	A_Reval_Multiplier: AD_Ref_List!
	A_Reval_Rate: Int!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input A_Asset_Reval_IndexInput {
	ID: ID
	A_Effective_Date: Date
	A_Reval_Code: AD_Ref_ListInput
	A_Reval_Multiplier: AD_Ref_ListInput
	A_Reval_Rate: Int
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# The record is active in the system
	IsActive: Boolean
}
