# Generated Schema for A_Asset_Acct - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	A_Asset_Acct(UU: String!): A_Asset_Acct
	A_Asset_AcctGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): A_Asset_AcctConnection!
}

extend type Mutation {
	A_Asset_AcctSave(Entity: A_Asset_AcctInput!): A_Asset_Acct!
	A_Asset_AcctSaveMany(Entities: [A_Asset_AcctInput!]!): [A_Asset_Acct!]!
	A_Asset_AcctDelete(UUs: [String!]!): Boolean!
}

type A_Asset_AcctConnection {
	Results: [A_Asset_Acct!]!
	PagingInfo: PagingInfo!
}

type A_Asset_Acct {
	A_Accumdepreciation_A: C_ValidCombination!
	A_Asset_A: C_ValidCombination!
	UU: ID!
	# Asset used internally or by customers
	A_Asset: A_Asset!
	A_Depreciation_A: C_ValidCombination!
	A_Depreciation_Conv_F: A_Depreciation_Convention
	A_Depreciation_Conv: A_Depreciation_Convention
	A_Depreciation_F: A_Depreciation!
	A_Depreciation: A_Depreciation!
	A_Depreciation_Manual_Amount: BigDecimal
	A_Depreciation_Manual_Period: AD_Ref_List
	A_Depreciation_Method_F: A_Depreciation_Method
	A_Depreciation_Method: A_Depreciation_Method
	A_Depreciation_Table_Header: A_Depreciation_Table_Header
	A_Depreciation_Variable_Perc: BigDecimal
	A_Depreciation_Variable_Perc_F: BigDecimal
	A_Disposal_Gain_A: C_ValidCombination
	A_Disposal_Loss_A: C_ValidCombination!
	A_Disposal_Revenue_A: C_ValidCombination!
	A_Period_End: Int!
	A_Period_Start: Int!
	A_Reval_Adep_Offset_Cur_A: C_ValidCombination
	A_Reval_Adep_Offset_Prior_A: C_ValidCombination
	A_Reval_Cal_Method: AD_Ref_List
	A_Reval_Cost_Offset_A: C_ValidCombination
	A_Reval_Cost_Offset_Prior_A: C_ValidCombination
	A_Reval_Depexp_Offset_A: C_ValidCombination
	A_Salvage_Value: BigDecimal
	A_Split_Percent: BigDecimal!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List!
	Processing: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Valid from including this date (first day)
	ValidFrom: Date
}

input A_Asset_AcctInput {
	A_Accumdepreciation_A: ForeignEntityInput
	A_Asset_A: ForeignEntityInput
	UU: ID
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	A_Depreciation_A: ForeignEntityInput
	A_Depreciation_Conv_F: ForeignEntityInput
	A_Depreciation_Conv: ForeignEntityInput
	A_Depreciation_F: ForeignEntityInput
	A_Depreciation: ForeignEntityInput
	A_Depreciation_Manual_Amount: BigDecimal
	A_Depreciation_Manual_Period: ForeignEntityInput
	A_Depreciation_Method_F: ForeignEntityInput
	A_Depreciation_Method: ForeignEntityInput
	A_Depreciation_Table_Header: ForeignEntityInput
	A_Depreciation_Variable_Perc: BigDecimal
	A_Depreciation_Variable_Perc_F: BigDecimal
	A_Disposal_Gain_A: ForeignEntityInput
	A_Disposal_Loss_A: ForeignEntityInput
	A_Disposal_Revenue_A: ForeignEntityInput
	A_Period_End: Int
	A_Period_Start: Int
	A_Reval_Adep_Offset_Cur_A: ForeignEntityInput
	A_Reval_Adep_Offset_Prior_A: ForeignEntityInput
	A_Reval_Cal_Method: ForeignEntityInput
	A_Reval_Cost_Offset_A: ForeignEntityInput
	A_Reval_Cost_Offset_Prior_A: ForeignEntityInput
	A_Reval_Depexp_Offset_A: ForeignEntityInput
	A_Salvage_Value: BigDecimal
	A_Split_Percent: BigDecimal
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# The type of posted amount for the transaction
	PostingType: ForeignEntityInput
	Processing: Boolean
	# Valid from including this date (first day)
	ValidFrom: Date
}
