# Generated Schema for AD_AllUsers_V - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	AD_AllUsers_V(UU: String!): AD_AllUsers_V
	AD_AllUsers_VGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_AllUsers_VConnection!
}

extend type Mutation {
	AD_AllUsers_VSave(Entity: AD_AllUsers_VInput!): AD_AllUsers_V!
	AD_AllUsers_VSaveMany(Entities: [AD_AllUsers_VInput!]!): [AD_AllUsers_V!]!
	AD_AllUsers_VDelete(UUs: [String!]!): Boolean!
}

type AD_AllUsers_VConnection {
	Results: [AD_AllUsers_V!]!
	PagingInfo: PagingInfo!
}

type AD_AllUsers_V {
	AD_AllClients_V: AD_AllClients_V
	UU: ID!
	# Tenant for this installation.
	AD_Client: AD_Client
	# Organizational entity within tenant
	AD_Org: AD_Org
	# Date this record was created
	Created: DateTime
	# User who created this records
	CreatedBy: AD_User
	DateAccountLocked: DateTime
	DateLastLogin: DateTime
	DatePasswordChanged: Date
	# Optional short description of the record
	Description: String
	# Electronic Mail Address
	EMail: String
	FailedLoginCount: Int
	# The record is active in the system
	IsActive: Boolean!
	IsExpired: Boolean!
	IsLocked: Boolean!
	IsNoExpire: Boolean!
	IsNoPasswordReset: Boolean!
	IsSupportUser: Boolean!
	# User Name used for authorization via LDAP (directory) services
	LDAPUser: String
	# Alphanumeric identifier of the entity
	Name: String
	# Password of any length (case sensitive)
	Password: String
	# Random data added to improve password hash effectiveness
	Salt: String
	# Date this record was updated
	Updated: DateTime
	# User who updated this records
	UpdatedBy: AD_User
	UserPIN: String
	# Search key for the record in the format required - must be unique
	Value: String
}

input AD_AllUsers_VInput {
	AD_AllClients_V: ForeignEntityInput
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	DateAccountLocked: DateTime
	DateLastLogin: DateTime
	DatePasswordChanged: Date
	# Optional short description of the record
	Description: String
	# Electronic Mail Address
	EMail: String
	FailedLoginCount: Int
	# The record is active in the system
	IsActive: Boolean
	IsExpired: Boolean
	IsLocked: Boolean
	IsNoExpire: Boolean
	IsNoPasswordReset: Boolean
	IsSupportUser: Boolean
	# User Name used for authorization via LDAP (directory) services
	LDAPUser: String
	# Alphanumeric identifier of the entity
	Name: String
	# Password of any length (case sensitive)
	Password: String
	# Random data added to improve password hash effectiveness
	Salt: String
	UserPIN: String
	# Search key for the record in the format required - must be unique
	Value: String
}
