# Generated Schema for AD_ZoomCondition - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_ZoomConditionGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_ZoomConditionConnection!
}

extend type Mutation {
	AD_ZoomConditionSave(Entity: AD_ZoomConditionInput!): AD_ZoomCondition!
	AD_ZoomConditionSaveMany(Entities: [AD_ZoomConditionInput!]!): [AD_ZoomCondition!]!
	AD_ZoomConditionDelete(UUs: [String!]!): Boolean!
}

type AD_ZoomConditionConnection {
	Results: [AD_ZoomCondition!]!
	PagingInfo: PagingInfo!
}

type AD_ZoomCondition {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table!
	# Data entry or display window
	AD_Window: AD_Window!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Fully qualified SQL WHERE clause
	WhereClause: String
	# the result determines if the zoom condition is applied
	ZoomLogic: String
}

input AD_ZoomConditionInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Data entry or display window
	AD_Window: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Fully qualified SQL WHERE clause
	WhereClause: String
	# the result determines if the zoom condition is applied
	ZoomLogic: String
}
