# Generated Schema for AD_Attribute_Value - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_Attribute_ValueGet(page: Int, size: Int, sort: String, filter: String): AD_Attribute_ValueConnection!
}

extend type Mutation {
	AD_Attribute_ValueSave(entity: AD_Attribute_ValueInput!): AD_Attribute_Value!
	AD_Attribute_ValueSaveMany(entities: [AD_Attribute_ValueInput!]!): [AD_Attribute_Value!]!
	AD_Attribute_ValueDelete(uuids: [String!]!): Boolean!
}

type AD_Attribute_ValueConnection {
	results: [AD_Attribute_Value!]!
	pagingInfo: PagingInfo!
}

type AD_Attribute_Value {
	AD_Attribute: AD_Attribute!
	UUID: ID!
	V_Date: Date
	V_Number: String
	V_String: String
}

input AD_Attribute_ValueInput {
	AD_Attribute: ForeignEntityInput
	UUID: ID
	V_Date: Date
	V_Number: String
	V_String: String
}
