# Generated Schema for AD_InfoProcess - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_InfoProcess(UU: String!): AD_InfoProcess
	AD_InfoProcessGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_InfoProcessConnection!
}

extend type Mutation {
	AD_InfoProcessSave(Entity: AD_InfoProcessInput!): AD_InfoProcess!
	AD_InfoProcessSaveMany(Entities: [AD_InfoProcessInput!]!): [AD_InfoProcess!]!
	AD_InfoProcessDelete(UUs: [String!]!): Boolean!
}

type AD_InfoProcessConnection {
	Results: [AD_InfoProcess!]!
	PagingInfo: PagingInfo!
}

type AD_InfoProcess {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Info Window Column
	AD_InfoColumn: AD_InfoColumn
	UU: ID!
	# Info and search/select Window
	AD_InfoWindow: AD_InfoWindow
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Process or Report
	AD_Process: AD_Process!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# URL of  image
	ImageURL: String
	# The record is active in the system
	IsActive: Boolean!
	# Layout type of info process
	LayoutType: AD_Ref_List!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_InfoProcessInput {
	# Info Window Column
	AD_InfoColumn: ForeignEntityInput
	UU: ID
	# Info and search/select Window
	AD_InfoWindow: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Process or Report
	AD_Process: ForeignEntityInput
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# URL of  image
	ImageURL: String
	# The record is active in the system
	IsActive: Boolean
	# Layout type of info process
	LayoutType: ForeignEntityInput
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
