# Generated Schema for AD_Sequence_Audit - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_Sequence_AuditGet(page: Int, size: Int, sort: String, filter: String): AD_Sequence_AuditConnection!
}

extend type Mutation {
	AD_Sequence_AuditSave(entity: AD_Sequence_AuditInput!): AD_Sequence_Audit!
	AD_Sequence_AuditSaveMany(entities: [AD_Sequence_AuditInput!]!): [AD_Sequence_Audit!]!
	AD_Sequence_AuditDelete(uuids: [String!]!): Boolean!
}

type AD_Sequence_AuditConnection {
	results: [AD_Sequence_Audit!]!
	pagingInfo: PagingInfo!
}

type AD_Sequence_Audit {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	UUID: ID!
	# Document Sequence
	AD_Sequence: AD_Sequence!
	# Database Table information
	AD_Table: AD_Table!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Document sequence number of the document
	DocumentNo: String!
	# The record is active in the system
	IsActive: Boolean!
	# Direct internal record ID
	Record_ID: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Sequence_AuditInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	UUID: ID
	# Document Sequence
	AD_Sequence: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean
	# Direct internal record ID
	Record_ID: Int
}
