# Generated Schema for AD_PasswordRule - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_PasswordRuleGet(page: Int, size: Int, sort: String, filter: String): AD_PasswordRuleConnection!
}

extend type Mutation {
	AD_PasswordRuleSave(entity: AD_PasswordRuleInput!): AD_PasswordRule!
	AD_PasswordRuleSaveMany(entities: [AD_PasswordRuleInput!]!): [AD_PasswordRule!]!
	AD_PasswordRuleDelete(uuids: [String!]!): Boolean!
}

type AD_PasswordRuleConnection {
	results: [AD_PasswordRule!]!
	pagingInfo: PagingInfo!
}

type AD_PasswordRule {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UUID: ID!
	AD_PasswordRule_UU: String
	# Require at least # alphabetical in passwords
	AlphabeticalCharacter: Int
	# Length of alphabetical sequence to validate
	AlphabeticalSequence: Int
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Define number of day can reuse password
	Days_Reuse_Password: Int
	# Require at least # digit in passwords
	DigitCharacter: Int
	# The record is active in the system
	IsActive: Boolean!
	# Match dictionary words backwards
	IsDictMatchBackwards: Boolean!
	# Validate the password doesn't contain user name (ignore case and match backwards)
	IsUserNameRule: Boolean!
	IsUsingDictionary: Boolean!
	# Whitespace validation
	IsWhitespace: Boolean!
	# Require at least # lower case char
	LowercaseCharacter: Int
	# Maximum Length of Data
	MaxLength: Int
	MinLength: Int
	# Alphanumeric identifier of the entity
	Name: String!
	# Require at least # non-alphanumeric char
	NonAlphaNumericCharacter: Int
	# Length of numerical sequence to validate
	NumericalSequence: Int
	PathDictionary: String
	# Length of QWERTY sequences to validate
	QWERTYSequence: Int
	# Length of repeated characters to validate
	RepeatCharacterRegex: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User
	# Require at least # upper case char
	UppercaseCharacter: Int
}

input AD_PasswordRuleInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UUID: ID
	AD_PasswordRule_UU: String
	# Require at least # alphabetical in passwords
	AlphabeticalCharacter: Int
	# Length of alphabetical sequence to validate
	AlphabeticalSequence: Int
	# Define number of day can reuse password
	Days_Reuse_Password: Int
	# Require at least # digit in passwords
	DigitCharacter: Int
	# The record is active in the system
	IsActive: Boolean
	# Match dictionary words backwards
	IsDictMatchBackwards: Boolean
	# Validate the password doesn't contain user name (ignore case and match backwards)
	IsUserNameRule: Boolean
	IsUsingDictionary: Boolean
	# Whitespace validation
	IsWhitespace: Boolean
	# Require at least # lower case char
	LowercaseCharacter: Int
	# Maximum Length of Data
	MaxLength: Int
	MinLength: Int
	# Alphanumeric identifier of the entity
	Name: String
	# Require at least # non-alphanumeric char
	NonAlphaNumericCharacter: Int
	# Length of numerical sequence to validate
	NumericalSequence: Int
	PathDictionary: String
	# Length of QWERTY sequences to validate
	QWERTYSequence: Int
	# Length of repeated characters to validate
	RepeatCharacterRegex: Int
	# Require at least # upper case char
	UppercaseCharacter: Int
}
