# Generated Schema for AD_WF_ActivityResult - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_WF_ActivityResultGet(page: Int, size: Int, sort: String, filter: String): AD_WF_ActivityResultConnection!
}

extend type Mutation {
	AD_WF_ActivityResultSave(entity: AD_WF_ActivityResultInput!): AD_WF_ActivityResult!
	AD_WF_ActivityResultSaveMany(entities: [AD_WF_ActivityResultInput!]!): [AD_WF_ActivityResult!]!
	AD_WF_ActivityResultDelete(uuids: [String!]!): Boolean!
}

type AD_WF_ActivityResultConnection {
	results: [AD_WF_ActivityResult!]!
	pagingInfo: PagingInfo!
}

type AD_WF_ActivityResult {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Workflow Activity
	AD_WF_Activity: AD_WF_Activity!
	UUID: ID!
	AD_WF_ActivityResult_UU: String
	# Name of the Attribute
	AttributeName: String!
	# Value of the Attribute
	AttributeValue: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_WF_ActivityResultInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Workflow Activity
	AD_WF_Activity: ForeignEntityInput
	UUID: ID
	AD_WF_ActivityResult_UU: String
	# Name of the Attribute
	AttributeName: String
	# Value of the Attribute
	AttributeValue: String
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
}
