# Generated Schema for AD_Password_History - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_Password_History(UU: String!): AD_Password_History
	AD_Password_HistoryGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_Password_HistoryConnection!
}

extend type Mutation {
	AD_Password_HistorySave(Entity: AD_Password_HistoryInput!): AD_Password_History!
	AD_Password_HistorySaveMany(Entities: [AD_Password_HistoryInput!]!): [AD_Password_History!]!
	AD_Password_HistoryDelete(UUs: [String!]!): Boolean!
}

type AD_Password_HistoryConnection {
	Results: [AD_Password_History!]!
	PagingInfo: PagingInfo!
}

type AD_Password_History {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	DatePasswordChanged: Date
	# The record is active in the system
	IsActive: Boolean!
	# Password of any length (case sensitive)
	Password: String
	# Random data added to improve password hash effectiveness
	Salt: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Password_HistoryInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	DatePasswordChanged: Date
	# The record is active in the system
	IsActive: Boolean
	# Password of any length (case sensitive)
	Password: String
	# Random data added to improve password hash effectiveness
	Salt: String
}
