# Generated Schema for AD_UserDef_Win - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_UserDef_Win(UU: String!): AD_UserDef_Win
	AD_UserDef_WinGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_UserDef_WinConnection!
}

extend type Mutation {
	AD_UserDef_WinSave(Entity: AD_UserDef_WinInput!): AD_UserDef_Win!
	AD_UserDef_WinSaveMany(Entities: [AD_UserDef_WinInput!]!): [AD_UserDef_Win!]!
	AD_UserDef_WinDelete(UUs: [String!]!): Boolean!
}

type AD_UserDef_WinConnection {
	Results: [AD_UserDef_Win!]!
	PagingInfo: PagingInfo!
}

type AD_UserDef_Win {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Language for this entity
	AD_Language: AD_Language
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	UU: ID!
	# Data entry or display window
	AD_Window: AD_Window!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# Field is read only
	IsReadOnly: Boolean!
	# The field can be updated by the user
	IsUserUpdateable: Boolean!
	# Alphanumeric identifier of the entity
	Name: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_UserDef_WinInput {
	# Language for this entity
	AD_Language: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	UU: ID
	# Data entry or display window
	AD_Window: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# Field is read only
	IsReadOnly: Boolean
	# The field can be updated by the user
	IsUserUpdateable: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
