# Generated Schema for AD_PrintLabelLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_PrintLabelLine(UU: String!): AD_PrintLabelLine
	AD_PrintLabelLineGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): AD_PrintLabelLineConnection!
}

extend type Mutation {
	AD_PrintLabelLineSave(Entity: AD_PrintLabelLineInput!): AD_PrintLabelLine!
	AD_PrintLabelLineSaveMany(Entities: [AD_PrintLabelLineInput!]!): [AD_PrintLabelLine!]!
	AD_PrintLabelLineDelete(UUs: [String!]!): Boolean!
}

type AD_PrintLabelLineConnection {
	Results: [AD_PrintLabelLine!]!
	PagingInfo: PagingInfo!
}

type AD_PrintLabelLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Column in the table
	AD_Column: AD_Column
	# Function of Label Printer
	AD_LabelPrinterFunction: AD_LabelPrinterFunction!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Label Format to print
	AD_PrintLabel: AD_PrintLabel!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Label Format Type
	LabelFormatType: AD_Ref_List!
	# Alphanumeric identifier of the entity
	Name: String!
	# The label text to be printed on a document or correspondence.
	PrintName: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Absolute X (horizontal) position in 1/72 of an inch
	XPosition: Int!
	# Absolute Y (vertical) position in 1/72 of an inch
	YPosition: Int!
}

input AD_PrintLabelLineInput {
	# Column in the table
	AD_Column: ForeignEntityInput
	# Function of Label Printer
	AD_LabelPrinterFunction: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Label Format to print
	AD_PrintLabel: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Label Format Type
	LabelFormatType: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# The label text to be printed on a document or correspondence.
	PrintName: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Absolute X (horizontal) position in 1/72 of an inch
	XPosition: Int
	# Absolute Y (vertical) position in 1/72 of an inch
	YPosition: Int
}
