# Generated Schema for AD_TreeNodeCMT - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_TreeNodeCMT(UU: String!): AD_TreeNodeCMT
	AD_TreeNodeCMTGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_TreeNodeCMTConnection!
}

extend type Mutation {
	AD_TreeNodeCMTSave(Entity: AD_TreeNodeCMTInput!): AD_TreeNodeCMT!
	AD_TreeNodeCMTSaveMany(Entities: [AD_TreeNodeCMTInput!]!): [AD_TreeNodeCMT!]!
	AD_TreeNodeCMTDelete(UUs: [String!]!): Boolean!
}

type AD_TreeNodeCMTConnection {
	Results: [AD_TreeNodeCMT!]!
	PagingInfo: PagingInfo!
}

type AD_TreeNodeCMT {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodeCMTInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
