# Generated Schema for AD_TreeNode - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_TreeNode(UU: String!): AD_TreeNode
	AD_TreeNodeGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_TreeNodeConnection!
}

extend type Mutation {
	AD_TreeNodeSave(Entity: AD_TreeNodeInput!): AD_TreeNode!
	AD_TreeNodeSaveMany(Entities: [AD_TreeNodeInput!]!): [AD_TreeNode!]!
	AD_TreeNodeDelete(UUs: [String!]!): Boolean!
}

type AD_TreeNodeConnection {
	Results: [AD_TreeNode!]!
	PagingInfo: PagingInfo!
}

type AD_TreeNode {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
