# Generated Schema for AD_Tab_Customization - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_Tab_CustomizationGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_Tab_CustomizationConnection!
}

extend type Mutation {
	AD_Tab_CustomizationSave(Entity: AD_Tab_CustomizationInput!): AD_Tab_Customization!
	AD_Tab_CustomizationSaveMany(Entities: [AD_Tab_CustomizationInput!]!): [AD_Tab_Customization!]!
	AD_Tab_CustomizationDelete(UUs: [String!]!): Boolean!
}

type AD_Tab_CustomizationConnection {
	Results: [AD_Tab_Customization!]!
	PagingInfo: PagingInfo!
}

type AD_Tab_Customization {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Tab within a Window
	AD_Tab: AD_Tab
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	Custom: String!
	# The record is active in the system
	IsActive: Boolean!
	IsAutoHideEmptyColumn: AD_Ref_List
	IsDisplayedGrid: AD_Ref_List
	# Display in Quick Form
	IsQuickForm: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Tab_CustomizationInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Tab within a Window
	AD_Tab: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	Custom: String
	# The record is active in the system
	IsActive: Boolean
	IsAutoHideEmptyColumn: ForeignEntityInput
	IsDisplayedGrid: ForeignEntityInput
	# Display in Quick Form
	IsQuickForm: Boolean
}
