# Generated Schema for AD_RecentItem - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_RecentItem(UU: String!): AD_RecentItem
	AD_RecentItemGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_RecentItemConnection!
}

extend type Mutation {
	AD_RecentItemSave(Entity: AD_RecentItemInput!): AD_RecentItem!
	AD_RecentItemSaveMany(Entities: [AD_RecentItemInput!]!): [AD_RecentItem!]!
	AD_RecentItemDelete(UUs: [String!]!): Boolean!
}

type AD_RecentItemConnection {
	Results: [AD_RecentItem!]!
	PagingInfo: PagingInfo!
}

type AD_RecentItem {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Responsibility Role
	AD_Role: AD_Role!
	# Tab within a Window
	AD_Tab: AD_Tab
	# Database Table information
	AD_Table: AD_Table!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Data entry or display window
	AD_Window: AD_Window
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_RecentItemInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# Tab within a Window
	AD_Tab: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Data entry or display window
	AD_Window: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
}
