# Generated Schema for AD_OrgType - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_OrgType(UU: String!): AD_OrgType
	AD_OrgTypeGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_OrgTypeConnection!
}

extend type Mutation {
	AD_OrgTypeSave(Entity: AD_OrgTypeInput!): AD_OrgType!
	AD_OrgTypeSaveMany(Entities: [AD_OrgTypeInput!]!): [AD_OrgType!]!
	AD_OrgTypeDelete(UUs: [String!]!): Boolean!
}

type AD_OrgTypeConnection {
	Results: [AD_OrgType!]!
	PagingInfo: PagingInfo!
}

type AD_OrgType {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Color used for printing and display
	AD_PrintColor: AD_PrintColor
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_OrgTypeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Color used for printing and display
	AD_PrintColor: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
