# Generated Schema for AD_CtxHelpSuggestion - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_CtxHelpSuggestion(UU: String!): AD_CtxHelpSuggestion
	AD_CtxHelpSuggestionGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_CtxHelpSuggestionConnection!
}

extend type Mutation {
	AD_CtxHelpSuggestionSave(Entity: AD_CtxHelpSuggestionInput!): AD_CtxHelpSuggestion!
	AD_CtxHelpSuggestionSaveMany(Entities: [AD_CtxHelpSuggestionInput!]!): [AD_CtxHelpSuggestion!]!
	AD_CtxHelpSuggestionDelete(UUs: [String!]!): Boolean!
}

type AD_CtxHelpSuggestionConnection {
	Results: [AD_CtxHelpSuggestion!]!
	PagingInfo: PagingInfo!
}

type AD_CtxHelpSuggestion {
	# Accept suggested changes
	AcceptSuggestion: String
	# Tenant for this installation.
	AD_Client: AD_Client!
	AD_CtxHelp: AD_CtxHelp!
	AD_CtxHelpMsg: AD_CtxHelpMsg!
	UU: ID!
	# Language for this entity
	AD_Language: AD_Language!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AD_UserClient: AD_AllClients_V!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_AllUsers_V!
	# Compare suggested text with original text
	CompareSuggestion: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Indicates if this document requires approval
	IsApproved: Boolean!
	# Apply changes as tenant customization
	IsSaveAsTenantCustomization: Boolean!
	# Textual Informational, Menu or Error Message
	MsgText: String!
	# The document has been processed
	Processed: Boolean!
	# Reject suggested changes
	RejectSuggestion: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_CtxHelpSuggestionInput {
	# Accept suggested changes
	AcceptSuggestion: String
	AD_CtxHelp: ForeignEntityInput
	AD_CtxHelpMsg: ForeignEntityInput
	UU: ID
	# Language for this entity
	AD_Language: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AD_UserClient: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Compare suggested text with original text
	CompareSuggestion: String
	# The record is active in the system
	IsActive: Boolean
	# Indicates if this document requires approval
	IsApproved: Boolean
	# Apply changes as tenant customization
	IsSaveAsTenantCustomization: Boolean
	# Textual Informational, Menu or Error Message
	MsgText: String
	# The document has been processed
	Processed: Boolean
	# Reject suggested changes
	RejectSuggestion: String
}
