# Generated Schema for AD_WorkbenchWindow - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	AD_WorkbenchWindowGet(page: Int, size: Int, sort: String, filter: String): AD_WorkbenchWindowConnection!
}

extend type Mutation {
	AD_WorkbenchWindowSave(entity: AD_WorkbenchWindowInput!): AD_WorkbenchWindow!
	AD_WorkbenchWindowDelete(uuids: [String!]!): Boolean!
}

type AD_WorkbenchWindowConnection {
	results: [AD_WorkbenchWindow!]!
	pagingInfo: PagingInfo!
}

type AD_WorkbenchWindow {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Special Form
	AD_Form: AD_Form
	# Organizational entity within client
	AD_Org: AD_Org!
	# Process or Report
	AD_Process: AD_Process
	# Operation System Task
	AD_Task: AD_Task
	# Data entry or display window
	AD_Window: AD_Window
	# Collection of windows, reports
	AD_Workbench: AD_Workbench!
	ID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Indicates if this is the primary budget
	IsPrimary: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_WorkbenchWindowInput {
	# Special Form
	AD_Form: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Process or Report
	AD_Process: ForeignEntityInput
	# Operation System Task
	AD_Task: ForeignEntityInput
	# Data entry or display window
	AD_Window: ForeignEntityInput
	# Collection of windows, reports
	AD_Workbench: ForeignEntityInput
	ID: ID
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Indicates if this is the primary budget
	IsPrimary: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
