# Generated Schema for AD_AuthorizationAccount - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_AuthorizationAccount(UU: String!): AD_AuthorizationAccount
	AD_AuthorizationAccountGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_AuthorizationAccountConnection!
}

extend type Mutation {
	AD_AuthorizationAccountSave(Entity: AD_AuthorizationAccountInput!): AD_AuthorizationAccount!
	AD_AuthorizationAccountSaveMany(Entities: [AD_AuthorizationAccountInput!]!): [AD_AuthorizationAccount!]!
	AD_AuthorizationAccountDelete(UUs: [String!]!): Boolean!
}

type AD_AuthorizationAccountConnection {
	Results: [AD_AuthorizationAccount!]!
	PagingInfo: PagingInfo!
}

type AD_AuthorizationAccount {
	AccessToken: String
	AccessTokenTimestamp: DateTime
	UU: ID!
	AD_AuthorizationCredential: AD_AuthorizationCredential
	AD_AuthorizationScopes: AD_Ref_List
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Electronic Mail Address
	EMail: String
	ExpireInSeconds: BigDecimal
	# Comment or Hint
	Help: String
	IsAccessRevoked: Boolean!
	# The record is active in the system
	IsActive: Boolean!
	IsAuthorized: Boolean!
	Preferred_UserName: String
	RefreshToken: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_AuthorizationAccountInput {
	AccessToken: String
	AccessTokenTimestamp: DateTime
	UU: ID
	AD_AuthorizationCredential: ForeignEntityInput
	AD_AuthorizationScopes: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Electronic Mail Address
	EMail: String
	ExpireInSeconds: BigDecimal
	# Comment or Hint
	Help: String
	IsAccessRevoked: Boolean
	# The record is active in the system
	IsActive: Boolean
	IsAuthorized: Boolean
	Preferred_UserName: String
	RefreshToken: String
}
