# Generated Model - DO NOT CHANGE

# Generated Model for AD_Client
# @author iDempiere (generated) 
# @version Release 8.2 - $Id$
#extend type Query {
#	AD_ClientGet(page: Int, size: Int, sort: String, filter: String): AD_ClientConnection!
#}

extend type Mutation {
	AD_ClientSave(entity: AD_ClientInput!): AD_Client!
	AD_ClientDelete(uuids: [String!]!): Boolean!
}

#type AD_ClientConnection {
#	results: [AD_Client!]!
#	pagingInfo: PagingInfo!
#}

type AD_Client {
	ID: ID!
}

input AD_ClientInput {
	ID: ID
}
