# Generated Schema for AD_AlertProcessor - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	AD_AlertProcessorGet(page: Int, size: Int, sort: String, filter: String): AD_AlertProcessorConnection!
}

extend type Mutation {
	AD_AlertProcessorSave(entity: AD_AlertProcessorInput!): AD_AlertProcessor!
	AD_AlertProcessorSaveMany(entities: [AD_AlertProcessorInput!]!): [AD_AlertProcessor!]!
	AD_AlertProcessorDelete(uuids: [String!]!): Boolean!
}

type AD_AlertProcessorConnection {
	results: [AD_AlertProcessor!]!
	pagingInfo: PagingInfo!
}

type AD_AlertProcessor {
	UUID: ID!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	AD_Schedule: AD_Schedule!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date the process was last run.
	DateLastRun: Date
	# Date the process will run next
	DateNextRun: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Number of days to keep the log entries
	KeepLogDays: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: AD_User!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_AlertProcessorInput {
	UUID: ID
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	AD_Schedule: ForeignEntityInput
	# Date the process was last run.
	DateLastRun: Date
	# Date the process will run next
	DateNextRun: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Number of days to keep the log entries
	KeepLogDays: Int
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: ForeignEntityInput
}
