# Generated Schema for AD_FieldGroup - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_FieldGroupGet(page: Int, size: Int, sort: String, filter: String): AD_FieldGroupConnection!
}

extend type Mutation {
	AD_FieldGroupSave(entity: AD_FieldGroupInput!): AD_FieldGroup!
	AD_FieldGroupSaveMany(entities: [AD_FieldGroupInput!]!): [AD_FieldGroup!]!
	AD_FieldGroupDelete(uuids: [String!]!): Boolean!
}

type AD_FieldGroupConnection {
	results: [AD_FieldGroup!]!
	pagingInfo: PagingInfo!
}

type AD_FieldGroup {
	# Tenant for this installation.
	AD_Client: AD_Client!
	UUID: ID!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# An abbreviation for a given name
	BH_Abbreviation: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	FieldGroupType: AD_Ref_List
	# The record is active in the system
	IsActive: Boolean!
	# Flag to set the initial state of collapsible field group.
	IsCollapsedByDefault: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_FieldGroupInput {
	UUID: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# An abbreviation for a given name
	BH_Abbreviation: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	FieldGroupType: AD_Ref_ListInput
	# The record is active in the system
	IsActive: Boolean
	# Flag to set the initial state of collapsible field group.
	IsCollapsedByDefault: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
