# Generated Schema for AD_WorkflowProcessor - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	AD_WorkflowProcessorGet(page: Int, size: Int, sort: String, filter: String): AD_WorkflowProcessorConnection!
}

type AD_WorkflowProcessorConnection {
	results: [AD_WorkflowProcessor!]!
	pagingInfo: PagingInfo!
}

type AD_WorkflowProcessor {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	AD_Schedule: AD_Schedule!
	ID: ID!
	# Send alert email when over priority
	AlertOverPriority: Int
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date the process was last run.
	DateLastRun: Date
	# Date the process will run next
	DateNextRun: Date
	# Optional short description of the record
	Description: String
	# Send Alert when there is no activity after days (0= no alert)
	InactivityAlertDays: Int
	# The record is active in the system
	IsActive: Boolean!
	# Number of days to keep the log entries
	KeepLogDays: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Days between sending Reminder Emails for a due or inactive Document
	RemindDays: Int
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: AD_User!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

