# Generated Schema for AD_Task_Access - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_Task_Access(UU: String!): AD_Task_Access
	AD_Task_AccessGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_Task_AccessConnection!
}

extend type Mutation {
	AD_Task_AccessSave(Entity: AD_Task_AccessInput!): AD_Task_Access!
	AD_Task_AccessSaveMany(Entities: [AD_Task_AccessInput!]!): [AD_Task_Access!]!
	AD_Task_AccessDelete(UUs: [String!]!): Boolean!
}

type AD_Task_AccessConnection {
	Results: [AD_Task_Access!]!
	PagingInfo: PagingInfo!
}

type AD_Task_Access {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role!
	UU: ID!
	# Operation System Task
	AD_Task: AD_Task!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Field is read / write
	IsReadWrite: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Task_AccessInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	UU: ID
	# Operation System Task
	AD_Task: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Field is read / write
	IsReadWrite: Boolean
}
