# Generated Schema for AD_Role_OrgAccess - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_Role_OrgAccessGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_Role_OrgAccessConnection!
}

extend type Mutation {
	AD_Role_OrgAccessSave(Entity: AD_Role_OrgAccessInput!): AD_Role_OrgAccess!
	AD_Role_OrgAccessSaveMany(Entities: [AD_Role_OrgAccessInput!]!): [AD_Role_OrgAccess!]!
	AD_Role_OrgAccessDelete(UUs: [String!]!): Boolean!
}

type AD_Role_OrgAccessConnection {
	Results: [AD_Role_OrgAccess!]!
	PagingInfo: PagingInfo!
}

type AD_Role_OrgAccess {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Field is read only
	IsReadOnly: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Role_OrgAccessInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Field is read only
	IsReadOnly: Boolean
}
