# Generated Schema for AD_CtxHelp - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_CtxHelp(UU: String!): AD_CtxHelp
	AD_CtxHelpGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_CtxHelpConnection!
}

extend type Mutation {
	AD_CtxHelpSave(Entity: AD_CtxHelpInput!): AD_CtxHelp!
	AD_CtxHelpSaveMany(Entities: [AD_CtxHelpInput!]!): [AD_CtxHelp!]!
	AD_CtxHelpDelete(UUs: [String!]!): Boolean!
}

type AD_CtxHelpConnection {
	Results: [AD_CtxHelp!]!
	PagingInfo: PagingInfo!
}

type AD_CtxHelp {
	# Tenant for this installation.
	AD_Client: AD_Client!
	UU: ID!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Type of Context Help
	CtxType: AD_Ref_List
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_CtxHelpInput {
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Type of Context Help
	CtxType: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
