# Generated Schema for AD_ImportTemplateAccess - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_ImportTemplateAccess(UU: String!): AD_ImportTemplateAccess
	AD_ImportTemplateAccessGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_ImportTemplateAccessConnection!
}

extend type Mutation {
	AD_ImportTemplateAccessSave(Entity: AD_ImportTemplateAccessInput!): AD_ImportTemplateAccess!
	AD_ImportTemplateAccessSaveMany(Entities: [AD_ImportTemplateAccessInput!]!): [AD_ImportTemplateAccess!]!
	AD_ImportTemplateAccessDelete(UUs: [String!]!): Boolean!
}

type AD_ImportTemplateAccessConnection {
	Results: [AD_ImportTemplateAccess!]!
	PagingInfo: PagingInfo!
}

type AD_ImportTemplateAccess {
	# Tenant for this installation.
	AD_Client: AD_Client
	AD_ImportTemplate: AD_ImportTemplate
	UU: ID!
	# Organizational entity within tenant
	AD_Org: AD_Org
	# Responsibility Role
	AD_Role: AD_Role
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User
	# The record is active in the system
	IsActive: Boolean!
	IsAllowInsert: Boolean!
	IsAllowMerge: Boolean!
	IsAllowUpdate: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User
}

input AD_ImportTemplateAccessInput {
	AD_ImportTemplate: ForeignEntityInput
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	IsAllowInsert: Boolean
	IsAllowMerge: Boolean
	IsAllowUpdate: Boolean
}
