# Generated Schema for AD_Style - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_StyleGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_StyleConnection!
}

extend type Mutation {
	AD_StyleSave(Entity: AD_StyleInput!): AD_Style!
	AD_StyleSaveMany(Entities: [AD_StyleInput!]!): [AD_Style!]!
	AD_StyleDelete(UUs: [String!]!): Boolean!
}

type AD_StyleConnection {
	Results: [AD_Style!]!
	PagingInfo: PagingInfo!
}

type AD_Style {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Date this record was created
	Created: Date
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Wrap content in Span and apply the Style to it.
	IsWrapWithSpan: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_StyleInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Wrap content in Span and apply the Style to it.
	IsWrapWithSpan: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
