# Generated Schema for AD_UserPreference - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_UserPreference(UU: String!): AD_UserPreference
	AD_UserPreferenceGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_UserPreferenceConnection!
}

extend type Mutation {
	AD_UserPreferenceSave(Entity: AD_UserPreferenceInput!): AD_UserPreference!
	AD_UserPreferenceSaveMany(Entities: [AD_UserPreferenceInput!]!): [AD_UserPreference!]!
	AD_UserPreferenceDelete(UUs: [String!]!): Boolean!
}

type AD_UserPreferenceConnection {
	Results: [AD_UserPreference!]!
	PagingInfo: PagingInfo!
}

type AD_UserPreference {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	UU: ID!
	# Automatically save changes to the current record upon user navigation.
	AutoCommit: Boolean!
	# Automatically insert a decimal point
	AutomaticDecimalPlacesForAmoun: Int
	AutoNew: Boolean!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Force grid view when Find panel closes if number of records exceed threshold
	GridAfterFindThreshold: Int
	# The record is active in the system
	IsActive: Boolean!
	IsDetailedZoomAcross: Boolean!
	IsReadOnlySession: Boolean!
	IsShowTechnicalInfOnHelp: Boolean!
	IsUseSimilarTo: Boolean!
	MigrationScriptComment: String
	# Defines if double click in a field on grid mode switch to form view
	ToggleOnDoubleClick: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Does the system must switch to grid mode after the Find panel closes
	ViewFindResult: AD_Ref_List!
}

input AD_UserPreferenceInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	UU: ID
	# Automatically save changes to the current record upon user navigation.
	AutoCommit: Boolean
	# Automatically insert a decimal point
	AutomaticDecimalPlacesForAmoun: Int
	AutoNew: Boolean
	# Force grid view when Find panel closes if number of records exceed threshold
	GridAfterFindThreshold: Int
	# The record is active in the system
	IsActive: Boolean
	IsDetailedZoomAcross: Boolean
	IsReadOnlySession: Boolean
	IsShowTechnicalInfOnHelp: Boolean
	IsUseSimilarTo: Boolean
	MigrationScriptComment: String
	# Defines if double click in a field on grid mode switch to form view
	ToggleOnDoubleClick: Boolean
	# Does the system must switch to grid mode after the Find panel closes
	ViewFindResult: ForeignEntityInput
}
