# Generated Schema for AD_User_OrgAccess - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_User_OrgAccessGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_User_OrgAccessConnection!
}

extend type Mutation {
	AD_User_OrgAccessSave(Entity: AD_User_OrgAccessInput!): AD_User_OrgAccess!
	AD_User_OrgAccessSaveMany(Entities: [AD_User_OrgAccessInput!]!): [AD_User_OrgAccess!]!
	AD_User_OrgAccessDelete(UUs: [String!]!): Boolean!
}

type AD_User_OrgAccessConnection {
	Results: [AD_User_OrgAccess!]!
	PagingInfo: PagingInfo!
}

type AD_User_OrgAccess {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Field is read only
	IsReadOnly: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_User_OrgAccessInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Field is read only
	IsReadOnly: Boolean
}
