# Generated Schema for AD_TreeNodeU4 - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_TreeNodeU4(UU: String!): AD_TreeNodeU4
	AD_TreeNodeU4Get(Page: Int, Size: Int, Sort: String, Filter: String): AD_TreeNodeU4Connection!
}

extend type Mutation {
	AD_TreeNodeU4Save(Entity: AD_TreeNodeU4Input!): AD_TreeNodeU4!
	AD_TreeNodeU4SaveMany(Entities: [AD_TreeNodeU4Input!]!): [AD_TreeNodeU4!]!
	AD_TreeNodeU4Delete(UUs: [String!]!): Boolean!
}

type AD_TreeNodeU4Connection {
	Results: [AD_TreeNodeU4!]!
	PagingInfo: PagingInfo!
}

type AD_TreeNodeU4 {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodeU4Input {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
