# Generated Schema for AD_SysConfig - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_SysConfig(UU: String!): AD_SysConfig
	AD_SysConfigGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): AD_SysConfigConnection!
}

extend type Mutation {
	AD_SysConfigSave(Entity: AD_SysConfigInput!): AD_SysConfig!
	AD_SysConfigSaveMany(Entities: [AD_SysConfigInput!]!): [AD_SysConfig!]!
	AD_SysConfigDelete(UUs: [String!]!): Boolean!
}

type AD_SysConfigConnection {
	Results: [AD_SysConfig!]!
	PagingInfo: PagingInfo!
}

type AD_SysConfig {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Configuration Level for this parameter
	ConfigurationLevel: AD_Ref_List
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input AD_SysConfigInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Configuration Level for this parameter
	ConfigurationLevel: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
