# Generated Schema for AD_Attachment - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_AttachmentGet(page: Int, size: Int, sort: String, filter: String): AD_AttachmentConnection!
}

extend type Mutation {
	AD_AttachmentSave(entity: AD_AttachmentInput!): AD_Attachment!
	AD_AttachmentDelete(uuids: [String!]!): Boolean!
}

type AD_AttachmentConnection {
	results: [AD_Attachment!]!
	pagingInfo: PagingInfo!
}

type AD_Attachment {
	ID: ID!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table!
	# Binary Data
	BinaryData: Binary
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Direct internal record ID
	Record_ID: Int!
	# Text Message
	TextMsg: String
	# Name this entity is referred to as
	Title: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_AttachmentInput {
	ID: ID
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Binary Data
	BinaryData: Binary
	# The record is active in the system
	IsActive: Boolean
	# Direct internal record ID
	Record_ID: Int
	# Text Message
	TextMsg: String
	# Name this entity is referred to as
	Title: String
}
