# Generated Schema for AD_StatusLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_StatusLineGet(page: Int, size: Int, sort: String, filter: String): AD_StatusLineConnection!
}

extend type Mutation {
	AD_StatusLineSave(entity: AD_StatusLineInput!): AD_StatusLine!
	AD_StatusLineSaveMany(entities: [AD_StatusLineInput!]!): [AD_StatusLine!]!
	AD_StatusLineDelete(uuids: [String!]!): Boolean!
}

type AD_StatusLineConnection {
	results: [AD_StatusLine!]!
	pagingInfo: PagingInfo!
}

type AD_StatusLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# System Message
	AD_Message: AD_Message!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UUID: ID!
	AD_StatusLine_UU: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	SQLStatement: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_StatusLineInput {
	# System Message
	AD_Message: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UUID: ID
	AD_StatusLine_UU: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	SQLStatement: String
}
