# Generated Schema for AD_AuthorizationCredential - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_AuthorizationCredentialGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_AuthorizationCredentialConnection!
}

extend type Mutation {
	AD_AuthorizationCredentialSave(Entity: AD_AuthorizationCredentialInput!): AD_AuthorizationCredential!
	AD_AuthorizationCredentialSaveMany(Entities: [AD_AuthorizationCredentialInput!]!): [AD_AuthorizationCredential!]!
	AD_AuthorizationCredentialDelete(UUs: [String!]!): Boolean!
}

type AD_AuthorizationCredentialConnection {
	Results: [AD_AuthorizationCredential!]!
	PagingInfo: PagingInfo!
}

type AD_AuthorizationCredential {
	UU: ID!
	AD_AuthorizationProvider: AD_AuthorizationProvider!
	AD_AuthorizationScopeList: AD_Ref_List!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AuthorizationClientId: String!
	AuthorizationClientSecret: String!
	AuthorizationRedirectURL: String!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_AuthorizationCredentialInput {
	UU: ID
	AD_AuthorizationProvider: ForeignEntityInput
	AD_AuthorizationScopeList: AD_Ref_ListInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AuthorizationClientId: String
	AuthorizationClientSecret: String
	AuthorizationRedirectURL: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
