# Generated Schema for AD_WF_NextCondition - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_WF_NextConditionGet(page: Int, size: Int, sort: String, filter: String): AD_WF_NextConditionConnection!
}

extend type Mutation {
	AD_WF_NextConditionSave(entity: AD_WF_NextConditionInput!): AD_WF_NextCondition!
	AD_WF_NextConditionSaveMany(entities: [AD_WF_NextConditionInput!]!): [AD_WF_NextCondition!]!
	AD_WF_NextConditionDelete(uuids: [String!]!): Boolean!
}

type AD_WF_NextConditionConnection {
	results: [AD_WF_NextCondition!]!
	pagingInfo: PagingInfo!
}

type AD_WF_NextCondition {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Column in the table
	AD_Column: AD_Column!
	# Organizational entity within client
	AD_Org: AD_Org!
	UUID: ID!
	# Workflow Node Transition
	AD_WF_NodeNext: AD_WF_NodeNext!
	# Logical operation: AND or OR
	AndOr: AD_Ref_List!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Compare Operation
	Operation: AD_Ref_List!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
	# Value To
	Value2: String
}

input AD_WF_NextConditionInput {
	# Column in the table
	AD_Column: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	UUID: ID
	# Workflow Node Transition
	AD_WF_NodeNext: ForeignEntityInput
	# Logical operation: AND or OR
	AndOr: AD_Ref_ListInput
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Compare Operation
	Operation: AD_Ref_ListInput
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Search key for the record in the format required - must be unique
	Value: String
	# Value To
	Value2: String
}
