# Generated Schema for AD_WorkflowProcessor - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_WorkflowProcessor(UU: String!): AD_WorkflowProcessor
	AD_WorkflowProcessorGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_WorkflowProcessorConnection!
}

extend type Mutation {
	AD_WorkflowProcessorSave(Entity: AD_WorkflowProcessorInput!): AD_WorkflowProcessor!
	AD_WorkflowProcessorSaveMany(Entities: [AD_WorkflowProcessorInput!]!): [AD_WorkflowProcessor!]!
	AD_WorkflowProcessorDelete(UUs: [String!]!): Boolean!
}

type AD_WorkflowProcessorConnection {
	Results: [AD_WorkflowProcessor!]!
	PagingInfo: PagingInfo!
}

type AD_WorkflowProcessor {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AD_Schedule: AD_Schedule!
	UU: ID!
	# Send alert email when over priority
	AlertOverPriority: Int
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Date the process was last run.
	DateLastRun: DateTime
	# Date the process will run next
	DateNextRun: DateTime
	# Optional short description of the record
	Description: String
	# Send Alert when there is no activity after days (0= no alert)
	InactivityAlertDays: Int
	# The record is active in the system
	IsActive: Boolean!
	# Number of days to keep the log entries
	KeepLogDays: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Days between sending Reminder Emails for a due or inactive Document
	RemindDays: Int
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: AD_User!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_WorkflowProcessorInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AD_Schedule: ForeignEntityInput
	UU: ID
	# Send alert email when over priority
	AlertOverPriority: Int
	# Date the process was last run.
	DateLastRun: DateTime
	# Date the process will run next
	DateNextRun: DateTime
	# Optional short description of the record
	Description: String
	# Send Alert when there is no activity after days (0= no alert)
	InactivityAlertDays: Int
	# The record is active in the system
	IsActive: Boolean
	# Number of days to keep the log entries
	KeepLogDays: Int
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	# Days between sending Reminder Emails for a due or inactive Document
	RemindDays: Int
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: ForeignEntityInput
}
