# Generated Schema for AD_ImportTemplate - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_ImportTemplate(UU: String!): AD_ImportTemplate
	AD_ImportTemplateGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): AD_ImportTemplateConnection!
}

extend type Mutation {
	AD_ImportTemplateSave(Entity: AD_ImportTemplateInput!): AD_ImportTemplate!
	AD_ImportTemplateSaveMany(Entities: [AD_ImportTemplateInput!]!): [AD_ImportTemplate!]!
	AD_ImportTemplateDelete(UUs: [String!]!): Boolean!
}

type AD_ImportTemplateConnection {
	Results: [AD_ImportTemplate!]!
	PagingInfo: PagingInfo!
}

type AD_ImportTemplate {
	# Tenant for this installation.
	AD_Client: AD_Client!
	UU: ID!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Tab within a Window
	AD_Tab: AD_Tab!
	# Data entry or display window
	AD_Window: AD_Window!
	CharacterSet: String!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	CSVAliasHeader: String
	CSVHeader: String!
	# Optional short description of the record
	Description: String
	ImportTemplateType: AD_Ref_List!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	QuoteChar: String!
	SeparatorChar: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_ImportTemplateInput {
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Tab within a Window
	AD_Tab: ForeignEntityInput
	# Data entry or display window
	AD_Window: ForeignEntityInput
	CharacterSet: String
	CSVAliasHeader: String
	CSVHeader: String
	# Optional short description of the record
	Description: String
	ImportTemplateType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	QuoteChar: String
	SeparatorChar: String
}
