# Generated Schema for AD_Error - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	AD_ErrorGet(page: Int, size: Int, sort: String, filter: String): AD_ErrorConnection!
}

extend type Mutation {
	AD_ErrorSave(entity: AD_ErrorInput!): AD_Error!
	AD_ErrorSaveMany(entities: [AD_ErrorInput!]!): [AD_Error!]!
	AD_ErrorDelete(uuids: [String!]!): Boolean!
}

type AD_ErrorConnection {
	results: [AD_Error!]!
	pagingInfo: PagingInfo!
}

type AD_Error {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	UUID: ID!
	# Language for this entity
	AD_Language: AD_Language
	# Organizational entity within client
	AD_Org: AD_Org!
	# Validation Code
	Code: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_ErrorInput {
	UUID: ID
	# Language for this entity
	AD_Language: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Validation Code
	Code: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
