# Generated Schema for AD_PInstance_Log - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_PInstance_LogGet(page: Int, size: Int, sort: String, filter: String): AD_PInstance_LogConnection!
}

extend type Mutation {
	AD_PInstance_LogSave(entity: AD_PInstance_LogInput!): AD_PInstance_Log!
	AD_PInstance_LogSaveMany(entities: [AD_PInstance_LogInput!]!): [AD_PInstance_Log!]!
	AD_PInstance_LogDelete(uuids: [String!]!): Boolean!
}

type AD_PInstance_LogConnection {
	results: [AD_PInstance_Log!]!
	pagingInfo: PagingInfo!
}

type AD_PInstance_Log {
	# Instance of the process
	AD_PInstance: AD_PInstance!
	UUID: ID!
	# Database Table information
	AD_Table: AD_Table
	Log_ID: Int!
	# Process Parameter
	P_Date: Date
	P_Msg: String
	# Process Parameter
	P_Number: BigDecimal
	# Process Audit Log Type
	PInstanceLogType: AD_Ref_List
}

input AD_PInstance_LogInput {
	# Instance of the process
	AD_PInstance: ForeignEntityInput
	UUID: ID
	# Database Table information
	AD_Table: ForeignEntityInput
	Log_ID: Int
	# Process Parameter
	P_Date: Date
	P_Msg: String
	# Process Parameter
	P_Number: BigDecimal
	# Process Audit Log Type
	PInstanceLogType: AD_Ref_ListInput
}
