# Generated Schema for AD_Role_OrgAccess - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_Role_OrgAccessGet(page: Int, size: Int, sort: String, filter: String): AD_Role_OrgAccessConnection!
}

extend type Mutation {
	AD_Role_OrgAccessSave(entity: AD_Role_OrgAccessInput!): AD_Role_OrgAccess!
	AD_Role_OrgAccessSaveMany(entities: [AD_Role_OrgAccessInput!]!): [AD_Role_OrgAccess!]!
	AD_Role_OrgAccessDelete(uuids: [String!]!): Boolean!
}

type AD_Role_OrgAccessConnection {
	results: [AD_Role_OrgAccess!]!
	pagingInfo: PagingInfo!
}

type AD_Role_OrgAccess {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role!
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Field is read only
	IsReadOnly: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Role_OrgAccessInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	UUID: ID
	# The record is active in the system
	IsActive: Boolean
	# Field is read only
	IsReadOnly: Boolean
}
