# Generated Schema for AD_Table_Access - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	AD_Table_Access(UU: String!): AD_Table_Access
	AD_Table_AccessGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_Table_AccessConnection!
}

extend type Mutation {
	AD_Table_AccessSave(Entity: AD_Table_AccessInput!): AD_Table_Access!
	AD_Table_AccessSaveMany(Entities: [AD_Table_AccessInput!]!): [AD_Table_Access!]!
	AD_Table_AccessDelete(UUs: [String!]!): Boolean!
}

type AD_Table_AccessConnection {
	Results: [AD_Table_Access!]!
	PagingInfo: PagingInfo!
}

type AD_Table_Access {
	# The type of access for this rule
	AccessTypeRule: AD_Ref_List!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role!
	UU: ID!
	# Database Table information
	AD_Table: AD_Table!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Exclude access to the data - if not selected Include access to the data
	IsExclude: Boolean!
	# Field is read only
	IsReadOnly: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Table_AccessInput {
	# The type of access for this rule
	AccessTypeRule: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	UU: ID
	# Database Table information
	AD_Table: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Exclude access to the data - if not selected Include access to the data
	IsExclude: Boolean
	# Field is read only
	IsReadOnly: Boolean
}
