# Generated Schema for AD_AlertProcessor - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_AlertProcessor(UU: String!): AD_AlertProcessor
	AD_AlertProcessorGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_AlertProcessorConnection!
}

extend type Mutation {
	AD_AlertProcessorSave(Entity: AD_AlertProcessorInput!): AD_AlertProcessor!
	AD_AlertProcessorSaveMany(Entities: [AD_AlertProcessorInput!]!): [AD_AlertProcessor!]!
	AD_AlertProcessorDelete(UUs: [String!]!): Boolean!
}

type AD_AlertProcessorConnection {
	Results: [AD_AlertProcessor!]!
	PagingInfo: PagingInfo!
}

type AD_AlertProcessor {
	UU: ID!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AD_Schedule: AD_Schedule!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date the process was last run.
	DateLastRun: Date
	# Date the process will run next
	DateNextRun: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Number of days to keep the log entries
	KeepLogDays: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: AD_User!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_AlertProcessorInput {
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AD_Schedule: ForeignEntityInput
	# Date the process was last run.
	DateLastRun: Date
	# Date the process will run next
	DateNextRun: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Number of days to keep the log entries
	KeepLogDays: Int
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: ForeignEntityInput
}
