# Generated Schema for AD_WorkflowProcessorLog - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_WorkflowProcessorLog(UU: String!): AD_WorkflowProcessorLog
	AD_WorkflowProcessorLogGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_WorkflowProcessorLogConnection!
}

extend type Mutation {
	AD_WorkflowProcessorLogSave(Entity: AD_WorkflowProcessorLogInput!): AD_WorkflowProcessorLog!
	AD_WorkflowProcessorLogSaveMany(Entities: [AD_WorkflowProcessorLogInput!]!): [AD_WorkflowProcessorLog!]!
	AD_WorkflowProcessorLogDelete(UUs: [String!]!): Boolean!
}

type AD_WorkflowProcessorLogConnection {
	Results: [AD_WorkflowProcessorLog!]!
	PagingInfo: PagingInfo!
}

type AD_WorkflowProcessorLog {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Workflow Processor Server
	AD_WorkflowProcessor: AD_WorkflowProcessor!
	UU: ID!
	# Binary Data
	BinaryData: Binary
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# An Error occurred in the execution
	IsError: Boolean!
	# Reference for this record
	Reference: String
	# Textual summary of this request
	Summary: String
	# Text Message
	TextMsg: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_WorkflowProcessorLogInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Workflow Processor Server
	AD_WorkflowProcessor: ForeignEntityInput
	UU: ID
	# Binary Data
	BinaryData: Binary
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# An Error occurred in the execution
	IsError: Boolean
	# Reference for this record
	Reference: String
	# Textual summary of this request
	Summary: String
	# Text Message
	TextMsg: String
}
