# Generated Schema for AD_ChangeLog - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_ChangeLogGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_ChangeLogConnection!
}

extend type Mutation {
	AD_ChangeLogSave(Entity: AD_ChangeLogInput!): AD_ChangeLog!
	AD_ChangeLogSaveMany(Entities: [AD_ChangeLogInput!]!): [AD_ChangeLog!]!
	AD_ChangeLogDelete(UUs: [String!]!): Boolean!
}

type AD_ChangeLogConnection {
	Results: [AD_ChangeLog!]!
	PagingInfo: PagingInfo!
}

type AD_ChangeLog {
	# Log of data changes
	AD_ChangeLog: AD_ChangeLog!
	UU: ID!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Column in the table
	AD_Column: AD_Column!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User Session Online or Web
	AD_Session: AD_Session!
	# Database Table information
	AD_Table: AD_Table!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Type of Event in Change Log
	EventChangeLog: AD_Ref_List
	# The record is active in the system
	IsActive: Boolean!
	# The change is a customization of the data dictionary and can be applied after Migration
	IsCustomization: Boolean!
	# New field value
	NewValue: String
	# The old file data
	OldValue: String
	Redo: String
	# Name of the transaction
	TrxName: String
	Undo: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_ChangeLogInput {
	# Log of data changes
	AD_ChangeLog: ForeignEntityInput
	UU: ID
	# Column in the table
	AD_Column: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User Session Online or Web
	AD_Session: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Type of Event in Change Log
	EventChangeLog: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# The change is a customization of the data dictionary and can be applied after Migration
	IsCustomization: Boolean
	# New field value
	NewValue: String
	# The old file data
	OldValue: String
	Redo: String
	# Name of the transaction
	TrxName: String
	Undo: String
}
