# Generated Schema for AD_SearchDefinition - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_SearchDefinition(UU: String!): AD_SearchDefinition
	AD_SearchDefinitionGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_SearchDefinitionConnection!
}

extend type Mutation {
	AD_SearchDefinitionSave(Entity: AD_SearchDefinitionInput!): AD_SearchDefinition!
	AD_SearchDefinitionSaveMany(Entities: [AD_SearchDefinitionInput!]!): [AD_SearchDefinition!]!
	AD_SearchDefinitionDelete(UUs: [String!]!): Boolean!
}

type AD_SearchDefinitionConnection {
	Results: [AD_SearchDefinition!]!
	PagingInfo: PagingInfo!
}

type AD_SearchDefinition {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Column in the table
	AD_Column: AD_Column
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Database Table information
	AD_Table: AD_Table!
	# Data entry or display window
	AD_Window: AD_Window!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User
	# Type of data
	DataType: String!
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# Alphanumeric identifier of the entity
	Name: String
	# Purchase Order Window
	PO_Window: AD_Window
	# SQL
	Query: String
	# Which kind of search is used (Query or Table)
	SearchType: String!
	# The transaction code represents the search definition
	TransactionCode: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_SearchDefinitionInput {
	# Column in the table
	AD_Column: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Database Table information
	AD_Table: ForeignEntityInput
	# Data entry or display window
	AD_Window: ForeignEntityInput
	# Type of data
	DataType: String
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Purchase Order Window
	PO_Window: ForeignEntityInput
	# SQL
	Query: String
	# Which kind of search is used (Query or Table)
	SearchType: String
	# The transaction code represents the search definition
	TransactionCode: String
}
