# Generated Schema for AD_OrgType - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_OrgTypeGet(page: Int, size: Int, sort: String, filter: String): AD_OrgTypeConnection!
}

extend type Mutation {
	AD_OrgTypeSave(entity: AD_OrgTypeInput!): AD_OrgType!
	AD_OrgTypeDelete(uuids: [String!]!): Boolean!
}

type AD_OrgTypeConnection {
	results: [AD_OrgType!]!
	pagingInfo: PagingInfo!
}

type AD_OrgType {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	# Color used for printing and display
	AD_PrintColor: AD_PrintColor
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_OrgTypeInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	# Color used for printing and display
	AD_PrintColor: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
