# Generated Schema for AD_PrintFont - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_PrintFontGet(page: Int, size: Int, sort: String, filter: String): AD_PrintFontConnection!
}

extend type Mutation {
	AD_PrintFontSave(entity: AD_PrintFontInput!): AD_PrintFont!
	AD_PrintFontDelete(uuids: [String!]!): Boolean!
}

type AD_PrintFontConnection {
	results: [AD_PrintFont!]!
	pagingInfo: PagingInfo!
}

type AD_PrintFont {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	# Validation Code
	Code: String!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_PrintFontInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	# Validation Code
	Code: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
