# Generated Schema for AD_Schedule - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	AD_ScheduleGet(page: Int, size: Int, sort: String, filter: String): AD_ScheduleConnection!
}

extend type Mutation {
	AD_ScheduleSave(entity: AD_ScheduleInput!): AD_Schedule!
	AD_ScheduleDelete(uuids: [String!]!): Boolean!
}

type AD_ScheduleConnection {
	results: [AD_Schedule!]!
	pagingInfo: PagingInfo!
}

type AD_Schedule {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Cron pattern to define when the process should be invoked.
	CronPattern: String
	# Optional short description of the record
	Description: String
	# Frequency of events
	Frequency: Int
	# Frequency of event
	FrequencyType: AD_Ref_List
	# The record is active in the system
	IsActive: Boolean!
	# Do not include processing time for the DateNextRun calculation
	IsIgnoreProcessingTime: Boolean!
	# Schedule Just For System
	IsSystemSchedule: Boolean!
	# Day of the month 1 to 28/29/30/31
	MonthDay: Int
	# Alphanumeric identifier of the entity
	Name: String!
	RunOnlyOnIP: String
	# Type of schedule
	ScheduleType: AD_Ref_List
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Day of the Week
	WeekDay: AD_Ref_List
}

input AD_ScheduleInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	# Cron pattern to define when the process should be invoked.
	CronPattern: String
	# Optional short description of the record
	Description: String
	# Frequency of events
	Frequency: Int
	# Frequency of event
	FrequencyType: AD_Ref_ListInput
	# The record is active in the system
	IsActive: Boolean
	# Do not include processing time for the DateNextRun calculation
	IsIgnoreProcessingTime: Boolean
	# Schedule Just For System
	IsSystemSchedule: Boolean
	# Day of the month 1 to 28/29/30/31
	MonthDay: Int
	# Alphanumeric identifier of the entity
	Name: String
	RunOnlyOnIP: String
	# Type of schedule
	ScheduleType: AD_Ref_ListInput
	# Day of the Week
	WeekDay: AD_Ref_ListInput
}
