# Generated Schema for AD_AlertProcessorLog - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	AD_AlertProcessorLog(UU: String!): AD_AlertProcessorLog
	AD_AlertProcessorLogGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_AlertProcessorLogConnection!
}

extend type Mutation {
	AD_AlertProcessorLogSave(Entity: AD_AlertProcessorLogInput!): AD_AlertProcessorLog!
	AD_AlertProcessorLogSaveMany(Entities: [AD_AlertProcessorLogInput!]!): [AD_AlertProcessorLog!]!
	AD_AlertProcessorLogDelete(UUs: [String!]!): Boolean!
}

type AD_AlertProcessorLogConnection {
	Results: [AD_AlertProcessorLog!]!
	PagingInfo: PagingInfo!
}

type AD_AlertProcessorLog {
	# Alert Processor/Server Parameter
	AD_AlertProcessor: AD_AlertProcessor!
	UU: ID!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Binary Data
	BinaryData: Binary
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# An Error occurred in the execution
	IsError: Boolean!
	# Reference for this record
	Reference: String
	# Textual summary of this request
	Summary: String
	# Text Message
	TextMsg: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_AlertProcessorLogInput {
	# Alert Processor/Server Parameter
	AD_AlertProcessor: ForeignEntityInput
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Binary Data
	BinaryData: Binary
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# An Error occurred in the execution
	IsError: Boolean
	# Reference for this record
	Reference: String
	# Textual summary of this request
	Summary: String
	# Text Message
	TextMsg: String
}
