# Generated Schema for AD_TreeNodePR - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_TreeNodePR(UU: String!): AD_TreeNodePR
	AD_TreeNodePRGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_TreeNodePRConnection!
}

extend type Mutation {
	AD_TreeNodePRSave(Entity: AD_TreeNodePRInput!): AD_TreeNodePR!
	AD_TreeNodePRSaveMany(Entities: [AD_TreeNodePRInput!]!): [AD_TreeNodePR!]!
	AD_TreeNodePRDelete(UUs: [String!]!): Boolean!
}

type AD_TreeNodePRConnection {
	Results: [AD_TreeNodePR!]!
	PagingInfo: PagingInfo!
}

type AD_TreeNodePR {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodePRInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
