# Generated Schema for AD_ToolBarButtonRestrict - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_ToolBarButtonRestrict(UU: String!): AD_ToolBarButtonRestrict
	AD_ToolBarButtonRestrictGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_ToolBarButtonRestrictConnection!
}

extend type Mutation {
	AD_ToolBarButtonRestrictSave(Entity: AD_ToolBarButtonRestrictInput!): AD_ToolBarButtonRestrict!
	AD_ToolBarButtonRestrictSaveMany(Entities: [AD_ToolBarButtonRestrictInput!]!): [AD_ToolBarButtonRestrict!]!
	AD_ToolBarButtonRestrictDelete(UUs: [String!]!): Boolean!
}

type AD_ToolBarButtonRestrictConnection {
	Results: [AD_ToolBarButtonRestrict!]!
	PagingInfo: PagingInfo!
}

type AD_ToolBarButtonRestrict {
	# Indicates the Action to be performed
	Action: AD_Ref_List!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Process or Report
	AD_Process: AD_Process
	# Responsibility Role
	AD_Role: AD_Role
	# Tab within a Window
	AD_Tab: AD_Tab
	AD_ToolBarButton: AD_ToolBarButton
	UU: ID!
	# Data entry or display window
	AD_Window: AD_Window
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Exclude access to the data - if not selected Include access to the data
	IsExclude: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_ToolBarButtonRestrictInput {
	# Indicates the Action to be performed
	Action: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Process or Report
	AD_Process: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# Tab within a Window
	AD_Tab: ForeignEntityInput
	AD_ToolBarButton: ForeignEntityInput
	UU: ID
	# Data entry or display window
	AD_Window: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Exclude access to the data - if not selected Include access to the data
	IsExclude: Boolean
}
