# Generated Schema for AD_UserDef_Tab - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_UserDef_TabGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_UserDef_TabConnection!
}

extend type Mutation {
	AD_UserDef_TabSave(Entity: AD_UserDef_TabInput!): AD_UserDef_Tab!
	AD_UserDef_TabSaveMany(Entities: [AD_UserDef_TabInput!]!): [AD_UserDef_Tab!]!
	AD_UserDef_TabDelete(UUs: [String!]!): Boolean!
}

type AD_UserDef_TabConnection {
	Results: [AD_UserDef_Tab!]!
	PagingInfo: PagingInfo!
}

type AD_UserDef_Tab {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Process or Report
	AD_Process: AD_Process
	# Tab within a Window
	AD_Tab: AD_Tab!
	UU: ID!
	AD_UserDef_Win: AD_UserDef_Win!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	DeleteConfirmationLogic: String
	# Optional short description of the record
	Description: String
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	IsAllowAdvancedLookup: AD_Ref_List
	# Use Search instead of Pick list
	IsHighVolume: AD_Ref_List
	# When defined to true Lookup panel will display only selection columns. Default to false.
	IsLookupOnlySelection: AD_Ref_List
	# This applies to Multi-Row view only
	IsMultiRowOnly: Boolean!
	# Field is read only
	IsReadOnly: AD_Ref_List
	# Default for toggle between Single- and Multi-Row (Grid) Layout
	IsSingleRow: AD_Ref_List
	# Alphanumeric identifier of the entity
	Name: String
	# Fully qualified ORDER BY clause
	OrderByClause: String
	# Logic to determine if field is read only (applies only when field is read-write)
	ReadOnlyLogic: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Fully qualified SQL WHERE clause
	WhereClause: String
}

input AD_UserDef_TabInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Process or Report
	AD_Process: ForeignEntityInput
	# Tab within a Window
	AD_Tab: ForeignEntityInput
	UU: ID
	AD_UserDef_Win: ForeignEntityInput
	DeleteConfirmationLogic: String
	# Optional short description of the record
	Description: String
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	IsAllowAdvancedLookup: AD_Ref_ListInput
	# Use Search instead of Pick list
	IsHighVolume: AD_Ref_ListInput
	# When defined to true Lookup panel will display only selection columns. Default to false.
	IsLookupOnlySelection: AD_Ref_ListInput
	# This applies to Multi-Row view only
	IsMultiRowOnly: Boolean
	# Field is read only
	IsReadOnly: AD_Ref_ListInput
	# Default for toggle between Single- and Multi-Row (Grid) Layout
	IsSingleRow: AD_Ref_ListInput
	# Alphanumeric identifier of the entity
	Name: String
	# Fully qualified ORDER BY clause
	OrderByClause: String
	# Logic to determine if field is read only (applies only when field is read-write)
	ReadOnlyLogic: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Fully qualified SQL WHERE clause
	WhereClause: String
}
