# Generated Schema for AD_AllClients_V - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	AD_AllClients_VGet(page: Int, size: Int, sort: String, filter: String): AD_AllClients_VConnection!
}

extend type Mutation {
	AD_AllClients_VSave(entity: AD_AllClients_VInput!): AD_AllClients_V!
	AD_AllClients_VSaveMany(entities: [AD_AllClients_VInput!]!): [AD_AllClients_V!]!
	AD_AllClients_VDelete(uuids: [String!]!): Boolean!
}

type AD_AllClients_VConnection {
	results: [AD_AllClients_V!]!
	pagingInfo: PagingInfo!
}

type AD_AllClients_V {
	UUID: ID!
	# Client/Tenant for this installation.
	AD_Client: AD_Client
	# Language for this entity
	AD_Language: AD_Language
	# Organizational entity within client
	AD_Org: AD_Org
	# Date this record was created
	Created: Date
	# User who created this records
	CreatedBy: AD_User
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String
	# Date this record was updated
	Updated: Date
	# User who updated this records
	UpdatedBy: AD_User
	# Search key for the record in the format required - must be unique
	Value: String
}

input AD_AllClients_VInput {
	UUID: ID
	# Language for this entity
	AD_Language: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
