# Generated Schema for AD_PrintLabel - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_PrintLabelGet(page: Int, size: Int, sort: String, filter: String): AD_PrintLabelConnection!
}

extend type Mutation {
	AD_PrintLabelSave(entity: AD_PrintLabelInput!): AD_PrintLabel!
	AD_PrintLabelDelete(uuids: [String!]!): Boolean!
}

type AD_PrintLabelConnection {
	results: [AD_PrintLabel!]!
	pagingInfo: PagingInfo!
}

type AD_PrintLabel {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Label Printer Definition
	AD_LabelPrinter: AD_LabelPrinter!
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	# Database Table information
	AD_Table: AD_Table!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Landscape orientation
	IsLandscape: Boolean!
	# Height of the label
	LabelHeight: Int!
	# Width of the Label
	LabelWidth: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	# Name of the Printer
	PrinterName: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_PrintLabelInput {
	# Label Printer Definition
	AD_LabelPrinter: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	# Database Table information
	AD_Table: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Landscape orientation
	IsLandscape: Boolean
	# Height of the label
	LabelHeight: Int
	# Width of the Label
	LabelWidth: Int
	# Alphanumeric identifier of the entity
	Name: String
	# Name of the Printer
	PrinterName: String
}
