# Generated Schema for AD_TreeNodeU2 - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	AD_TreeNodeU2(UU: String!): AD_TreeNodeU2
	AD_TreeNodeU2Get(Page: Int, Size: Int, Sort: String, Filter: String): AD_TreeNodeU2Connection!
}

extend type Mutation {
	AD_TreeNodeU2Save(Entity: AD_TreeNodeU2Input!): AD_TreeNodeU2!
	AD_TreeNodeU2SaveMany(Entities: [AD_TreeNodeU2Input!]!): [AD_TreeNodeU2!]!
	AD_TreeNodeU2Delete(UUs: [String!]!): Boolean!
}

type AD_TreeNodeU2Connection {
	Results: [AD_TreeNodeU2!]!
	PagingInfo: PagingInfo!
}

type AD_TreeNodeU2 {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodeU2Input {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
