# Generated Schema for AD_Scheduler - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_Scheduler(UU: String!): AD_Scheduler
	AD_SchedulerGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_SchedulerConnection!
}

extend type Mutation {
	AD_SchedulerSave(Entity: AD_SchedulerInput!): AD_Scheduler!
	AD_SchedulerSaveMany(Entities: [AD_SchedulerInput!]!): [AD_Scheduler!]!
	AD_SchedulerDelete(UUs: [String!]!): Boolean!
}

type AD_SchedulerConnection {
	Results: [AD_Scheduler!]!
	PagingInfo: PagingInfo!
}

type AD_Scheduler {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Data Print Format
	AD_PrintFormat: AD_PrintFormat
	# Process or Report
	AD_Process: AD_Process!
	AD_Schedule: AD_Schedule!
	UU: ID!
	# Database Table information
	AD_Table: AD_Table
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Date the process was last run.
	DateLastRun: DateTime
	# Date the process will run next
	DateNextRun: DateTime
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Number of days to keep the log entries
	KeepLogDays: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	ReportOutputType: AD_Ref_List
	# Text templates for mailings
	R_MailText: R_MailText
	# State of this scheduler record (not scheduled, started or stopped)
	SchedulerState: Object
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: AD_User!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_SchedulerInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Data Print Format
	AD_PrintFormat: ForeignEntityInput
	# Process or Report
	AD_Process: ForeignEntityInput
	AD_Schedule: ForeignEntityInput
	UU: ID
	# Database Table information
	AD_Table: ForeignEntityInput
	# Date the process was last run.
	DateLastRun: DateTime
	# Date the process will run next
	DateNextRun: DateTime
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Number of days to keep the log entries
	KeepLogDays: Int
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	ReportOutputType: ForeignEntityInput
	# Text templates for mailings
	R_MailText: ForeignEntityInput
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: ForeignEntityInput
}
