# Generated Schema for AD_UserDef_Info_Related - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_UserDef_Info_RelatedGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_UserDef_Info_RelatedConnection!
}

extend type Mutation {
	AD_UserDef_Info_RelatedSave(Entity: AD_UserDef_Info_RelatedInput!): AD_UserDef_Info_Related!
	AD_UserDef_Info_RelatedSaveMany(Entities: [AD_UserDef_Info_RelatedInput!]!): [AD_UserDef_Info_Related!]!
	AD_UserDef_Info_RelatedDelete(UUs: [String!]!): Boolean!
}

type AD_UserDef_Info_RelatedConnection {
	Results: [AD_UserDef_Info_Related!]!
	PagingInfo: PagingInfo!
}

type AD_UserDef_Info_Related {
	# Tenant for this installation.
	AD_Client: AD_Client!
	AD_InfoRelated: AD_InfoRelated!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AD_UserDef_Info: AD_UserDef_Info!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_UserDef_Info_RelatedInput {
	AD_InfoRelated: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AD_UserDef_Info: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
