# Generated Schema for AD_TreeNodeCMS - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_TreeNodeCMS(UU: String!): AD_TreeNodeCMS
	AD_TreeNodeCMSGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_TreeNodeCMSConnection!
}

extend type Mutation {
	AD_TreeNodeCMSSave(Entity: AD_TreeNodeCMSInput!): AD_TreeNodeCMS!
	AD_TreeNodeCMSSaveMany(Entities: [AD_TreeNodeCMSInput!]!): [AD_TreeNodeCMS!]!
	AD_TreeNodeCMSDelete(UUs: [String!]!): Boolean!
}

type AD_TreeNodeCMSConnection {
	Results: [AD_TreeNodeCMS!]!
	PagingInfo: PagingInfo!
}

type AD_TreeNodeCMS {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodeCMSInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
