# Generated Schema for AD_ViewColumn - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_ViewColumnGet(page: Int, size: Int, sort: String, filter: String): AD_ViewColumnConnection!
}

extend type Mutation {
	AD_ViewColumnSave(entity: AD_ViewColumnInput!): AD_ViewColumn!
	AD_ViewColumnDelete(uuids: [String!]!): Boolean!
}

type AD_ViewColumnConnection {
	results: [AD_ViewColumn!]!
	pagingInfo: PagingInfo!
}

type AD_ViewColumn {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	AD_ViewComponent: AD_ViewComponent!
	# Name of the column in the database
	ColumnName: String!
	# Virtual Column (r/o)
	ColumnSQL: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	DBDataType: AD_Ref_List
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_ViewColumnInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	AD_ViewComponent: ForeignEntityInput
	# Name of the column in the database
	ColumnName: String
	# Virtual Column (r/o)
	ColumnSQL: String
	DBDataType: AD_Ref_ListInput
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
