# Generated Schema for AD_ModelValidator - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_ModelValidator(UU: String!): AD_ModelValidator
	AD_ModelValidatorGet(Page: Int, Size: Int, Sort: String, Filter: String): AD_ModelValidatorConnection!
}

extend type Mutation {
	AD_ModelValidatorSave(Entity: AD_ModelValidatorInput!): AD_ModelValidator!
	AD_ModelValidatorSaveMany(Entities: [AD_ModelValidatorInput!]!): [AD_ModelValidator!]!
	AD_ModelValidatorDelete(UUs: [String!]!): Boolean!
}

type AD_ModelValidatorConnection {
	Results: [AD_ModelValidator!]!
	PagingInfo: PagingInfo!
}

type AD_ModelValidator {
	# Tenant for this installation.
	AD_Client: AD_Client!
	UU: ID!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	ModelValidationClass: String!
	# Alphanumeric identifier of the entity
	Name: String!
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_ModelValidatorInput {
	UU: ID
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	ModelValidationClass: String
	# Alphanumeric identifier of the entity
	Name: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
