# Generated Schema for AD_TreeNodeU1 - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	AD_TreeNodeU1(UU: String!): AD_TreeNodeU1
	AD_TreeNodeU1Get(Page: Int, Size: Int, Sort: String, Filter: String): AD_TreeNodeU1Connection!
}

extend type Mutation {
	AD_TreeNodeU1Save(Entity: AD_TreeNodeU1Input!): AD_TreeNodeU1!
	AD_TreeNodeU1SaveMany(Entities: [AD_TreeNodeU1Input!]!): [AD_TreeNodeU1!]!
	AD_TreeNodeU1Delete(UUs: [String!]!): Boolean!
}

type AD_TreeNodeU1Connection {
	Results: [AD_TreeNodeU1!]!
	PagingInfo: PagingInfo!
}

type AD_TreeNodeU1 {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodeU1Input {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
