# Generated Schema for AD_TreeNodeMM - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_TreeNodeMMGet(page: Int, size: Int, sort: String, filter: String): AD_TreeNodeMMConnection!
}

extend type Mutation {
	AD_TreeNodeMMSave(entity: AD_TreeNodeMMInput!): AD_TreeNodeMM!
	AD_TreeNodeMMSaveMany(entities: [AD_TreeNodeMMInput!]!): [AD_TreeNodeMM!]!
	AD_TreeNodeMMDelete(uuids: [String!]!): Boolean!
}

type AD_TreeNodeMMConnection {
	results: [AD_TreeNodeMM!]!
	pagingInfo: PagingInfo!
}

type AD_TreeNodeMM {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_TreeNodeMMInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UUID: ID
	# The record is active in the system
	IsActive: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
