# Generated Schema for AD_Package_Exp - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	AD_Package_ExpGet(page: Int, size: Int, sort: String, filter: String): AD_Package_ExpConnection!
}

extend type Mutation {
	AD_Package_ExpSave(entity: AD_Package_ExpInput!): AD_Package_Exp!
	AD_Package_ExpSaveMany(entities: [AD_Package_ExpInput!]!): [AD_Package_Exp!]!
	AD_Package_ExpDelete(uuids: [String!]!): Boolean!
}

type AD_Package_ExpConnection {
	results: [AD_Package_Exp!]!
	pagingInfo: PagingInfo!
}

type AD_Package_Exp {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	UUID: ID!
	AD_Package_Type: AD_Ref_List
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Starting date for a range
	DateFrom: Date
	# Optional short description of the record
	Description: String
	# Electronic Mail Address
	EMail: String
	File_Directory: String
	Instructions: String
	# The record is active in the system
	IsActive: Boolean!
	IsExportDictionaryEntity: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	PK_Version: String!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Internal Release Number
	ReleaseNo: AD_Ref_List
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	UserName: String
	# Version of the table definition
	Version: String
}

input AD_Package_ExpInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	UUID: ID
	AD_Package_Type: AD_Ref_ListInput
	# Starting date for a range
	DateFrom: Date
	# Optional short description of the record
	Description: String
	# Electronic Mail Address
	EMail: String
	File_Directory: String
	Instructions: String
	# The record is active in the system
	IsActive: Boolean
	IsExportDictionaryEntity: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	PK_Version: String
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Internal Release Number
	ReleaseNo: AD_Ref_ListInput
	UserName: String
	# Version of the table definition
	Version: String
}
