# Generated Schema for AD_Record_Access - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	AD_Record_Access(UU: String!): AD_Record_Access
	AD_Record_AccessGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): AD_Record_AccessConnection!
}

extend type Mutation {
	AD_Record_AccessSave(Entity: AD_Record_AccessInput!): AD_Record_Access!
	AD_Record_AccessSaveMany(Entities: [AD_Record_AccessInput!]!): [AD_Record_Access!]!
	AD_Record_AccessDelete(UUs: [String!]!): Boolean!
}

type AD_Record_AccessConnection {
	Results: [AD_Record_Access!]!
	PagingInfo: PagingInfo!
}

type AD_Record_Access {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Responsibility Role
	AD_Role: AD_Role!
	# Database Table information
	AD_Table: AD_Table!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Also check access in dependent entities
	IsDependentEntities: Boolean!
	# Exclude access to the data - if not selected Include access to the data
	IsExclude: Boolean!
	# Field is read only
	IsReadOnly: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input AD_Record_AccessInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Also check access in dependent entities
	IsDependentEntities: Boolean
	# Exclude access to the data - if not selected Include access to the data
	IsExclude: Boolean
	# Field is read only
	IsReadOnly: Boolean
}
