# Generated Schema for ASP_Process - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	ASP_Process(UU: String!): ASP_Process
	ASP_ProcessGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): ASP_ProcessConnection!
}

extend type Mutation {
	ASP_ProcessSave(Entity: ASP_ProcessInput!): ASP_Process!
	ASP_ProcessSaveMany(Entities: [ASP_ProcessInput!]!): [ASP_Process!]!
	ASP_ProcessDelete(UUs: [String!]!): Boolean!
}

type ASP_ProcessConnection {
	Results: [ASP_Process!]!
	PagingInfo: PagingInfo!
}

type ASP_Process {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Process or Report
	AD_Process: AD_Process!
	ASP_Level: ASP_Level!
	UU: ID!
	ASP_Status: AD_Ref_List!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input ASP_ProcessInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Process or Report
	AD_Process: ForeignEntityInput
	ASP_Level: ForeignEntityInput
	UU: ID
	ASP_Status: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
}
