# Generated Schema for ASP_Field - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	ASP_FieldGet(page: Int, size: Int, sort: String, filter: String): ASP_FieldConnection!
}

extend type Mutation {
	ASP_FieldSave(entity: ASP_FieldInput!): ASP_Field!
	ASP_FieldDelete(uuids: [String!]!): Boolean!
}

type ASP_FieldConnection {
	results: [ASP_Field!]!
	pagingInfo: PagingInfo!
}

type ASP_Field {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Field on a database table
	AD_Field: AD_Field
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	ASP_Status: AD_Ref_List!
	ASP_Tab: ASP_Tab
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input ASP_FieldInput {
	# Field on a database table
	AD_Field: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	ASP_Status: AD_Ref_ListInput
	ASP_Tab: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
}
