# Generated Schema for ASP_ClientLevel - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	ASP_ClientLevelGet(Page: Int, Size: Int, Sort: String, Filter: String): ASP_ClientLevelConnection!
}

extend type Mutation {
	ASP_ClientLevelSave(Entity: ASP_ClientLevelInput!): ASP_ClientLevel!
	ASP_ClientLevelSaveMany(Entities: [ASP_ClientLevelInput!]!): [ASP_ClientLevel!]!
	ASP_ClientLevelDelete(UUs: [String!]!): Boolean!
}

type ASP_ClientLevelConnection {
	Results: [ASP_ClientLevel!]!
	PagingInfo: PagingInfo!
}

type ASP_ClientLevel {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	ASP_Level: ASP_Level!
	ASP_Module: ASP_Module!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input ASP_ClientLevelInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	ASP_Level: ForeignEntityInput
	ASP_Module: ForeignEntityInput
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
}
