# Generated Schema for ASP_Form - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	ASP_FormGet(page: Int, size: Int, sort: String, filter: String): ASP_FormConnection!
}

extend type Mutation {
	ASP_FormSave(entity: ASP_FormInput!): ASP_Form!
	ASP_FormDelete(uuids: [String!]!): Boolean!
}

type ASP_FormConnection {
	results: [ASP_Form!]!
	pagingInfo: PagingInfo!
}

type ASP_Form {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Special Form
	AD_Form: AD_Form!
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	ASP_Level: ASP_Level!
	ASP_Status: AD_Ref_List!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input ASP_FormInput {
	# Special Form
	AD_Form: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	ASP_Level: ForeignEntityInput
	ASP_Status: AD_Ref_ListInput
	# The record is active in the system
	IsActive: Boolean
}
