# Generated Schema for ASP_Task - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	ASP_TaskGet(page: Int, size: Int, sort: String, filter: String): ASP_TaskConnection!
}

extend type Mutation {
	ASP_TaskSave(entity: ASP_TaskInput!): ASP_Task!
	ASP_TaskDelete(uuids: [String!]!): Boolean!
}

type ASP_TaskConnection {
	results: [ASP_Task!]!
	pagingInfo: PagingInfo!
}

type ASP_Task {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Operation System Task
	AD_Task: AD_Task!
	ASP_Level: ASP_Level!
	ASP_Status: AD_Ref_List!
	ID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input ASP_TaskInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Operation System Task
	AD_Task: ForeignEntityInput
	ASP_Level: ForeignEntityInput
	ASP_Status: AD_Ref_ListInput
	ID: ID
	# The record is active in the system
	IsActive: Boolean
}
