# Generated Schema for ASP_Level - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	ASP_LevelGet(page: Int, size: Int, sort: String, filter: String): ASP_LevelConnection!
}

extend type Mutation {
	ASP_LevelSave(entity: ASP_LevelInput!): ASP_Level!
	ASP_LevelSaveMany(entities: [ASP_LevelInput!]!): [ASP_Level!]!
	ASP_LevelDelete(uuids: [String!]!): Boolean!
}

type ASP_LevelConnection {
	results: [ASP_Level!]!
	pagingInfo: PagingInfo!
}

type ASP_Level {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	UUID: ID!
	ASP_Module: ASP_Module!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input ASP_LevelInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	UUID: ID
	ASP_Module: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	# Search key for the record in the format required - must be unique
	Value: String
}
