# Generated Schema for B_Bid - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	B_Bid(UU: String!): B_Bid
	B_BidGet(Page: Int, Size: Int, Sort: String, Filter: String): B_BidConnection!
}

extend type Mutation {
	B_BidSave(Entity: B_BidInput!): B_Bid!
	B_BidSaveMany(Entities: [B_BidInput!]!): [B_Bid!]!
	B_BidDelete(UUs: [String!]!): Boolean!
}

type B_BidConnection {
	Results: [B_Bid!]!
	PagingInfo: PagingInfo!
}

type B_Bid {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	UU: ID!
	# Buyer Funds for Bids on Topics
	B_BuyerFunds: B_BuyerFunds!
	# Auction Topic
	B_Topic: B_Topic!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	IsWillingToCommit: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Private Note - not visible to the other parties
	PrivateNote: String
	# Text Message
	TextMsg: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input B_BidInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	UU: ID
	# Buyer Funds for Bids on Topics
	B_BuyerFunds: ForeignEntityInput
	# Auction Topic
	B_Topic: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	IsWillingToCommit: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Private Note - not visible to the other parties
	PrivateNote: String
	# Text Message
	TextMsg: String
}
