# Generated Schema for B_TopicCategory - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	B_TopicCategoryGet(page: Int, size: Int, sort: String, filter: String): B_TopicCategoryConnection!
}

extend type Mutation {
	B_TopicCategorySave(entity: B_TopicCategoryInput!): B_TopicCategory!
	B_TopicCategorySaveMany(entities: [B_TopicCategoryInput!]!): [B_TopicCategory!]!
	B_TopicCategoryDelete(uuids: [String!]!): Boolean!
}

type B_TopicCategoryConnection {
	results: [B_TopicCategory!]!
	pagingInfo: PagingInfo!
}

type B_TopicCategory {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UUID: ID!
	B_TopicCategory_UU: String
	# Auction Topic Type
	B_TopicType: B_TopicType!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input B_TopicCategoryInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UUID: ID
	B_TopicCategory_UU: String
	# Auction Topic Type
	B_TopicType: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
