# Generated Schema for B_TopicCategory - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	B_TopicCategory(UU: String!): B_TopicCategory
	B_TopicCategoryGet(Page: Int, Size: Int, Sort: String, Filter: String): B_TopicCategoryConnection!
}

extend type Mutation {
	B_TopicCategorySave(Entity: B_TopicCategoryInput!): B_TopicCategory!
	B_TopicCategorySaveMany(Entities: [B_TopicCategoryInput!]!): [B_TopicCategory!]!
	B_TopicCategoryDelete(UUs: [String!]!): Boolean!
}

type B_TopicCategoryConnection {
	Results: [B_TopicCategory!]!
	PagingInfo: PagingInfo!
}

type B_TopicCategory {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Auction Topic Type
	B_TopicType: B_TopicType!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input B_TopicCategoryInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Auction Topic Type
	B_TopicType: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
