# Generated Schema for B_BidComment - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	B_BidComment(UU: String!): B_BidComment
	B_BidCommentGet(Page: Int, Size: Int, Sort: String, Filter: String): B_BidCommentConnection!
}

extend type Mutation {
	B_BidCommentSave(Entity: B_BidCommentInput!): B_BidComment!
	B_BidCommentSaveMany(Entities: [B_BidCommentInput!]!): [B_BidComment!]!
	B_BidCommentDelete(UUs: [String!]!): Boolean!
}

type B_BidCommentConnection {
	Results: [B_BidComment!]!
	PagingInfo: PagingInfo!
}

type B_BidComment {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	UU: ID!
	# Auction Topic
	B_Topic: B_Topic!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Text Message
	TextMsg: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input B_BidCommentInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	UU: ID
	# Auction Topic
	B_Topic: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Text Message
	TextMsg: String
}
