# Generated Schema for BH_Encounter_Diagnostic - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	BH_Encounter_Diagnostic(UU: String!): BH_Encounter_Diagnostic
	BH_Encounter_DiagnosticGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): BH_Encounter_DiagnosticConnection!
}

extend type Mutation {
	BH_Encounter_DiagnosticSave(Entity: BH_Encounter_DiagnosticInput!): BH_Encounter_Diagnostic!
	BH_Encounter_DiagnosticSaveMany(Entities: [BH_Encounter_DiagnosticInput!]!): [BH_Encounter_Diagnostic!]!
	BH_Encounter_DiagnosticDelete(UUs: [String!]!): Boolean!
}

type BH_Encounter_DiagnosticConnection {
	Results: [BH_Encounter_Diagnostic!]!
	PagingInfo: PagingInfo!
}

type BH_Encounter_Diagnostic {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	BH_Concept: BH_Concept
	# Notes about the results
	BH_Diagnostic_Note: String
	BH_Diagnostic_Status: AD_Ref_List
	UU: ID!
	BH_Encounter: BH_Encounter!
	# BH_Value
	BH_Value: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	Group1: String
	# The record is active in the system
	IsActive: Boolean!
	# Line No
	LineNo: Int
	Selected_Panel: BH_Concept
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_Encounter_DiagnosticInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	BH_Concept: ForeignEntityInput
	# Notes about the results
	BH_Diagnostic_Note: String
	BH_Diagnostic_Status: ForeignEntityInput
	UU: ID
	BH_Encounter: ForeignEntityInput
	# BH_Value
	BH_Value: String
	Group1: String
	# The record is active in the system
	IsActive: Boolean
	# Line No
	LineNo: Int
	Selected_Panel: ForeignEntityInput
}
