# Generated Schema for BH_Payer_Info_Fld_Sug - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	BH_Payer_Info_Fld_Sug(UU: String!): BH_Payer_Info_Fld_Sug
	BH_Payer_Info_Fld_SugGet(Page: Int, Size: Int, Sort: String, Filter: String): BH_Payer_Info_Fld_SugConnection!
}

extend type Mutation {
	BH_Payer_Info_Fld_SugSave(Entity: BH_Payer_Info_Fld_SugInput!): BH_Payer_Info_Fld_Sug!
	BH_Payer_Info_Fld_SugSaveMany(Entities: [BH_Payer_Info_Fld_SugInput!]!): [BH_Payer_Info_Fld_Sug!]!
	BH_Payer_Info_Fld_SugDelete(UUs: [String!]!): Boolean!
}

type BH_Payer_Info_Fld_SugConnection {
	Results: [BH_Payer_Info_Fld_Sug!]!
	PagingInfo: PagingInfo!
}

type BH_Payer_Info_Fld_Sug {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	BH_FillFromPatient: Boolean!
	UU: ID!
	BH_PayerInfoFieldDataType: AD_Ref_List!
	# Meant to be a sub-type of the charge type
	BH_SubType: AD_Ref_List!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Unique line for this document
	Line: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_Payer_Info_Fld_SugInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	BH_FillFromPatient: Boolean
	UU: ID
	BH_PayerInfoFieldDataType: ForeignEntityInput
	# Meant to be a sub-type of the charge type
	BH_SubType: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Unique line for this document
	Line: Int
	# Alphanumeric identifier of the entity
	Name: String
}
