# Generated Schema for BH_Payer_Info_Fld_Val_Sug - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	BH_Payer_Info_Fld_Val_SugGet(page: Int, size: Int, sort: String, filter: String): BH_Payer_Info_Fld_Val_SugConnection!
}

extend type Mutation {
	BH_Payer_Info_Fld_Val_SugSave(entity: BH_Payer_Info_Fld_Val_SugInput!): BH_Payer_Info_Fld_Val_Sug!
	BH_Payer_Info_Fld_Val_SugDelete(uuids: [String!]!): Boolean!
}

type BH_Payer_Info_Fld_Val_SugConnection {
	results: [BH_Payer_Info_Fld_Val_Sug!]!
	pagingInfo: PagingInfo!
}

type BH_Payer_Info_Fld_Val_Sug {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	BH_Payer_Info_Fld_Sug: BH_Payer_Info_Fld_Sug!
	ID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Unique line for this document
	Line: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_Payer_Info_Fld_Val_SugInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	BH_Payer_Info_Fld_Sug: ForeignEntityInput
	ID: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Unique line for this document
	Line: Int
	# Alphanumeric identifier of the entity
	Name: String
}
