# Generated Schema for BH_SickOff_Print_Log - DO NOT CHANGE
#		@author Banda Health (generated)
#		@version Release 12 - $Id$
extend type Query {
	BH_SickOff_Print_Log(UU: String!): BH_SickOff_Print_Log
	BH_SickOff_Print_LogGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): BH_SickOff_Print_LogConnection!
}

extend type Mutation {
	BH_SickOff_Print_LogSave(Entity: BH_SickOff_Print_LogInput!): BH_SickOff_Print_Log!
	BH_SickOff_Print_LogSaveMany(Entities: [BH_SickOff_Print_LogInput!]!): [BH_SickOff_Print_Log!]!
	BH_SickOff_Print_LogDelete(UUs: [String!]!): Boolean!
}

type BH_SickOff_Print_LogConnection {
	Results: [BH_SickOff_Print_Log!]!
	PagingInfo: PagingInfo!
}

type BH_SickOff_Print_Log {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	BH_SickOff: BH_SickOff!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date and time this record was printed
	Printed: DateTime!
	# User who printed this record
	PrintedBy: AD_User!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_SickOff_Print_LogInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	BH_SickOff: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Date and time this record was printed
	Printed: DateTime
	# User who printed this record
	PrintedBy: ForeignEntityInput
}
