# Generated Schema for BH_Default_DocAction_Access - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	BH_Default_DocAction_AccessGet(page: Int, size: Int, sort: String, filter: String): BH_Default_DocAction_AccessConnection!
}

extend type Mutation {
	BH_Default_DocAction_AccessSave(entity: BH_Default_DocAction_AccessInput!): BH_Default_DocAction_Access!
	BH_Default_DocAction_AccessSaveMany(entities: [BH_Default_DocAction_AccessInput!]!): [BH_Default_DocAction_Access!]!
	BH_Default_DocAction_AccessDelete(uuids: [String!]!): Boolean!
}

type BH_Default_DocAction_AccessConnection {
	results: [BH_Default_DocAction_Access!]!
	pagingInfo: PagingInfo!
}

type BH_Default_DocAction_Access {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Reference List based on Table
	AD_Ref_List: AD_Ref_List!
	UUID: ID!
	BH_Default_DocAction_Access_UU: String
	# Document type or rules
	C_DocType: C_DocType!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The User Type when a new client is created
	DB_UserType: AD_Ref_List!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_Default_DocAction_AccessInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Reference List based on Table
	AD_Ref_List: ForeignEntityInput
	UUID: ID
	BH_Default_DocAction_Access_UU: String
	# Document type or rules
	C_DocType: ForeignEntityInput
	# The User Type when a new client is created
	DB_UserType: AD_Ref_ListInput
	# The record is active in the system
	IsActive: Boolean
}
