# Generated Schema for BH_Encounter - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	BH_Encounter(UU: String!): BH_Encounter
	BH_EncounterGet(Page: Int, Size: Int, Sort: String, Filter: String): BH_EncounterConnection!
}

extend type Mutation {
	BH_EncounterSave(Entity: BH_EncounterInput!): BH_Encounter!
	BH_EncounterSaveMany(Entities: [BH_EncounterInput!]!): [BH_Encounter!]!
	BH_EncounterDelete(UUs: [String!]!): Boolean!
}

type BH_EncounterConnection {
	Results: [BH_Encounter!]!
	PagingInfo: PagingInfo!
}

type BH_Encounter {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	BH_Encounter_Type: AD_Ref_List!
	UU: ID!
	BH_Visit: BH_Visit!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_EncounterInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	BH_Encounter_Type: ForeignEntityInput
	UU: ID
	BH_Visit: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
}
