# Generated Schema for BH_Encounter_Diagnosis - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	BH_Encounter_Diagnosis(UU: String!): BH_Encounter_Diagnosis
	BH_Encounter_DiagnosisGet(Page: Int, Size: Int, Sort: String, Filter: String): BH_Encounter_DiagnosisConnection!
}

extend type Mutation {
	BH_Encounter_DiagnosisSave(Entity: BH_Encounter_DiagnosisInput!): BH_Encounter_Diagnosis!
	BH_Encounter_DiagnosisSaveMany(Entities: [BH_Encounter_DiagnosisInput!]!): [BH_Encounter_Diagnosis!]!
	BH_Encounter_DiagnosisDelete(UUs: [String!]!): Boolean!
}

type BH_Encounter_DiagnosisConnection {
	Results: [BH_Encounter_Diagnosis!]!
	PagingInfo: PagingInfo!
}

type BH_Encounter_Diagnosis {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	BH_Concept: BH_Concept
	UU: ID!
	BH_Encounter: BH_Encounter!
	# uncoded diagnosis
	BH_Uncoded_Diagnosis: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Line No
	LineNo: Int
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_Encounter_DiagnosisInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	BH_Concept: ForeignEntityInput
	UU: ID
	BH_Encounter: ForeignEntityInput
	# uncoded diagnosis
	BH_Uncoded_Diagnosis: String
	# The record is active in the system
	IsActive: Boolean
	# Line No
	LineNo: Int
}
