# Generated Schema for BH_Encounter_Type_Window - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	BH_Encounter_Type_Window(UU: String!): BH_Encounter_Type_Window
	BH_Encounter_Type_WindowGet(Page: Int, Size: Int, Sort: String, Filter: String): BH_Encounter_Type_WindowConnection!
}

extend type Mutation {
	BH_Encounter_Type_WindowSave(Entity: BH_Encounter_Type_WindowInput!): BH_Encounter_Type_Window!
	BH_Encounter_Type_WindowSaveMany(Entities: [BH_Encounter_Type_WindowInput!]!): [BH_Encounter_Type_Window!]!
	BH_Encounter_Type_WindowDelete(UUs: [String!]!): Boolean!
}

type BH_Encounter_Type_WindowConnection {
	Results: [BH_Encounter_Type_Window!]!
	PagingInfo: PagingInfo!
}

type BH_Encounter_Type_Window {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Data entry or display window
	AD_Window: AD_Window!
	BH_Encounter_Type: AD_Ref_List!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_Encounter_Type_WindowInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Data entry or display window
	AD_Window: ForeignEntityInput
	BH_Encounter_Type: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
}
