# Generated Schema for BH_Product_CategoryDefault - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	BH_Product_CategoryDefault(UU: String!): BH_Product_CategoryDefault
	BH_Product_CategoryDefaultGet(Page: Int, Size: Int, Sort: String, Filter: String): BH_Product_CategoryDefaultConnection!
}

extend type Mutation {
	BH_Product_CategoryDefaultSave(Entity: BH_Product_CategoryDefaultInput!): BH_Product_CategoryDefault!
	BH_Product_CategoryDefaultSaveMany(Entities: [BH_Product_CategoryDefaultInput!]!): [BH_Product_CategoryDefault!]!
	BH_Product_CategoryDefaultDelete(UUs: [String!]!): Boolean!
}

type BH_Product_CategoryDefaultConnection {
	Results: [BH_Product_CategoryDefault!]!
	PagingInfo: PagingInfo!
}

type BH_Product_CategoryDefault {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Contains a character the is linked to a ref list to determine types of product categories
	BH_Product_Category_Type: AD_Ref_List!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input BH_Product_CategoryDefaultInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Contains a character the is linked to a ref list to determine types of product categories
	BH_Product_Category_Type: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
