# Generated Schema for BH_Voided_Reason - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	BH_Voided_ReasonGet(page: Int, size: Int, sort: String, filter: String): BH_Voided_ReasonConnection!
}

extend type Mutation {
	BH_Voided_ReasonSave(entity: BH_Voided_ReasonInput!): BH_Voided_Reason!
	BH_Voided_ReasonSaveMany(entities: [BH_Voided_ReasonInput!]!): [BH_Voided_Reason!]!
	BH_Voided_ReasonDelete(uuids: [String!]!): Boolean!
}

type BH_Voided_ReasonConnection {
	results: [BH_Voided_Reason!]!
	pagingInfo: PagingInfo!
}

type BH_Voided_Reason {
	# Client/Tenant for this installation.
	AD_Client: AD_Client
	# Organizational entity within client
	AD_Org: AD_Org
	UUID: ID!
	bh_window_id: BigDecimal
	# Date this record was created
	Created: Date
	# User who created this records
	CreatedBy: AD_User
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Line No
	LineNo: Int
	# Alphanumeric identifier of the entity
	Name: String
	# Date this record was updated
	Updated: Date
	# User who updated this records
	UpdatedBy: AD_User
}

input BH_Voided_ReasonInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	UUID: ID
	bh_window_id: BigDecimal
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Line No
	LineNo: Int
	# Alphanumeric identifier of the entity
	Name: String
}
