# Generated Schema for BH_BP_Specific_Payer_Info - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	BH_BP_Specific_Payer_Info(UU: String!): BH_BP_Specific_Payer_Info
	BH_BP_Specific_Payer_InfoGet(Page: Int, Size: Int, Sort: String, Filter: String): BH_BP_Specific_Payer_InfoConnection!
}

extend type Mutation {
	BH_BP_Specific_Payer_InfoSave(Entity: BH_BP_Specific_Payer_InfoInput!): BH_BP_Specific_Payer_Info!
	BH_BP_Specific_Payer_InfoSaveMany(Entities: [BH_BP_Specific_Payer_InfoInput!]!): [BH_BP_Specific_Payer_Info!]!
	BH_BP_Specific_Payer_InfoDelete(UUs: [String!]!): Boolean!
}

type BH_BP_Specific_Payer_InfoConnection {
	Results: [BH_BP_Specific_Payer_Info!]!
	PagingInfo: PagingInfo!
}

type BH_BP_Specific_Payer_Info {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	BH_Payer_Info_Fld: BH_Payer_Info_Fld!
	# Invoice Detail Line
	C_InvoiceLine: C_InvoiceLine!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_BP_Specific_Payer_InfoInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	BH_Payer_Info_Fld: ForeignEntityInput
	# Invoice Detail Line
	C_InvoiceLine: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
