# Generated Schema for BH_Tag - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	BH_Tag(UU: String!): BH_Tag
	BH_TagGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): BH_TagConnection!
}

extend type Mutation {
	BH_TagSave(Entity: BH_TagInput!): BH_Tag!
	BH_TagSaveMany(Entities: [BH_TagInput!]!): [BH_Tag!]!
	BH_TagDelete(UUs: [String!]!): Boolean!
}

type BH_TagConnection {
	Results: [BH_Tag!]!
	PagingInfo: PagingInfo!
}

type BH_Tag {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	BH_ColourCode: String
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_TagInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	BH_ColourCode: String
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
