# Generated Schema for BH_TabNavBtn - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	BH_TabNavBtnGet(page: Int, size: Int, sort: String, filter: String): BH_TabNavBtnConnection!
}

extend type Mutation {
	BH_TabNavBtnSave(entity: BH_TabNavBtnInput!): BH_TabNavBtn!
	BH_TabNavBtnSaveMany(entities: [BH_TabNavBtnInput!]!): [BH_TabNavBtn!]!
	BH_TabNavBtnDelete(uuids: [String!]!): Boolean!
}

type BH_TabNavBtnConnection {
	results: [BH_TabNavBtn!]!
	pagingInfo: PagingInfo!
}

type BH_TabNavBtn {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Column in the table
	AD_Column: AD_Column
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Tab within a Window
	AD_Tab: AD_Tab
	# Database Table information
	AD_Table: AD_Table
	# Data entry or display window
	AD_Window: AD_Window
	UUID: ID!
	# The action this button will perform
	ButtonAction: AD_Ref_List!
	# The class(es) the button will have
	ButtonClassName: String
	# The text displayed when a user hovers over the button
	ButtonHelpText: String
	# The position of this button on the screen
	ButtonLocation: AD_Ref_List!
	# The text displayed in the button
	ButtonText: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# The class(es) to display the correct Font Awesome icon
	IconClassName: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_TabNavBtnInput {
	# Column in the table
	AD_Column: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Tab within a Window
	AD_Tab: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Data entry or display window
	AD_Window: ForeignEntityInput
	UUID: ID
	# The action this button will perform
	ButtonAction: AD_Ref_ListInput
	# The class(es) the button will have
	ButtonClassName: String
	# The text displayed when a user hovers over the button
	ButtonHelpText: String
	# The position of this button on the screen
	ButtonLocation: AD_Ref_ListInput
	# The text displayed in the button
	ButtonText: String
	# Optional short description of the record
	Description: String
	# If the Field is displayed, the result determines if the field is actually displayed
	DisplayLogic: String
	# The class(es) to display the correct Font Awesome icon
	IconClassName: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
