# Generated Schema for BH_Observation - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	BH_ObservationGet(page: Int, size: Int, sort: String, filter: String): BH_ObservationConnection!
}

extend type Mutation {
	BH_ObservationSave(entity: BH_ObservationInput!): BH_Observation!
	BH_ObservationSaveMany(entities: [BH_ObservationInput!]!): [BH_Observation!]!
	BH_ObservationDelete(uuids: [String!]!): Boolean!
}

type BH_ObservationConnection {
	results: [BH_Observation!]!
	pagingInfo: PagingInfo!
}

type BH_Observation {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Field on a database table
	AD_Field: AD_Field!
	# Organizational entity within client
	AD_Org: AD_Org!
	BH_Encounter: BH_Encounter!
	UUID: ID!
	# BH_Value
	BH_Value: String!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input BH_ObservationInput {
	# Field on a database table
	AD_Field: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	BH_Encounter: ForeignEntityInput
	UUID: ID
	# BH_Value
	BH_Value: String
	# The record is active in the system
	IsActive: Boolean
}
