# Generated Schema for C_Period - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_Period(UU: String!): C_Period
	C_PeriodGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_PeriodConnection!
}

extend type Mutation {
	C_PeriodSave(Entity: C_PeriodInput!): C_Period!
	C_PeriodSaveMany(Entities: [C_PeriodInput!]!): [C_Period!]!
	C_PeriodDelete(UUs: [String!]!): Boolean!
}

type C_PeriodConnection {
	Results: [C_Period!]!
	PagingInfo: PagingInfo!
}

type C_Period {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Calendar Year
	C_Year: C_Year!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Last effective date (inclusive)
	EndDate: Date
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Unique Period Number
	PeriodNo: Int!
	# Period Type
	PeriodType: AD_Ref_List!
	Processing: Boolean!
	# First effective day (inclusive)
	StartDate: Date!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_PeriodInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Calendar Year
	C_Year: ForeignEntityInput
	# Last effective date (inclusive)
	EndDate: Date
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Unique Period Number
	PeriodNo: Int
	# Period Type
	PeriodType: ForeignEntityInput
	Processing: Boolean
	# First effective day (inclusive)
	StartDate: Date
}
