# Generated Schema for C_JobAssignment - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_JobAssignment(UU: String!): C_JobAssignment
	C_JobAssignmentGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_JobAssignmentConnection!
}

extend type Mutation {
	C_JobAssignmentSave(Entity: C_JobAssignmentInput!): C_JobAssignment!
	C_JobAssignmentSaveMany(Entities: [C_JobAssignmentInput!]!): [C_JobAssignment!]!
	C_JobAssignmentDelete(UUs: [String!]!): Boolean!
}

type C_JobAssignmentConnection {
	Results: [C_JobAssignment!]!
	PagingInfo: PagingInfo!
}

type C_JobAssignment {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	# Job Position
	C_Job: C_Job!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Valid from including this date (first day)
	ValidFrom: DateTime!
	# Valid to including this date (last day)
	ValidTo: DateTime
}

input C_JobAssignmentInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Job Position
	C_Job: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Valid from including this date (first day)
	ValidFrom: DateTime
	# Valid to including this date (last day)
	ValidTo: DateTime
}
