# Generated Schema for C_ChargeType - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_ChargeType(UU: String!): C_ChargeType
	C_ChargeTypeGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_ChargeTypeConnection!
}

extend type Mutation {
	C_ChargeTypeSave(Entity: C_ChargeTypeInput!): C_ChargeType!
	C_ChargeTypeSaveMany(Entities: [C_ChargeTypeInput!]!): [C_ChargeType!]!
	C_ChargeTypeDelete(UUs: [String!]!): Boolean!
}

type C_ChargeTypeConnection {
	Results: [C_ChargeType!]!
	PagingInfo: PagingInfo!
}

type C_ChargeType {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input C_ChargeTypeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
