# Generated Schema for C_SubAcct - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_SubAcctGet(page: Int, size: Int, sort: String, filter: String): C_SubAcctConnection!
}

extend type Mutation {
	C_SubAcctSave(entity: C_SubAcctInput!): C_SubAcct!
	C_SubAcctSaveMany(entities: [C_SubAcctInput!]!): [C_SubAcct!]!
	C_SubAcctDelete(uuids: [String!]!): Boolean!
}

type C_SubAcctConnection {
	results: [C_SubAcct!]!
	pagingInfo: PagingInfo!
}

type C_SubAcct {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Account Element
	C_ElementValue: C_ElementValue!
	UUID: ID!
	C_SubAcct_UU: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input C_SubAcctInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Account Element
	C_ElementValue: ForeignEntityInput
	UUID: ID
	C_SubAcct_UU: String
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
