# Generated Schema for C_PaymentBatch - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_PaymentBatch(UU: String!): C_PaymentBatch
	C_PaymentBatchGet(Page: Int, Size: Int, Sort: String, Filter: String): C_PaymentBatchConnection!
}

extend type Mutation {
	C_PaymentBatchSave(Entity: C_PaymentBatchInput!): C_PaymentBatch!
	C_PaymentBatchSaveMany(Entities: [C_PaymentBatchInput!]!): [C_PaymentBatch!]!
	C_PaymentBatchDelete(UUs: [String!]!): Boolean!
}

type C_PaymentBatchConnection {
	Results: [C_PaymentBatch!]!
	PagingInfo: PagingInfo!
}

type C_PaymentBatch {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Payment processor for electronic payments
	C_PaymentProcessor: C_PaymentProcessor!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	ProcessingDate: Date
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_PaymentBatchInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Payment processor for electronic payments
	C_PaymentProcessor: ForeignEntityInput
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	ProcessingDate: Date
}
