# Generated Schema for C_OrderPaySchedule - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_OrderPayScheduleGet(page: Int, size: Int, sort: String, filter: String): C_OrderPayScheduleConnection!
}

extend type Mutation {
	C_OrderPayScheduleSave(entity: C_OrderPayScheduleInput!): C_OrderPaySchedule!
	C_OrderPayScheduleDelete(uuids: [String!]!): Boolean!
}

type C_OrderPayScheduleConnection {
	results: [C_OrderPaySchedule!]!
	pagingInfo: PagingInfo!
}

type C_OrderPaySchedule {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Order
	C_Order: C_Order!
	ID: ID!
	# Payment Schedule Template
	C_PaySchedule: C_PaySchedule
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Calculated amount of discount
	DiscountAmt: Int!
	# Last Date for payments with discount
	DiscountDate: Date!
	# Amount of the payment due
	DueAmt: Int!
	# Date when the payment is due
	DueDate: Date!
	# The record is active in the system
	IsActive: Boolean!
	# Element is valid
	IsValid: Boolean!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_OrderPayScheduleInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Order
	C_Order: ForeignEntityInput
	ID: ID
	# Payment Schedule Template
	C_PaySchedule: ForeignEntityInput
	# Calculated amount of discount
	DiscountAmt: Int
	# Last Date for payments with discount
	DiscountDate: Date
	# Amount of the payment due
	DueAmt: Int
	# Date when the payment is due
	DueDate: Date
	# The record is active in the system
	IsActive: Boolean
	# Element is valid
	IsValid: Boolean
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
}
