# Generated Schema for C_PaySchedule - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_PaySchedule(UU: String!): C_PaySchedule
	C_PayScheduleGet(Page: Int, Size: Int, Sort: String, Filter: String): C_PayScheduleConnection!
}

extend type Mutation {
	C_PayScheduleSave(Entity: C_PayScheduleInput!): C_PaySchedule!
	C_PayScheduleSaveMany(Entities: [C_PayScheduleInput!]!): [C_PaySchedule!]!
	C_PayScheduleDelete(UUs: [String!]!): Boolean!
}

type C_PayScheduleConnection {
	Results: [C_PaySchedule!]!
	PagingInfo: PagingInfo!
}

type C_PaySchedule {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# The terms of Payment (timing, discount)
	C_PaymentTerm: C_PaymentTerm!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Discount in percent
	Discount: BigDecimal!
	# Number of days from invoice date to be eligible for discount
	DiscountDays: Int!
	# Days after due date to send first dunning letter
	GraceDays: Int!
	# The record is active in the system
	IsActive: Boolean!
	# Element is valid
	IsValid: Boolean!
	# Day when payment is due net
	NetDay: AD_Ref_List
	# Net Days in which payment is due
	NetDays: Int!
	# Percent of the entire amount
	Percentage: BigDecimal!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_PayScheduleInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# The terms of Payment (timing, discount)
	C_PaymentTerm: ForeignEntityInput
	UU: ID
	# Discount in percent
	Discount: BigDecimal
	# Number of days from invoice date to be eligible for discount
	DiscountDays: Int
	# Days after due date to send first dunning letter
	GraceDays: Int
	# The record is active in the system
	IsActive: Boolean
	# Element is valid
	IsValid: Boolean
	# Day when payment is due net
	NetDay: ForeignEntityInput
	# Net Days in which payment is due
	NetDays: Int
	# Percent of the entire amount
	Percentage: BigDecimal
}
