# Generated Schema for C_JobRemuneration - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_JobRemuneration(UU: String!): C_JobRemuneration
	C_JobRemunerationGet(Page: Int, Size: Int, Sort: String, Filter: String): C_JobRemunerationConnection!
}

extend type Mutation {
	C_JobRemunerationSave(Entity: C_JobRemunerationInput!): C_JobRemuneration!
	C_JobRemunerationSaveMany(Entities: [C_JobRemunerationInput!]!): [C_JobRemuneration!]!
	C_JobRemunerationDelete(UUs: [String!]!): Boolean!
}

type C_JobRemunerationConnection {
	Results: [C_JobRemuneration!]!
	PagingInfo: PagingInfo!
}

type C_JobRemuneration {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Job Position
	C_Job: C_Job!
	UU: ID!
	# Wage or Salary
	C_Remuneration: C_Remuneration!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Valid from including this date (first day)
	ValidFrom: DateTime!
	# Valid to including this date (last day)
	ValidTo: DateTime
}

input C_JobRemunerationInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Job Position
	C_Job: ForeignEntityInput
	UU: ID
	# Wage or Salary
	C_Remuneration: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Valid from including this date (first day)
	ValidFrom: DateTime
	# Valid to including this date (last day)
	ValidTo: DateTime
}
