# Generated Schema for C_OrderLandedCost - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_OrderLandedCostGet(page: Int, size: Int, sort: String, filter: String): C_OrderLandedCostConnection!
}

extend type Mutation {
	C_OrderLandedCostSave(entity: C_OrderLandedCostInput!): C_OrderLandedCost!
	C_OrderLandedCostSaveMany(entities: [C_OrderLandedCostInput!]!): [C_OrderLandedCost!]!
	C_OrderLandedCostDelete(uuids: [String!]!): Boolean!
}

type C_OrderLandedCostConnection {
	results: [C_OrderLandedCost!]!
	pagingInfo: PagingInfo!
}

type C_OrderLandedCost {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Amount
	Amt: BigDecimal!
	# Order
	C_Order: C_Order!
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Landed Cost Distribution
	LandedCostDistribution: AD_Ref_List!
	# Product Cost Element
	M_CostElement: M_CostElement!
	# The document has been processed
	Processed: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_OrderLandedCostInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Amount
	Amt: BigDecimal
	# Order
	C_Order: ForeignEntityInput
	UUID: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Landed Cost Distribution
	LandedCostDistribution: AD_Ref_ListInput
	# Product Cost Element
	M_CostElement: ForeignEntityInput
	# The document has been processed
	Processed: Boolean
}
