# Generated Schema for C_BankAccount_Processor - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	C_BankAccount_ProcessorGet(page: Int, size: Int, sort: String, filter: String): C_BankAccount_ProcessorConnection!
}

extend type Mutation {
	C_BankAccount_ProcessorSave(entity: C_BankAccount_ProcessorInput!): C_BankAccount_Processor!
	C_BankAccount_ProcessorSaveMany(entities: [C_BankAccount_ProcessorInput!]!): [C_BankAccount_Processor!]!
	C_BankAccount_ProcessorDelete(uuids: [String!]!): Boolean!
}

type C_BankAccount_ProcessorConnection {
	results: [C_BankAccount_Processor!]!
	pagingInfo: PagingInfo!
}

type C_BankAccount_Processor {
	# Accept American Express Card
	AcceptAMEX: Boolean!
	# Accept Bank ATM Card
	AcceptATM: Boolean!
	# Accept ECheck (Electronic Checks)
	AcceptCheck: Boolean!
	# Accept Corporate Purchase Cards
	AcceptCorporate: Boolean!
	# Accept Diner's Club
	AcceptDiners: Boolean!
	# Accept Direct Debits (vendor initiated)
	AcceptDirectDebit: Boolean!
	# Accept Direct Deposit (payee initiated)
	AcceptDirectDeposit: Boolean!
	# Accept Discover Card
	AcceptDiscover: Boolean!
	# Accept Master Card
	AcceptMC: Boolean!
	# Accept Visa Cards
	AcceptVisa: Boolean!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Account at the Bank
	C_BankAccount: C_BankAccount!
	UUID: ID!
	# The Currency for this record
	C_Currency: C_Currency
	# Payment processor for electronic payments
	C_PaymentProcessor: C_PaymentProcessor!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	IsPPAcceptAMEX: Boolean!
	IsPPAcceptATM: Boolean!
	IsPPAcceptCheck: Boolean!
	IsPPAcceptCorporate: Boolean!
	IsPPAcceptDiners: Boolean!
	IsPPAcceptDirectDebit: Boolean!
	IsPPAcceptDirectDeposit: Boolean!
	IsPPAcceptDiscover: Boolean!
	IsPPAcceptMC: Boolean!
	IsPPAcceptVisa: Boolean!
	# Minimum Amount in Document Currency
	MinimumAmt: BigDecimal
	# Partner ID or Account for the Payment Processor
	PartnerID: String
	# Password of any length (case sensitive)
	Password: String!
	# Require 3/4 digit Credit Verification Code
	RequireVV: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# User ID or account number
	UserID: String!
	# Vendor ID for the Payment Processor
	VendorID: String
}

input C_BankAccount_ProcessorInput {
	# Accept American Express Card
	AcceptAMEX: Boolean
	# Accept Bank ATM Card
	AcceptATM: Boolean
	# Accept ECheck (Electronic Checks)
	AcceptCheck: Boolean
	# Accept Corporate Purchase Cards
	AcceptCorporate: Boolean
	# Accept Diner's Club
	AcceptDiners: Boolean
	# Accept Direct Debits (vendor initiated)
	AcceptDirectDebit: Boolean
	# Accept Direct Deposit (payee initiated)
	AcceptDirectDeposit: Boolean
	# Accept Discover Card
	AcceptDiscover: Boolean
	# Accept Master Card
	AcceptMC: Boolean
	# Accept Visa Cards
	AcceptVisa: Boolean
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Account at the Bank
	C_BankAccount: ForeignEntityInput
	UUID: ID
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Payment processor for electronic payments
	C_PaymentProcessor: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Minimum Amount in Document Currency
	MinimumAmt: BigDecimal
	# Partner ID or Account for the Payment Processor
	PartnerID: String
	# Password of any length (case sensitive)
	Password: String
	# Require 3/4 digit Credit Verification Code
	RequireVV: Boolean
	# User ID or account number
	UserID: String
	# Vendor ID for the Payment Processor
	VendorID: String
}
