# Generated Schema for C_InvoiceTax - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_InvoiceTaxGet(page: Int, size: Int, sort: String, filter: String): C_InvoiceTaxConnection!
}

extend type Mutation {
	C_InvoiceTaxSave(entity: C_InvoiceTaxInput!): C_InvoiceTax!
	C_InvoiceTaxSaveMany(entities: [C_InvoiceTaxInput!]!): [C_InvoiceTax!]!
	C_InvoiceTaxDelete(uuids: [String!]!): Boolean!
}

type C_InvoiceTaxConnection {
	results: [C_InvoiceTax!]!
	pagingInfo: PagingInfo!
}

type C_InvoiceTax {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Invoice Identifier
	C_Invoice: C_Invoice!
	UUID: ID!
	C_InvoiceTax_UU: String
	# Tax identifier
	C_Tax: C_Tax!
	C_TaxProvider: C_TaxProvider
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Tax is included in the price 
	IsTaxIncluded: Boolean!
	# The document has been processed
	Processed: Boolean!
	# Tax Amount for a document
	TaxAmt: BigDecimal!
	# Base for calculating the tax amount
	TaxBaseAmt: BigDecimal!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_InvoiceTaxInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	UUID: ID
	C_InvoiceTax_UU: String
	# Tax identifier
	C_Tax: ForeignEntityInput
	C_TaxProvider: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Tax is included in the price 
	IsTaxIncluded: Boolean
	# The document has been processed
	Processed: Boolean
	# Tax Amount for a document
	TaxAmt: BigDecimal
	# Base for calculating the tax amount
	TaxBaseAmt: BigDecimal
}
