# Generated Schema for C_AcctProcessor - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_AcctProcessor(UU: String!): C_AcctProcessor
	C_AcctProcessorGet(Page: Int, Size: Int, Sort: String, Filter: String): C_AcctProcessorConnection!
}

extend type Mutation {
	C_AcctProcessorSave(Entity: C_AcctProcessorInput!): C_AcctProcessor!
	C_AcctProcessorSaveMany(Entities: [C_AcctProcessorInput!]!): [C_AcctProcessor!]!
	C_AcctProcessorDelete(UUs: [String!]!): Boolean!
}

type C_AcctProcessorConnection {
	Results: [C_AcctProcessor!]!
	PagingInfo: PagingInfo!
}

type C_AcctProcessor {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AD_Schedule: AD_Schedule!
	# Database Table information
	AD_Table: AD_Table
	UU: ID!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Date the process was last run.
	DateLastRun: DateTime
	# Date the process will run next
	DateNextRun: DateTime
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Number of days to keep the log entries
	KeepLogDays: Int!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: AD_User!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_AcctProcessorInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AD_Schedule: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	UU: ID
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# Date the process was last run.
	DateLastRun: DateTime
	# Date the process will run next
	DateNextRun: DateTime
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Number of days to keep the log entries
	KeepLogDays: Int
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: ForeignEntityInput
}
