# Generated Schema for C_POSKey - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_POSKey(UU: String!): C_POSKey
	C_POSKeyGet(Page: Int, Size: Int, Sort: String, Filter: String): C_POSKeyConnection!
}

extend type Mutation {
	C_POSKeySave(Entity: C_POSKeyInput!): C_POSKey!
	C_POSKeySaveMany(Entities: [C_POSKeyInput!]!): [C_POSKey!]!
	C_POSKeyDelete(UUs: [String!]!): Boolean!
}

type C_POSKeyConnection {
	Results: [C_POSKey!]!
	PagingInfo: PagingInfo!
}

type C_POSKey {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Image or Icon
	AD_Image: AD_Image
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Color used for printing and display
	AD_PrintColor: AD_PrintColor
	# Maintain Print Font
	AD_PrintFont: AD_PrintFont
	UU: ID!
	# POS Function Key Layout
	C_POSKeyLayout: C_POSKeyLayout!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String!
	# Quantity
	Qty: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Number of columns spanned
	SpanX: Int
	# Number of rows spanned
	SpanY: Int
	# Key Layout to be displayed when this key is pressed
	SubKeyLayout: C_POSKeyLayout
	Text: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_POSKeyInput {
	# Image or Icon
	AD_Image: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Color used for printing and display
	AD_PrintColor: ForeignEntityInput
	# Maintain Print Font
	AD_PrintFont: ForeignEntityInput
	UU: ID
	# POS Function Key Layout
	C_POSKeyLayout: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# Quantity
	Qty: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Number of columns spanned
	SpanX: Int
	# Number of rows spanned
	SpanY: Int
	# Key Layout to be displayed when this key is pressed
	SubKeyLayout: ForeignEntityInput
	Text: String
}
