# Generated Schema for C_PaySelectionCheck - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	C_PaySelectionCheckGet(page: Int, size: Int, sort: String, filter: String): C_PaySelectionCheckConnection!
}

extend type Mutation {
	C_PaySelectionCheckSave(entity: C_PaySelectionCheckInput!): C_PaySelectionCheck!
	C_PaySelectionCheckDelete(uuids: [String!]!): Boolean!
}

type C_PaySelectionCheckConnection {
	results: [C_PaySelectionCheck!]!
	pagingInfo: PagingInfo!
}

type C_PaySelectionCheck {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Bank Account of the Business Partner
	C_BP_BankAccount: C_BP_BankAccount
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	# Payment identifier
	C_Payment: C_Payment
	# Payment Selection
	C_PaySelection: C_PaySelection!
	ID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Calculated amount of discount
	DiscountAmt: BigDecimal!
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean!
	IsGeneratedDraft: Boolean!
	# Indicates if this document / line is printed
	IsPrinted: Boolean!
	# This is a sales transaction (receipt)
	IsReceipt: Boolean!
	# Amount being paid
	PayAmt: BigDecimal!
	# How you pay the invoice
	PaymentRule: AD_Ref_List!
	# The document has been processed
	Processed: Boolean!
	# Quantity
	Qty: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Amount to write-off
	WriteOffAmt: BigDecimal!
}

input C_PaySelectionCheckInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Bank Account of the Business Partner
	C_BP_BankAccount: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Payment identifier
	C_Payment: ForeignEntityInput
	# Payment Selection
	C_PaySelection: ForeignEntityInput
	ID: ID
	# Calculated amount of discount
	DiscountAmt: BigDecimal
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean
	IsGeneratedDraft: Boolean
	# Indicates if this document / line is printed
	IsPrinted: Boolean
	# This is a sales transaction (receipt)
	IsReceipt: Boolean
	# Amount being paid
	PayAmt: BigDecimal
	# How you pay the invoice
	PaymentRule: AD_Ref_ListInput
	# The document has been processed
	Processed: Boolean
	# Quantity
	Qty: Int
	# Amount to write-off
	WriteOffAmt: BigDecimal
}
