# Generated Schema for C_Dunning - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_DunningGet(Page: Int, Size: Int, Sort: String, Filter: String): C_DunningConnection!
}

extend type Mutation {
	C_DunningSave(Entity: C_DunningInput!): C_Dunning!
	C_DunningSaveMany(Entities: [C_DunningInput!]!): [C_Dunning!]!
	C_DunningDelete(UUs: [String!]!): Boolean!
}

type C_DunningConnection {
	Results: [C_Dunning!]!
	PagingInfo: PagingInfo!
}

type C_Dunning {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Create Dunning Letter by level sequentially
	CreateLevelsSequentially: Boolean!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Indicates if dunning letters will be sent
	SendDunningLetter: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_DunningInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Create Dunning Letter by level sequentially
	CreateLevelsSequentially: Boolean
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Indicates if dunning letters will be sent
	SendDunningLetter: Boolean
}
