# Generated Schema for C_Channel - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_Channel(UU: String!): C_Channel
	C_ChannelGet(Page: Int, Size: Int, Sort: String, Filter: String): C_ChannelConnection!
}

extend type Mutation {
	C_ChannelSave(Entity: C_ChannelInput!): C_Channel!
	C_ChannelSaveMany(Entities: [C_ChannelInput!]!): [C_Channel!]!
	C_ChannelDelete(UUs: [String!]!): Boolean!
}

type C_ChannelConnection {
	Results: [C_Channel!]!
	PagingInfo: PagingInfo!
}

type C_Channel {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Color used for printing and display
	AD_PrintColor: AD_PrintColor
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_ChannelInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Color used for printing and display
	AD_PrintColor: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
