# Generated Schema for C_BPartner_Product - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_BPartner_Product(UU: String!): C_BPartner_Product
	C_BPartner_ProductGet(Page: Int, Size: Int, Sort: String, Filter: String): C_BPartner_ProductConnection!
}

extend type Mutation {
	C_BPartner_ProductSave(Entity: C_BPartner_ProductInput!): C_BPartner_Product!
	C_BPartner_ProductSaveMany(Entities: [C_BPartner_ProductInput!]!): [C_BPartner_Product!]!
	C_BPartner_ProductDelete(UUs: [String!]!): Boolean!
}

type C_BPartner_ProductConnection {
	Results: [C_BPartner_Product!]!
	PagingInfo: PagingInfo!
}

type C_BPartner_Product {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Indicate role of this Business partner as Manufacturer
	IsManufacturer: Boolean!
	# Manufacturer of the Product
	Manufacturer: String
	# Product, Service, Item
	M_Product: M_Product!
	# Method for rating vendors
	QualityRating: BigDecimal
	# Minimum Shelf Life in days based on Product Instance Guarantee Date
	ShelfLifeMinDays: Int!
	# Minimum Shelf Life in percent based on Product Instance Guarantee Date
	ShelfLifeMinPct: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Product Category of the Business Partner
	VendorCategory: String
	# Product Key of the Business Partner
	VendorProductNo: String
}

input C_BPartner_ProductInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Indicate role of this Business partner as Manufacturer
	IsManufacturer: Boolean
	# Manufacturer of the Product
	Manufacturer: String
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Method for rating vendors
	QualityRating: BigDecimal
	# Minimum Shelf Life in days based on Product Instance Guarantee Date
	ShelfLifeMinDays: Int
	# Minimum Shelf Life in percent based on Product Instance Guarantee Date
	ShelfLifeMinPct: Int
	# Product Category of the Business Partner
	VendorCategory: String
	# Product Key of the Business Partner
	VendorProductNo: String
}
