# Generated Schema for C_PaymentTransaction - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_PaymentTransactionGet(page: Int, size: Int, sort: String, filter: String): C_PaymentTransactionConnection!
}

extend type Mutation {
	C_PaymentTransactionSave(entity: C_PaymentTransactionInput!): C_PaymentTransaction!
	C_PaymentTransactionDelete(uuids: [String!]!): Boolean!
}

type C_PaymentTransactionConnection {
	results: [C_PaymentTransaction!]!
	pagingInfo: PagingInfo!
}

type C_PaymentTransaction {
	# City or the Credit Card or Account Holder
	A_City: String
	# Country
	A_Country: String
	# Email Address
	A_EMail: String
	# Payment Identification - Driver License
	A_Ident_DL: String
	# Payment Identification - Social Security No
	A_Ident_SSN: String
	# Name on Credit Card or Account holder
	A_Name: String
	# State of the Credit Card or Account holder
	A_State: String
	# Street address of the Credit Card or Account holder
	A_Street: String
	# Zip Code of the Credit Card or Account Holder
	A_Zip: String
	# Account Number
	AccountNo: String
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Business Activity
	C_Activity: C_Activity
	# Account at the Bank
	C_BankAccount: C_BankAccount
	# Bank Account of the Business Partner
	C_BP_BankAccount: C_BP_BankAccount
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	# Marketing Campaign
	C_Campaign: C_Campaign
	# Cash Book for recording petty cash transactions
	C_CashBook: C_CashBook
	# Additional document charges
	C_Charge: C_Charge
	# Currency Conversion Rate Type
	C_ConversionType: C_ConversionType
	# The Currency for this record
	C_Currency: C_Currency!
	# Invoice Identifier
	C_Invoice: C_Invoice
	# Order
	C_Order: C_Order
	# Payment identifier
	C_Payment: C_Payment
	# Payment batch for EFT
	C_PaymentBatch: C_PaymentBatch
	# Payment processor for electronic payments
	C_PaymentProcessor: C_PaymentProcessor
	ID: ID!
	C_POSTenderType: C_POSTenderType
	# Financial Project
	C_Project: C_Project
	# Check Number
	CheckNo: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Expiry Month
	CreditCardExpMM: Int
	# Expiry Year
	CreditCardExpYY: Int
	# Credit Card Number 
	CreditCardNumber: String
	# Credit Card (Visa, MC, AmEx)
	CreditCardType: AD_Ref_List
	# Credit Card Verification code on credit card
	CreditCardVV: String
	CustomerAddressID: String
	CustomerPaymentProfileID: String
	CustomerProfileID: String
	# Transaction Date
	DateTrx: Date!
	# Optional short description of the record
	Description: String
	# International Bank Account Number
	IBAN: String
	# The record is active in the system
	IsActive: Boolean!
	# Indicates if this document requires approval
	IsApproved: Boolean!
	# Charge after Shipment
	IsDelayedCapture: Boolean!
	# Can be accessed online 
	IsOnline: Boolean!
	# This is a sales transaction (receipt)
	IsReceipt: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	IsVoided: Boolean!
	# Combination of routing no, account and check no
	Micr: String
	# Original Transaction ID
	Orig_TrxID: String
	# Amount being paid
	PayAmt: Int!
	# Purchase Order Number
	PONum: String
	# The document has been processed
	Processed: Boolean!
	# Authorization Code returned
	R_AuthCode: String
	# This address has been verified
	R_AvsAddr: AD_Ref_List
	# The Zip Code has been verified
	R_AvsZip: AD_Ref_List
	# Credit Card Verification Code Match
	R_CVV2Match: Boolean!
	# Response info
	R_Info: String
	# Payment reference
	R_PnRef: String
	# Response message
	R_RespMsg: String
	# Result of transmission
	R_Result: String
	R_VoidMsg: String
	Ref_PaymentTransaction: C_PaymentTransaction
	# Bank Routing Number
	RoutingNo: String
	# Swift Code or BIC
	SwiftCode: String
	# Tax Amount for a document
	TaxAmt: Int
	# Method of Payment
	TenderType: AD_Ref_List!
	# Type of credit card transaction
	TrxType: AD_Ref_List!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# User defined list element #1
	User1: C_ElementValue
	# User defined list element #2
	User2: C_ElementValue
	# Voice Authorization Code from credit card company
	VoiceAuthCode: String
	VoidIt: String
}

input C_PaymentTransactionInput {
	# City or the Credit Card or Account Holder
	A_City: String
	# Country
	A_Country: String
	# Email Address
	A_EMail: String
	# Payment Identification - Driver License
	A_Ident_DL: String
	# Payment Identification - Social Security No
	A_Ident_SSN: String
	# Name on Credit Card or Account holder
	A_Name: String
	# State of the Credit Card or Account holder
	A_State: String
	# Street address of the Credit Card or Account holder
	A_Street: String
	# Zip Code of the Credit Card or Account Holder
	A_Zip: String
	# Account Number
	AccountNo: String
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Business Activity
	C_Activity: ForeignEntityInput
	# Account at the Bank
	C_BankAccount: ForeignEntityInput
	# Bank Account of the Business Partner
	C_BP_BankAccount: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Marketing Campaign
	C_Campaign: ForeignEntityInput
	# Cash Book for recording petty cash transactions
	C_CashBook: ForeignEntityInput
	# Additional document charges
	C_Charge: ForeignEntityInput
	# Currency Conversion Rate Type
	C_ConversionType: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# Order
	C_Order: ForeignEntityInput
	# Payment identifier
	C_Payment: ForeignEntityInput
	# Payment batch for EFT
	C_PaymentBatch: ForeignEntityInput
	# Payment processor for electronic payments
	C_PaymentProcessor: ForeignEntityInput
	ID: ID
	C_POSTenderType: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Check Number
	CheckNo: String
	# Expiry Month
	CreditCardExpMM: Int
	# Expiry Year
	CreditCardExpYY: Int
	# Credit Card Number 
	CreditCardNumber: String
	# Credit Card (Visa, MC, AmEx)
	CreditCardType: AD_Ref_ListInput
	# Credit Card Verification code on credit card
	CreditCardVV: String
	CustomerAddressID: String
	CustomerPaymentProfileID: String
	CustomerProfileID: String
	# Transaction Date
	DateTrx: Date
	# Optional short description of the record
	Description: String
	# International Bank Account Number
	IBAN: String
	# The record is active in the system
	IsActive: Boolean
	# Indicates if this document requires approval
	IsApproved: Boolean
	# Charge after Shipment
	IsDelayedCapture: Boolean
	# Can be accessed online 
	IsOnline: Boolean
	# This is a sales transaction (receipt)
	IsReceipt: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	IsVoided: Boolean
	# Combination of routing no, account and check no
	Micr: String
	# Original Transaction ID
	Orig_TrxID: String
	# Amount being paid
	PayAmt: Int
	# Purchase Order Number
	PONum: String
	# The document has been processed
	Processed: Boolean
	# Authorization Code returned
	R_AuthCode: String
	# This address has been verified
	R_AvsAddr: AD_Ref_ListInput
	# The Zip Code has been verified
	R_AvsZip: AD_Ref_ListInput
	# Credit Card Verification Code Match
	R_CVV2Match: Boolean
	# Response info
	R_Info: String
	# Payment reference
	R_PnRef: String
	# Response message
	R_RespMsg: String
	# Result of transmission
	R_Result: String
	R_VoidMsg: String
	Ref_PaymentTransaction: ForeignEntityInput
	# Bank Routing Number
	RoutingNo: String
	# Swift Code or BIC
	SwiftCode: String
	# Tax Amount for a document
	TaxAmt: Int
	# Method of Payment
	TenderType: AD_Ref_ListInput
	# Type of credit card transaction
	TrxType: AD_Ref_ListInput
	# User defined list element #1
	User1: ForeignEntityInput
	# User defined list element #2
	User2: ForeignEntityInput
	# Voice Authorization Code from credit card company
	VoiceAuthCode: String
	VoidIt: String
}
