# Generated Schema for C_SubAcct - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_SubAcct(UU: String!): C_SubAcct
	C_SubAcctGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_SubAcctConnection!
}

extend type Mutation {
	C_SubAcctSave(Entity: C_SubAcctInput!): C_SubAcct!
	C_SubAcctSaveMany(Entities: [C_SubAcctInput!]!): [C_SubAcct!]!
	C_SubAcctDelete(UUs: [String!]!): Boolean!
}

type C_SubAcctConnection {
	Results: [C_SubAcct!]!
	PagingInfo: PagingInfo!
}

type C_SubAcct {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Account Element
	C_ElementValue: C_ElementValue!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input C_SubAcctInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Account Element
	C_ElementValue: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
