# Generated Schema for C_UserRemuneration - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_UserRemuneration(UU: String!): C_UserRemuneration
	C_UserRemunerationGet(Page: Int, Size: Int, Sort: String, Filter: String): C_UserRemunerationConnection!
}

extend type Mutation {
	C_UserRemunerationSave(Entity: C_UserRemunerationInput!): C_UserRemuneration!
	C_UserRemunerationSaveMany(Entities: [C_UserRemunerationInput!]!): [C_UserRemuneration!]!
	C_UserRemunerationDelete(UUs: [String!]!): Boolean!
}

type C_UserRemunerationConnection {
	Results: [C_UserRemuneration!]!
	PagingInfo: PagingInfo!
}

type C_UserRemuneration {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	# Wage or Salary
	C_Remuneration: C_Remuneration!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Gross Remuneration Amount
	GrossRAmt: BigDecimal!
	# Gross Remuneration Costs
	GrossRCost: BigDecimal!
	# The record is active in the system
	IsActive: Boolean!
	# Hourly Overtime Rate
	OvertimeAmt: BigDecimal!
	# Hourly Overtime Cost
	OvertimeCost: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Valid from including this date (first day)
	ValidFrom: DateTime!
	# Valid to including this date (last day)
	ValidTo: DateTime
}

input C_UserRemunerationInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Wage or Salary
	C_Remuneration: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Gross Remuneration Amount
	GrossRAmt: BigDecimal
	# Gross Remuneration Costs
	GrossRCost: BigDecimal
	# The record is active in the system
	IsActive: Boolean
	# Hourly Overtime Rate
	OvertimeAmt: BigDecimal
	# Hourly Overtime Cost
	OvertimeCost: BigDecimal
	# Valid from including this date (first day)
	ValidFrom: DateTime
	# Valid to including this date (last day)
	ValidTo: DateTime
}
