# Generated Schema for C_CommissionAmt - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_CommissionAmtGet(page: Int, size: Int, sort: String, filter: String): C_CommissionAmtConnection!
}

extend type Mutation {
	C_CommissionAmtSave(entity: C_CommissionAmtInput!): C_CommissionAmt!
	C_CommissionAmtSaveMany(entities: [C_CommissionAmtInput!]!): [C_CommissionAmt!]!
	C_CommissionAmtDelete(uuids: [String!]!): Boolean!
}

type C_CommissionAmtConnection {
	results: [C_CommissionAmt!]!
	pagingInfo: PagingInfo!
}

type C_CommissionAmt {
	# The actual quantity
	ActualQty: BigDecimal!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UUID: ID!
	C_CommissionAmt_UU: String
	# Commission Line
	C_CommissionLine: C_CommissionLine!
	# Commission Run or Process
	C_CommissionRun: C_CommissionRun!
	# Commission Amount
	CommissionAmt: BigDecimal!
	# Converted Amount
	ConvertedAmt: BigDecimal!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_CommissionAmtInput {
	# The actual quantity
	ActualQty: BigDecimal
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UUID: ID
	C_CommissionAmt_UU: String
	# Commission Line
	C_CommissionLine: ForeignEntityInput
	# Commission Run or Process
	C_CommissionRun: ForeignEntityInput
	# Commission Amount
	CommissionAmt: BigDecimal
	# Converted Amount
	ConvertedAmt: BigDecimal
	# The record is active in the system
	IsActive: Boolean
}
