# Generated Schema for C_ProjectTask - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_ProjectTaskGet(page: Int, size: Int, sort: String, filter: String): C_ProjectTaskConnection!
}

extend type Mutation {
	C_ProjectTaskSave(entity: C_ProjectTaskInput!): C_ProjectTask!
	C_ProjectTaskDelete(uuids: [String!]!): Boolean!
}

type C_ProjectTaskConnection {
	results: [C_ProjectTask!]!
	pagingInfo: PagingInfo!
}

type C_ProjectTask {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Phase of a Project
	C_ProjectPhase: C_ProjectPhase!
	ID: ID!
	# Standard Project Type Task
	C_Task: C_Task
	# The (legal) commitment amount
	CommittedAmt: Int!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String!
	# Planned amount for this project
	PlannedAmt: Int!
	# Invoice Rule for the project
	ProjInvoiceRule: AD_Ref_List!
	# Quantity
	Qty: Int
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_ProjectTaskInput {
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Phase of a Project
	C_ProjectPhase: C_ProjectPhaseInput
	ID: ID
	# Standard Project Type Task
	C_Task: C_TaskInput
	# The (legal) commitment amount
	CommittedAmt: Int
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: M_ProductInput
	# Alphanumeric identifier of the entity
	Name: String
	# Planned amount for this project
	PlannedAmt: Int
	# Invoice Rule for the project
	ProjInvoiceRule: AD_Ref_ListInput
	# Quantity
	Qty: Int
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
