# Generated Schema for C_Recurring_Run - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_Recurring_RunGet(page: Int, size: Int, sort: String, filter: String): C_Recurring_RunConnection!
}

extend type Mutation {
	C_Recurring_RunSave(entity: C_Recurring_RunInput!): C_Recurring_Run!
	C_Recurring_RunSaveMany(entities: [C_Recurring_RunInput!]!): [C_Recurring_Run!]!
	C_Recurring_RunDelete(uuids: [String!]!): Boolean!
}

type C_Recurring_RunConnection {
	results: [C_Recurring_Run!]!
	pagingInfo: PagingInfo!
}

type C_Recurring_Run {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Invoice Identifier
	C_Invoice: C_Invoice
	# Order
	C_Order: C_Order
	# Payment identifier
	C_Payment: C_Payment
	# Financial Project
	C_Project: C_Project
	# Recurring Document
	C_Recurring: C_Recurring!
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date of the Document
	DateDoc: Date
	# General Ledger Journal Batch
	GL_JournalBatch: GL_JournalBatch
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_Recurring_RunInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# Order
	C_Order: ForeignEntityInput
	# Payment identifier
	C_Payment: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Recurring Document
	C_Recurring: ForeignEntityInput
	UUID: ID
	# Date of the Document
	DateDoc: Date
	# General Ledger Journal Batch
	GL_JournalBatch: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
}
