# Generated Schema for C_Element - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_Element(UU: String!): C_Element
	C_ElementGet(Page: Int, Size: Int, Sort: String, Filter: String): C_ElementConnection!
}

extend type Mutation {
	C_ElementSave(Entity: C_ElementInput!): C_Element!
	C_ElementSaveMany(Entities: [C_ElementInput!]!): [C_Element!]!
	C_ElementDelete(UUs: [String!]!): Boolean!
}

type C_ElementConnection {
	Results: [C_Element!]!
	PagingInfo: PagingInfo!
}

type C_Element {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Identifies a Tree
	AD_Tree: AD_Tree!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Element Type (account or user defined)
	ElementType: AD_Ref_List!
	# The record is active in the system
	IsActive: Boolean!
	# All transactions within an element value must balance (e.g. cost centers)
	IsBalancing: Boolean!
	# The primary natural account
	IsNaturalAccount: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Format of the value; Can contain fixed format elements, Variables: "_lLoOaAcCa09", or ~regex
	VFormat: String
}

input C_ElementInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Identifies a Tree
	AD_Tree: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Element Type (account or user defined)
	ElementType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# All transactions within an element value must balance (e.g. cost centers)
	IsBalancing: Boolean
	# The primary natural account
	IsNaturalAccount: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Format of the value; Can contain fixed format elements, Variables: "_lLoOaAcCa09", or ~regex
	VFormat: String
}
