# Generated Schema for C_CashLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_CashLineGet(page: Int, size: Int, sort: String, filter: String): C_CashLineConnection!
}

extend type Mutation {
	C_CashLineSave(entity: C_CashLineInput!): C_CashLine!
	C_CashLineDelete(uuids: [String!]!): Boolean!
}

type C_CashLineConnection {
	results: [C_CashLine!]!
	pagingInfo: PagingInfo!
}

type C_CashLine {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Amount in a defined currency
	Amount: Int!
	# Account at the Bank
	C_BankAccount: C_BankAccount
	# Cash Journal
	C_Cash: C_Cash!
	ID: ID!
	# Additional document charges
	C_Charge: C_Charge
	# The Currency for this record
	C_Currency: C_Currency
	# Invoice Identifier
	C_Invoice: C_Invoice
	# Payment identifier
	C_Payment: C_Payment
	# Source of Cash
	CashType_RL: AD_Ref_List!
	# Date this record was created
	Created: Date!
	# User who created this records
	Create: AD_User!
	# Optional short description of the record
	Description: String
	# Calculated amount of discount
	DiscountAmt: Int
	# The record is active in the system
	IsActive: Boolean!
	# This Line is generated
	IsGenerated: Boolean!
	# Unique line for this document
	Line: Int!
	# The document has been processed
	Processed: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	Update: AD_User!
	# Amount to write-off
	WriteOffAmt: Int
}

input C_CashLineInput {
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Amount in a defined currency
	Amount: Int
	# Account at the Bank
	C_BankAccount: C_BankAccountInput
	# Cash Journal
	C_Cash: C_CashInput
	ID: ID
	# Additional document charges
	C_Charge: C_ChargeInput
	# The Currency for this record
	C_Currency: C_CurrencyInput
	# Invoice Identifier
	C_Invoice: C_InvoiceInput
	# Payment identifier
	C_Payment: C_PaymentInput
	# Source of Cash
	CashType_RL: AD_Ref_ListInput
	# Optional short description of the record
	Description: String
	# Calculated amount of discount
	DiscountAmt: Int
	# The record is active in the system
	IsActive: Boolean
	# This Line is generated
	IsGenerated: Boolean
	# Unique line for this document
	Line: Int
	# The document has been processed
	Processed: Boolean
	# Amount to write-off
	WriteOffAmt: Int
}
