# Generated Schema for C_Activity - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_Activity(UU: String!): C_Activity
	C_ActivityGet(Page: Int, Size: Int, Sort: String, Filter: String): C_ActivityConnection!
}

extend type Mutation {
	C_ActivitySave(Entity: C_ActivityInput!): C_Activity!
	C_ActivitySaveMany(Entities: [C_ActivityInput!]!): [C_Activity!]!
	C_ActivityDelete(UUs: [String!]!): Boolean!
}

type C_ActivityConnection {
	Results: [C_Activity!]!
	PagingInfo: PagingInfo!
}

type C_Activity {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# This is a summary entity
	IsSummary: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input C_ActivityInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# This is a summary entity
	IsSummary: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
