# Generated Schema for C_BankStatement - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_BankStatement(UU: String!): C_BankStatement
	C_BankStatementGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_BankStatementConnection!
}

extend type Mutation {
	C_BankStatementSave(Entity: C_BankStatementInput!): C_BankStatement!
	C_BankStatementSaveMany(Entities: [C_BankStatementInput!]!): [C_BankStatement!]!
	C_BankStatementDelete(UUs: [String!]!): Boolean!
}

type C_BankStatementConnection {
	Results: [C_BankStatement!]!
	PagingInfo: PagingInfo!
}

type C_BankStatement {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Balance prior to any transactions
	BeginningBalance: BigDecimal
	# Account at the Bank
	C_BankAccount: C_BankAccount!
	UU: ID!
	# Document type or rules
	C_DocType: C_DocType!
	# Copy From Record
	CopyFrom: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Process which will generate a new document lines based on an existing document
	CreateFrom: String
	CreateFromBatch: String
	# Accounting Date
	DateAcct: Date!
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: AD_Ref_List!
	# The current status of the document
	DocStatus: AD_Ref_List!
	# Document sequence number of the document
	DocumentNo: String!
	# Electronic Funds Transfer Statement Date
	EftStatementDate: Date
	# Electronic Funds Transfer Statement Reference
	EftStatementReference: String
	# Ending  or closing balance
	EndingBalance: BigDecimal!
	# The record is active in the system
	IsActive: Boolean!
	# Indicates if this document requires approval
	IsApproved: Boolean!
	# This is a manual process
	IsManual: Boolean!
	MatchStatement: String
	# Alphanumeric identifier of the entity
	Name: String!
	# Posting status
	Posted: Boolean!
	# The document has been processed
	Processed: Boolean!
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean!
	# Date of the statement
	StatementDate: Date!
	# Difference between statement ending balance and actual ending balance
	StatementDifference: BigDecimal
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_BankStatementInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Balance prior to any transactions
	BeginningBalance: BigDecimal
	# Account at the Bank
	C_BankAccount: ForeignEntityInput
	UU: ID
	# Document type or rules
	C_DocType: ForeignEntityInput
	# Copy From Record
	CopyFrom: String
	# Process which will generate a new document lines based on an existing document
	CreateFrom: String
	CreateFromBatch: String
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: ForeignEntityInput
	# The current status of the document
	DocStatus: ForeignEntityInput
	# Document sequence number of the document
	DocumentNo: String
	# Electronic Funds Transfer Statement Date
	EftStatementDate: Date
	# Electronic Funds Transfer Statement Reference
	EftStatementReference: String
	# Ending  or closing balance
	EndingBalance: BigDecimal
	# The record is active in the system
	IsActive: Boolean
	# Indicates if this document requires approval
	IsApproved: Boolean
	# This is a manual process
	IsManual: Boolean
	MatchStatement: String
	# Alphanumeric identifier of the entity
	Name: String
	# Posting status
	Posted: Boolean
	# The document has been processed
	Processed: Boolean
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean
	# Date of the statement
	StatementDate: Date
	# Difference between statement ending balance and actual ending balance
	StatementDifference: BigDecimal
}
