# Generated Schema for C_OrderLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_OrderLineGet(page: Int, size: Int, sort: String, filter: String): C_OrderLineConnection!
}

extend type Mutation {
	C_OrderLineSave(entity: C_OrderLineInput!): C_OrderLine!
	C_OrderLineDelete(uuids: [String!]!): Boolean!
}

type C_OrderLineConnection {
	results: [C_OrderLine!]!
	pagingInfo: PagingInfo!
}

type C_OrderLine {
	ID: ID!
}

input C_OrderLineInput {
	ID: ID
}
