# Generated Schema for C_InvoiceBatch - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_InvoiceBatchGet(Page: Int, Size: Int, Sort: String, Filter: String): C_InvoiceBatchConnection!
}

extend type Mutation {
	C_InvoiceBatchSave(Entity: C_InvoiceBatchInput!): C_InvoiceBatch!
	C_InvoiceBatchSaveMany(Entities: [C_InvoiceBatchInput!]!): [C_InvoiceBatch!]!
	C_InvoiceBatchDelete(UUs: [String!]!): Boolean!
}

type C_InvoiceBatchConnection {
	Results: [C_InvoiceBatch!]!
	PagingInfo: PagingInfo!
}

type C_InvoiceBatch {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Currency Conversion Rate Type
	C_ConversionType: C_ConversionType
	# The Currency for this record
	C_Currency: C_Currency!
	UU: ID!
	# If not zero, the Debit amount of the document must be equal this amount
	ControlAmt: BigDecimal!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date of the Document
	DateDoc: Date!
	# Optional short description of the record
	Description: String
	# Document Amount
	DocumentAmt: BigDecimal!
	# Document sequence number of the document
	DocumentNo: String!
	# The record is active in the system
	IsActive: Boolean!
	# This is a Sales Transaction
	IsSOTrx: Boolean!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Sales Representative or Company Agent
	SalesRep: AD_User!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_InvoiceBatchInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Currency Conversion Rate Type
	C_ConversionType: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	UU: ID
	# If not zero, the Debit amount of the document must be equal this amount
	ControlAmt: BigDecimal
	# Date of the Document
	DateDoc: Date
	# Optional short description of the record
	Description: String
	# Document Amount
	DocumentAmt: BigDecimal
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean
	# This is a Sales Transaction
	IsSOTrx: Boolean
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Sales Representative or Company Agent
	SalesRep: ForeignEntityInput
}
