# Generated Schema for C_LandedCostAllocation - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_LandedCostAllocationGet(page: Int, size: Int, sort: String, filter: String): C_LandedCostAllocationConnection!
}

extend type Mutation {
	C_LandedCostAllocationSave(entity: C_LandedCostAllocationInput!): C_LandedCostAllocation!
	C_LandedCostAllocationSaveMany(entities: [C_LandedCostAllocationInput!]!): [C_LandedCostAllocation!]!
	C_LandedCostAllocationDelete(uuids: [String!]!): Boolean!
}

type C_LandedCostAllocationConnection {
	results: [C_LandedCostAllocation!]!
	pagingInfo: PagingInfo!
}

type C_LandedCostAllocation {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Amount
	Amt: BigDecimal!
	# Calculation Base
	Base: BigDecimal!
	# Invoice Detail Line
	C_InvoiceLine: C_InvoiceLine!
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance
	# Product Cost Element
	M_CostElement: M_CostElement!
	# Line on Shipment or Receipt document
	M_InOutLine: M_InOutLine
	# Product, Service, Item
	M_Product: M_Product!
	# Quantity
	Qty: BigDecimal!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_LandedCostAllocationInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Amount
	Amt: BigDecimal
	# Calculation Base
	Base: BigDecimal
	# Invoice Detail Line
	C_InvoiceLine: ForeignEntityInput
	UUID: ID
	# Product Attribute Set Instance
	M_AttributeSetInstance: ForeignEntityInput
	# Product Cost Element
	M_CostElement: ForeignEntityInput
	# Line on Shipment or Receipt document
	M_InOutLine: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Quantity
	Qty: BigDecimal
}
