# Generated Schema for C_BankStatementMatcher - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_BankStatementMatcher(UU: String!): C_BankStatementMatcher
	C_BankStatementMatcherGet(Page: Int, Size: Int, Sort: String, Filter: String): C_BankStatementMatcherConnection!
}

extend type Mutation {
	C_BankStatementMatcherSave(Entity: C_BankStatementMatcherInput!): C_BankStatementMatcher!
	C_BankStatementMatcherSaveMany(Entities: [C_BankStatementMatcherInput!]!): [C_BankStatementMatcher!]!
	C_BankStatementMatcherDelete(UUs: [String!]!): Boolean!
}

type C_BankStatementMatcherConnection {
	Results: [C_BankStatementMatcher!]!
	PagingInfo: PagingInfo!
}

type C_BankStatementMatcher {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Java Classname
	Classname: String!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_BankStatementMatcherInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Java Classname
	Classname: String
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
