# Generated Schema for C_AddressValidationCfg - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_AddressValidationCfg(UU: String!): C_AddressValidationCfg
	C_AddressValidationCfgGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_AddressValidationCfgConnection!
}

extend type Mutation {
	C_AddressValidationCfgSave(Entity: C_AddressValidationCfgInput!): C_AddressValidationCfg!
	C_AddressValidationCfgSaveMany(Entities: [C_AddressValidationCfgInput!]!): [C_AddressValidationCfg!]!
	C_AddressValidationCfgDelete(UUs: [String!]!): Boolean!
}

type C_AddressValidationCfgConnection {
	Results: [C_AddressValidationCfg!]!
	PagingInfo: PagingInfo!
}

type C_AddressValidationCfg {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AddressValidationClass: String
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Host Address URL or DNS
	HostAddress: String!
	# Host Communication Port
	HostPort: Int!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	#  Address of your proxy server
	ProxyAddress: String
	# Logon of your proxy server
	ProxyLogon: String
	# Password of your proxy server
	ProxyPassword: String
	# Port of your proxy server
	ProxyPort: Int
	ServicePath: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_AddressValidationCfgInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AddressValidationClass: String
	UU: ID
	# Optional short description of the record
	Description: String
	# Host Address URL or DNS
	HostAddress: String
	# Host Communication Port
	HostPort: Int
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	#  Address of your proxy server
	ProxyAddress: String
	# Logon of your proxy server
	ProxyLogon: String
	# Password of your proxy server
	ProxyPassword: String
	# Port of your proxy server
	ProxyPort: Int
	ServicePath: String
}
