# Generated Schema for C_SubscriptionType - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_SubscriptionType(UU: String!): C_SubscriptionType
	C_SubscriptionTypeGet(Page: Int, Size: Int, Sort: String, Filter: String): C_SubscriptionTypeConnection!
}

extend type Mutation {
	C_SubscriptionTypeSave(Entity: C_SubscriptionTypeInput!): C_SubscriptionType!
	C_SubscriptionTypeSaveMany(Entities: [C_SubscriptionTypeInput!]!): [C_SubscriptionType!]!
	C_SubscriptionTypeDelete(UUs: [String!]!): Boolean!
}

type C_SubscriptionTypeConnection {
	Results: [C_SubscriptionType!]!
	PagingInfo: PagingInfo!
}

type C_SubscriptionType {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Frequency of events
	Frequency: Int!
	# Frequency of event
	FrequencyType: AD_Ref_List!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_SubscriptionTypeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Frequency of events
	Frequency: Int
	# Frequency of event
	FrequencyType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
