# Generated Schema for C_RfQResponse - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	C_RfQResponseGet(page: Int, size: Int, sort: String, filter: String): C_RfQResponseConnection!
}

extend type Mutation {
	C_RfQResponseSave(entity: C_RfQResponseInput!): C_RfQResponse!
	C_RfQResponseDelete(uuids: [String!]!): Boolean!
}

type C_RfQResponseConnection {
	results: [C_RfQResponse!]!
	pagingInfo: PagingInfo!
}

type C_RfQResponse {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: C_BPartner_Location!
	# The Currency for this record
	C_Currency: C_Currency!
	# Order
	C_Order: C_Order
	# Request for Quotation
	C_RfQ: C_RfQ!
	ID: ID!
	CheckComplete: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date when (last) invitation was sent
	DateInvited: Date
	# Date of the Response
	DateResponse: Date
	# Date when work is (planned to be) complete
	DateWorkComplete: Date
	# Date when work is (planned to be) started
	DateWorkStart: Date
	# Number of Days (planned) until Delivery
	DeliveryDays: Int
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# It is complete
	IsComplete: Boolean!
	# The response is the selected winner
	IsSelectedWinner: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Price
	Price: BigDecimal!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Relative Rank Number
	Ranking: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_RfQResponseInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Order
	C_Order: ForeignEntityInput
	# Request for Quotation
	C_RfQ: ForeignEntityInput
	ID: ID
	CheckComplete: String
	# Date when (last) invitation was sent
	DateInvited: Date
	# Date of the Response
	DateResponse: Date
	# Date when work is (planned to be) complete
	DateWorkComplete: Date
	# Date when work is (planned to be) started
	DateWorkStart: Date
	# Number of Days (planned) until Delivery
	DeliveryDays: Int
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# It is complete
	IsComplete: Boolean
	# The response is the selected winner
	IsSelectedWinner: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Price
	Price: BigDecimal
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Relative Rank Number
	Ranking: Int
}
