# Generated Schema for C_CountryGroupCountry - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_CountryGroupCountryGet(page: Int, size: Int, sort: String, filter: String): C_CountryGroupCountryConnection!
}

extend type Mutation {
	C_CountryGroupCountrySave(entity: C_CountryGroupCountryInput!): C_CountryGroupCountry!
	C_CountryGroupCountrySaveMany(entities: [C_CountryGroupCountryInput!]!): [C_CountryGroupCountry!]!
	C_CountryGroupCountryDelete(uuids: [String!]!): Boolean!
}

type C_CountryGroupCountryConnection {
	results: [C_CountryGroupCountry!]!
	pagingInfo: PagingInfo!
}

type C_CountryGroupCountry {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Country 
	C_Country: C_Country
	C_CountryGroup: C_CountryGroup
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Starting date for a range
	DateFrom: Date
	# End date of a date range
	DateTo: Date
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_CountryGroupCountryInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Country 
	C_Country: ForeignEntityInput
	C_CountryGroup: ForeignEntityInput
	UUID: ID
	# Starting date for a range
	DateFrom: Date
	# End date of a date range
	DateTo: Date
	# The record is active in the system
	IsActive: Boolean
}
