# Generated Schema for C_Invoice - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
#extend type Query {
#	C_InvoiceGet(page: Int, size: Int, sort: String, filter: String): C_InvoiceConnection!
#}

extend type Mutation {
	C_InvoiceSave(entity: C_InvoiceInput!): C_Invoice!
	C_InvoiceDelete(uuids: [String!]!): Boolean!
}

#type C_InvoiceConnection {
#	results: [C_Invoice!]!
#	pagingInfo: PagingInfo!
#}

type C_Invoice {
	ID: ID!
}

input C_InvoiceInput {
	ID: ID
}
