# Generated Schema for C_InvoiceBatchLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_InvoiceBatchLine(UU: String!): C_InvoiceBatchLine
	C_InvoiceBatchLineGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_InvoiceBatchLineConnection!
}

extend type Mutation {
	C_InvoiceBatchLineSave(Entity: C_InvoiceBatchLineInput!): C_InvoiceBatchLine!
	C_InvoiceBatchLineSaveMany(Entities: [C_InvoiceBatchLineInput!]!): [C_InvoiceBatchLine!]!
	C_InvoiceBatchLineDelete(UUs: [String!]!): Boolean!
}

type C_InvoiceBatchLineConnection {
	Results: [C_InvoiceBatchLine!]!
	PagingInfo: PagingInfo!
}

type C_InvoiceBatchLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Business Activity
	C_Activity: C_Activity
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: C_BPartner_Location!
	# Additional document charges
	C_Charge: C_Charge!
	# Document type or rules
	C_DocType: C_DocType!
	# Invoice Identifier
	C_Invoice: C_Invoice
	# Expense Invoice Batch Header
	C_InvoiceBatch: C_InvoiceBatch!
	UU: ID!
	# Invoice Detail Line
	C_InvoiceLine: C_InvoiceLine
	# Financial Project
	C_Project: C_Project
	# Tax identifier
	C_Tax: C_Tax!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date!
	# Date printed on Invoice
	DateInvoiced: Date!
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String!
	# The record is active in the system
	IsActive: Boolean!
	# Tax is included in the price 
	IsTaxIncluded: Boolean!
	# Unique line for this document
	Line: Int!
	# Line Extended Amount (Quantity * Actual Price) without Freight and Charges
	LineNetAmt: BigDecimal!
	# Total line amount incl. Tax
	LineTotalAmt: BigDecimal!
	# Price Entered - the price based on the selected/base UoM
	PriceEntered: BigDecimal!
	# The document has been processed
	Processed: Boolean!
	# The Quantity Entered is based on the selected UoM
	QtyEntered: BigDecimal!
	# Tax Amount for a document
	TaxAmt: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# User defined list element #1
	User1: C_ElementValue
	# User defined list element #2
	User2: C_ElementValue
}

input C_InvoiceBatchLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Business Activity
	C_Activity: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: ForeignEntityInput
	# Additional document charges
	C_Charge: ForeignEntityInput
	# Document type or rules
	C_DocType: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# Expense Invoice Batch Header
	C_InvoiceBatch: ForeignEntityInput
	UU: ID
	# Invoice Detail Line
	C_InvoiceLine: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Tax identifier
	C_Tax: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Date printed on Invoice
	DateInvoiced: Date
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean
	# Tax is included in the price 
	IsTaxIncluded: Boolean
	# Unique line for this document
	Line: Int
	# Line Extended Amount (Quantity * Actual Price) without Freight and Charges
	LineNetAmt: BigDecimal
	# Total line amount incl. Tax
	LineTotalAmt: BigDecimal
	# Price Entered - the price based on the selected/base UoM
	PriceEntered: BigDecimal
	# The document has been processed
	Processed: Boolean
	# The Quantity Entered is based on the selected UoM
	QtyEntered: BigDecimal
	# Tax Amount for a document
	TaxAmt: BigDecimal
	# User defined list element #1
	User1: ForeignEntityInput
	# User defined list element #2
	User2: ForeignEntityInput
}
