# Generated Schema for C_Region - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_Region(UU: String!): C_Region
	C_RegionGet(Page: Int, Size: Int, Sort: String, Filter: String): C_RegionConnection!
}

extend type Mutation {
	C_RegionSave(Entity: C_RegionInput!): C_Region!
	C_RegionSaveMany(Entities: [C_RegionInput!]!): [C_Region!]!
	C_RegionDelete(UUs: [String!]!): Boolean!
}

type C_RegionConnection {
	Results: [C_Region!]!
	PagingInfo: PagingInfo!
}

type C_Region {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Country 
	C_Country: C_Country!
	UU: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_RegionInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Country 
	C_Country: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
