# Generated Schema for C_ServiceLevel - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_ServiceLevel(UU: String!): C_ServiceLevel
	C_ServiceLevelGet(Page: Int, Size: Int, Sort: String, Filter: String): C_ServiceLevelConnection!
}

extend type Mutation {
	C_ServiceLevelSave(Entity: C_ServiceLevelInput!): C_ServiceLevel!
	C_ServiceLevelSaveMany(Entities: [C_ServiceLevelInput!]!): [C_ServiceLevel!]!
	C_ServiceLevelDelete(UUs: [String!]!): Boolean!
}

type C_ServiceLevelConnection {
	Results: [C_ServiceLevel!]!
	PagingInfo: PagingInfo!
}

type C_ServiceLevel {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Plan for recognizing or recording revenue
	C_RevenueRecognition_Plan: C_RevenueRecognition_Plan!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Quantity of product or service invoiced
	ServiceLevelInvoiced: BigDecimal!
	# Quantity of service or product provided
	ServiceLevelProvided: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_ServiceLevelInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Plan for recognizing or recording revenue
	C_RevenueRecognition_Plan: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Quantity of product or service invoiced
	ServiceLevelInvoiced: BigDecimal
	# Quantity of service or product provided
	ServiceLevelProvided: BigDecimal
}
