# Generated Schema for C_CashPlanLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_CashPlanLine(UU: String!): C_CashPlanLine
	C_CashPlanLineGet(Page: Int, Size: Int, Sort: String, Filter: String): C_CashPlanLineConnection!
}

extend type Mutation {
	C_CashPlanLineSave(Entity: C_CashPlanLineInput!): C_CashPlanLine!
	C_CashPlanLineSaveMany(Entities: [C_CashPlanLineInput!]!): [C_CashPlanLine!]!
	C_CashPlanLineDelete(UUs: [String!]!): Boolean!
}

type C_CashPlanLineConnection {
	Results: [C_CashPlanLine!]!
	PagingInfo: PagingInfo!
}

type C_CashPlanLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Business Activity
	C_Activity: C_Activity
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Marketing Campaign
	C_Campaign: C_Campaign
	C_CashPlan: C_CashPlan!
	UU: ID!
	# Additional document charges
	C_Charge: C_Charge
	# Financial Project
	C_Project: C_Project
	# Phase of a Project
	C_ProjectPhase: C_ProjectPhase
	# Actual Project Task in a Phase
	C_ProjectTask: C_ProjectTask
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Transaction Date
	DateTrx: Date!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Unique line for this document
	Line: Int!
	# Total line amount incl. Tax
	LineTotalAmt: BigDecimal
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String
	Probability: BigDecimal
	# The document has been processed
	Processed: Boolean!
	# The Quantity Entered is based on the selected UoM
	QtyEntered: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# User defined list element #1
	User1: C_ElementValue
	# User defined list element #2
	User2: C_ElementValue
}

input C_CashPlanLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Business Activity
	C_Activity: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Marketing Campaign
	C_Campaign: ForeignEntityInput
	C_CashPlan: ForeignEntityInput
	UU: ID
	# Additional document charges
	C_Charge: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Phase of a Project
	C_ProjectPhase: ForeignEntityInput
	# Actual Project Task in a Phase
	C_ProjectTask: ForeignEntityInput
	# Transaction Date
	DateTrx: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Unique line for this document
	Line: Int
	# Total line amount incl. Tax
	LineTotalAmt: BigDecimal
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	Probability: BigDecimal
	# The document has been processed
	Processed: Boolean
	# The Quantity Entered is based on the selected UoM
	QtyEntered: BigDecimal
	# User defined list element #1
	User1: ForeignEntityInput
	# User defined list element #2
	User2: ForeignEntityInput
}
