# Generated Schema for C_PaySelectionLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	C_PaySelectionLineGet(page: Int, size: Int, sort: String, filter: String): C_PaySelectionLineConnection!
}

extend type Mutation {
	C_PaySelectionLineSave(entity: C_PaySelectionLineInput!): C_PaySelectionLine!
	C_PaySelectionLineSaveMany(entities: [C_PaySelectionLineInput!]!): [C_PaySelectionLine!]!
	C_PaySelectionLineDelete(uuids: [String!]!): Boolean!
}

type C_PaySelectionLineConnection {
	results: [C_PaySelectionLine!]!
	pagingInfo: PagingInfo!
}

type C_PaySelectionLine {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Invoice Identifier
	C_Invoice: C_Invoice!
	# Payment Selection
	C_PaySelection: C_PaySelection!
	# Payment Selection Check
	C_PaySelectionCheck: C_PaySelectionCheck
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Difference Amount
	DifferenceAmt: BigDecimal!
	# Calculated amount of discount
	DiscountAmt: BigDecimal!
	# The record is active in the system
	IsActive: Boolean!
	# This is a manual process
	IsManual: Boolean!
	# This is a Sales Transaction
	IsSOTrx: Boolean!
	# Unique line for this document
	Line: Int!
	# Open item amount
	OpenAmt: BigDecimal!
	# Amount being paid
	PayAmt: BigDecimal!
	# How you pay the invoice
	PaymentRule: AD_Ref_List!
	# The document has been processed
	Processed: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Amount to write-off
	WriteOffAmt: BigDecimal!
}

input C_PaySelectionLineInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# Payment Selection
	C_PaySelection: ForeignEntityInput
	# Payment Selection Check
	C_PaySelectionCheck: ForeignEntityInput
	UUID: ID
	# Optional short description of the record
	Description: String
	# Difference Amount
	DifferenceAmt: BigDecimal
	# Calculated amount of discount
	DiscountAmt: BigDecimal
	# The record is active in the system
	IsActive: Boolean
	# This is a manual process
	IsManual: Boolean
	# This is a Sales Transaction
	IsSOTrx: Boolean
	# Unique line for this document
	Line: Int
	# Open item amount
	OpenAmt: BigDecimal
	# Amount being paid
	PayAmt: BigDecimal
	# How you pay the invoice
	PaymentRule: AD_Ref_ListInput
	# The document has been processed
	Processed: Boolean
	# Amount to write-off
	WriteOffAmt: BigDecimal
}
