# Generated Schema for C_AddressValidationCfg - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_AddressValidationCfgGet(page: Int, size: Int, sort: String, filter: String): C_AddressValidationCfgConnection!
}

type C_AddressValidationCfgConnection {
	results: [C_AddressValidationCfg!]!
	pagingInfo: PagingInfo!
}

type C_AddressValidationCfg {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	AddressValidationClass: String
	ID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Host Address URL or DNS
	HostAddress: String!
	# Host Communication Port
	HostPort: Int!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	#  Address of your proxy server
	ProxyAddress: String
	# Logon of your proxy server
	ProxyLogon: String
	# Password of your proxy server
	ProxyPassword: String
	# Port of your proxy server
	ProxyPort: Int
	ServicePath: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

