# Generated Schema for C_CommissionDetail - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_CommissionDetail(UU: String!): C_CommissionDetail
	C_CommissionDetailGet(Page: Int, Size: Int, Sort: String, Filter: String): C_CommissionDetailConnection!
}

extend type Mutation {
	C_CommissionDetailSave(Entity: C_CommissionDetailInput!): C_CommissionDetail!
	C_CommissionDetailSaveMany(Entities: [C_CommissionDetailInput!]!): [C_CommissionDetail!]!
	C_CommissionDetailDelete(UUs: [String!]!): Boolean!
}

type C_CommissionDetailConnection {
	Results: [C_CommissionDetail!]!
	PagingInfo: PagingInfo!
}

type C_CommissionDetail {
	# The actual amount
	ActualAmt: BigDecimal!
	# The actual quantity
	ActualQty: BigDecimal!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Generated Commission Amount 
	C_CommissionAmt: C_CommissionAmt!
	UU: ID!
	# The Currency for this record
	C_Currency: C_Currency!
	# Invoice Detail Line
	C_InvoiceLine: C_InvoiceLine
	# Sales Order Line
	C_OrderLine: C_OrderLine
	# Converted Amount
	ConvertedAmt: BigDecimal!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Information
	Info: String
	# The record is active in the system
	IsActive: Boolean!
	# Reference for this record
	Reference: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_CommissionDetailInput {
	# The actual amount
	ActualAmt: BigDecimal
	# The actual quantity
	ActualQty: BigDecimal
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Generated Commission Amount 
	C_CommissionAmt: ForeignEntityInput
	UU: ID
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Invoice Detail Line
	C_InvoiceLine: ForeignEntityInput
	# Sales Order Line
	C_OrderLine: ForeignEntityInput
	# Converted Amount
	ConvertedAmt: BigDecimal
	# Information
	Info: String
	# The record is active in the system
	IsActive: Boolean
	# Reference for this record
	Reference: String
}
