# Generated Schema for C_Phase - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_PhaseGet(Page: Int, Size: Int, Sort: String, Filter: String): C_PhaseConnection!
}

extend type Mutation {
	C_PhaseSave(Entity: C_PhaseInput!): C_Phase!
	C_PhaseSaveMany(Entities: [C_PhaseInput!]!): [C_Phase!]!
	C_PhaseDelete(UUs: [String!]!): Boolean!
}

type C_PhaseConnection {
	Results: [C_Phase!]!
	PagingInfo: PagingInfo!
}

type C_Phase {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Type of the project
	C_ProjectType: C_ProjectType!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Standard Quantity
	StandardQty: BigDecimal!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_PhaseInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Type of the project
	C_ProjectType: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Standard Quantity
	StandardQty: BigDecimal
}
