# Generated Schema for C_Calendar - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_Calendar(UU: String!): C_Calendar
	C_CalendarGet(Page: Int, Size: Int, Sort: String, Filter: String): C_CalendarConnection!
}

extend type Mutation {
	C_CalendarSave(Entity: C_CalendarInput!): C_Calendar!
	C_CalendarSaveMany(Entities: [C_CalendarInput!]!): [C_Calendar!]!
	C_CalendarDelete(UUs: [String!]!): Boolean!
}

type C_CalendarConnection {
	Results: [C_Calendar!]!
	PagingInfo: PagingInfo!
}

type C_Calendar {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_CalendarInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
