# Generated Schema for C_BPartner - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
#extend type Query {
#	C_BPartnerGet(page: Int, size: Int, sort: String, filter: String): C_BPartnerConnection!
#}

extend type Mutation {
	C_BPartnerSave(entity: C_BPartnerInput!): C_BPartner!
	C_BPartnerDelete(uuids: [String!]!): Boolean!
}

#type C_BPartnerConnection {
#	results: [C_BPartner!]!
#	pagingInfo: PagingInfo!
#}

type C_BPartner {
	ID: ID!
}

input C_BPartnerInput {
	ID: ID
}
