# Generated Schema for C_TaxProvider - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_TaxProviderGet(page: Int, size: Int, sort: String, filter: String): C_TaxProviderConnection!
}

extend type Mutation {
	C_TaxProviderSave(entity: C_TaxProviderInput!): C_TaxProvider!
	C_TaxProviderDelete(uuids: [String!]!): Boolean!
}

type C_TaxProviderConnection {
	results: [C_TaxProvider!]!
	pagingInfo: PagingInfo!
}

type C_TaxProvider {
	Account: String
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	ID: ID!
	C_TaxProviderCfg: C_TaxProviderCfg!
	CompanyCode: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	License: String
	# Alphanumeric identifier of the entity
	Name: String!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	ValidateConnection: String
}

input C_TaxProviderInput {
	Account: String
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ID: ID
	C_TaxProviderCfg: ForeignEntityInput
	CompanyCode: String
	# The record is active in the system
	IsActive: Boolean
	License: String
	# Alphanumeric identifier of the entity
	Name: String
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	ValidateConnection: String
}
