# Generated Schema for C_Payment - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
#extend type Query {
#	C_PaymentGet(page: Int, size: Int, sort: String, filter: String): C_PaymentConnection!
#}

extend type Mutation {
	C_PaymentSave(entity: C_PaymentInput!): C_Payment!
	C_PaymentDelete(uuids: [String!]!): Boolean!
}

#type C_PaymentConnection {
#	results: [C_Payment!]!
#	pagingInfo: PagingInfo!
#}

type C_Payment {
	ID: ID!
}

input C_PaymentInput {
	ID: ID
}
