# Generated Schema for C_InvoiceLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_InvoiceLineGet(page: Int, size: Int, sort: String, filter: String): C_InvoiceLineConnection!
}

type C_InvoiceLineConnection {
	results: [C_InvoiceLine!]!
	pagingInfo: PagingInfo!
}

type C_InvoiceLine {
	# Group of Assets
	A_Asset_Group: A_Asset_Group
	# Asset used internally or by customers
	A_Asset: A_Asset
	A_CapvsExp: AD_Ref_List
	A_CreateAsset: Boolean!
	A_Processed: Boolean!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Element to allow buttons to be displayed that trigger tab navigation
	BH_NavButtons: Object
	C_1099Box: C_1099Box
	# Business Activity
	C_Activity: C_Activity
	# Marketing Campaign
	C_Campaign: C_Campaign
	# Additional document charges
	C_Charge: C_Charge
	# Invoice Identifier
	C_Invoice: C_Invoice!
	ID: ID!
	# Sales Order Line
	C_OrderLine: C_OrderLine
	# Financial Project
	C_Project: C_Project
	# Phase of a Project
	C_ProjectPhase: C_ProjectPhase
	# Actual Project Task in a Phase
	C_ProjectTask: C_ProjectTask
	# Tax identifier
	C_Tax: C_Tax!
	# Unit of Measure
	C_UOM: C_UOM
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# if true, the line is just description and no transaction
	IsDescription: Boolean!
	IsFixedAssetInvoice: Boolean!
	# Indicates if this document / line is printed
	IsPrinted: Boolean!
	# Unique line for this document
	Line: Int!
	# Line Extended Amount (Quantity * Actual Price) without Freight and Charges
	LineNetAmt: Int!
	# Total line amount incl. Tax
	LineTotalAmt: Int
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance!
	# Line on Shipment or Receipt document
	M_InOutLine: M_InOutLine
	# Product, Service, Item
	M_Product: M_Product
	# Return Material Authorization Line
	M_RMALine: M_RMALine
	# Actual Price 
	PriceActual: Int!
	# Price Entered - the price based on the selected/base UoM
	PriceEntered: Int!
	# Lowest price for a product
	PriceLimit: Int!
	# List Price
	PriceList: Int!
	# The document has been processed
	Processed: Boolean!
	# The Quantity Entered is based on the selected UoM
	QtyEntered: Int!
	# Invoiced Quantity
	QtyInvoiced: Int!
	# Revenue Recognition Amount
	RRAmt: Int
	# Revenue Recognition Start Date
	RRStartDate: Date
	# Resource Assignment
	S_ResourceAssignment: S_ResourceAssignment
	# Tax Amount for a document
	TaxAmt: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# User defined list element #1
	User1: C_ElementValue
	# User defined list element #2
	User2: C_ElementValue
}

