# Generated Schema for C_RevenueRecognition_Plan - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_RevenueRecognition_Plan(UU: String!): C_RevenueRecognition_Plan
	C_RevenueRecognition_PlanGet(Page: Int, Size: Int, Sort: String, Filter: String): C_RevenueRecognition_PlanConnection!
}

extend type Mutation {
	C_RevenueRecognition_PlanSave(Entity: C_RevenueRecognition_PlanInput!): C_RevenueRecognition_Plan!
	C_RevenueRecognition_PlanSaveMany(Entities: [C_RevenueRecognition_PlanInput!]!): [C_RevenueRecognition_Plan!]!
	C_RevenueRecognition_PlanDelete(UUs: [String!]!): Boolean!
}

type C_RevenueRecognition_PlanConnection {
	Results: [C_RevenueRecognition_Plan!]!
	PagingInfo: PagingInfo!
}

type C_RevenueRecognition_Plan {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema!
	# The Currency for this record
	C_Currency: C_Currency!
	# Invoice Detail Line
	C_InvoiceLine: C_InvoiceLine!
	# Method for recording revenue
	C_RevenueRecognition: C_RevenueRecognition!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Account for Product Revenue (Sales Account)
	P_Revenue_A: C_ValidCombination!
	RecognizedAmt: BigDecimal!
	# Total Amount
	TotalAmt: BigDecimal!
	# Account for unearned revenue
	UnEarnedRevenue_A: C_ValidCombination!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_RevenueRecognition_PlanInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Invoice Detail Line
	C_InvoiceLine: ForeignEntityInput
	# Method for recording revenue
	C_RevenueRecognition: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Account for Product Revenue (Sales Account)
	P_Revenue_A: ForeignEntityInput
	RecognizedAmt: BigDecimal
	# Total Amount
	TotalAmt: BigDecimal
	# Account for unearned revenue
	UnEarnedRevenue_A: ForeignEntityInput
}
