# Generated Schema for C_Invoice - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_InvoiceGet(page: Int, size: Int, sort: String, filter: String): C_InvoiceConnection!
}

extend type Mutation {
	C_InvoiceSave(entity: C_InvoiceInput!): C_Invoice!
	C_InvoiceSaveMany(entities: [C_InvoiceInput!]!): [C_Invoice!]!
	C_InvoiceDelete(uuids: [String!]!): Boolean!
}

type C_InvoiceConnection {
	results: [C_Invoice!]!
	pagingInfo: PagingInfo!
}

type C_Invoice {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Element to allow buttons to be displayed that trigger tab navigation
	BH_NavButtons: Object
	BH_Visit: BH_Visit
	BH_Voided_Reason: BH_Voided_Reason
	# Business Activity
	C_Activity: C_Activity
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: C_BPartner_Location!
	# Marketing Campaign
	C_Campaign: C_Campaign
	# Cash Journal Line
	C_CashLine: C_CashLine
	C_CashPlanLine: C_CashPlanLine
	# Additional document charges
	C_Charge: C_Charge
	# Currency Conversion Rate Type
	C_ConversionType: C_ConversionType
	# The Currency for this record
	C_Currency: C_Currency!
	# Document type or rules
	C_DocType: C_DocType!
	# Target document type for conversing documents
	C_DocTypeTarget: C_DocType!
	C_DunningLevel: C_DunningLevel
	UUID: ID!
	# Order
	C_Order: C_Order
	# Payment identifier
	C_Payment: C_Payment
	# The terms of Payment (timing, discount)
	C_PaymentTerm: C_PaymentTerm!
	# Financial Project
	C_Project: C_Project
	# Charge Amount
	ChargeAmt: BigDecimal
	# Copy From Record
	CopyFrom: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Process which will generate a new document lines based on an existing document
	CreateFrom: String
	# Currency Conversion Rate
	CurrencyRate: BigDecimal
	# Accounting Date
	DateAcct: Date!
	# Date printed on Invoice
	DateInvoiced: Date!
	# Date of Order
	DateOrdered: Date
	# Date the document was printed.
	DatePrinted: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: AD_Ref_List!
	# The current status of the document
	DocStatus: AD_Ref_List!
	# Document sequence number of the document
	DocumentNo: String!
	DunningGrace: Date
	# Generate To
	GenerateTo: String
	# Total amount of document
	GrandTotal: BigDecimal!
	# Invoice Collection Status
	InvoiceCollectionType: AD_Ref_List
	# The record is active in the system
	IsActive: Boolean!
	# Indicates if this document requires approval
	IsApproved: Boolean!
	# Print Discount on Invoice and Order
	IsDiscountPrinted: Boolean!
	IsFixedAssetInvoice: Boolean!
	# Document is in dispute
	IsInDispute: Boolean!
	# Override Currency Conversion Rate
	IsOverrideCurrencyRate: Boolean!
	# The document is paid
	IsPaid: Boolean!
	# Is the Payment Schedule is valid
	IsPayScheduleValid: Boolean!
	# Indicates if this document / line is printed
	IsPrinted: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	# This is a Sales Transaction
	IsSOTrx: Boolean!
	# Tax is included in the price 
	IsTaxIncluded: Boolean!
	# Transferred to General Ledger (i.e. accounted)
	IsTransferred: Boolean!
	# Unique identifier of a Price List
	M_PriceList: M_PriceList!
	# Return Material Authorization
	M_RMA: M_RMA
	# How you pay the invoice
	PaymentRule: String!
	# Transaction Reference Number (Sales Order, Purchase Order) of your Business Partner
	POReference: String
	# Posting status
	Posted: Boolean!
	# The document has been processed
	Processed: Boolean!
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean!
	RelatedInvoice: C_Invoice
	# ID of document reversal
	Reversal: C_Invoice
	# Sales Representative or Company Agent
	SalesRep: AD_User
	# Enable sending Document EMail
	SendEMail: Boolean!
	# Total of all document lines
	TotalLines: BigDecimal!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# User defined list element #1
	User1: C_ElementValue
	# User defined list element #2
	User2: C_ElementValue
}

input C_InvoiceInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Element to allow buttons to be displayed that trigger tab navigation
	BH_NavButtons: Object
	BH_Visit: ForeignEntityInput
	BH_Voided_Reason: ForeignEntityInput
	# Business Activity
	C_Activity: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: ForeignEntityInput
	# Marketing Campaign
	C_Campaign: ForeignEntityInput
	# Cash Journal Line
	C_CashLine: ForeignEntityInput
	C_CashPlanLine: ForeignEntityInput
	# Additional document charges
	C_Charge: ForeignEntityInput
	# Currency Conversion Rate Type
	C_ConversionType: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Document type or rules
	C_DocType: ForeignEntityInput
	# Target document type for conversing documents
	C_DocTypeTarget: ForeignEntityInput
	C_DunningLevel: ForeignEntityInput
	UUID: ID
	# Order
	C_Order: ForeignEntityInput
	# Payment identifier
	C_Payment: ForeignEntityInput
	# The terms of Payment (timing, discount)
	C_PaymentTerm: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Charge Amount
	ChargeAmt: BigDecimal
	# Copy From Record
	CopyFrom: String
	# Process which will generate a new document lines based on an existing document
	CreateFrom: String
	# Currency Conversion Rate
	CurrencyRate: BigDecimal
	# Accounting Date
	DateAcct: Date
	# Date printed on Invoice
	DateInvoiced: Date
	# Date of Order
	DateOrdered: Date
	# Date the document was printed.
	DatePrinted: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: AD_Ref_ListInput
	# The current status of the document
	DocStatus: AD_Ref_ListInput
	# Document sequence number of the document
	DocumentNo: String
	DunningGrace: Date
	# Generate To
	GenerateTo: String
	# Total amount of document
	GrandTotal: BigDecimal
	# Invoice Collection Status
	InvoiceCollectionType: AD_Ref_ListInput
	# The record is active in the system
	IsActive: Boolean
	# Indicates if this document requires approval
	IsApproved: Boolean
	# Print Discount on Invoice and Order
	IsDiscountPrinted: Boolean
	IsFixedAssetInvoice: Boolean
	# Document is in dispute
	IsInDispute: Boolean
	# Override Currency Conversion Rate
	IsOverrideCurrencyRate: Boolean
	# The document is paid
	IsPaid: Boolean
	# Is the Payment Schedule is valid
	IsPayScheduleValid: Boolean
	# Indicates if this document / line is printed
	IsPrinted: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	# This is a Sales Transaction
	IsSOTrx: Boolean
	# Tax is included in the price 
	IsTaxIncluded: Boolean
	# Transferred to General Ledger (i.e. accounted)
	IsTransferred: Boolean
	# Unique identifier of a Price List
	M_PriceList: ForeignEntityInput
	# Return Material Authorization
	M_RMA: ForeignEntityInput
	# How you pay the invoice
	PaymentRule: String
	# Transaction Reference Number (Sales Order, Purchase Order) of your Business Partner
	POReference: String
	# Posting status
	Posted: Boolean
	# The document has been processed
	Processed: Boolean
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean
	RelatedInvoice: ForeignEntityInput
	# ID of document reversal
	Reversal: ForeignEntityInput
	# Sales Representative or Company Agent
	SalesRep: ForeignEntityInput
	# Enable sending Document EMail
	SendEMail: Boolean
	# Total of all document lines
	TotalLines: BigDecimal
	# User defined list element #1
	User1: ForeignEntityInput
	# User defined list element #2
	User2: ForeignEntityInput
}
