# Generated Schema for C_POS - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	C_POS(UU: String!): C_POS
	C_POSGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): C_POSConnection!
}

extend type Mutation {
	C_POSSave(Entity: C_POSInput!): C_POS!
	C_POSSaveMany(Entities: [C_POSInput!]!): [C_POS!]!
	C_POSDelete(UUs: [String!]!): Boolean!
}

type C_POSConnection {
	Results: [C_POS!]!
	PagingInfo: PagingInfo!
}

type C_POS {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Automatically logout if terminal inactive for this period
	AutoLogoutDelay: Int
	# Account at the Bank
	C_BankAccount: C_BankAccount
	# Business Partner used for creating new Business Partners on the fly
	C_BPartnerCashTrx: C_BPartner
	# Cash Book for recording petty cash transactions
	C_CashBook: C_CashBook
	# Document type or rules
	C_DocType: C_DocType
	UU: ID!
	# POS Function Key Layout
	C_POSKeyLayout: C_POSKeyLayout
	CashDrawer: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Allow modifying the price
	IsModifyPrice: Boolean!
	# Unique identifier of a Price List
	M_PriceList: M_PriceList!
	# Storage Warehouse and Service Point
	M_Warehouse: M_Warehouse!
	# Alphanumeric identifier of the entity
	Name: String!
	# The key layout to use for on screen keyboard for text fields.
	OSK_KeyLayout: C_POSKeyLayout
	# The key layout to use for on screen number pad for numeric fields.
	OSNP_KeyLayout: C_POSKeyLayout
	# Name of the Printer
	PrinterName: String
	# Sales Representative or Company Agent
	SalesRep: AD_User!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_POSInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Automatically logout if terminal inactive for this period
	AutoLogoutDelay: Int
	# Account at the Bank
	C_BankAccount: ForeignEntityInput
	# Business Partner used for creating new Business Partners on the fly
	C_BPartnerCashTrx: ForeignEntityInput
	# Cash Book for recording petty cash transactions
	C_CashBook: ForeignEntityInput
	# Document type or rules
	C_DocType: ForeignEntityInput
	UU: ID
	# POS Function Key Layout
	C_POSKeyLayout: ForeignEntityInput
	CashDrawer: String
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Allow modifying the price
	IsModifyPrice: Boolean
	# Unique identifier of a Price List
	M_PriceList: ForeignEntityInput
	# Storage Warehouse and Service Point
	M_Warehouse: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# The key layout to use for on screen keyboard for text fields.
	OSK_KeyLayout: ForeignEntityInput
	# The key layout to use for on screen number pad for numeric fields.
	OSNP_KeyLayout: ForeignEntityInput
	# Name of the Printer
	PrinterName: String
	# Sales Representative or Company Agent
	SalesRep: ForeignEntityInput
}
