# Generated Schema for C_BankAccount_Acct - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_BankAccount_Acct(UU: String!): C_BankAccount_Acct
	C_BankAccount_AcctGet(Page: Int, Size: Int, Sort: String, Filter: String): C_BankAccount_AcctConnection!
}

extend type Mutation {
	C_BankAccount_AcctSave(Entity: C_BankAccount_AcctInput!): C_BankAccount_Acct!
	C_BankAccount_AcctSaveMany(Entities: [C_BankAccount_AcctInput!]!): [C_BankAccount_Acct!]!
	C_BankAccount_AcctDelete(UUs: [String!]!): Boolean!
}

type C_BankAccount_AcctConnection {
	Results: [C_BankAccount_Acct!]!
	PagingInfo: PagingInfo!
}

type C_BankAccount_Acct {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Bank Asset Account
	B_Asset_A: C_ValidCombination!
	# Bank Interest Expense Account
	B_InterestExp_A: C_ValidCombination!
	# Bank Interest Revenue Account
	B_InterestRev_A: C_ValidCombination!
	# Bank In Transit Account
	B_InTransit_A: C_ValidCombination!
	# AP Payment Selection Clearing Account
	B_PaymentSelect_A: C_ValidCombination!
	# Unallocated Cash Clearing Account
	B_UnallocatedCash_A: C_ValidCombination!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema!
	UU: ID!
	# Account at the Bank
	C_BankAccount: C_BankAccount!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_BankAccount_AcctInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Bank Asset Account
	B_Asset_A: ForeignEntityInput
	# Bank Interest Expense Account
	B_InterestExp_A: ForeignEntityInput
	# Bank Interest Revenue Account
	B_InterestRev_A: ForeignEntityInput
	# Bank In Transit Account
	B_InTransit_A: ForeignEntityInput
	# AP Payment Selection Clearing Account
	B_PaymentSelect_A: ForeignEntityInput
	# Unallocated Cash Clearing Account
	B_UnallocatedCash_A: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	UU: ID
	# Account at the Bank
	C_BankAccount: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
}
