# Generated Schema for C_DunningRun - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	C_DunningRunGet(page: Int, size: Int, sort: String, filter: String): C_DunningRunConnection!
}

extend type Mutation {
	C_DunningRunSave(entity: C_DunningRunInput!): C_DunningRun!
	C_DunningRunSaveMany(entities: [C_DunningRunInput!]!): [C_DunningRun!]!
	C_DunningRunDelete(uuids: [String!]!): Boolean!
}

type C_DunningRunConnection {
	results: [C_DunningRun!]!
	pagingInfo: PagingInfo!
}

type C_DunningRun {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Dunning Rules for overdue invoices
	C_Dunning: C_Dunning!
	C_DunningLevel: C_DunningLevel
	UUID: ID!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Date of Dunning
	DunningDate: Date!
	# The record is active in the system
	IsActive: Boolean!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	SendIt: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input C_DunningRunInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Dunning Rules for overdue invoices
	C_Dunning: ForeignEntityInput
	C_DunningLevel: ForeignEntityInput
	UUID: ID
	# Optional short description of the record
	Description: String
	# Date of Dunning
	DunningDate: Date
	# The record is active in the system
	IsActive: Boolean
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	SendIt: String
}
