# Generated Schema for C_BP_Vendor_Acct - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	C_BP_Vendor_AcctGet(page: Int, size: Int, sort: String, filter: String): C_BP_Vendor_AcctConnection!
}

extend type Mutation {
	C_BP_Vendor_AcctSave(entity: C_BP_Vendor_AcctInput!): C_BP_Vendor_Acct!
	C_BP_Vendor_AcctSaveMany(entities: [C_BP_Vendor_AcctInput!]!): [C_BP_Vendor_Acct!]!
	C_BP_Vendor_AcctDelete(uuids: [String!]!): Boolean!
}

type C_BP_Vendor_AcctConnection {
	results: [C_BP_Vendor_Acct!]!
	pagingInfo: PagingInfo!
}

type C_BP_Vendor_Acct {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema!
	UUID: ID!
	C_BP_Vendor_Acct_UU: String
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Account for Vendor Liability
	V_Liability_A: C_ValidCombination!
	# Account for Vendor Service Liability
	V_Liability_Services_A: C_ValidCombination
	# Account for Vendor Prepayments
	V_Prepayment_A: C_ValidCombination!
}

input C_BP_Vendor_AcctInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	UUID: ID
	C_BP_Vendor_Acct_UU: String
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Account for Vendor Liability
	V_Liability_A: ForeignEntityInput
	# Account for Vendor Service Liability
	V_Liability_Services_A: ForeignEntityInput
	# Account for Vendor Prepayments
	V_Prepayment_A: ForeignEntityInput
}
