# Generated Schema for C_TaxType - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	C_TaxType(UU: String!): C_TaxType
	C_TaxTypeGet(Page: Int, Size: Int, Sort: String, Filter: String): C_TaxTypeConnection!
}

extend type Mutation {
	C_TaxTypeSave(Entity: C_TaxTypeInput!): C_TaxType!
	C_TaxTypeSaveMany(Entities: [C_TaxTypeInput!]!): [C_TaxType!]!
	C_TaxTypeDelete(UUs: [String!]!): Boolean!
}

type C_TaxTypeConnection {
	Results: [C_TaxType!]!
	PagingInfo: PagingInfo!
}

type C_TaxType {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	UU: ID!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input C_TaxTypeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	UU: ID
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
