# Generated Schema for CM_Chat - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	CM_ChatGet(page: Int, size: Int, sort: String, filter: String): CM_ChatConnection!
}

extend type Mutation {
	CM_ChatSave(entity: CM_ChatInput!): CM_Chat!
	CM_ChatSaveMany(entities: [CM_ChatInput!]!): [CM_Chat!]!
	CM_ChatDelete(uuids: [String!]!): Boolean!
}

type CM_ChatConnection {
	results: [CM_Chat!]!
	pagingInfo: PagingInfo!
}

type CM_Chat {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table!
	UUID: ID!
	# Type of discussion / chat
	CM_ChatType: CM_ChatType
	# Type of Confidentiality
	ConfidentialType: AD_Ref_List!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String!
	# The record is active in the system
	IsActive: Boolean!
	# Type of moderation
	ModerationType: AD_Ref_List
	# Direct internal record ID
	Record_ID: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input CM_ChatInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	UUID: ID
	# Type of discussion / chat
	CM_ChatType: ForeignEntityInput
	# Type of Confidentiality
	ConfidentialType: AD_Ref_ListInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Type of moderation
	ModerationType: AD_Ref_ListInput
	# Direct internal record ID
	Record_ID: Int
}
