# Generated Schema for EXP_Processor - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	EXP_Processor(UU: String!): EXP_Processor
	EXP_ProcessorGet(Page: Int, Size: Int, Sort: String, Filter: String): EXP_ProcessorConnection!
}

extend type Mutation {
	EXP_ProcessorSave(Entity: EXP_ProcessorInput!): EXP_Processor!
	EXP_ProcessorSaveMany(Entities: [EXP_ProcessorInput!]!): [EXP_Processor!]!
	EXP_ProcessorDelete(UUs: [String!]!): Boolean!
}

type EXP_ProcessorConnection {
	Results: [EXP_Processor!]!
	PagingInfo: PagingInfo!
}

type EXP_Processor {
	Account: String
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	EXP_Processor_Type: EXP_Processor_Type!
	UU: ID!
	# Comment or Hint
	Help: String
	Host: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	PasswordInfo: String
	Port: Int
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input EXP_ProcessorInput {
	Account: String
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	EXP_Processor_Type: ForeignEntityInput
	UU: ID
	# Comment or Hint
	Help: String
	Host: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	PasswordInfo: String
	Port: Int
	# Search key for the record in the format required - must be unique
	Value: String
}
