# Generated Schema for EXP_Format - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	EXP_FormatGet(Page: Int, Size: Int, Sort: String, Filter: String): EXP_FormatConnection!
}

extend type Mutation {
	EXP_FormatSave(Entity: EXP_FormatInput!): EXP_Format!
	EXP_FormatSaveMany(Entities: [EXP_FormatInput!]!): [EXP_Format!]!
	EXP_FormatDelete(UUs: [String!]!): Boolean!
}

type EXP_FormatConnection {
	Results: [EXP_Format!]!
	PagingInfo: PagingInfo!
}

type EXP_Format {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	UU: ID!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	TestExportModel: String
	TestImportModel: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
	# Version of the table definition
	Version: String!
	# Fully qualified SQL WHERE clause
	WhereClause: String
}

input EXP_FormatInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Optional short description of the record
	Description: String
	UU: ID
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	TestExportModel: String
	TestImportModel: String
	# Search key for the record in the format required - must be unique
	Value: String
	# Version of the table definition
	Version: String
	# Fully qualified SQL WHERE clause
	WhereClause: String
}
