# Generated Schema for GL_FundRestriction - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	GL_FundRestrictionGet(page: Int, size: Int, sort: String, filter: String): GL_FundRestrictionConnection!
}

extend type Mutation {
	GL_FundRestrictionSave(entity: GL_FundRestrictionInput!): GL_FundRestriction!
	GL_FundRestrictionSaveMany(entities: [GL_FundRestrictionInput!]!): [GL_FundRestriction!]!
	GL_FundRestrictionDelete(uuids: [String!]!): Boolean!
}

type GL_FundRestrictionConnection {
	results: [GL_FundRestriction!]!
	pagingInfo: PagingInfo!
}

type GL_FundRestriction {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Account Element
	C_ElementValue: C_ElementValue!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# General Ledger Funds Control
	GL_Fund: GL_Fund!
	UUID: ID!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input GL_FundRestrictionInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Account Element
	C_ElementValue: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# General Ledger Funds Control
	GL_Fund: ForeignEntityInput
	UUID: ID
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
}
