# Generated Schema for GL_JournalGeneratorSource - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	GL_JournalGeneratorSource(UU: String!): GL_JournalGeneratorSource
	GL_JournalGeneratorSourceGet(Page: Int, Size: Int, Sort: String, Filter: String): GL_JournalGeneratorSourceConnection!
}

extend type Mutation {
	GL_JournalGeneratorSourceSave(Entity: GL_JournalGeneratorSourceInput!): GL_JournalGeneratorSource!
	GL_JournalGeneratorSourceSaveMany(Entities: [GL_JournalGeneratorSourceInput!]!): [GL_JournalGeneratorSource!]!
	GL_JournalGeneratorSourceDelete(UUs: [String!]!): Boolean!
}

type GL_JournalGeneratorSourceConnection {
	Results: [GL_JournalGeneratorSource!]!
	PagingInfo: PagingInfo!
}

type GL_JournalGeneratorSource {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Multiplier Amount for generating commissions
	AmtMultiplier: BigDecimal!
	# Account Element
	C_ElementValue: C_ElementValue!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# General Ledger Category
	GL_Category: GL_Category
	GL_JournalGeneratorLine: GL_JournalGeneratorLine!
	UU: ID!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	RoundFactor: Int
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input GL_JournalGeneratorSourceInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Multiplier Amount for generating commissions
	AmtMultiplier: BigDecimal
	# Account Element
	C_ElementValue: ForeignEntityInput
	# General Ledger Category
	GL_Category: ForeignEntityInput
	GL_JournalGeneratorLine: ForeignEntityInput
	UU: ID
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	RoundFactor: Int
}
