# Generated Schema for GL_DistributionLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	GL_DistributionLine(UU: String!): GL_DistributionLine
	GL_DistributionLineGet(Page: Int, Size: Int, Sort: String, Filter: String): GL_DistributionLineConnection!
}

extend type Mutation {
	GL_DistributionLineSave(Entity: GL_DistributionLineInput!): GL_DistributionLine!
	GL_DistributionLineSaveMany(Entities: [GL_DistributionLineInput!]!): [GL_DistributionLine!]!
	GL_DistributionLineDelete(UUs: [String!]!): Boolean!
}

type GL_DistributionLineConnection {
	Results: [GL_DistributionLine!]!
	PagingInfo: PagingInfo!
}

type GL_DistributionLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Business Activity
	C_Activity: C_Activity
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Marketing Campaign
	C_Campaign: C_Campaign
	# Location that inventory was moved from
	C_LocFrom: C_Location
	# Location that inventory was moved to
	C_LocTo: C_Location
	# Financial Project
	C_Project: C_Project
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Sales coverage region
	C_SalesRegion: C_SalesRegion
	# Optional short description of the record
	Description: String
	# General Ledger Distribution
	GL_Distribution: GL_Distribution!
	UU: ID!
	# The record is active in the system
	IsActive: Boolean!
	# Unique line for this document
	Line: Int!
	# Product, Service, Item
	M_Product: M_Product
	# Overwrite the account segment Account with the value specified
	OverwriteAcct: Boolean!
	# Overwrite the account segment Activity with the value specified
	OverwriteActivity: Boolean!
	# Overwrite the account segment Business Partner with the value specified
	OverwriteBPartner: Boolean!
	# Overwrite the account segment Campaign with the value specified
	OverwriteCampaign: Boolean!
	# Overwrite the account segment Location From with the value specified
	OverwriteLocFrom: Boolean!
	# Overwrite the account segment Location From with the value specified
	OverwriteLocTo: Boolean!
	# Overwrite the account segment Organization with the value specified
	OverwriteOrg: Boolean!
	# Overwrite the account segment Transaction Organization with the value specified
	OverwriteOrgTrx: Boolean!
	# Overwrite the account segment Product with the value specified
	OverwriteProduct: Boolean!
	# Overwrite the account segment Project with the value specified
	OverwriteProject: Boolean!
	# Overwrite the account segment Sales Region with the value specified
	OverwriteSalesRegion: Boolean!
	# Overwrite the account segment User 1 with the value specified
	OverwriteUser1: Boolean!
	# Overwrite the account segment User 2 with the value specified
	OverwriteUser2: Boolean!
	# Percentage
	Percent: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# User defined list element #1
	User1: C_ElementValue
	# User defined list element #2
	User2: C_ElementValue
}

input GL_DistributionLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Business Activity
	C_Activity: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Marketing Campaign
	C_Campaign: ForeignEntityInput
	# Location that inventory was moved from
	C_LocFrom: ForeignEntityInput
	# Location that inventory was moved to
	C_LocTo: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Sales coverage region
	C_SalesRegion: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# General Ledger Distribution
	GL_Distribution: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Unique line for this document
	Line: Int
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Overwrite the account segment Account with the value specified
	OverwriteAcct: Boolean
	# Overwrite the account segment Activity with the value specified
	OverwriteActivity: Boolean
	# Overwrite the account segment Business Partner with the value specified
	OverwriteBPartner: Boolean
	# Overwrite the account segment Campaign with the value specified
	OverwriteCampaign: Boolean
	# Overwrite the account segment Location From with the value specified
	OverwriteLocFrom: Boolean
	# Overwrite the account segment Location From with the value specified
	OverwriteLocTo: Boolean
	# Overwrite the account segment Organization with the value specified
	OverwriteOrg: Boolean
	# Overwrite the account segment Transaction Organization with the value specified
	OverwriteOrgTrx: Boolean
	# Overwrite the account segment Product with the value specified
	OverwriteProduct: Boolean
	# Overwrite the account segment Project with the value specified
	OverwriteProject: Boolean
	# Overwrite the account segment Sales Region with the value specified
	OverwriteSalesRegion: Boolean
	# Overwrite the account segment User 1 with the value specified
	OverwriteUser1: Boolean
	# Overwrite the account segment User 2 with the value specified
	OverwriteUser2: Boolean
	# Percentage
	Percent: BigDecimal
	# User defined list element #1
	User1: ForeignEntityInput
	# User defined list element #2
	User2: ForeignEntityInput
}
