# Generated Schema for GL_Journal - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	GL_Journal(UU: String!): GL_Journal
	GL_JournalGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): GL_JournalConnection!
}

extend type Mutation {
	GL_JournalSave(Entity: GL_JournalInput!): GL_Journal!
	GL_JournalSaveMany(Entities: [GL_JournalInput!]!): [GL_Journal!]!
	GL_JournalDelete(UUs: [String!]!): Boolean!
}

type GL_JournalConnection {
	Results: [GL_Journal!]!
	PagingInfo: PagingInfo!
}

type GL_Journal {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema!
	# Currency Conversion Rate Type
	C_ConversionType: C_ConversionType!
	# The Currency for this record
	C_Currency: C_Currency!
	# Document type or rules
	C_DocType: C_DocType!
	# Period of the Calendar
	C_Period: C_Period!
	# If not zero, the Debit amount of the document must be equal this amount
	ControlAmt: BigDecimal
	# Copy From Record
	CopyFrom: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Currency Conversion Rate
	CurrencyRate: BigDecimal!
	# Accounting Date
	DateAcct: Date!
	# Date of the Document
	DateDoc: Date!
	# Optional short description of the record
	Description: String!
	# The targeted status of the document
	DocAction: AD_Ref_List!
	# The current status of the document
	DocStatus: AD_Ref_List!
	# Document sequence number of the document
	DocumentNo: String!
	# General Ledger Budget
	GL_Budget: GL_Budget
	# General Ledger Category
	GL_Category: GL_Category!
	UU: ID!
	# General Ledger Journal Batch
	GL_JournalBatch: GL_JournalBatch
	# The record is active in the system
	IsActive: Boolean!
	# Indicates if this document requires approval
	IsApproved: Boolean!
	# Indicates if this document / line is printed
	IsPrinted: Boolean!
	# Posting status
	Posted: Boolean!
	# The type of posted amount for the transaction
	PostingType: AD_Ref_List!
	# The document has been processed
	Processed: Boolean!
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean!
	# ID of document reversal
	Reversal: GL_Journal
	# Total Credit in document currency
	TotalCr: BigDecimal!
	# Total debit in document currency
	TotalDr: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input GL_JournalInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# Currency Conversion Rate Type
	C_ConversionType: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Document type or rules
	C_DocType: ForeignEntityInput
	# Period of the Calendar
	C_Period: ForeignEntityInput
	# If not zero, the Debit amount of the document must be equal this amount
	ControlAmt: BigDecimal
	# Copy From Record
	CopyFrom: String
	# Currency Conversion Rate
	CurrencyRate: BigDecimal
	# Accounting Date
	DateAcct: Date
	# Date of the Document
	DateDoc: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: ForeignEntityInput
	# The current status of the document
	DocStatus: ForeignEntityInput
	# Document sequence number of the document
	DocumentNo: String
	# General Ledger Budget
	GL_Budget: ForeignEntityInput
	# General Ledger Category
	GL_Category: ForeignEntityInput
	UU: ID
	# General Ledger Journal Batch
	GL_JournalBatch: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Indicates if this document requires approval
	IsApproved: Boolean
	# Indicates if this document / line is printed
	IsPrinted: Boolean
	# Posting status
	Posted: Boolean
	# The type of posted amount for the transaction
	PostingType: ForeignEntityInput
	# The document has been processed
	Processed: Boolean
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean
	# ID of document reversal
	Reversal: ForeignEntityInput
	# Total Credit in document currency
	TotalCr: BigDecimal
	# Total debit in document currency
	TotalDr: BigDecimal
}
