# Generated Schema for GL_JournalLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	GL_JournalLine(UU: String!): GL_JournalLine
	GL_JournalLineGet(Page: Int, Size: Int, Sort: String, Filter: String): GL_JournalLineConnection!
}

extend type Mutation {
	GL_JournalLineSave(Entity: GL_JournalLineInput!): GL_JournalLine!
	GL_JournalLineSaveMany(Entities: [GL_JournalLineInput!]!): [GL_JournalLine!]!
	GL_JournalLineDelete(UUs: [String!]!): Boolean!
}

type GL_JournalLineConnection {
	Results: [GL_JournalLine!]!
	PagingInfo: PagingInfo!
}

type GL_JournalLine {
	# Group of Assets
	A_Asset_Group: A_Asset_Group
	# Asset used internally or by customers
	A_Asset: A_Asset
	A_CreateAsset: Boolean!
	A_Processed: Boolean!
	# Account used
	Account: C_ElementValue
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Valid Account Alias List
	Alias_ValidCombination: C_ValidCombination
	# Accounted Credit Amount
	AmtAcctCr: BigDecimal!
	# Accounted Debit Amount
	AmtAcctDr: BigDecimal!
	# Source Credit Amount
	AmtSourceCr: BigDecimal!
	# Source Debit Amount
	AmtSourceDr: BigDecimal!
	# Business Activity
	C_Activity: C_Activity
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Marketing Campaign
	C_Campaign: C_Campaign
	# Currency Conversion Rate Type
	C_ConversionType: C_ConversionType!
	# The Currency for this record
	C_Currency: C_Currency!
	# Location that inventory was moved from
	C_LocFrom: C_Location
	# Location that inventory was moved to
	C_LocTo: C_Location
	# Financial Project
	C_Project: C_Project
	# Sales coverage region
	C_SalesRegion: C_SalesRegion
	# Sub account for Element Value
	C_SubAcct: C_SubAcct
	# Unit of Measure
	C_UOM: C_UOM
	# Valid Account Combination
	C_ValidCombination: C_ValidCombination
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Currency Conversion Rate
	CurrencyRate: BigDecimal!
	# Accounting Date
	DateAcct: Date!
	# Optional short description of the record
	Description: String
	# General Ledger Journal
	GL_Journal: GL_Journal!
	UU: ID!
	# The record is active in the system
	IsActive: Boolean!
	# This Line is generated
	IsGenerated: Boolean!
	# Unique line for this document
	Line: Int!
	# Product, Service, Item
	M_Product: M_Product
	# The document has been processed
	Processed: Boolean!
	# Quantity
	Qty: BigDecimal
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# User defined list element #1
	User1: C_ElementValue
	# User defined list element #2
	User2: C_ElementValue
}

input GL_JournalLineInput {
	# Group of Assets
	A_Asset_Group: ForeignEntityInput
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	A_CreateAsset: Boolean
	A_Processed: Boolean
	# Account used
	Account: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Valid Account Alias List
	Alias_ValidCombination: ForeignEntityInput
	# Accounted Credit Amount
	AmtAcctCr: BigDecimal
	# Accounted Debit Amount
	AmtAcctDr: BigDecimal
	# Source Credit Amount
	AmtSourceCr: BigDecimal
	# Source Debit Amount
	AmtSourceDr: BigDecimal
	# Business Activity
	C_Activity: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Marketing Campaign
	C_Campaign: ForeignEntityInput
	# Currency Conversion Rate Type
	C_ConversionType: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Location that inventory was moved from
	C_LocFrom: ForeignEntityInput
	# Location that inventory was moved to
	C_LocTo: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Sales coverage region
	C_SalesRegion: ForeignEntityInput
	# Sub account for Element Value
	C_SubAcct: ForeignEntityInput
	# Unit of Measure
	C_UOM: ForeignEntityInput
	# Valid Account Combination
	C_ValidCombination: ForeignEntityInput
	# Currency Conversion Rate
	CurrencyRate: BigDecimal
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# General Ledger Journal
	GL_Journal: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# This Line is generated
	IsGenerated: Boolean
	# Unique line for this document
	Line: Int
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# The document has been processed
	Processed: Boolean
	# Quantity
	Qty: BigDecimal
	# User defined list element #1
	User1: ForeignEntityInput
	# User defined list element #2
	User2: ForeignEntityInput
}
