# Generated Schema for HR_Job - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	HR_Job(UU: String!): HR_Job
	HR_JobGet(Page: Int, Size: Int, Sort: String, Filter: String): HR_JobConnection!
}

extend type Mutation {
	HR_JobSave(Entity: HR_JobInput!): HR_Job!
	HR_JobSaveMany(Entities: [HR_JobInput!]!): [HR_Job!]!
	HR_JobDelete(UUs: [String!]!): Boolean!
}

type HR_JobConnection {
	Results: [HR_Job!]!
	PagingInfo: PagingInfo!
}

type HR_Job {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	HR_Department: HR_Department
	UU: ID!
	# The record is active in the system
	IsActive: Boolean!
	# This column is a link to the parent table (e.g. header from lines) - incl. Association key columns
	IsParent: Boolean!
	JobCant: Int
	# Alphanumeric identifier of the entity
	Name: String!
	Next_Job: HR_Job
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: AD_User
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String
}

input HR_JobInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	HR_Department: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# This column is a link to the parent table (e.g. header from lines) - incl. Association key columns
	IsParent: Boolean
	JobCant: Int
	# Alphanumeric identifier of the entity
	Name: String
	Next_Job: ForeignEntityInput
	# Supervisor for this user/organization - used for escalation and approval
	Supervisor: ForeignEntityInput
	# Search key for the record in the format required - must be unique
	Value: String
}
