# Generated Schema for HR_Period - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	HR_Period(UU: String!): HR_Period
	HR_PeriodGet(Page: Int, Size: Int, Sort: String, Filter: String): HR_PeriodConnection!
}

extend type Mutation {
	HR_PeriodSave(Entity: HR_PeriodInput!): HR_Period!
	HR_PeriodSaveMany(Entities: [HR_PeriodInput!]!): [HR_Period!]!
	HR_PeriodDelete(UUs: [String!]!): Boolean!
}

type HR_PeriodConnection {
	Results: [HR_Period!]!
	PagingInfo: PagingInfo!
}

type HR_Period {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Period of the Calendar
	C_Period: C_Period!
	# Calendar Year
	C_Year: C_Year!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date!
	# Optional short description of the record
	Description: String
	# Last effective date (inclusive)
	EndDate: Date
	HR_Payroll: HR_Payroll!
	UU: ID!
	HR_Year: HR_Year
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Action taken for this period
	PeriodAction: String
	# Unique Period Number
	PeriodNo: Int!
	# Current state of this period
	PeriodStatus: String
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# First effective day (inclusive)
	StartDate: Date!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input HR_PeriodInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Period of the Calendar
	C_Period: ForeignEntityInput
	# Calendar Year
	C_Year: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# Last effective date (inclusive)
	EndDate: Date
	HR_Payroll: ForeignEntityInput
	UU: ID
	HR_Year: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Action taken for this period
	PeriodAction: String
	# Unique Period Number
	PeriodNo: Int
	# Current state of this period
	PeriodStatus: String
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# First effective day (inclusive)
	StartDate: Date
}
