# Generated Schema for I_FixedAsset - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	I_FixedAsset(UU: String!): I_FixedAsset
	I_FixedAssetGet(Page: Int, Size: Int, Sort: String, Filter: String): I_FixedAssetConnection!
}

extend type Mutation {
	I_FixedAssetSave(Entity: I_FixedAssetInput!): I_FixedAsset!
	I_FixedAssetSaveMany(Entities: [I_FixedAssetInput!]!): [I_FixedAsset!]!
	I_FixedAssetDelete(UUs: [String!]!): Boolean!
}

type I_FixedAssetConnection {
	Results: [I_FixedAsset!]!
	PagingInfo: PagingInfo!
}

type I_FixedAsset {
	A_Accumulated_Depr: BigDecimal
	A_Accumulated_Depr_F: BigDecimal
	A_Asset_Class: A_Asset_Class
	A_Asset_Class_Value: String
	A_Asset_Cost: BigDecimal!
	# Group of Assets
	A_Asset_Group: A_Asset_Group
	A_Asset_Group_Value: String
	# Asset used internally or by customers
	A_Asset: A_Asset
	A_Asset_Type: A_Asset_Type
	A_Asset_Type_Value: String
	A_Current_Period: Int
	A_Remaining_Period: Int!
	A_Salvage_Value: BigDecimal
	# Name of the Accounting Schema
	AcctSchemaName: String
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	AssetAmtEntered: BigDecimal!
	# Date of last depreciation
	AssetDepreciationDate: Date
	# Applies to Straight Line depreciation
	AssetPeriodDepreciationAmt: BigDecimal!
	# Date when Asset was put into service
	AssetServiceDate: Date
	AssetSourceAmt: BigDecimal!
	# The Key of the Business Partner
	BPartner_Value: String
	# Rules for accounting
	C_AcctSchema: C_AcctSchema
	# Business Partner (Agent or Sales Rep)
	C_BPartnerSR: C_BPartner
	# City
	C_City: C_City
	C_City_Value: String
	# The Currency for this record
	C_Currency: C_Currency
	# Unit of Measure
	C_UOM: C_UOM
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: AD_Ref_List!
	# Messages generated from import process
	I_ErrorMsg: String
	UU: ID!
	# Has this import been processed
	I_IsImported: Boolean!
	InventoryNo: String
	# The record is active in the system
	IsActive: Boolean!
	# Three letter ISO 4217 Code of the Currency
	ISO_Code: String
	# Key of the Warehouse Locator
	LocatorValue: String
	# Warehouse Locator
	M_Locator: M_Locator
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Key of the Product
	ProductValue: String
	# Quantity
	Qty: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Symbol for a Unit of Measure
	UOMSymbol: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Months of the usable life of the asset
	UseLifeMonths: Int
	UseLifeMonths_F: Int
}

input I_FixedAssetInput {
	A_Accumulated_Depr: BigDecimal
	A_Accumulated_Depr_F: BigDecimal
	A_Asset_Class: ForeignEntityInput
	A_Asset_Class_Value: String
	A_Asset_Cost: BigDecimal
	# Group of Assets
	A_Asset_Group: ForeignEntityInput
	A_Asset_Group_Value: String
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	A_Asset_Type: ForeignEntityInput
	A_Asset_Type_Value: String
	A_Current_Period: Int
	A_Remaining_Period: Int
	A_Salvage_Value: BigDecimal
	# Name of the Accounting Schema
	AcctSchemaName: String
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	AssetAmtEntered: BigDecimal
	# Date of last depreciation
	AssetDepreciationDate: Date
	# Applies to Straight Line depreciation
	AssetPeriodDepreciationAmt: BigDecimal
	# Date when Asset was put into service
	AssetServiceDate: Date
	AssetSourceAmt: BigDecimal
	# The Key of the Business Partner
	BPartner_Value: String
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# Business Partner (Agent or Sales Rep)
	C_BPartnerSR: ForeignEntityInput
	# City
	C_City: ForeignEntityInput
	C_City_Value: String
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Unit of Measure
	C_UOM: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: ForeignEntityInput
	# Messages generated from import process
	I_ErrorMsg: String
	UU: ID
	# Has this import been processed
	I_IsImported: Boolean
	InventoryNo: String
	# The record is active in the system
	IsActive: Boolean
	# Three letter ISO 4217 Code of the Currency
	ISO_Code: String
	# Key of the Warehouse Locator
	LocatorValue: String
	# Warehouse Locator
	M_Locator: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Key of the Product
	ProductValue: String
	# Quantity
	Qty: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Symbol for a Unit of Measure
	UOMSymbol: String
	# Months of the usable life of the asset
	UseLifeMonths: Int
	UseLifeMonths_F: Int
}
