# Generated Schema for I_BankStatement - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	I_BankStatement(UU: String!): I_BankStatement
	I_BankStatementGet(Page: Int, Size: Int, Sort: String, Filter: String): I_BankStatementConnection!
}

extend type Mutation {
	I_BankStatementSave(Entity: I_BankStatementInput!): I_BankStatement!
	I_BankStatementSaveMany(Entities: [I_BankStatementInput!]!): [I_BankStatement!]!
	I_BankStatementDelete(UUs: [String!]!): Boolean!
}

type I_BankStatementConnection {
	Results: [I_BankStatement!]!
	PagingInfo: PagingInfo!
}

type I_BankStatement {
	# Tenant for this installation.
	AD_Client: AD_Client
	# Organizational entity within tenant
	AD_Org: AD_Org
	# Bank Account Number
	BankAccountNo: String
	# Key of the Business Partner
	BPartnerValue: String
	# Account at the Bank
	C_BankAccount: C_BankAccount
	# Bank Statement of account
	C_BankStatement: C_BankStatement
	# Line on a statement from this Bank
	C_BankStatementLine: C_BankStatementLine
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Additional document charges
	C_Charge: C_Charge
	# The Currency for this record
	C_Currency: C_Currency
	# Invoice Identifier
	C_Invoice: C_Invoice
	# Payment identifier
	C_Payment: C_Payment
	# Charge Amount
	ChargeAmt: BigDecimal
	# Name of the Charge
	ChargeName: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User
	CreatePayment: String
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# Electronic Funds Transfer Amount
	EftAmt: BigDecimal
	# Electronic Funds Transfer Check No
	EftCheckNo: String
	# Electronic Funds Transfer Currency
	EftCurrency: String
	# Electronic Funds Transfer Memo
	EftMemo: String
	# Electronic Funds Transfer Payee information
	EftPayee: String
	# Electronic Funds Transfer Payee Account Information
	EftPayeeAccount: String
	# Electronic Funds Transfer Reference
	EftReference: String
	# Electronic Funds Transfer Statement Date
	EftStatementDate: Date
	# Electronic Funds Transfer Statement Line Date
	EftStatementLineDate: Date
	# Electronic Funds Transfer Statement Reference
	EftStatementReference: String
	# Electronic Funds Transfer Transaction ID
	EftTrxID: String
	# Electronic Funds Transfer Transaction Type
	EftTrxType: String
	# Electronic Funds Transfer Valuta (effective) Date
	EftValutaDate: Date
	UU: ID!
	# Messages generated from import process
	I_ErrorMsg: String
	# Has this import been processed
	I_IsImported: Boolean!
	# International Bank Account Number
	IBAN: String
	# Interest Amount
	InterestAmt: BigDecimal
	# Document Number of the Invoice
	InvoiceDocumentNo: String
	# The record is active in the system
	IsActive: Boolean!
	# Three letter ISO 4217 Code of the Currency
	ISO_Code: String
	# This is a reversing transaction
	IsReversal: Boolean!
	# Unique line for this document
	Line: Int
	# Description of the Line
	LineDescription: String
	MatchStatement: String
	# Memo Text
	Memo: String
	# Alphanumeric identifier of the entity
	Name: String
	# Document number of the Payment
	PaymentDocumentNo: String
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Your customer or vendor number at the Business Partner's site
	ReferenceNo: String
	# Bank Routing Number
	RoutingNo: String
	# Date of the statement
	StatementDate: Date
	# Date of the Statement Line
	StatementLineDate: Date
	# Statement Amount
	StmtAmt: BigDecimal
	# Amount of a transaction
	TrxAmt: BigDecimal
	# Type of credit card transaction
	TrxType: AD_Ref_List
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User
	# Date when money is available
	ValutaDate: Date
}

input I_BankStatementInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Bank Account Number
	BankAccountNo: String
	# Key of the Business Partner
	BPartnerValue: String
	# Account at the Bank
	C_BankAccount: ForeignEntityInput
	# Bank Statement of account
	C_BankStatement: ForeignEntityInput
	# Line on a statement from this Bank
	C_BankStatementLine: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Additional document charges
	C_Charge: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# Payment identifier
	C_Payment: ForeignEntityInput
	# Charge Amount
	ChargeAmt: BigDecimal
	# Name of the Charge
	ChargeName: String
	CreatePayment: String
	# Accounting Date
	DateAcct: Date
	# Optional short description of the record
	Description: String
	# Electronic Funds Transfer Amount
	EftAmt: BigDecimal
	# Electronic Funds Transfer Check No
	EftCheckNo: String
	# Electronic Funds Transfer Currency
	EftCurrency: String
	# Electronic Funds Transfer Memo
	EftMemo: String
	# Electronic Funds Transfer Payee information
	EftPayee: String
	# Electronic Funds Transfer Payee Account Information
	EftPayeeAccount: String
	# Electronic Funds Transfer Reference
	EftReference: String
	# Electronic Funds Transfer Statement Date
	EftStatementDate: Date
	# Electronic Funds Transfer Statement Line Date
	EftStatementLineDate: Date
	# Electronic Funds Transfer Statement Reference
	EftStatementReference: String
	# Electronic Funds Transfer Transaction ID
	EftTrxID: String
	# Electronic Funds Transfer Transaction Type
	EftTrxType: String
	# Electronic Funds Transfer Valuta (effective) Date
	EftValutaDate: Date
	UU: ID
	# Messages generated from import process
	I_ErrorMsg: String
	# Has this import been processed
	I_IsImported: Boolean
	# International Bank Account Number
	IBAN: String
	# Interest Amount
	InterestAmt: BigDecimal
	# Document Number of the Invoice
	InvoiceDocumentNo: String
	# The record is active in the system
	IsActive: Boolean
	# Three letter ISO 4217 Code of the Currency
	ISO_Code: String
	# This is a reversing transaction
	IsReversal: Boolean
	# Unique line for this document
	Line: Int
	# Description of the Line
	LineDescription: String
	MatchStatement: String
	# Memo Text
	Memo: String
	# Alphanumeric identifier of the entity
	Name: String
	# Document number of the Payment
	PaymentDocumentNo: String
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Your customer or vendor number at the Business Partner's site
	ReferenceNo: String
	# Bank Routing Number
	RoutingNo: String
	# Date of the statement
	StatementDate: Date
	# Date of the Statement Line
	StatementLineDate: Date
	# Statement Amount
	StmtAmt: BigDecimal
	# Amount of a transaction
	TrxAmt: BigDecimal
	# Type of credit card transaction
	TrxType: ForeignEntityInput
	# Date when money is available
	ValutaDate: Date
}
