# Generated Schema for IMP_ProcessorParameter - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	IMP_ProcessorParameter(UU: String!): IMP_ProcessorParameter
	IMP_ProcessorParameterGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): IMP_ProcessorParameterConnection!
}

extend type Mutation {
	IMP_ProcessorParameterSave(Entity: IMP_ProcessorParameterInput!): IMP_ProcessorParameter!
	IMP_ProcessorParameterSaveMany(Entities: [IMP_ProcessorParameterInput!]!): [IMP_ProcessorParameter!]!
	IMP_ProcessorParameterDelete(UUs: [String!]!): Boolean!
}

type IMP_ProcessorParameterConnection {
	Results: [IMP_ProcessorParameter!]!
	PagingInfo: PagingInfo!
}

type IMP_ProcessorParameter {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	IMP_Processor: IMP_Processor!
	UU: ID!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	ParameterValue: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input IMP_ProcessorParameterInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	IMP_Processor: ForeignEntityInput
	UU: ID
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	ParameterValue: String
	# Search key for the record in the format required - must be unique
	Value: String
}
