# Generated Schema for IMP_ProcessorLog - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	IMP_ProcessorLogGet(page: Int, size: Int, sort: String, filter: String): IMP_ProcessorLogConnection!
}

extend type Mutation {
	IMP_ProcessorLogSave(entity: IMP_ProcessorLogInput!): IMP_ProcessorLog!
	IMP_ProcessorLogSaveMany(entities: [IMP_ProcessorLogInput!]!): [IMP_ProcessorLog!]!
	IMP_ProcessorLogDelete(uuids: [String!]!): Boolean!
}

type IMP_ProcessorLogConnection {
	results: [IMP_ProcessorLog!]!
	pagingInfo: PagingInfo!
}

type IMP_ProcessorLog {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Binary Data
	BinaryData: Binary
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	IMP_Processor: IMP_Processor!
	UUID: ID!
	# The record is active in the system
	IsActive: Boolean!
	# An Error occurred in the execution
	IsError: Boolean!
	# Reference for this record
	Reference: String
	# Textual summary of this request
	Summary: String
	# Text Message
	TextMsg: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input IMP_ProcessorLogInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Binary Data
	BinaryData: Binary
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	IMP_Processor: ForeignEntityInput
	UUID: ID
	# The record is active in the system
	IsActive: Boolean
	# An Error occurred in the execution
	IsError: Boolean
	# Reference for this record
	Reference: String
	# Textual summary of this request
	Summary: String
	# Text Message
	TextMsg: String
}
