# Generated Schema for M_PromotionGroupLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_PromotionGroupLine(UU: String!): M_PromotionGroupLine
	M_PromotionGroupLineGet(Page: Int, Size: Int, Sort: String, Filter: String): M_PromotionGroupLineConnection!
}

extend type Mutation {
	M_PromotionGroupLineSave(Entity: M_PromotionGroupLineInput!): M_PromotionGroupLine!
	M_PromotionGroupLineSaveMany(Entities: [M_PromotionGroupLineInput!]!): [M_PromotionGroupLine!]!
	M_PromotionGroupLineDelete(UUs: [String!]!): Boolean!
}

type M_PromotionGroupLineConnection {
	Results: [M_PromotionGroupLine!]!
	PagingInfo: PagingInfo!
}

type M_PromotionGroupLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	M_PromotionGroup: M_PromotionGroup!
	UU: ID!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_PromotionGroupLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	M_PromotionGroup: ForeignEntityInput
	UU: ID
}
