# Generated Schema for M_Product_QualityTest - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	M_Product_QualityTestGet(page: Int, size: Int, sort: String, filter: String): M_Product_QualityTestConnection!
}

extend type Mutation {
	M_Product_QualityTestSave(entity: M_Product_QualityTestInput!): M_Product_QualityTest!
	M_Product_QualityTestDelete(uuids: [String!]!): Boolean!
}

type M_Product_QualityTestConnection {
	results: [M_Product_QualityTest!]!
	pagingInfo: PagingInfo!
}

type M_Product_QualityTest {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	ExpectedResult: String!
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	ID: ID!
	M_QualityTest: M_QualityTest!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_Product_QualityTestInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	ExpectedResult: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	ID: ID
	M_QualityTest: ForeignEntityInput
}
