# Generated Schema for M_ShipperPickupTypes - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_ShipperPickupTypes(UU: String!): M_ShipperPickupTypes
	M_ShipperPickupTypesGet(Page: Int, Size: Int, Sort: String, Filter: String): M_ShipperPickupTypesConnection!
}

extend type Mutation {
	M_ShipperPickupTypesSave(Entity: M_ShipperPickupTypesInput!): M_ShipperPickupTypes!
	M_ShipperPickupTypesSaveMany(Entities: [M_ShipperPickupTypesInput!]!): [M_ShipperPickupTypes!]!
	M_ShipperPickupTypesDelete(UUs: [String!]!): Boolean!
}

type M_ShipperPickupTypesConnection {
	Results: [M_ShipperPickupTypes!]!
	PagingInfo: PagingInfo!
}

type M_ShipperPickupTypes {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# Method or manner of product delivery
	M_Shipper: M_Shipper!
	M_ShipperPickupTypesCfg: M_ShipperPickupTypesCfg!
	UU: ID!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_ShipperPickupTypesInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# Method or manner of product delivery
	M_Shipper: ForeignEntityInput
	M_ShipperPickupTypesCfg: ForeignEntityInput
	UU: ID
	# Alphanumeric identifier of the entity
	Name: String
}
