# Generated Schema for M_FreightCategory - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_FreightCategory(UU: String!): M_FreightCategory
	M_FreightCategoryGet(Page: Int, Size: Int, Sort: String, Filter: String): M_FreightCategoryConnection!
}

extend type Mutation {
	M_FreightCategorySave(Entity: M_FreightCategoryInput!): M_FreightCategory!
	M_FreightCategorySaveMany(Entities: [M_FreightCategoryInput!]!): [M_FreightCategory!]!
	M_FreightCategoryDelete(UUs: [String!]!): Boolean!
}

type M_FreightCategoryConnection {
	Results: [M_FreightCategory!]!
	PagingInfo: PagingInfo!
}

type M_FreightCategory {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	UU: ID!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input M_FreightCategoryInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	UU: ID
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
}
