# Generated Schema for M_LotCtl - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	M_LotCtlGet(page: Int, size: Int, sort: String, filter: String): M_LotCtlConnection!
}

extend type Mutation {
	M_LotCtlSave(entity: M_LotCtlInput!): M_LotCtl!
	M_LotCtlSaveMany(entities: [M_LotCtlInput!]!): [M_LotCtl!]!
	M_LotCtlDelete(uuids: [String!]!): Boolean!
}

type M_LotCtlConnection {
	results: [M_LotCtl!]!
	pagingInfo: PagingInfo!
}

type M_LotCtl {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The next number to be used
	CurrentNext: Int!
	# Optional short description of the record
	Description: String
	# The number to increment the last document number by
	IncrementNo: Int!
	# The record is active in the system
	IsActive: Boolean!
	UUID: ID!
	# Alphanumeric identifier of the entity
	Name: String!
	# Prefix before the sequence number
	Prefix: String
	# Starting number/position
	StartNo: Int!
	# Suffix after the number
	Suffix: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_LotCtlInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# The next number to be used
	CurrentNext: Int
	# Optional short description of the record
	Description: String
	# The number to increment the last document number by
	IncrementNo: Int
	# The record is active in the system
	IsActive: Boolean
	UUID: ID
	# Alphanumeric identifier of the entity
	Name: String
	# Prefix before the sequence number
	Prefix: String
	# Starting number/position
	StartNo: Int
	# Suffix after the number
	Suffix: String
}
