# Generated Schema for M_ProductPrice - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	M_ProductPriceGet(page: Int, size: Int, sort: String, filter: String): M_ProductPriceConnection!
}

extend type Mutation {
	M_ProductPriceSave(entity: M_ProductPriceInput!): M_ProductPrice!
	M_ProductPriceSaveMany(entities: [M_ProductPriceInput!]!): [M_ProductPrice!]!
	M_ProductPriceDelete(uuids: [String!]!): Boolean!
}

type M_ProductPriceConnection {
	results: [M_ProductPrice!]!
	pagingInfo: PagingInfo!
}

type M_ProductPrice {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Element to allow buttons to be displayed that trigger tab navigation
	BH_NavButtons: Object
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Identifies a unique instance of a Price List
	M_PriceList_Version: M_PriceList_Version!
	# Product, Service, Item
	M_Product: M_Product!
	UUID: ID!
	# Lowest price for a product
	PriceLimit: BigDecimal!
	# List Price
	PriceList: BigDecimal!
	# Standard Price
	PriceStd: BigDecimal!
	# Name of the Product
	ProductName: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_ProductPriceInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Element to allow buttons to be displayed that trigger tab navigation
	BH_NavButtons: Object
	# The record is active in the system
	IsActive: Boolean
	# Identifies a unique instance of a Price List
	M_PriceList_Version: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	UUID: ID
	# Lowest price for a product
	PriceLimit: BigDecimal
	# List Price
	PriceList: BigDecimal
	# Standard Price
	PriceStd: BigDecimal
}
