# Generated Schema for M_DemandLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_DemandLineGet(Page: Int, Size: Int, Sort: String, Filter: String): M_DemandLineConnection!
}

extend type Mutation {
	M_DemandLineSave(Entity: M_DemandLineInput!): M_DemandLine!
	M_DemandLineSaveMany(Entities: [M_DemandLineInput!]!): [M_DemandLine!]!
	M_DemandLineDelete(UUs: [String!]!): Boolean!
}

type M_DemandLineConnection {
	Results: [M_DemandLine!]!
	PagingInfo: PagingInfo!
}

type M_DemandLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Period of the Calendar
	C_Period: C_Period!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Material Demand
	M_Demand: M_Demand!
	UU: ID!
	# Product, Service, Item
	M_Product: M_Product!
	# Quantity
	Qty: BigDecimal!
	# Calculated Quantity
	QtyCalculated: BigDecimal!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_DemandLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Period of the Calendar
	C_Period: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Material Demand
	M_Demand: ForeignEntityInput
	UU: ID
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Quantity
	Qty: BigDecimal
	# Calculated Quantity
	QtyCalculated: BigDecimal
}
