# Generated Schema for M_Product_Category - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	M_Product_CategoryGet(page: Int, size: Int, sort: String, filter: String): M_Product_CategoryConnection!
}

extend type Mutation {
	M_Product_CategorySave(entity: M_Product_CategoryInput!): M_Product_Category!
	M_Product_CategoryDelete(uuids: [String!]!): Boolean!
}

type M_Product_CategoryConnection {
	results: [M_Product_Category!]!
	pagingInfo: PagingInfo!
}

type M_Product_Category {
	# Group of Assets
	A_Asset_Group: A_Asset_Group
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Color used for printing and display
	AD_PrintColor: AD_PrintColor
	# Contains a character the is linked to a ref list to determine types of product categories
	BH_Product_Category_Type_RL: AD_Ref_List
	# Date this record was created
	Created: Date!
	# User who created this records
	Create: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	M_Product_Category_Parent: M_Product_Category
	ID: ID!
	# Material Movement Policy
	MMPolicy_RL: AD_Ref_List!
	# Alphanumeric identifier of the entity
	Name: String!
	# Project's planned margin as a percentage
	PlannedMargin: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	Update: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input M_Product_CategoryInput {
	# Group of Assets
	A_Asset_Group: A_Asset_GroupInput
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Color used for printing and display
	AD_PrintColor: AD_PrintColorInput
	# Contains a character the is linked to a ref list to determine types of product categories
	BH_Product_Category_Type_RL: AD_Ref_ListInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	M_Product_Category_Parent: M_Product_CategoryInput
	ID: ID
	# Material Movement Policy
	MMPolicy_RL: AD_Ref_ListInput
	# Alphanumeric identifier of the entity
	Name: String
	# Project's planned margin as a percentage
	PlannedMargin: Int
	# Search key for the record in the format required - must be unique
	Value: String
}
