# Generated Schema for M_Demand - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_DemandGet(Page: Int, Size: Int, Sort: String, Filter: String): M_DemandConnection!
}

extend type Mutation {
	M_DemandSave(Entity: M_DemandInput!): M_Demand!
	M_DemandSaveMany(Entities: [M_DemandInput!]!): [M_Demand!]!
	M_DemandDelete(UUs: [String!]!): Boolean!
}

type M_DemandConnection {
	Results: [M_Demand!]!
	PagingInfo: PagingInfo!
}

type M_Demand {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Accounting Calendar Name
	C_Calendar: C_Calendar!
	# Calendar Year
	C_Year: C_Year!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	UU: ID!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_DemandInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Accounting Calendar Name
	C_Calendar: ForeignEntityInput
	# Calendar Year
	C_Year: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	UU: ID
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
}
