# Generated Schema for M_Package - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	M_PackageGet(page: Int, size: Int, sort: String, filter: String): M_PackageConnection!
}

extend type Mutation {
	M_PackageSave(entity: M_PackageInput!): M_Package!
	M_PackageDelete(uuids: [String!]!): Boolean!
}

type M_PackageConnection {
	results: [M_Package!]!
	pagingInfo: PagingInfo!
}

type M_Package {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	BoxCount: Int
	C_BP_ShippingAcct: C_BP_ShippingAcct
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: C_BPartner_Location
	# The Currency for this record
	C_Currency: C_Currency
	# Standard Unit of Measure for Length
	C_UOM_Length: C_UOM
	# Standard Unit of Measure for Weight
	C_UOM_Weight: C_UOM
	CashOnDelivery: Boolean!
	# Date this record was created
	Created: Date!
	# User who created this records
	Create: AD_User!
	# Date a product was received
	DateReceived: Date
	# EMail Delivery confirmation
	DeliveryConfirmation: Boolean!
	DeliveryConfirmationType_RL: AD_Ref_List
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String!
	DotHazardClassOrDivision_RL: AD_Ref_List
	DryIceWeight: Int
	DutiesShipperAccount: String
	EstimatedWeight: Int
	FOB_RL: AD_Ref_List
	FreightCharges_RL: AD_Ref_List
	HandlingCharge: Int
	Height: Int
	HoldAddress: C_BPartner_Location
	HomeDeliveryPremiumDate: Date
	HomeDeliveryPremiumPhone: String
	HomeDeliveryPremiumType_RL: AD_Ref_List
	Insurance_RL: AD_Ref_List
	InsuredAmount: Int
	IsAccessible: Boolean!
	# The record is active in the system
	IsActive: Boolean!
	IsAddedHandling: Boolean!
	IsCargoAircraftOnly: Boolean!
	IsDryIce: Boolean!
	IsDutiable: Boolean!
	IsFutureDayShipment: Boolean!
	IsHazMat: Boolean!
	IsHoldAtLocation: Boolean!
	IsIgnoreZipNotFound: Boolean!
	IsIgnoreZipStateNotMatch: Boolean!
	IsResidential: Boolean!
	IsSaturdayDelivery: Boolean!
	IsSaturdayPickup: Boolean!
	IsVerbalConfirmation: Boolean!
	LabelPrint: String
	LatestPickupTime: Date
	Length: Int
	# Material Shipment Document
	M_InOut: M_InOut!
	ID: ID!
	# Method or manner of product delivery
	M_Shipper: M_Shipper!
	M_ShipperLabels: M_ShipperLabels
	M_ShipperPackaging: M_ShipperPackaging
	M_ShipperPickupTypes: M_ShipperPickupTypes
	M_ShippingProcessor: M_ShippingProcessor
	NotificationMessage: String
	# Type of Notifications
	NotificationType_RL: AD_Ref_List
	# This payment can be processed online
	OProcessing: String
	# How you pay the invoice
	PaymentRule_RL: AD_Ref_List
	# Price
	Price: Int
	# Actual Price 
	PriceActual: Int
	# The document has been processed
	Processed: Boolean!
	RateInquiryMessage: String
	# Information of the receipt of the package (acknowledgement)
	ReceivedInfo: String
	# Shipment Date/Time
	ShipDate: Date
	ShipperAccount: String
	ShippingRateInquiry: String
	ShippingRespMessage: String
	Surcharges: Int
	TotalPrice: Int
	TrackingInfo: String
	# Number to track the shipment
	TrackingNo: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	Update: AD_User!
	VoidIt: String
	# Weight of a product
	Weight: Int
	Width: Int
}

input M_PackageInput {
	# Organizational entity within client
	AD_Org: AD_OrgInput
	BoxCount: Int
	C_BP_ShippingAcct: C_BP_ShippingAcctInput
	# Identifies the (ship to) address for this Business Partner
	C_BPartner_Location: C_BPartner_LocationInput
	# The Currency for this record
	C_Currency: C_CurrencyInput
	# Standard Unit of Measure for Length
	C_UOM_Length: C_UOMInput
	# Standard Unit of Measure for Weight
	C_UOM_Weight: C_UOMInput
	CashOnDelivery: Boolean
	# Date a product was received
	DateReceived: Date
	# EMail Delivery confirmation
	DeliveryConfirmation: Boolean
	DeliveryConfirmationType_RL: AD_Ref_ListInput
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String
	DotHazardClassOrDivision_RL: AD_Ref_ListInput
	DryIceWeight: Int
	DutiesShipperAccount: String
	HandlingCharge: Int
	Height: Int
	HoldAddress: C_BPartner_LocationInput
	HomeDeliveryPremiumDate: Date
	HomeDeliveryPremiumPhone: String
	HomeDeliveryPremiumType_RL: AD_Ref_ListInput
	InsuredAmount: Int
	IsAccessible: Boolean
	# The record is active in the system
	IsActive: Boolean
	IsAddedHandling: Boolean
	IsCargoAircraftOnly: Boolean
	IsDryIce: Boolean
	IsDutiable: Boolean
	IsFutureDayShipment: Boolean
	IsHazMat: Boolean
	IsHoldAtLocation: Boolean
	IsIgnoreZipNotFound: Boolean
	IsIgnoreZipStateNotMatch: Boolean
	IsResidential: Boolean
	IsSaturdayDelivery: Boolean
	IsSaturdayPickup: Boolean
	IsVerbalConfirmation: Boolean
	LabelPrint: String
	LatestPickupTime: Date
	Length: Int
	# Material Shipment Document
	M_InOut: M_InOutInput
	ID: ID
	# Method or manner of product delivery
	M_Shipper: M_ShipperInput
	M_ShipperLabels: M_ShipperLabelsInput
	M_ShipperPackaging: M_ShipperPackagingInput
	M_ShipperPickupTypes: M_ShipperPickupTypesInput
	NotificationMessage: String
	# Type of Notifications
	NotificationType_RL: AD_Ref_ListInput
	# This payment can be processed online
	OProcessing: String
	# How you pay the invoice
	PaymentRule_RL: AD_Ref_ListInput
	# Price
	Price: Int
	# Actual Price 
	PriceActual: Int
	# The document has been processed
	Processed: Boolean
	RateInquiryMessage: String
	# Information of the receipt of the package (acknowledgement)
	ReceivedInfo: String
	# Shipment Date/Time
	ShipDate: Date
	ShipperAccount: String
	ShippingRateInquiry: String
	ShippingRespMessage: String
	Surcharges: Int
	TrackingInfo: String
	# Number to track the shipment
	TrackingNo: String
	VoidIt: String
	# Weight of a product
	Weight: Int
	Width: Int
}
