# Generated Schema for M_PackageMPS - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_PackageMPS(UU: String!): M_PackageMPS
	M_PackageMPSGet(Page: Int, Size: Int, Sort: String, Filter: String): M_PackageMPSConnection!
}

extend type Mutation {
	M_PackageMPSSave(Entity: M_PackageMPSInput!): M_PackageMPS!
	M_PackageMPSSaveMany(Entities: [M_PackageMPSInput!]!): [M_PackageMPS!]!
	M_PackageMPSDelete(UUs: [String!]!): Boolean!
}

type M_PackageMPSConnection {
	Results: [M_PackageMPS!]!
	PagingInfo: PagingInfo!
}

type M_PackageMPS {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Process which will generate a new document lines based on an existing document
	CreateFrom: String
	# Standard Unit of Measure for Length
	C_UOM_Length: C_UOM
	# Standard Unit of Measure for Weight
	C_UOM_Weight: C_UOM
	# Optional short description of the record
	Description: String
	EstimatedWeight: BigDecimal
	Height: BigDecimal
	# The record is active in the system
	IsActive: Boolean!
	Length: BigDecimal
	MasterTrackingNo: String
	# Shipment Package
	M_Package: M_Package!
	UU: ID!
	# Price
	Price: BigDecimal
	# The document has been processed
	Processed: Boolean!
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Number to track the shipment
	TrackingNo: String
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Weight of a product
	Weight: BigDecimal
	Width: BigDecimal
}

input M_PackageMPSInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Process which will generate a new document lines based on an existing document
	CreateFrom: String
	# Standard Unit of Measure for Length
	C_UOM_Length: ForeignEntityInput
	# Standard Unit of Measure for Weight
	C_UOM_Weight: ForeignEntityInput
	# Optional short description of the record
	Description: String
	Height: BigDecimal
	# The record is active in the system
	IsActive: Boolean
	Length: BigDecimal
	MasterTrackingNo: String
	# Shipment Package
	M_Package: ForeignEntityInput
	UU: ID
	# Price
	Price: BigDecimal
	# The document has been processed
	Processed: Boolean
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Number to track the shipment
	TrackingNo: String
	# Weight of a product
	Weight: BigDecimal
	Width: BigDecimal
}
