# Generated Schema for M_MatchInv - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	M_MatchInvGet(page: Int, size: Int, sort: String, filter: String): M_MatchInvConnection!
}

extend type Mutation {
	M_MatchInvSave(entity: M_MatchInvInput!): M_MatchInv!
	M_MatchInvSaveMany(entities: [M_MatchInvInput!]!): [M_MatchInv!]!
	M_MatchInvDelete(uuids: [String!]!): Boolean!
}

type M_MatchInvConnection {
	results: [M_MatchInv!]!
	pagingInfo: PagingInfo!
}

type M_MatchInv {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Invoice Detail Line
	C_InvoiceLine: C_InvoiceLine!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Accounting Date
	DateAcct: Date!
	# Transaction Date
	DateTrx: Date!
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean!
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance
	# Line on Shipment or Receipt document
	M_InOutLine: M_InOutLine
	UUID: ID!
	# Product, Service, Item
	M_Product: M_Product!
	# Posting status
	Posted: Boolean!
	# The document has been processed
	Processed: Boolean!
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean!
	# Quantity
	Qty: BigDecimal!
	Ref_MatchInv: M_MatchInv
	# ID of document reversal
	Reversal: M_MatchInv
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_MatchInvInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Invoice Detail Line
	C_InvoiceLine: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Transaction Date
	DateTrx: Date
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String
	# The record is active in the system
	IsActive: Boolean
	# Product Attribute Set Instance
	M_AttributeSetInstance: ForeignEntityInput
	# Line on Shipment or Receipt document
	M_InOutLine: ForeignEntityInput
	UUID: ID
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Posting status
	Posted: Boolean
	# The document has been processed
	Processed: Boolean
	# The date+time (expressed in decimal format) when the document has been processed
	ProcessedOn: BigDecimal
	Processing: Boolean
	# Quantity
	Qty: BigDecimal
	Ref_MatchInv: ForeignEntityInput
	# ID of document reversal
	Reversal: ForeignEntityInput
}
