# Generated Schema for M_ProductDownload - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	M_ProductDownload(UU: String!): M_ProductDownload
	M_ProductDownloadGet(Page: Int, Size: Int, Sort: String, Filter: String): M_ProductDownloadConnection!
}

extend type Mutation {
	M_ProductDownloadSave(Entity: M_ProductDownloadInput!): M_ProductDownload!
	M_ProductDownloadSaveMany(Entities: [M_ProductDownloadInput!]!): [M_ProductDownload!]!
	M_ProductDownloadDelete(UUs: [String!]!): Boolean!
}

type M_ProductDownloadConnection {
	Results: [M_ProductDownload!]!
	PagingInfo: PagingInfo!
}

type M_ProductDownload {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# URL of the Download files
	DownloadURL: String!
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	UU: ID!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_ProductDownloadInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# URL of the Download files
	DownloadURL: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	UU: ID
	# Alphanumeric identifier of the entity
	Name: String
}
