# Generated Schema for M_AttributeUse - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_AttributeUse(UU: String!): M_AttributeUse
	M_AttributeUseGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): M_AttributeUseConnection!
}

extend type Mutation {
	M_AttributeUseSave(Entity: M_AttributeUseInput!): M_AttributeUse!
	M_AttributeUseSaveMany(Entities: [M_AttributeUseInput!]!): [M_AttributeUse!]!
	M_AttributeUseDelete(UUs: [String!]!): Boolean!
}

type M_AttributeUseConnection {
	Results: [M_AttributeUse!]!
	PagingInfo: PagingInfo!
}

type M_AttributeUse {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Product Attribute
	M_Attribute: M_Attribute!
	# Product Attribute Set
	M_AttributeSet: M_AttributeSet!
	UU: ID!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_AttributeUseInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Product Attribute
	M_Attribute: ForeignEntityInput
	# Product Attribute Set
	M_AttributeSet: ForeignEntityInput
	UU: ID
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
