# Generated Schema for M_StorageOnHand - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_StorageOnHand(UU: String!): M_StorageOnHand
	M_StorageOnHandGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): M_StorageOnHandConnection!
}

extend type Mutation {
	M_StorageOnHandSave(Entity: M_StorageOnHandInput!): M_StorageOnHand!
	M_StorageOnHandSaveMany(Entities: [M_StorageOnHandInput!]!): [M_StorageOnHand!]!
	M_StorageOnHandDelete(UUs: [String!]!): Boolean!
}

type M_StorageOnHandConnection {
	Results: [M_StorageOnHand!]!
	PagingInfo: PagingInfo!
}

type M_StorageOnHand {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Date of Last Inventory Count
	DateLastInventory: Date
	# Time used for LIFO and FIFO Material Policy
	DateMaterialPolicy: Date!
	# The record is active in the system
	IsActive: Boolean!
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance!
	# Warehouse Locator
	M_Locator: M_Locator!
	# Product, Service, Item
	M_Product: M_Product!
	UU: ID!
	# On Hand Quantity
	QtyOnHand: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_StorageOnHandInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Date of Last Inventory Count
	DateLastInventory: Date
	# Time used for LIFO and FIFO Material Policy
	DateMaterialPolicy: Date
	# The record is active in the system
	IsActive: Boolean
	# Product Attribute Set Instance
	M_AttributeSetInstance: ForeignEntityInput
	# Warehouse Locator
	M_Locator: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	UU: ID
	# On Hand Quantity
	QtyOnHand: BigDecimal
}
