# Generated Schema for M_DemandDetail - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_DemandDetail(UU: String!): M_DemandDetail
	M_DemandDetailGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): M_DemandDetailConnection!
}

extend type Mutation {
	M_DemandDetailSave(Entity: M_DemandDetailInput!): M_DemandDetail!
	M_DemandDetailSaveMany(Entities: [M_DemandDetailInput!]!): [M_DemandDetail!]!
	M_DemandDetailDelete(UUs: [String!]!): Boolean!
}

type M_DemandDetailConnection {
	Results: [M_DemandDetail!]!
	PagingInfo: PagingInfo!
}

type M_DemandDetail {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Sales Order Line
	C_OrderLine: C_OrderLine
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	UU: ID!
	# Material Demand Line
	M_DemandLine: M_DemandLine!
	# Forecast Line
	M_ForecastLine: M_ForecastLine
	# Material Requisition Line
	M_RequisitionLine: M_RequisitionLine
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_DemandDetailInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Sales Order Line
	C_OrderLine: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	UU: ID
	# Material Demand Line
	M_DemandLine: ForeignEntityInput
	# Forecast Line
	M_ForecastLine: ForeignEntityInput
	# Material Requisition Line
	M_RequisitionLine: ForeignEntityInput
}
