# Generated Schema for M_Product_QualityTest - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	M_Product_QualityTest(UU: String!): M_Product_QualityTest
	M_Product_QualityTestGet(Page: Int, Size: Int, Sort: String, Filter: String): M_Product_QualityTestConnection!
}

extend type Mutation {
	M_Product_QualityTestSave(Entity: M_Product_QualityTestInput!): M_Product_QualityTest!
	M_Product_QualityTestSaveMany(Entities: [M_Product_QualityTestInput!]!): [M_Product_QualityTest!]!
	M_Product_QualityTestDelete(UUs: [String!]!): Boolean!
}

type M_Product_QualityTestConnection {
	Results: [M_Product_QualityTest!]!
	PagingInfo: PagingInfo!
}

type M_Product_QualityTest {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	ExpectedResult: String!
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	UU: ID!
	M_QualityTest: M_QualityTest!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_Product_QualityTestInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	ExpectedResult: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	UU: ID
	M_QualityTest: ForeignEntityInput
}
