# Generated Schema for M_Lot - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	M_LotGet(page: Int, size: Int, sort: String, filter: String): M_LotConnection!
}

extend type Mutation {
	M_LotSave(entity: M_LotInput!): M_Lot!
	M_LotDelete(uuids: [String!]!): Boolean!
}

type M_LotConnection {
	results: [M_Lot!]!
	pagingInfo: PagingInfo!
}

type M_Lot {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Starting date for a range
	DateFrom: Date
	# End date of a date range
	DateTo: Date
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	ID: ID!
	# Product Lot Control
	M_LotCtl: M_LotCtl
	# Product, Service, Item
	M_Product: M_Product!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_LotInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Starting date for a range
	DateFrom: Date
	# End date of a date range
	DateTo: Date
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	ID: ID
	# Product Lot Control
	M_LotCtl: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
}
