# Generated Schema for M_PromotionDistribution - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_PromotionDistributionGet(Page: Int, Size: Int, Sort: String, Filter: String): M_PromotionDistributionConnection!
}

extend type Mutation {
	M_PromotionDistributionSave(Entity: M_PromotionDistributionInput!): M_PromotionDistribution!
	M_PromotionDistributionSaveMany(Entities: [M_PromotionDistributionInput!]!): [M_PromotionDistribution!]!
	M_PromotionDistributionDelete(UUs: [String!]!): Boolean!
}

type M_PromotionDistributionConnection {
	Results: [M_PromotionDistribution!]!
	PagingInfo: PagingInfo!
}

type M_PromotionDistribution {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Quantity distribution sorting by unit price
	DistributionSorting: AD_Ref_List
	# Type of quantity distribution calculation using comparison qty and order qty as operand
	DistributionType: AD_Ref_List!
	# The record is active in the system
	IsActive: Boolean!
	M_Promotion: M_Promotion!
	UU: ID!
	M_PromotionLine: M_PromotionLine!
	# Compare Operation
	Operation: AD_Ref_List!
	# Quantity
	Qty: BigDecimal!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_PromotionDistributionInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Quantity distribution sorting by unit price
	DistributionSorting: ForeignEntityInput
	# Type of quantity distribution calculation using comparison qty and order qty as operand
	DistributionType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	M_Promotion: ForeignEntityInput
	UU: ID
	M_PromotionLine: ForeignEntityInput
	# Compare Operation
	Operation: ForeignEntityInput
	# Quantity
	Qty: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
