# Generated Schema for M_Forecast - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_Forecast(UU: String!): M_Forecast
	M_ForecastGet(Page: Int, Size: Int, Sort: String, Filter: String): M_ForecastConnection!
}

extend type Mutation {
	M_ForecastSave(Entity: M_ForecastInput!): M_Forecast!
	M_ForecastSaveMany(Entities: [M_ForecastInput!]!): [M_Forecast!]!
	M_ForecastDelete(UUs: [String!]!): Boolean!
}

type M_ForecastConnection {
	Results: [M_Forecast!]!
	PagingInfo: PagingInfo!
}

type M_Forecast {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Accounting Calendar Name
	C_Calendar: C_Calendar!
	# Calendar Year
	C_Year: C_Year!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	UU: ID!
	# Unique identifier of a Price List
	M_PriceList: M_PriceList
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_ForecastInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Accounting Calendar Name
	C_Calendar: ForeignEntityInput
	# Calendar Year
	C_Year: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	UU: ID
	# Unique identifier of a Price List
	M_PriceList: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
}
