# Generated Schema for M_ProductionLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_ProductionLine(UU: String!): M_ProductionLine
	M_ProductionLineGet(Page: Int, Size: Int, Sort: String, Filter: String): M_ProductionLineConnection!
}

extend type Mutation {
	M_ProductionLineSave(Entity: M_ProductionLineInput!): M_ProductionLine!
	M_ProductionLineSaveMany(Entities: [M_ProductionLineInput!]!): [M_ProductionLine!]!
	M_ProductionLineDelete(UUs: [String!]!): Boolean!
}

type M_ProductionLineConnection {
	Results: [M_ProductionLine!]!
	PagingInfo: PagingInfo!
}

type M_ProductionLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# End Product of production
	IsEndProduct: Boolean!
	# Unique line for this document
	Line: Int!
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance!
	# Warehouse Locator
	M_Locator: M_Locator!
	# Quantity of a product moved.
	MovementQty: BigDecimal!
	# Product, Service, Item
	M_Product: M_Product!
	# Plan for producing a product
	M_Production: M_Production
	UU: ID!
	# Plan for how a product is produced
	M_ProductionPlan: M_ProductionPlan
	# Planned quantity for this project
	PlannedQty: BigDecimal
	# The document has been processed
	Processed: Boolean!
	# Type of product
	ProductType: String
	# Available Quantity (On Hand - Reserved)
	QtyAvailable: BigDecimal
	QtyUsed: BigDecimal
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_ProductionLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# End Product of production
	IsEndProduct: Boolean
	# Unique line for this document
	Line: Int
	# Product Attribute Set Instance
	M_AttributeSetInstance: ForeignEntityInput
	# Warehouse Locator
	M_Locator: ForeignEntityInput
	# Quantity of a product moved.
	MovementQty: BigDecimal
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Plan for producing a product
	M_Production: ForeignEntityInput
	UU: ID
	# Plan for how a product is produced
	M_ProductionPlan: ForeignEntityInput
	# Planned quantity for this project
	PlannedQty: BigDecimal
	# The document has been processed
	Processed: Boolean
	QtyUsed: BigDecimal
}
