# Generated Schema for M_LocatorType - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_LocatorTypeGet(page: Int, size: Int, sort: String, filter: String): M_LocatorTypeConnection!
}

extend type Mutation {
	M_LocatorTypeSave(entity: M_LocatorTypeInput!): M_LocatorType!
	M_LocatorTypeSaveMany(entities: [M_LocatorTypeInput!]!): [M_LocatorType!]!
	M_LocatorTypeDelete(uuids: [String!]!): Boolean!
}

type M_LocatorTypeConnection {
	results: [M_LocatorType!]!
	pagingInfo: PagingInfo!
}

type M_LocatorType {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	IsAvailableForReplenishment: Boolean!
	IsAvailableForReservation: Boolean!
	IsAvailableForShipping: Boolean!
	UUID: ID!
	M_LocatorType_UU: String
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_LocatorTypeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	IsAvailableForReplenishment: Boolean
	IsAvailableForReservation: Boolean
	IsAvailableForShipping: Boolean
	UUID: ID
	M_LocatorType_UU: String
	# Alphanumeric identifier of the entity
	Name: String
}
