# Generated Schema for M_PackageLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_PackageLine(UU: String!): M_PackageLine
	M_PackageLineGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): M_PackageLineConnection!
}

extend type Mutation {
	M_PackageLineSave(Entity: M_PackageLineInput!): M_PackageLine!
	M_PackageLineSaveMany(Entities: [M_PackageLineInput!]!): [M_PackageLine!]!
	M_PackageLineDelete(UUs: [String!]!): Boolean!
}

type M_PackageLineConnection {
	Results: [M_PackageLine!]!
	PagingInfo: PagingInfo!
}

type M_PackageLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Line on Shipment or Receipt document
	M_InOutLine: M_InOutLine!
	# Shipment Package
	M_Package: M_Package!
	UU: ID!
	M_PackageMPS: M_PackageMPS
	# Product, Service, Item
	M_Product: M_Product
	# Quantity
	Qty: BigDecimal!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_PackageLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Line on Shipment or Receipt document
	M_InOutLine: ForeignEntityInput
	# Shipment Package
	M_Package: ForeignEntityInput
	UU: ID
	M_PackageMPS: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Quantity
	Qty: BigDecimal
}
