# Generated Schema for M_Substitute - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_Substitute(UU: String!): M_Substitute
	M_SubstituteGet(Page: Int, Size: Int, Sort: String, Filter: String): M_SubstituteConnection!
}

extend type Mutation {
	M_SubstituteSave(Entity: M_SubstituteInput!): M_Substitute!
	M_SubstituteSaveMany(Entities: [M_SubstituteInput!]!): [M_Substitute!]!
	M_SubstituteDelete(UUs: [String!]!): Boolean!
}

type M_SubstituteConnection {
	Results: [M_Substitute!]!
	PagingInfo: PagingInfo!
}

type M_Substitute {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	UU: ID!
	# Alphanumeric identifier of the entity
	Name: String!
	# Entity which can be used in place of this entity
	Substitute: M_Product!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_SubstituteInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	UU: ID
	# Alphanumeric identifier of the entity
	Name: String
	# Entity which can be used in place of this entity
	Substitute: ForeignEntityInput
}
