# Generated Schema for M_ShipperLabels - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_ShipperLabels(UU: String!): M_ShipperLabels
	M_ShipperLabelsGet(Page: Int, Size: Int, Sort: String, Filter: String): M_ShipperLabelsConnection!
}

extend type Mutation {
	M_ShipperLabelsSave(Entity: M_ShipperLabelsInput!): M_ShipperLabels!
	M_ShipperLabelsSaveMany(Entities: [M_ShipperLabelsInput!]!): [M_ShipperLabels!]!
	M_ShipperLabelsDelete(UUs: [String!]!): Boolean!
}

type M_ShipperLabelsConnection {
	Results: [M_ShipperLabels!]!
	PagingInfo: PagingInfo!
}

type M_ShipperLabels {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	LabelPrintMethod: AD_Ref_List
	# Method or manner of product delivery
	M_Shipper: M_Shipper!
	UU: ID!
	M_ShipperLabelsCfg: M_ShipperLabelsCfg!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_ShipperLabelsInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	LabelPrintMethod: ForeignEntityInput
	# Method or manner of product delivery
	M_Shipper: ForeignEntityInput
	UU: ID
	M_ShipperLabelsCfg: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
}
