# Generated Schema for M_ProductOperation - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	M_ProductOperationGet(page: Int, size: Int, sort: String, filter: String): M_ProductOperationConnection!
}

extend type Mutation {
	M_ProductOperationSave(entity: M_ProductOperationInput!): M_ProductOperation!
	M_ProductOperationSaveMany(entities: [M_ProductOperationInput!]!): [M_ProductOperation!]!
	M_ProductOperationDelete(uuids: [String!]!): Boolean!
}

type M_ProductOperationConnection {
	results: [M_ProductOperation!]!
	pagingInfo: PagingInfo!
}

type M_ProductOperation {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	UUID: ID!
	M_ProductOperation_UU: String
	# Alphanumeric identifier of the entity
	Name: String!
	# Setup time before starting Production
	SetupTime: BigDecimal
	# Time at the end of the operation
	TeardownTime: BigDecimal
	# Time to produce one unit
	UnitRuntime: BigDecimal
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_ProductOperationInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	UUID: ID
	M_ProductOperation_UU: String
	# Alphanumeric identifier of the entity
	Name: String
	# Setup time before starting Production
	SetupTime: BigDecimal
	# Time at the end of the operation
	TeardownTime: BigDecimal
	# Time to produce one unit
	UnitRuntime: BigDecimal
}
