# Generated Schema for M_PerpetualInv - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	M_PerpetualInvGet(page: Int, size: Int, sort: String, filter: String): M_PerpetualInvConnection!
}

extend type Mutation {
	M_PerpetualInvSave(entity: M_PerpetualInvInput!): M_PerpetualInv!
	M_PerpetualInvSaveMany(entities: [M_PerpetualInvInput!]!): [M_PerpetualInv!]!
	M_PerpetualInvDelete(uuids: [String!]!): Boolean!
}

type M_PerpetualInvConnection {
	results: [M_PerpetualInv!]!
	pagingInfo: PagingInfo!
}

type M_PerpetualInv {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Count High Movement products
	CountHighMovement: Boolean!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date the process was last run.
	DateLastRun: Date
	# Date the process will run next
	DateNextRun: Date!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	UUID: ID!
	# Category of a Product
	M_Product_Category: M_Product_Category
	# Storage Warehouse and Service Point
	M_Warehouse: M_Warehouse
	# Alphanumeric identifier of the entity
	Name: String!
	# Frequency of inventory counts per year
	NoInventoryCount: Int!
	# Frequency of product counts per year
	NoProductCount: Int!
	# Frequency of processing Perpetual Inventory
	NumberOfRuns: Int!
	Processing: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_PerpetualInvInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Count High Movement products
	CountHighMovement: Boolean
	# Date the process was last run.
	DateLastRun: Date
	# Date the process will run next
	DateNextRun: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	UUID: ID
	# Category of a Product
	M_Product_Category: ForeignEntityInput
	# Storage Warehouse and Service Point
	M_Warehouse: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# Frequency of inventory counts per year
	NoInventoryCount: Int
	# Frequency of product counts per year
	NoProductCount: Int
	# Frequency of processing Perpetual Inventory
	NumberOfRuns: Int
	Processing: Boolean
}
