# Generated Schema for M_LotCtlExclude - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	M_LotCtlExclude(UU: String!): M_LotCtlExclude
	M_LotCtlExcludeGet(Page: Int, Size: Int, Sort: String, Filter: String): M_LotCtlExcludeConnection!
}

extend type Mutation {
	M_LotCtlExcludeSave(Entity: M_LotCtlExcludeInput!): M_LotCtlExclude!
	M_LotCtlExcludeSaveMany(Entities: [M_LotCtlExcludeInput!]!): [M_LotCtlExclude!]!
	M_LotCtlExcludeDelete(UUs: [String!]!): Boolean!
}

type M_LotCtlExcludeConnection {
	Results: [M_LotCtlExclude!]!
	PagingInfo: PagingInfo!
}

type M_LotCtlExclude {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# This is a Sales Transaction
	IsSOTrx: Boolean!
	UU: ID!
	# Product Lot Control
	M_LotCtl: M_LotCtl!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_LotCtlExcludeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# This is a Sales Transaction
	IsSOTrx: Boolean
	UU: ID
	# Product Lot Control
	M_LotCtl: ForeignEntityInput
}
