# Generated Schema for M_Attribute - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	M_Attribute(UU: String!): M_Attribute
	M_AttributeGet(Page: Int, Size: Int, Sort: String, Filter: String): M_AttributeConnection!
}

extend type Mutation {
	M_AttributeSave(Entity: M_AttributeInput!): M_Attribute!
	M_AttributeSaveMany(Entities: [M_AttributeInput!]!): [M_Attribute!]!
	M_AttributeDelete(UUs: [String!]!): Boolean!
}

type M_AttributeConnection {
	Results: [M_Attribute!]!
	PagingInfo: PagingInfo!
}

type M_Attribute {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# System Reference and Validation
	AD_Reference: AD_Reference
	# Required to specify, if data type is Table or List
	AD_Reference_Value: AD_Reference
	# Dynamic Validation Rule
	AD_Val_Rule: AD_Val_Rule
	# Type of Attribute Value
	AttributeValueType: AD_Ref_List!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Date format used in the input format
	DateFormat: String
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# The product attribute is specific to the instance (like Serial No, Lot or Guarantee Date)
	IsInstanceAttribute: Boolean!
	# Data entry is required in this column
	IsMandatory: Boolean!
	UU: ID!
	# Common Search Attribute 
	M_AttributeSearch: M_AttributeSearch
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input M_AttributeInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# System Reference and Validation
	AD_Reference: ForeignEntityInput
	# Required to specify, if data type is Table or List
	AD_Reference_Value: ForeignEntityInput
	# Dynamic Validation Rule
	AD_Val_Rule: ForeignEntityInput
	# Type of Attribute Value
	AttributeValueType: ForeignEntityInput
	# Date format used in the input format
	DateFormat: String
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# The product attribute is specific to the instance (like Serial No, Lot or Guarantee Date)
	IsInstanceAttribute: Boolean
	# Data entry is required in this column
	IsMandatory: Boolean
	UU: ID
	# Common Search Attribute 
	M_AttributeSearch: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
}
