# Generated Schema for M_Product - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	M_ProductGet(page: Int, size: Int, sort: String, filter: String): M_ProductConnection!
}

extend type Mutation {
	M_ProductSave(entity: M_ProductInput!): M_Product!
	M_ProductDelete(uuids: [String!]!): Boolean!
}

type M_ProductConnection {
	results: [M_Product!]!
	pagingInfo: PagingInfo!
}

type M_Product {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Purchase price of product
	BH_BuyPrice: BigDecimal
	BH_HasExpiration: Boolean!
	# Element to allow buttons to be displayed that trigger tab navigation
	BH_NavButtons: Object
	BH_PriceMargin: BigDecimal
	bh_reorder_level: Int
	# How much quantity you want to re-order
	bh_reorder_quantity: Int
	# Selling price of BandaGo product
	BH_SellPrice: BigDecimal
	# Method for recording revenue
	C_RevenueRecognition: C_RevenueRecognition
	# Type of subscription
	C_SubscriptionType: C_SubscriptionType
	# Tax Category
	C_TaxCategory: C_TaxCategory!
	# Unit of Measure
	C_UOM: C_UOM!
	# Classification for grouping
	Classification: String
	# Copy From Record
	CopyFrom: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# URL for the description
	DescriptionURL: String
	# This product is no longer available
	Discontinued: Boolean!
	# Discontinued At indicates Date when product was discontinued
	DiscontinuedAt: Date
	# Discontinued By
	DiscontinuedBy: Date
	# Additional information for a Document
	DocumentNote: String
	# URL of the Download files
	DownloadURL: String
	Group1: String
	Group2: String
	# Number of days the product is guaranteed or available
	GuaranteeDays: Int
	# Minimum number of guarantee days
	GuaranteeDaysMin: Int
	# Comment or Hint
	Help: String
	# URL of  image
	ImageURL: String
	# The record is active in the system
	IsActive: Boolean!
	# Bill of Materials
	IsBOM: Boolean!
	# Drop Shipments are sent from the Vendor directly to the Customer
	IsDropShip: Boolean!
	# Exclude from automatic Delivery
	IsExcludeAutoDelivery: Boolean!
	# Print detail BOM elements on the invoice
	IsInvoicePrintDetails: Boolean!
	# This part is Kanban controlled
	IsKanban: Boolean!
	# This product is manufactured
	IsManufactured: Boolean!
	IsOwnBox: Boolean!
	# Phantom Component
	IsPhantom: Boolean!
	# Print detail BOM elements on the pick list
	IsPickListPrintDetails: Boolean!
	# Organization purchases this product
	IsPurchased: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	# Organization sells this product
	IsSold: Boolean!
	# Organization stocks this product
	IsStocked: Boolean!
	# This is a summary entity
	IsSummary: Boolean!
	istoformule: Boolean!
	# The BOM configuration has been verified
	IsVerified: Boolean!
	# If selected, the product is displayed in the initial or any empty search
	IsWebStoreFeatured: Boolean!
	# The Low Level is used to calculate the material plan and determines if a net requirement should be exploited
	LowLevel: Int!
	# Product Attribute Set
	M_AttributeSet: M_AttributeSet
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance!
	# Category of the Freight
	M_FreightCategory: M_FreightCategory
	# Warehouse Locator
	M_Locator: M_Locator
	M_PartType: M_PartType
	# Category of a Product
	M_Product_Category: M_Product_Category!
	ID: ID!
	# Alphanumeric identifier of the entity
	Name: String!
	Processing: Boolean!
	# Type of product
	ProductType: AD_Ref_List!
	# Quantity In Store
	QtyInStore: Int
	# Text templates for mailings
	R_MailText: R_MailText
	# Expense report type
	S_ExpenseType: S_ExpenseType
	# Resource
	S_Resource: S_Resource
	# Sales Representative or Company Agent
	SalesRep: AD_User
	# Shelf depth required
	ShelfDepth: Int
	# Shelf height required
	ShelfHeight: BigDecimal
	# Shelf width required
	ShelfWidth: Int
	# Stock Keeping Unit
	SKU: String
	# The Units Per Pack indicates the no of units of a product packed together.
	UnitsPerPack: Int
	# Units Per Pallet
	UnitsPerPallet: BigDecimal
	# Bar Code (Universal Product Code or its superset European Article Number)
	UPC: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
	# Version Number
	VersionNo: String
	# Volume of a product
	Volume: BigDecimal
	# Weight of a product
	Weight: BigDecimal
}

input M_ProductInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Purchase price of product
	BH_BuyPrice: BigDecimal
	BH_HasExpiration: Boolean
	# Element to allow buttons to be displayed that trigger tab navigation
	BH_NavButtons: Object
	BH_PriceMargin: BigDecimal
	bh_reorder_level: Int
	# How much quantity you want to re-order
	bh_reorder_quantity: Int
	# Selling price of BandaGo product
	BH_SellPrice: BigDecimal
	# Method for recording revenue
	C_RevenueRecognition: ForeignEntityInput
	# Type of subscription
	C_SubscriptionType: ForeignEntityInput
	# Tax Category
	C_TaxCategory: ForeignEntityInput
	# Unit of Measure
	C_UOM: ForeignEntityInput
	# Classification for grouping
	Classification: String
	# Copy From Record
	CopyFrom: String
	# Optional short description of the record
	Description: String
	# URL for the description
	DescriptionURL: String
	# This product is no longer available
	Discontinued: Boolean
	# Discontinued At indicates Date when product was discontinued
	DiscontinuedAt: Date
	# Discontinued By
	DiscontinuedBy: Date
	# Additional information for a Document
	DocumentNote: String
	# URL of the Download files
	DownloadURL: String
	Group1: String
	Group2: String
	# Number of days the product is guaranteed or available
	GuaranteeDays: Int
	# Minimum number of guarantee days
	GuaranteeDaysMin: Int
	# Comment or Hint
	Help: String
	# URL of  image
	ImageURL: String
	# The record is active in the system
	IsActive: Boolean
	# Bill of Materials
	IsBOM: Boolean
	# Drop Shipments are sent from the Vendor directly to the Customer
	IsDropShip: Boolean
	# Exclude from automatic Delivery
	IsExcludeAutoDelivery: Boolean
	# Print detail BOM elements on the invoice
	IsInvoicePrintDetails: Boolean
	# This part is Kanban controlled
	IsKanban: Boolean
	# This product is manufactured
	IsManufactured: Boolean
	IsOwnBox: Boolean
	# Phantom Component
	IsPhantom: Boolean
	# Print detail BOM elements on the pick list
	IsPickListPrintDetails: Boolean
	# Organization purchases this product
	IsPurchased: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	# Organization sells this product
	IsSold: Boolean
	# Organization stocks this product
	IsStocked: Boolean
	# This is a summary entity
	IsSummary: Boolean
	istoformule: Boolean
	# The BOM configuration has been verified
	IsVerified: Boolean
	# If selected, the product is displayed in the initial or any empty search
	IsWebStoreFeatured: Boolean
	# The Low Level is used to calculate the material plan and determines if a net requirement should be exploited
	LowLevel: Int
	# Product Attribute Set
	M_AttributeSet: ForeignEntityInput
	# Product Attribute Set Instance
	M_AttributeSetInstance: ForeignEntityInput
	# Category of the Freight
	M_FreightCategory: ForeignEntityInput
	# Warehouse Locator
	M_Locator: ForeignEntityInput
	M_PartType: ForeignEntityInput
	# Category of a Product
	M_Product_Category: ForeignEntityInput
	ID: ID
	# Alphanumeric identifier of the entity
	Name: String
	Processing: Boolean
	# Type of product
	ProductType: AD_Ref_ListInput
	# Text templates for mailings
	R_MailText: ForeignEntityInput
	# Expense report type
	S_ExpenseType: ForeignEntityInput
	# Resource
	S_Resource: ForeignEntityInput
	# Sales Representative or Company Agent
	SalesRep: ForeignEntityInput
	# Shelf depth required
	ShelfDepth: Int
	# Shelf height required
	ShelfHeight: BigDecimal
	# Shelf width required
	ShelfWidth: Int
	# Stock Keeping Unit
	SKU: String
	# The Units Per Pack indicates the no of units of a product packed together.
	UnitsPerPack: Int
	# Units Per Pallet
	UnitsPerPallet: BigDecimal
	# Bar Code (Universal Product Code or its superset European Article Number)
	UPC: String
	# Search key for the record in the format required - must be unique
	Value: String
	# Version Number
	VersionNo: String
	# Volume of a product
	Volume: BigDecimal
	# Weight of a product
	Weight: BigDecimal
}
