# Generated Schema for PA_DashboardPreference - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	PA_DashboardPreferenceGet(page: Int, size: Int, sort: String, filter: String): PA_DashboardPreferenceConnection!
}

extend type Mutation {
	PA_DashboardPreferenceSave(entity: PA_DashboardPreferenceInput!): PA_DashboardPreference!
	PA_DashboardPreferenceSaveMany(entities: [PA_DashboardPreferenceInput!]!): [PA_DashboardPreference!]!
	PA_DashboardPreferenceDelete(uuids: [String!]!): Boolean!
}

type PA_DashboardPreferenceConnection {
	results: [PA_DashboardPreference!]!
	pagingInfo: PagingInfo!
}

type PA_DashboardPreference {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	# Dashboard content column number
	ColumnNo: Int
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# This defines the ability for a flex item to grow if necessary. It accepts a unitless value that serves as a proportion. It dictates what amount of the available space inside the flex container the item should take up.
	FlexGrow: Int!
	# The record is active in the system
	IsActive: Boolean!
	# Flag to set the initial state of collapsible field group.
	IsCollapsedByDefault: Boolean!
	# Show the dashlet in the dashboard
	IsShowInDashboard: Boolean!
	# Unique line for this document
	Line: BigDecimal
	PA_DashboardContent: PA_DashboardContent!
	UUID: ID!
	PA_DashboardPreference_UU: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PA_DashboardPreferenceInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Dashboard content column number
	ColumnNo: Int
	# This defines the ability for a flex item to grow if necessary. It accepts a unitless value that serves as a proportion. It dictates what amount of the available space inside the flex container the item should take up.
	FlexGrow: Int
	# The record is active in the system
	IsActive: Boolean
	# Flag to set the initial state of collapsible field group.
	IsCollapsedByDefault: Boolean
	# Show the dashlet in the dashboard
	IsShowInDashboard: Boolean
	# Unique line for this document
	Line: BigDecimal
	PA_DashboardContent: ForeignEntityInput
	UUID: ID
	PA_DashboardPreference_UU: String
}
