# Generated Schema for PA_Goal - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	PA_GoalGet(Page: Int, Size: Int, Sort: String, Filter: String): PA_GoalConnection!
}

extend type Mutation {
	PA_GoalSave(Entity: PA_GoalInput!): PA_Goal!
	PA_GoalSaveMany(Entities: [PA_GoalInput!]!): [PA_Goal!]!
	PA_GoalDelete(UUs: [String!]!): Boolean!
}

type PA_GoalConnection {
	Results: [PA_Goal!]!
	PagingInfo: PagingInfo!
}

type PA_Goal {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Type of chart to render
	ChartType: AD_Ref_List!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Starting date for a range
	DateFrom: Date
	# Date the process was last run.
	DateLastRun: Date
	# End date of a date range
	DateTo: Date
	# Optional short description of the record
	Description: String
	# Target achievement from 0..1
	GoalPerformance: BigDecimal!
	# The record is active in the system
	IsActive: Boolean!
	# This is a summary entity
	IsSummary: Boolean!
	# Actual value that has been measured.
	MeasureActual: BigDecimal!
	# Measure Scope initially displayed
	MeasureDisplay: AD_Ref_List
	# Performance Measure Scope
	MeasureScope: AD_Ref_List!
	# Target value for measure
	MeasureTarget: BigDecimal!
	# Alphanumeric identifier of the entity
	Name: String!
	# Optional additional user defined information
	Note: String
	# Performance Color Schema
	PA_ColorSchema: PA_ColorSchema!
	UU: ID!
	# Parent Goal
	PA_GoalParent: PA_Goal
	# Concrete Performance Measurement
	PA_Measure: PA_Measure
	# Relative weight of this step (0 = ignored)
	RelativeWeight: BigDecimal!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PA_GoalInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Type of chart to render
	ChartType: AD_Ref_ListInput
	# Starting date for a range
	DateFrom: Date
	# Date the process was last run.
	DateLastRun: Date
	# End date of a date range
	DateTo: Date
	# Optional short description of the record
	Description: String
	# Target achievement from 0..1
	GoalPerformance: BigDecimal
	# The record is active in the system
	IsActive: Boolean
	# This is a summary entity
	IsSummary: Boolean
	# Actual value that has been measured.
	MeasureActual: BigDecimal
	# Measure Scope initially displayed
	MeasureDisplay: AD_Ref_ListInput
	# Performance Measure Scope
	MeasureScope: AD_Ref_ListInput
	# Target value for measure
	MeasureTarget: BigDecimal
	# Alphanumeric identifier of the entity
	Name: String
	# Optional additional user defined information
	Note: String
	# Performance Color Schema
	PA_ColorSchema: ForeignEntityInput
	UU: ID
	# Parent Goal
	PA_GoalParent: ForeignEntityInput
	# Concrete Performance Measurement
	PA_Measure: ForeignEntityInput
	# Relative weight of this step (0 = ignored)
	RelativeWeight: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
