# Generated Schema for PA_Benchmark - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	PA_BenchmarkGet(page: Int, size: Int, sort: String, filter: String): PA_BenchmarkConnection!
}

extend type Mutation {
	PA_BenchmarkSave(entity: PA_BenchmarkInput!): PA_Benchmark!
	PA_BenchmarkSaveMany(entities: [PA_BenchmarkInput!]!): [PA_Benchmark!]!
	PA_BenchmarkDelete(uuids: [String!]!): Boolean!
}

type PA_BenchmarkConnection {
	results: [PA_Benchmark!]!
	pagingInfo: PagingInfo!
}

type PA_Benchmark {
	# How to accumulate data on time axis
	AccumulationType: AD_Ref_List!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	UUID: ID!
	PA_Benchmark_UU: String
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PA_BenchmarkInput {
	# How to accumulate data on time axis
	AccumulationType: AD_Ref_ListInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	UUID: ID
	PA_Benchmark_UU: String
}
