# Generated Schema for PA_ColorSchema - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	PA_ColorSchema(UU: String!): PA_ColorSchema
	PA_ColorSchemaGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): PA_ColorSchemaConnection!
}

extend type Mutation {
	PA_ColorSchemaSave(Entity: PA_ColorSchemaInput!): PA_ColorSchema!
	PA_ColorSchemaSaveMany(Entities: [PA_ColorSchemaInput!]!): [PA_ColorSchema!]!
	PA_ColorSchemaDelete(UUs: [String!]!): Boolean!
}

type PA_ColorSchemaConnection {
	Results: [PA_ColorSchema!]!
	PagingInfo: PagingInfo!
}

type PA_ColorSchema {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# First color used
	AD_PrintColor1: AD_PrintColor!
	# Second color used
	AD_PrintColor2: AD_PrintColor!
	# Third color used
	AD_PrintColor3: AD_PrintColor
	# Forth color used
	AD_PrintColor4: AD_PrintColor
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# The record is active in the system
	IsActive: Boolean!
	# Percentage up to this color is used
	Mark1Percent: Int!
	# Percentage up to this color is used
	Mark2Percent: Int!
	# Percentage up to this color is used
	Mark3Percent: Int
	# Percentage up to this color is used
	Mark4Percent: Int
	# Alphanumeric identifier of the entity
	Name: String!
	UU: ID!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PA_ColorSchemaInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# First color used
	AD_PrintColor1: ForeignEntityInput
	# Second color used
	AD_PrintColor2: ForeignEntityInput
	# Third color used
	AD_PrintColor3: ForeignEntityInput
	# Forth color used
	AD_PrintColor4: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Percentage up to this color is used
	Mark1Percent: Int
	# Percentage up to this color is used
	Mark2Percent: Int
	# Percentage up to this color is used
	Mark3Percent: Int
	# Percentage up to this color is used
	Mark4Percent: Int
	# Alphanumeric identifier of the entity
	Name: String
	UU: ID
}
