# Generated Schema for PA_SLA_Measure - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	PA_SLA_MeasureGet(page: Int, size: Int, sort: String, filter: String): PA_SLA_MeasureConnection!
}

extend type Mutation {
	PA_SLA_MeasureSave(entity: PA_SLA_MeasureInput!): PA_SLA_Measure!
	PA_SLA_MeasureSaveMany(entities: [PA_SLA_MeasureInput!]!): [PA_SLA_Measure!]!
	PA_SLA_MeasureDelete(uuids: [String!]!): Boolean!
}

type PA_SLA_MeasureConnection {
	results: [PA_SLA_Measure!]!
	pagingInfo: PagingInfo!
}

type PA_SLA_Measure {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Transaction Date
	DateTrx: Date!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Actual value that has been measured.
	MeasureActual: BigDecimal!
	# Service Level Agreement Goal
	PA_SLA_Goal: PA_SLA_Goal!
	UUID: ID!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	# Direct internal record ID
	Record_ID: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PA_SLA_MeasureInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Transaction Date
	DateTrx: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Actual value that has been measured.
	MeasureActual: BigDecimal
	# Service Level Agreement Goal
	PA_SLA_Goal: ForeignEntityInput
	UUID: ID
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	# Direct internal record ID
	Record_ID: Int
}
