# Generated Schema for PA_Hierarchy - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	PA_Hierarchy(UU: String!): PA_Hierarchy
	PA_HierarchyGet(Page: Int, Size: Int, Sort: String, Filter: String): PA_HierarchyConnection!
}

extend type Mutation {
	PA_HierarchySave(Entity: PA_HierarchyInput!): PA_Hierarchy!
	PA_HierarchySaveMany(Entities: [PA_HierarchyInput!]!): [PA_Hierarchy!]!
	PA_HierarchyDelete(UUs: [String!]!): Boolean!
}

type PA_HierarchyConnection {
	Results: [PA_Hierarchy!]!
	PagingInfo: PagingInfo!
}

type PA_Hierarchy {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Tree for Natural Account Tree
	AD_Tree_Account: AD_Tree!
	# Trees are used for (financial) reporting
	AD_Tree_Activity: AD_Tree!
	# Trees are used for (financial) reporting
	AD_Tree_BPartner: AD_Tree!
	# Trees are used for (financial) reporting
	AD_Tree_Campaign: AD_Tree!
	# Trees are used for (financial) reporting and security access (via role)
	AD_Tree_Org: AD_Tree!
	# Trees are used for (financial) reporting
	AD_Tree_Product: AD_Tree!
	# Trees are used for (financial) reporting
	AD_Tree_Project: AD_Tree!
	# Trees are used for (financial) reporting
	AD_Tree_SalesRegion: AD_Tree!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	UU: ID!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PA_HierarchyInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Tree for Natural Account Tree
	AD_Tree_Account: ForeignEntityInput
	# Trees are used for (financial) reporting
	AD_Tree_Activity: ForeignEntityInput
	# Trees are used for (financial) reporting
	AD_Tree_BPartner: ForeignEntityInput
	# Trees are used for (financial) reporting
	AD_Tree_Campaign: ForeignEntityInput
	# Trees are used for (financial) reporting and security access (via role)
	AD_Tree_Org: ForeignEntityInput
	# Trees are used for (financial) reporting
	AD_Tree_Product: ForeignEntityInput
	# Trees are used for (financial) reporting
	AD_Tree_Project: ForeignEntityInput
	# Trees are used for (financial) reporting
	AD_Tree_SalesRegion: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	UU: ID
}
