# Generated Schema for PA_Measure - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	PA_MeasureGet(page: Int, size: Int, sort: String, filter: String): PA_MeasureConnection!
}

extend type Mutation {
	PA_MeasureSave(entity: PA_MeasureInput!): PA_Measure!
	PA_MeasureSaveMany(entities: [PA_MeasureInput!]!): [PA_Measure!]!
	PA_MeasureDelete(uuids: [String!]!): Boolean!
}

type PA_MeasureConnection {
	results: [PA_Measure!]!
	pagingInfo: PagingInfo!
}

type PA_Measure {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Type of the project
	C_ProjectType: C_ProjectType
	# Java Class for calculation, implementing Interface Measure
	CalculationClass: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Manually entered actual value
	ManualActual: BigDecimal
	# Note for manual entry
	ManualNote: String
	# Type of data - Status or in Time
	MeasureDataType: AD_Ref_List!
	# Determines how the actual performance is derived
	MeasureType: AD_Ref_List!
	# Alphanumeric identifier of the entity
	Name: String!
	# Performance Benchmark
	PA_Benchmark: PA_Benchmark
	# Optional Reporting Hierarchy - If not selected the default hierarchy trees are used.
	PA_Hierarchy: PA_Hierarchy
	UUID: ID!
	# Calculation method for measuring performance
	PA_MeasureCalc: PA_MeasureCalc
	# Performance Ratio
	PA_Ratio: PA_Ratio
	# Type of request (e.g. Inquiry, Complaint, ..)
	R_RequestType: R_RequestType
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PA_MeasureInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Type of the project
	C_ProjectType: ForeignEntityInput
	# Java Class for calculation, implementing Interface Measure
	CalculationClass: String
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Manually entered actual value
	ManualActual: BigDecimal
	# Note for manual entry
	ManualNote: String
	# Type of data - Status or in Time
	MeasureDataType: AD_Ref_ListInput
	# Determines how the actual performance is derived
	MeasureType: AD_Ref_ListInput
	# Alphanumeric identifier of the entity
	Name: String
	# Performance Benchmark
	PA_Benchmark: ForeignEntityInput
	# Optional Reporting Hierarchy - If not selected the default hierarchy trees are used.
	PA_Hierarchy: ForeignEntityInput
	UUID: ID
	# Calculation method for measuring performance
	PA_MeasureCalc: ForeignEntityInput
	# Performance Ratio
	PA_Ratio: ForeignEntityInput
	# Type of request (e.g. Inquiry, Complaint, ..)
	R_RequestType: ForeignEntityInput
}
