# Generated Schema for PP_Order_Workflow - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	PP_Order_WorkflowGet(page: Int, size: Int, sort: String, filter: String): PP_Order_WorkflowConnection!
}

extend type Mutation {
	PP_Order_WorkflowSave(entity: PP_Order_WorkflowInput!): PP_Order_Workflow!
	PP_Order_WorkflowDelete(uuids: [String!]!): Boolean!
}

type PP_Order_WorkflowConnection {
	results: [PP_Order_Workflow!]!
	pagingInfo: PagingInfo!
}

type PP_Order_Workflow {
	# Access Level required
	AccessLevel_RL: AD_Ref_List!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table
	# Workflow Node (activity), step or process
	AD_WF_Node: AD_WF_Node
	# Responsible for Workflow Execution
	AD_WF_Responsible: AD_WF_Responsible
	# Workflow or combination of tasks
	AD_Workflow: AD_Workflow!
	# Workflow Processor Server
	AD_WorkflowProcessor: AD_WorkflowProcessor
	# Author/Creator of the Entity
	Author: String!
	# Cost information
	Cost: Int!
	# Date this record was created
	Created: Date!
	# User who created this records
	Create: AD_User!
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String
	# Normal Duration in Duration Unit
	Duration: Int!
	# Unit of Duration
	DurationUnit_RL: AD_Ref_List!
	# Dictionary Entity Type; Determines ownership and synchronization
	EntityType: AD_EntityType!
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Default value
	IsDefault: Boolean!
	# Maximum Duration in Duration Unit
	Limit: Int!
	MovingTime: Int
	# Alphanumeric identifier of the entity
	Name: String!
	# Overlap Units are number of units that must be completed before they are moved the next activity
	OverlapUnits: Int
	# Manufacturing Order
	PP_Order: PP_Order!
	# Workflow Node (activity), step or process
	PP_Order_Node: PP_Order_Node
	ID: ID!
	# Indicates if this request is of a high, medium or low priority.
	Priority: Int!
	ProcessType_RL: AD_Ref_List
	# Status of Publication
	PublishStatus_RL: AD_Ref_List!
	QtyBatchSize: Int
	# Queue time is the time a job waits at a work center before begin handled.
	QueuingTime: Int
	# Resource
	S_Resource: S_Resource
	# Setup time before starting Production
	SetupTime: Int
	# The Units by Cycles are defined for process type  Flow Repetitive Dedicated and  indicated the product to be manufactured on a production line for duration unit.
	UnitsCycles: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	Update: AD_User!
	ValidateWorkflow: String
	# Valid from including this date (first day)
	ValidFrom: Date
	# Valid to including this date (last day)
	ValidTo: Date
	# Search key for the record in the format required - must be unique
	Value: String
	# Version of the table definition
	Version: Int!
	# Workflow Simulation Waiting time
	WaitingTime: Int!
	# Type of Workflow
	WorkflowType_RL: AD_Ref_List
	# Workflow Simulation Execution Time
	WorkingTime: Int
	# The Yield is the percentage of a lot that is expected to be of acceptable wuality may fall below 100 percent
	Yield: Int
}

input PP_Order_WorkflowInput {
	# Access Level required
	AccessLevel_RL: AD_Ref_ListInput
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Database Table information
	AD_Table: AD_TableInput
	# Workflow Node (activity), step or process
	AD_WF_Node: AD_WF_NodeInput
	# Responsible for Workflow Execution
	AD_WF_Responsible: AD_WF_ResponsibleInput
	# Workflow or combination of tasks
	AD_Workflow: AD_WorkflowInput
	# Workflow Processor Server
	AD_WorkflowProcessor: AD_WorkflowProcessorInput
	# Author/Creator of the Entity
	Author: String
	# Cost information
	Cost: Int
	# Optional short description of the record
	Description: String
	# Document sequence number of the document
	DocumentNo: String
	# Normal Duration in Duration Unit
	Duration: Int
	# Unit of Duration
	DurationUnit_RL: AD_Ref_ListInput
	# Dictionary Entity Type; Determines ownership and synchronization
	EntityType: AD_EntityTypeInput
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Default value
	IsDefault: Boolean
	# Maximum Duration in Duration Unit
	Limit: Int
	MovingTime: Int
	# Alphanumeric identifier of the entity
	Name: String
	# Overlap Units are number of units that must be completed before they are moved the next activity
	OverlapUnits: Int
	# Manufacturing Order
	PP_Order: PP_OrderInput
	# Workflow Node (activity), step or process
	PP_Order_Node: PP_Order_NodeInput
	ID: ID
	# Indicates if this request is of a high, medium or low priority.
	Priority: Int
	ProcessType_RL: AD_Ref_ListInput
	# Status of Publication
	PublishStatus_RL: AD_Ref_ListInput
	QtyBatchSize: Int
	# Queue time is the time a job waits at a work center before begin handled.
	QueuingTime: Int
	# Resource
	S_Resource: S_ResourceInput
	# Setup time before starting Production
	SetupTime: Int
	# The Units by Cycles are defined for process type  Flow Repetitive Dedicated and  indicated the product to be manufactured on a production line for duration unit.
	UnitsCycles: Int
	ValidateWorkflow: String
	# Valid from including this date (first day)
	ValidFrom: Date
	# Valid to including this date (last day)
	ValidTo: Date
	# Search key for the record in the format required - must be unique
	Value: String
	# Version of the table definition
	Version: Int
	# Workflow Simulation Waiting time
	WaitingTime: Int
	# Type of Workflow
	WorkflowType_RL: AD_Ref_ListInput
	# Workflow Simulation Execution Time
	WorkingTime: Int
	# The Yield is the percentage of a lot that is expected to be of acceptable wuality may fall below 100 percent
	Yield: Int
}
