# Generated Schema for PP_Order_Cost - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	PP_Order_CostGet(page: Int, size: Int, sort: String, filter: String): PP_Order_CostConnection!
}

type PP_Order_CostConnection {
	results: [PP_Order_Cost!]!
	pagingInfo: PagingInfo!
}

type PP_Order_Cost {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Workflow or combination of tasks
	AD_Workflow: AD_Workflow
	# Rules for accounting
	C_AcctSchema: C_AcctSchema!
	# Indicates how Costs will be calculated
	CostingMethod: AD_Ref_List
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Total Amount
	CumulatedAmt: Int
	CumulatedAmtPost: Int
	# Total Quantity
	CumulatedQty: Int
	CumulatedQtyPost: Int
	# The currently used cost price
	CurrentCostPrice: Int
	# Current Price Lower Level Is the sum of the costs of the components of this product manufactured for this level.
	CurrentCostPriceLL: Int
	# Current Quantity
	CurrentQty: Int
	# The record is active in the system
	IsActive: Boolean!
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance
	# Product Cost Element
	M_CostElement: M_CostElement
	# Type of Cost (e.g. Current, Plan, Future)
	M_CostType: M_CostType!
	# Product, Service, Item
	M_Product: M_Product!
	ID: ID!
	# Manufacturing Order
	PP_Order: PP_Order!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

