# Generated Schema for PP_Order_Node - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	PP_Order_NodeGet(page: Int, size: Int, sort: String, filter: String): PP_Order_NodeConnection!
}

type PP_Order_NodeConnection {
	results: [PP_Order_Node!]!
	pagingInfo: PagingInfo!
}

type PP_Order_Node {
	# Indicates the Action to be performed
	Action: AD_Ref_List!
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Column in the table
	AD_Column: AD_Column
	# Special Form
	AD_Form: AD_Form
	# Image or Icon
	AD_Image: AD_Image
	# Organizational entity within client
	AD_Org: AD_Org!
	# Process or Report
	AD_Process: AD_Process
	# Operation System Task
	AD_Task: AD_Task
	# Workflow Transaction Execution Block
	AD_WF_Block: AD_WF_Block
	# Workflow Node (activity), step or process
	AD_WF_Node: AD_WF_Node!
	# Responsible for Workflow Execution
	AD_WF_Responsible: AD_WF_Responsible
	# Data entry or display window
	AD_Window: AD_Window
	# Workflow or combination of tasks
	AD_Workflow: AD_Workflow!
	# Name of the Attribute
	AttributeName: String
	# Value of the Attribute
	AttributeValue: String
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Cost information
	Cost: Int!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Finish or (planned) completion date
	DateFinish: Date
	# Scheduled Finish date for this Order
	DateFinishSchedule: Date
	# Date Start for this Order
	DateStart: Date
	# Scheduled start date for this Order
	DateStartSchedule: Date
	# Optional short description of the record
	Description: String
	# The targeted status of the document
	DocAction: AD_Ref_List
	# The current status of the document
	DocStatus: AD_Ref_List
	# Normal Duration in Duration Unit
	Duration: Int
	DurationReal: Int
	DurationRequiered: Int
	# Dictionary Entity Type; Determines ownership and synchronization
	AD_EntityType: AD_EntityType!
	# Workflow Activity Finish Mode
	FinishMode: AD_Ref_List
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Information maintained in System Element table
	IsCentrallyMaintained: Boolean!
	IsMilestone: Boolean!
	IsSubcontracting: Boolean!
	# Semantics for multiple incoming Transitions
	JoinElement: AD_Ref_List!
	# Maximum Duration in Duration Unit
	Limit: Int!
	MovingTime: Int
	# Alphanumeric identifier of the entity
	Name: String!
	# Overlap Units are number of units that must be completed before they are moved the next activity
	OverlapUnits: Int
	# Manufacturing Order
	PP_Order: PP_Order!
	ID: ID!
	PP_Order_Workflow: PP_Order_Workflow!
	# Indicates if this request is of a high, medium or low priority.
	Priority: Int!
	# Delivered Quantity
	QtyDelivered: Int
	QtyReject: Int
	QtyRequiered: Int
	# Scrap % Quantity for this componet
	QtyScrap: Int
	# Queue time is the time a job waits at a work center before begin handled.
	QueuingTime: Int
	# Resource
	S_Resource: S_Resource
	# Setup time before starting Production
	SetupTime: Int
	SetupTimeReal: Int
	SetupTimeRequiered: Int
	# Semantics for multiple outgoing Transitions
	SplitElement: AD_Ref_List!
	# Workflow Activity Start Mode 
	StartMode: AD_Ref_List
	# Mode how the sub-workflow is executed
	SubflowExecution: AD_Ref_List
	# The Units by Cycles are defined for process type  Flow Repetitive Dedicated and  indicated the product to be manufactured on a production line for duration unit.
	UnitsCycles: Int
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Valid from including this date (first day)
	ValidFrom: Date
	# Valid to including this date (last day)
	ValidTo: Date
	# Search key for the record in the format required - must be unique
	Value: String!
	# Workflow Simulation Waiting time
	WaitingTime: Int!
	# Workflow or tasks
	Workflow: AD_Workflow
	# Workflow Simulation Execution Time
	WorkingTime: Int!
	# Absolute X (horizontal) position in 1/72 of an inch
	XPosition: Int!
	# The Yield is the percentage of a lot that is expected to be of acceptable wuality may fall below 100 percent
	Yield: Int
	# Absolute Y (vertical) position in 1/72 of an inch
	YPosition: Int!
}

