# Generated Schema for PP_Order_BOMLine - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	PP_Order_BOMLineGet(page: Int, size: Int, sort: String, filter: String): PP_Order_BOMLineConnection!
}

extend type Mutation {
	PP_Order_BOMLineSave(entity: PP_Order_BOMLineInput!): PP_Order_BOMLine!
	PP_Order_BOMLineSaveMany(entities: [PP_Order_BOMLineInput!]!): [PP_Order_BOMLine!]!
	PP_Order_BOMLineDelete(uuids: [String!]!): Boolean!
}

type PP_Order_BOMLineConnection {
	results: [PP_Order_BOMLine!]!
	pagingInfo: PagingInfo!
}

type PP_Order_BOMLine {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Indicated the Quantity Assay to use into Quality Order
	Assay: BigDecimal
	# The Grouping Components to the Backflush
	BackflushGroup: String
	# Unit of Measure
	C_UOM: C_UOM!
	# Component Type for a Bill of Material or Formula
	ComponentType: AD_Ref_List
	# Cost allocation percent in case of a co-product.
	CostAllocationPerc: BigDecimal
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Date when the product was delivered
	DateDelivered: Date
	# Optional short description of the record
	Description: String
	# Indicated the Feature for Product Configure
	Feature: String
	# Indicated the % of participation this component into a of the BOM Planning
	Forecast: BigDecimal
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Indicate that a Manufacturing Order can not begin without have this component
	IsCritical: Boolean!
	# Indicate that this component is based in % Quantity
	IsQtyPercentage: Boolean!
	# There are two methods for issue the components to Manufacturing Order
	IssueMethod: AD_Ref_List
	# Optional Lead Time offset before starting production
	LeadTimeOffset: Int
	# Unique line for this document
	Line: Int!
	# Product Attribute Set Instance
	M_AttributeSetInstance: M_AttributeSetInstance
	# Bill of Materials (Engineering) Change Notice (Version)
	M_ChangeNotice: M_ChangeNotice
	# Warehouse Locator
	M_Locator: M_Locator
	# Product, Service, Item
	M_Product: M_Product!
	# Storage Warehouse and Service Point
	M_Warehouse: M_Warehouse!
	PP_Order_BOM: PP_Order_BOM!
	UUID: ID!
	PP_Order_BOMLine_UU: String
	# Manufacturing Order
	PP_Order: PP_Order!
	# Indicate the Quantity % use in this Formula
	QtyBatch: BigDecimal!
	# Indicate the Quantity  use in this BOM
	QtyBOM: BigDecimal!
	# Delivered Quantity
	QtyDelivered: BigDecimal!
	# The Quantity Entered is based on the selected UoM
	QtyEntered: BigDecimal
	QtyPost: BigDecimal!
	QtyReject: BigDecimal!
	QtyRequiered: BigDecimal!
	# Reserved Quantity
	QtyReserved: BigDecimal!
	# Scrap % Quantity for this component
	QtyScrap: BigDecimal!
	# Indicate the Scrap %  for calculate the Scrap Quantity
	Scrap: BigDecimal
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Valid from including this date (first day)
	ValidFrom: Date!
	# Valid to including this date (last day)
	ValidTo: Date
}

input PP_Order_BOMLineInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Indicated the Quantity Assay to use into Quality Order
	Assay: BigDecimal
	# The Grouping Components to the Backflush
	BackflushGroup: String
	# Unit of Measure
	C_UOM: ForeignEntityInput
	# Component Type for a Bill of Material or Formula
	ComponentType: AD_Ref_ListInput
	# Cost allocation percent in case of a co-product.
	CostAllocationPerc: BigDecimal
	# Date when the product was delivered
	DateDelivered: Date
	# Optional short description of the record
	Description: String
	# Indicated the Feature for Product Configure
	Feature: String
	# Indicated the % of participation this component into a of the BOM Planning
	Forecast: BigDecimal
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Indicate that a Manufacturing Order can not begin without have this component
	IsCritical: Boolean
	# Indicate that this component is based in % Quantity
	IsQtyPercentage: Boolean
	# There are two methods for issue the components to Manufacturing Order
	IssueMethod: AD_Ref_ListInput
	# Optional Lead Time offset before starting production
	LeadTimeOffset: Int
	# Unique line for this document
	Line: Int
	# Product Attribute Set Instance
	M_AttributeSetInstance: ForeignEntityInput
	# Bill of Materials (Engineering) Change Notice (Version)
	M_ChangeNotice: ForeignEntityInput
	# Warehouse Locator
	M_Locator: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Storage Warehouse and Service Point
	M_Warehouse: ForeignEntityInput
	PP_Order_BOM: ForeignEntityInput
	UUID: ID
	PP_Order_BOMLine_UU: String
	# Manufacturing Order
	PP_Order: ForeignEntityInput
	# Indicate the Quantity % use in this Formula
	QtyBatch: BigDecimal
	# Indicate the Quantity  use in this BOM
	QtyBOM: BigDecimal
	# Delivered Quantity
	QtyDelivered: BigDecimal
	# The Quantity Entered is based on the selected UoM
	QtyEntered: BigDecimal
	QtyPost: BigDecimal
	QtyReject: BigDecimal
	QtyRequiered: BigDecimal
	# Reserved Quantity
	QtyReserved: BigDecimal
	# Scrap % Quantity for this component
	QtyScrap: BigDecimal
	# Indicate the Scrap %  for calculate the Scrap Quantity
	Scrap: BigDecimal
	# Valid from including this date (first day)
	ValidFrom: Date
	# Valid to including this date (last day)
	ValidTo: Date
}
