# Generated Schema for PP_Order_Node_Product - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	PP_Order_Node_Product(UU: String!): PP_Order_Node_Product
	PP_Order_Node_ProductGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): PP_Order_Node_ProductConnection!
}

extend type Mutation {
	PP_Order_Node_ProductSave(Entity: PP_Order_Node_ProductInput!): PP_Order_Node_Product!
	PP_Order_Node_ProductSaveMany(Entities: [PP_Order_Node_ProductInput!]!): [PP_Order_Node_Product!]!
	PP_Order_Node_ProductDelete(UUs: [String!]!): Boolean!
}

type PP_Order_Node_ProductConnection {
	Results: [PP_Order_Node_Product!]!
	PagingInfo: PagingInfo!
}

type PP_Order_Node_Product {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	IsSubcontracting: Boolean!
	# Product, Service, Item
	M_Product: M_Product!
	# Manufacturing Order
	PP_Order: PP_Order!
	# Workflow Node (activity), step or process
	PP_Order_Node: PP_Order_Node!
	UU: ID!
	PP_Order_Workflow: PP_Order_Workflow!
	# Quantity
	Qty: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PP_Order_Node_ProductInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	IsSubcontracting: Boolean
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Manufacturing Order
	PP_Order: ForeignEntityInput
	# Workflow Node (activity), step or process
	PP_Order_Node: ForeignEntityInput
	UU: ID
	PP_Order_Workflow: ForeignEntityInput
	# Quantity
	Qty: BigDecimal
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
