# Generated Schema for PP_WF_Node_Asset - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	PP_WF_Node_Asset(UU: String!): PP_WF_Node_Asset
	PP_WF_Node_AssetGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): PP_WF_Node_AssetConnection!
}

extend type Mutation {
	PP_WF_Node_AssetSave(Entity: PP_WF_Node_AssetInput!): PP_WF_Node_Asset!
	PP_WF_Node_AssetSaveMany(Entities: [PP_WF_Node_AssetInput!]!): [PP_WF_Node_Asset!]!
	PP_WF_Node_AssetDelete(UUs: [String!]!): Boolean!
}

type PP_WF_Node_AssetConnection {
	Results: [PP_WF_Node_Asset!]!
	PagingInfo: PagingInfo!
}

type PP_WF_Node_Asset {
	# Asset used internally or by customers
	A_Asset: A_Asset!
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Workflow Node (activity), step or process
	AD_WF_Node: AD_WF_Node!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	UU: ID!
	# Method of ordering records; lowest number comes first
	SeqNo: Int!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input PP_WF_Node_AssetInput {
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Workflow Node (activity), step or process
	AD_WF_Node: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	UU: ID
	# Method of ordering records; lowest number comes first
	SeqNo: Int
}
