# Generated Schema for R_ContactInterest - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	R_ContactInterestGet(page: Int, size: Int, sort: String, filter: String): R_ContactInterestConnection!
}

extend type Mutation {
	R_ContactInterestSave(entity: R_ContactInterestInput!): R_ContactInterest!
	R_ContactInterestSaveMany(entities: [R_ContactInterestInput!]!): [R_ContactInterest!]!
	R_ContactInterestDelete(uuids: [String!]!): Boolean!
}

type R_ContactInterestConnection {
	results: [R_ContactInterest!]!
	pagingInfo: PagingInfo!
}

type R_ContactInterest {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Date the contact opted out
	OptOutDate: Date
	UUID: ID!
	R_ContactInterest_UU: String
	# Interest Area or Topic
	R_InterestArea: R_InterestArea!
	# Date the contact actively subscribed
	SubscribeDate: Date
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input R_ContactInterestInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Date the contact opted out
	OptOutDate: Date
	UUID: ID
	R_ContactInterest_UU: String
	# Interest Area or Topic
	R_InterestArea: ForeignEntityInput
	# Date the contact actively subscribed
	SubscribeDate: Date
}
