# Generated Schema for R_InterestArea - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	R_InterestArea(UU: String!): R_InterestArea
	R_InterestAreaGet(Page: Int, Size: Int, Sort: String, Filter: String): R_InterestAreaConnection!
}

extend type Mutation {
	R_InterestAreaSave(Entity: R_InterestAreaInput!): R_InterestArea!
	R_InterestAreaSaveMany(Entities: [R_InterestAreaInput!]!): [R_InterestArea!]!
	R_InterestAreaDelete(UUs: [String!]!): Boolean!
}

type R_InterestAreaConnection {
	Results: [R_InterestArea!]!
	PagingInfo: PagingInfo!
}

type R_InterestArea {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	UU: ID!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
}

input R_InterestAreaInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	UU: ID
	# Search key for the record in the format required - must be unique
	Value: String
}
