# Generated Schema for R_GroupUpdates - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	R_GroupUpdates(UU: String!): R_GroupUpdates
	R_GroupUpdatesGet(Page: Int, Size: Int, Sort: String, Filter: String): R_GroupUpdatesConnection!
}

extend type Mutation {
	R_GroupUpdatesSave(Entity: R_GroupUpdatesInput!): R_GroupUpdates!
	R_GroupUpdatesSaveMany(Entities: [R_GroupUpdatesInput!]!): [R_GroupUpdates!]!
	R_GroupUpdatesDelete(UUs: [String!]!): Boolean!
}

type R_GroupUpdatesConnection {
	Results: [R_GroupUpdates!]!
	PagingInfo: PagingInfo!
}

type R_GroupUpdates {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	# Request Group
	R_Group: R_Group!
	UU: ID!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input R_GroupUpdatesInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	# Request Group
	R_Group: ForeignEntityInput
	UU: ID
}
