# Generated Schema for R_Request - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	R_Request(UU: String!): R_Request
	R_RequestGet(Page: Int, Size: Int, Sort: String, Filter: String): R_RequestConnection!
}

extend type Mutation {
	R_RequestSave(Entity: R_RequestInput!): R_Request!
	R_RequestSaveMany(Entities: [R_RequestInput!]!): [R_Request!]!
	R_RequestDelete(UUs: [String!]!): Boolean!
}

type R_RequestConnection {
	Results: [R_Request!]!
	PagingInfo: PagingInfo!
}

type R_Request {
	# Asset used internally or by customers
	A_Asset: A_Asset
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Responsibility Role
	AD_Role: AD_Role
	# Database Table information
	AD_Table: AD_Table
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	# Business Activity
	C_Activity: C_Activity
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Marketing Campaign
	C_Campaign: C_Campaign
	# Invoice Identifier
	C_Invoice: C_Invoice
	# The generated invoice for this request
	C_InvoiceRequest: C_Invoice
	# Close Date
	CloseDate: DateTime
	# Type of Confidentiality
	ConfidentialType: AD_Ref_List!
	# Confidentiality of the individual entry
	ConfidentialTypeEntry: AD_Ref_List!
	# Order
	C_Order: C_Order
	# Payment identifier
	C_Payment: C_Payment
	# Financial Project
	C_Project: C_Project
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Planned Completion Date
	DateCompletePlan: DateTime
	# Date this request was last acted on
	DateLastAction: DateTime
	# Date when last alert were sent
	DateLastAlert: DateTime
	# Date that this request should be acted on
	DateNextAction: DateTime
	# Planned Start Date
	DateStartPlan: DateTime
	# Document sequence number of the document
	DocumentNo: String!
	# Status of the next action for this Request
	DueType: AD_Ref_List!
	# End of the time span
	EndTime: DateTime
	# The record is active in the system
	IsActive: Boolean!
	# This request has been escalated
	IsEscalated: Boolean!
	# Is this invoiced?
	IsInvoiced: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	# Result of last contact
	LastResult: String
	# BOM (Engineering) Change Request
	M_ChangeRequest: M_ChangeRequest
	# Fixed in Change Notice
	M_FixChangeNotice: M_ChangeNotice
	# Material Shipment Document
	M_InOut: M_InOut
	# Product, Service, Item
	M_Product: M_Product
	# Product/Resource/Service used in Request
	M_ProductSpent: M_Product
	# Return Material Authorization
	M_RMA: M_RMA
	# Next Action to be taken
	NextAction: AD_Ref_List
	# Indicates if this request is of a high, medium or low priority.
	Priority: AD_Ref_List!
	# Priority of the issue for the User
	PriorityUser: AD_Ref_List
	# The document has been processed
	Processed: Boolean!
	# Invoiced Quantity
	QtyInvoiced: BigDecimal
	# Planned Quantity
	QtyPlan: BigDecimal
	# Quantity used for this event
	QtySpent: BigDecimal
	# Request Category
	R_Category: R_Category
	# Amount associated with this request
	RequestAmt: BigDecimal!
	# Result of the action taken
	Result: String
	# Request Group
	R_Group: R_Group
	# Text templates for mailings
	R_MailText: R_MailText
	# Related Request (Master Issue, ..)
	R_RequestRelated: R_Request
	# Type of request (e.g. Inquiry, Complaint, ..)
	R_RequestType: R_RequestType!
	UU: ID!
	# Request Resolution
	R_Resolution: R_Resolution
	# Request Standard Response 
	R_StandardResponse: R_StandardResponse
	# Request Status
	R_Status: R_Status
	# Sales Representative or Company Agent
	SalesRep: AD_User
	# First effective day (inclusive)
	StartDate: DateTime
	# Time started
	StartTime: DateTime
	# Textual summary of this request
	Summary: String!
	# Status of the Task
	TaskStatus: AD_Ref_List
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input R_RequestInput {
	# Asset used internally or by customers
	A_Asset: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Responsibility Role
	AD_Role: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	# Business Activity
	C_Activity: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Marketing Campaign
	C_Campaign: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# The generated invoice for this request
	C_InvoiceRequest: ForeignEntityInput
	# Close Date
	CloseDate: DateTime
	# Type of Confidentiality
	ConfidentialType: ForeignEntityInput
	# Confidentiality of the individual entry
	ConfidentialTypeEntry: ForeignEntityInput
	# Order
	C_Order: ForeignEntityInput
	# Payment identifier
	C_Payment: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	# Planned Completion Date
	DateCompletePlan: DateTime
	# Date this request was last acted on
	DateLastAction: DateTime
	# Date when last alert were sent
	DateLastAlert: DateTime
	# Date that this request should be acted on
	DateNextAction: DateTime
	# Planned Start Date
	DateStartPlan: DateTime
	# Document sequence number of the document
	DocumentNo: String
	# Status of the next action for this Request
	DueType: ForeignEntityInput
	# End of the time span
	EndTime: DateTime
	# The record is active in the system
	IsActive: Boolean
	# This request has been escalated
	IsEscalated: Boolean
	# Is this invoiced?
	IsInvoiced: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	# Result of last contact
	LastResult: String
	# BOM (Engineering) Change Request
	M_ChangeRequest: ForeignEntityInput
	# Fixed in Change Notice
	M_FixChangeNotice: ForeignEntityInput
	# Material Shipment Document
	M_InOut: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Product/Resource/Service used in Request
	M_ProductSpent: ForeignEntityInput
	# Return Material Authorization
	M_RMA: ForeignEntityInput
	# Next Action to be taken
	NextAction: ForeignEntityInput
	# Indicates if this request is of a high, medium or low priority.
	Priority: ForeignEntityInput
	# Priority of the issue for the User
	PriorityUser: ForeignEntityInput
	# The document has been processed
	Processed: Boolean
	# Invoiced Quantity
	QtyInvoiced: BigDecimal
	# Planned Quantity
	QtyPlan: BigDecimal
	# Quantity used for this event
	QtySpent: BigDecimal
	# Request Category
	R_Category: ForeignEntityInput
	# Amount associated with this request
	RequestAmt: BigDecimal
	# Result of the action taken
	Result: String
	# Request Group
	R_Group: ForeignEntityInput
	# Text templates for mailings
	R_MailText: ForeignEntityInput
	# Related Request (Master Issue, ..)
	R_RequestRelated: ForeignEntityInput
	# Type of request (e.g. Inquiry, Complaint, ..)
	R_RequestType: ForeignEntityInput
	UU: ID
	# Request Resolution
	R_Resolution: ForeignEntityInput
	# Request Standard Response 
	R_StandardResponse: ForeignEntityInput
	# Request Status
	R_Status: ForeignEntityInput
	# Sales Representative or Company Agent
	SalesRep: ForeignEntityInput
	# First effective day (inclusive)
	StartDate: DateTime
	# Time started
	StartTime: DateTime
	# Textual summary of this request
	Summary: String
	# Status of the Task
	TaskStatus: ForeignEntityInput
}
