# Generated Schema for R_RequestUpdate - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	R_RequestUpdate(UU: String!): R_RequestUpdate
	R_RequestUpdateGet(Page: Int, Size: Int, Sort: String, Filter: String): R_RequestUpdateConnection!
}

extend type Mutation {
	R_RequestUpdateSave(Entity: R_RequestUpdateInput!): R_RequestUpdate!
	R_RequestUpdateSaveMany(Entities: [R_RequestUpdateInput!]!): [R_RequestUpdate!]!
	R_RequestUpdateDelete(UUs: [String!]!): Boolean!
}

type R_RequestUpdateConnection {
	Results: [R_RequestUpdate!]!
	PagingInfo: PagingInfo!
}

type R_RequestUpdate {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Confidentiality of the individual entry
	ConfidentialTypeEntry: AD_Ref_List!
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# End of the time span
	EndTime: DateTime
	# The record is active in the system
	IsActive: Boolean!
	# Product/Resource/Service used in Request
	M_ProductSpent: M_Product
	# Invoiced Quantity
	QtyInvoiced: BigDecimal
	# Quantity used for this event
	QtySpent: BigDecimal
	# Result of the action taken
	Result: String
	# Request from a Business Partner or Prospect
	R_Request: R_Request!
	UU: ID!
	# Time started
	StartTime: DateTime
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input R_RequestUpdateInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Confidentiality of the individual entry
	ConfidentialTypeEntry: ForeignEntityInput
	# End of the time span
	EndTime: DateTime
	# The record is active in the system
	IsActive: Boolean
	# Product/Resource/Service used in Request
	M_ProductSpent: ForeignEntityInput
	# Invoiced Quantity
	QtyInvoiced: BigDecimal
	# Quantity used for this event
	QtySpent: BigDecimal
	# Result of the action taken
	Result: String
	# Request from a Business Partner or Prospect
	R_Request: ForeignEntityInput
	UU: ID
	# Time started
	StartTime: DateTime
}
