# Generated Schema for R_RequestType - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	R_RequestTypeGet(page: Int, size: Int, sort: String, filter: String): R_RequestTypeConnection!
}

extend type Mutation {
	R_RequestTypeSave(entity: R_RequestTypeInput!): R_RequestType!
	R_RequestTypeDelete(uuids: [String!]!): Boolean!
}

type R_RequestTypeConnection {
	results: [R_RequestType!]!
	pagingInfo: PagingInfo!
}

type R_RequestType {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Automatic Due Date Days
	AutoDueDateDays: Int
	# Type of Confidentiality
	ConfidentialType: AD_Ref_List!
	# Content color of calendar dashlet
	ContentColor: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Tolerance in days between the Date Next Action and the date the request is regarded as overdue
	DueDateTolerance: Int!
	# Header color of calendar dashlet
	HeaderColor: String
	# The record is active in the system
	IsActive: Boolean!
	# Automatically create BOM (Engineering) Change Request
	IsAutoChangeRequest: Boolean!
	# Can enter confidential information
	IsConfidentialInfo: Boolean!
	# Default value
	IsDefault: Boolean!
	# Send EMail when Request becomes due
	IsEMailWhenDue: Boolean!
	# Send EMail when Request becomes overdue
	IsEMailWhenOverdue: Boolean!
	# Index the document for the internal search engine
	IsIndexed: Boolean!
	# Is this invoiced?
	IsInvoiced: Boolean!
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	ID: ID!
	# Request Status Category
	R_StatusCategory: R_StatusCategory!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input R_RequestTypeInput {
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Automatic Due Date Days
	AutoDueDateDays: Int
	# Type of Confidentiality
	ConfidentialType: AD_Ref_ListInput
	# Content color of calendar dashlet
	ContentColor: String
	# Optional short description of the record
	Description: String
	# Tolerance in days between the Date Next Action and the date the request is regarded as overdue
	DueDateTolerance: Int
	# Header color of calendar dashlet
	HeaderColor: String
	# The record is active in the system
	IsActive: Boolean
	# Automatically create BOM (Engineering) Change Request
	IsAutoChangeRequest: Boolean
	# Can enter confidential information
	IsConfidentialInfo: Boolean
	# Default value
	IsDefault: Boolean
	# Send EMail when Request becomes due
	IsEMailWhenDue: Boolean
	# Send EMail when Request becomes overdue
	IsEMailWhenOverdue: Boolean
	# Index the document for the internal search engine
	IsIndexed: Boolean
	# Is this invoiced?
	IsInvoiced: Boolean
	# This is a Self-Service entry or this entry can be changed via Self-Service
	IsSelfService: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	ID: ID
	# Request Status Category
	R_StatusCategory: R_StatusCategoryInput
}
