# Generated Schema for R_StandardResponse - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	R_StandardResponseGet(page: Int, size: Int, sort: String, filter: String): R_StandardResponseConnection!
}

extend type Mutation {
	R_StandardResponseSave(entity: R_StandardResponseInput!): R_StandardResponse!
	R_StandardResponseSaveMany(entities: [R_StandardResponseInput!]!): [R_StandardResponse!]!
	R_StandardResponseDelete(uuids: [String!]!): Boolean!
}

type R_StandardResponseConnection {
	results: [R_StandardResponse!]!
	pagingInfo: PagingInfo!
}

type R_StandardResponse {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	UUID: ID!
	# Request Response Text
	ResponseText: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input R_StandardResponseInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	UUID: ID
	# Request Response Text
	ResponseText: String
}
