# Generated Schema for R_Resolution - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	R_Resolution(UU: String!): R_Resolution
	R_ResolutionGet(Page: Int, Size: Int, Sort: String, Filter: String): R_ResolutionConnection!
}

extend type Mutation {
	R_ResolutionSave(Entity: R_ResolutionInput!): R_Resolution!
	R_ResolutionSaveMany(Entities: [R_ResolutionInput!]!): [R_Resolution!]!
	R_ResolutionDelete(UUs: [String!]!): Boolean!
}

type R_ResolutionConnection {
	Results: [R_Resolution!]!
	PagingInfo: PagingInfo!
}

type R_Resolution {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	UU: ID!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input R_ResolutionInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	UU: ID
}
