# Generated Schema for S_ResourceAssignment - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 12 - $Id$
extend type Query {
	S_ResourceAssignment(UU: String!): S_ResourceAssignment
	S_ResourceAssignmentGet(Page: Int, Size: Int, Sort: String, Filter: String, Where: String, Parameters: [Object!]): S_ResourceAssignmentConnection!
}

extend type Mutation {
	S_ResourceAssignmentSave(Entity: S_ResourceAssignmentInput!): S_ResourceAssignment!
	S_ResourceAssignmentSaveMany(Entities: [S_ResourceAssignmentInput!]!): [S_ResourceAssignment!]!
	S_ResourceAssignmentDelete(UUs: [String!]!): Boolean!
}

type S_ResourceAssignmentConnection {
	Results: [S_ResourceAssignment!]!
	PagingInfo: PagingInfo!
}

type S_ResourceAssignment {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Assign resource from
	AssignDateFrom: DateTime!
	# Assign resource until
	AssignDateTo: DateTime
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Assignment is confirmed
	IsConfirmed: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Quantity
	Qty: BigDecimal
	# Resource
	S_Resource: S_Resource!
	UU: ID!
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input S_ResourceAssignmentInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Assign resource from
	AssignDateFrom: DateTime
	# Assign resource until
	AssignDateTo: DateTime
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Assignment is confirmed
	IsConfirmed: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Quantity
	Qty: BigDecimal
	# Resource
	S_Resource: ForeignEntityInput
	UU: ID
}
