# Generated Schema for S_Resource - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	S_ResourceGet(page: Int, size: Int, sort: String, filter: String): S_ResourceConnection!
}

extend type Mutation {
	S_ResourceSave(entity: S_ResourceInput!): S_Resource!
	S_ResourceSaveMany(entities: [S_ResourceInput!]!): [S_Resource!]!
	S_ResourceDelete(uuids: [String!]!): Boolean!
}

type S_ResourceConnection {
	results: [S_Resource!]!
	pagingInfo: PagingInfo!
}

type S_Resource {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# User within the system - Internal or Business Partner Contact
	AD_User: AD_User
	ChargeableQty: BigDecimal
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	DailyCapacity: BigDecimal
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Resource is available
	IsAvailable: Boolean!
	IsManufacturingResource: Boolean!
	# Storage Warehouse and Service Point
	M_Warehouse: M_Warehouse!
	ManufacturingResourceType: AD_Ref_List
	# Alphanumeric identifier of the entity
	Name: String!
	PercentUtilization: BigDecimal!
	# The planning horizon is the amount of time (Days) an organisation will look into the future when preparing a strategic plan.
	PlanningHorizon: Int
	# Queue time is the time a job waits at a work center before begin handled.
	QueuingTime: BigDecimal
	UUID: ID!
	S_ResourceType: S_ResourceType!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
	# Workflow Simulation Waiting time
	WaitingTime: BigDecimal
}

input S_ResourceInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# User within the system - Internal or Business Partner Contact
	AD_User: ForeignEntityInput
	ChargeableQty: BigDecimal
	DailyCapacity: BigDecimal
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Resource is available
	IsAvailable: Boolean
	IsManufacturingResource: Boolean
	# Storage Warehouse and Service Point
	M_Warehouse: ForeignEntityInput
	ManufacturingResourceType: AD_Ref_ListInput
	# Alphanumeric identifier of the entity
	Name: String
	PercentUtilization: BigDecimal
	# The planning horizon is the amount of time (Days) an organisation will look into the future when preparing a strategic plan.
	PlanningHorizon: Int
	# Queue time is the time a job waits at a work center before begin handled.
	QueuingTime: BigDecimal
	UUID: ID
	S_ResourceType: ForeignEntityInput
	# Search key for the record in the format required - must be unique
	Value: String
	# Workflow Simulation Waiting time
	WaitingTime: BigDecimal
}
