# Generated Schema for S_ResourceAssignment - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	S_ResourceAssignmentGet(page: Int, size: Int, sort: String, filter: String): S_ResourceAssignmentConnection!
}

extend type Mutation {
	S_ResourceAssignmentSave(entity: S_ResourceAssignmentInput!): S_ResourceAssignment!
	S_ResourceAssignmentDelete(uuids: [String!]!): Boolean!
}

type S_ResourceAssignmentConnection {
	results: [S_ResourceAssignment!]!
	pagingInfo: PagingInfo!
}

type S_ResourceAssignment {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Assign resource from
	AssignDateFrom: Date!
	# Assign resource until
	AssignDateTo: Date
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# Assignment is confirmed
	IsConfirmed: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Quantity
	Qty: Int
	# Resource
	S_Resource: S_Resource!
	ID: ID!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input S_ResourceAssignmentInput {
	# Organizational entity within client
	AD_Org: AD_OrgInput
	# Assign resource from
	AssignDateFrom: Date
	# Assign resource until
	AssignDateTo: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# Assignment is confirmed
	IsConfirmed: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Quantity
	Qty: Int
	# Resource
	S_Resource: S_ResourceInput
	ID: ID
}
