# Generated Schema for T_BankRegister - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	T_BankRegisterGet(page: Int, size: Int, sort: String, filter: String): T_BankRegisterConnection!
}

extend type Mutation {
	T_BankRegisterSave(entity: T_BankRegisterInput!): T_BankRegister!
	T_BankRegisterDelete(uuids: [String!]!): Boolean!
}

type T_BankRegisterConnection {
	results: [T_BankRegister!]!
	pagingInfo: PagingInfo!
}

type T_BankRegister {
	Account: String
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Instance of the process
	AD_PInstance: AD_PInstance!
	# Accounted Credit Amount
	AmtAcctCr: BigDecimal
	# Accounted Debit Amount
	AmtAcctDr: BigDecimal
	Balance: BigDecimal
	BankName: String
	BPartner: String
	# Bank
	C_Bank: C_Bank
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Accounting Date
	DateAcct: Date
	# Document sequence number of the document
	DocumentNo: String
	ID: ID!
}

input T_BankRegisterInput {
	Account: String
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Instance of the process
	AD_PInstance: ForeignEntityInput
	# Accounted Credit Amount
	AmtAcctCr: BigDecimal
	# Accounted Debit Amount
	AmtAcctDr: BigDecimal
	Balance: BigDecimal
	BankName: String
	BPartner: String
	# Bank
	C_Bank: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Accounting Date
	DateAcct: Date
	# Document sequence number of the document
	DocumentNo: String
	ID: ID
}
