# Generated Schema for T_Replenish - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	T_ReplenishGet(page: Int, size: Int, sort: String, filter: String): T_ReplenishConnection!
}

extend type Mutation {
	T_ReplenishSave(entity: T_ReplenishInput!): T_Replenish!
	T_ReplenishDelete(uuids: [String!]!): Boolean!
}

type T_ReplenishConnection {
	results: [T_Replenish!]!
	pagingInfo: PagingInfo!
}

type T_Replenish {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Instance of the process
	AD_PInstance: AD_PInstance!
	# Identifies a Business Partner
	C_BPartner: C_BPartner!
	# Document type or rules
	C_DocType: C_DocType
	# Maximum Inventory level for this product
	Level_Max: Int!
	# Minimum Inventory level for this product
	Level_Min: Int!
	# Product, Service, Item
	M_Product: M_Product!
	# Storage Warehouse and Service Point
	M_Warehouse: M_Warehouse!
	# Optional Warehouse to replenish from
	M_WarehouseSource: M_Warehouse
	# Minimum order quantity in UOM
	Order_Min: Int
	# Package order size in UOM (e.g. order set of 5 units)
	Order_Pack: Int
	# On Hand Quantity
	QtyOnHand: Int
	# Ordered Quantity
	QtyOrdered: Int
	# Reserved Quantity
	QtyReserved: Int
	QtyToOrder: Int
	# Create from Replenishment
	ReplenishmentCreate: AD_Ref_List
	# Method for re-ordering a product
	ReplenishType: AD_Ref_List!
	ID: ID!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input T_ReplenishInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Instance of the process
	AD_PInstance: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Document type or rules
	C_DocType: ForeignEntityInput
	# Maximum Inventory level for this product
	Level_Max: Int
	# Minimum Inventory level for this product
	Level_Min: Int
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Storage Warehouse and Service Point
	M_Warehouse: ForeignEntityInput
	# Optional Warehouse to replenish from
	M_WarehouseSource: ForeignEntityInput
	# Minimum order quantity in UOM
	Order_Min: Int
	# Package order size in UOM (e.g. order set of 5 units)
	Order_Pack: Int
	# On Hand Quantity
	QtyOnHand: Int
	# Ordered Quantity
	QtyOrdered: Int
	# Reserved Quantity
	QtyReserved: Int
	QtyToOrder: Int
	# Create from Replenishment
	ReplenishmentCreate: AD_Ref_ListInput
	# Method for re-ordering a product
	ReplenishType: AD_Ref_ListInput
	ID: ID
}
