# Generated Schema for T_CashFlow - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 11 - $Id$
extend type Query {
	T_CashFlowGet(Page: Int, Size: Int, Sort: String, Filter: String): T_CashFlowConnection!
}

extend type Mutation {
	T_CashFlowSave(Entity: T_CashFlowInput!): T_CashFlow!
	T_CashFlowSaveMany(Entities: [T_CashFlowInput!]!): [T_CashFlow!]!
	T_CashFlowDelete(UUs: [String!]!): Boolean!
}

type T_CashFlowConnection {
	Results: [T_CashFlow!]!
	PagingInfo: PagingInfo!
}

type T_CashFlow {
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Instance of the process
	AD_PInstance: AD_PInstance!
	# Rules for accounting
	C_AcctSchema: C_AcctSchema
	# Business Activity
	C_Activity: C_Activity
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# Marketing Campaign
	C_Campaign: C_Campaign
	C_CashPlanLine: C_CashPlanLine
	# Additional document charges
	C_Charge: C_Charge
	# Account Element
	C_ElementValue: C_ElementValue
	# Invoice Identifier
	C_Invoice: C_Invoice
	# Order
	C_Order: C_Order
	# Financial Project
	C_Project: C_Project
	CashFlowSource: AD_Ref_List
	CashFlowType: AD_Ref_List
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# End date of a date range
	DateTo: Date
	# Transaction Date
	DateTrx: Date!
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean!
	# This is a Sales Transaction
	IsSOTrx: Boolean!
	# Total line amount incl. Tax
	LineTotalAmt: BigDecimal
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String
	Probability: BigDecimal
	UU: ID!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
}

input T_CashFlowInput {
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Instance of the process
	AD_PInstance: ForeignEntityInput
	# Rules for accounting
	C_AcctSchema: ForeignEntityInput
	# Business Activity
	C_Activity: ForeignEntityInput
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# Marketing Campaign
	C_Campaign: ForeignEntityInput
	C_CashPlanLine: ForeignEntityInput
	# Additional document charges
	C_Charge: ForeignEntityInput
	# Account Element
	C_ElementValue: ForeignEntityInput
	# Invoice Identifier
	C_Invoice: ForeignEntityInput
	# Order
	C_Order: ForeignEntityInput
	# Financial Project
	C_Project: ForeignEntityInput
	CashFlowSource: ForeignEntityInput
	CashFlowType: ForeignEntityInput
	# End date of a date range
	DateTo: Date
	# Transaction Date
	DateTrx: Date
	# Optional short description of the record
	Description: String
	# The record is active in the system
	IsActive: Boolean
	# This is a Sales Transaction
	IsSOTrx: Boolean
	# Total line amount incl. Tax
	LineTotalAmt: BigDecimal
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	Probability: BigDecimal
	UU: ID
}
