# Generated Schema for Test - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 13 - $Id$
extend type Query {
	Test(UU: String!): Test
	TestGet(Page: Int, Size: Int, Sort: String, Filter: String): TestConnection!
}

extend type Mutation {
	TestSave(Entity: TestInput!): Test!
	TestSaveMany(Entities: [TestInput!]!): [Test!]!
	TestDelete(UUs: [String!]!): Boolean!
}

type TestConnection {
	Results: [Test!]!
	PagingInfo: PagingInfo!
}

type Test {
	Account_A: C_ValidCombination
	# Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within tenant
	AD_Org: AD_Org!
	# Database Table information
	AD_Table: AD_Table
	# Binary Data
	BinaryData: Binary
	# Identifies a Business Partner
	C_BPartner: C_BPartner
	# The Currency for this record
	C_Currency: C_Currency
	# Location or Address
	C_Location: C_Location
	# Payment identifier
	C_Payment: C_Payment
	# Unit of Measure
	C_UOM: C_UOM
	# Long Character Field
	CharacterData: String
	Color: String
	# Date this record was created
	Created: DateTime!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# The json field stores json data.
	JsonData: String
	# Warehouse Locator
	M_Locator: M_Locator
	# Product, Service, Item
	M_Product: M_Product
	# Alphanumeric identifier of the entity
	Name: String!
	# The document has been processed
	Processed: Boolean!
	Processing: Boolean!
	T_Amount: BigDecimal
	T_Date: Date
	T_DateTime: DateTime
	T_Integer: Int
	T_Number: BigDecimal
	T_Qty: BigDecimal
	# Timestamp with time zone
	T_Timestamp: DateTime
	UU: ID!
	# Used only for testing purposes
	TestVirtualQty: BigDecimal
	# Date this record was updated
	Updated: DateTime!
	# User who updated this records
	UpdatedBy: AD_User!
}

input TestInput {
	Account_A: ForeignEntityInput
	# Organizational entity within tenant
	AD_Org: ForeignEntityInput
	# Database Table information
	AD_Table: ForeignEntityInput
	# Binary Data
	BinaryData: Binary
	# Identifies a Business Partner
	C_BPartner: ForeignEntityInput
	# The Currency for this record
	C_Currency: ForeignEntityInput
	# Location or Address
	C_Location: ForeignEntityInput
	# Payment identifier
	C_Payment: ForeignEntityInput
	# Unit of Measure
	C_UOM: ForeignEntityInput
	# Long Character Field
	CharacterData: String
	Color: String
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# The json field stores json data.
	JsonData: String
	# Warehouse Locator
	M_Locator: ForeignEntityInput
	# Product, Service, Item
	M_Product: ForeignEntityInput
	# Alphanumeric identifier of the entity
	Name: String
	# The document has been processed
	Processed: Boolean
	Processing: Boolean
	T_Amount: BigDecimal
	T_Date: Date
	T_DateTime: DateTime
	T_Integer: Int
	T_Number: BigDecimal
	T_Qty: BigDecimal
	# Timestamp with time zone
	T_Timestamp: DateTime
	UU: ID
}
