# Generated Schema for WS_WebServiceMethod - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	WS_WebServiceMethodGet(page: Int, size: Int, sort: String, filter: String): WS_WebServiceMethodConnection!
}

extend type Mutation {
	WS_WebServiceMethodSave(entity: WS_WebServiceMethodInput!): WS_WebServiceMethod!
	WS_WebServiceMethodDelete(uuids: [String!]!): Boolean!
}

type WS_WebServiceMethodConnection {
	results: [WS_WebServiceMethod!]!
	pagingInfo: PagingInfo!
}

type WS_WebServiceMethod {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User!
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean!
	# Alphanumeric identifier of the entity
	Name: String!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User!
	# Search key for the record in the format required - must be unique
	Value: String!
	WS_WebService: WS_WebService
	ID: ID!
}

input WS_WebServiceMethodInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Optional short description of the record
	Description: String
	# Comment or Hint
	Help: String
	# The record is active in the system
	IsActive: Boolean
	# Alphanumeric identifier of the entity
	Name: String
	# Search key for the record in the format required - must be unique
	Value: String
	WS_WebService: ForeignEntityInput
	ID: ID
}
