# Generated Schema for WS_WebServiceFieldInput - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 8.2 - $Id$
extend type Query {
	WS_WebServiceFieldInputGet(page: Int, size: Int, sort: String, filter: String): WS_WebServiceFieldInputConnection!
}

extend type Mutation {
	WS_WebServiceFieldInputSave(entity: WS_WebServiceFieldInputInput!): WS_WebServiceFieldInput!
	WS_WebServiceFieldInputDelete(uuids: [String!]!): Boolean!
}

type WS_WebServiceFieldInputConnection {
	results: [WS_WebServiceFieldInput!]!
	pagingInfo: PagingInfo!
}

type WS_WebServiceFieldInput {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Column in the table
	AD_Column: AD_Column
	# Organizational entity within client
	AD_Org: AD_Org!
	# System Reference and Validation
	AD_Reference: AD_Reference
	# Required to specify, if data type is Table or List
	AD_Reference_Value: AD_Reference
	# Name of the column in the database
	ColumnName: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User
	IdentifierLogic: String
	# The record is active in the system
	IsActive: Boolean!
	# This column is part of the record identifier
	IsIdentifier: Boolean!
	# Should allow null value for identifiere field
	IsNullIdentifier: Boolean!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User
	ID: ID!
	WS_WebServiceType: WS_WebServiceType!
}

input WS_WebServiceFieldInputInput {
	# Column in the table
	AD_Column: ForeignEntityInput
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# System Reference and Validation
	AD_Reference: ForeignEntityInput
	# Required to specify, if data type is Table or List
	AD_Reference_Value: ForeignEntityInput
	# Name of the column in the database
	ColumnName: String
	IdentifierLogic: String
	# The record is active in the system
	IsActive: Boolean
	# This column is part of the record identifier
	IsIdentifier: Boolean
	# Should allow null value for identifiere field
	IsNullIdentifier: Boolean
	ID: ID
	WS_WebServiceType: ForeignEntityInput
}
