# Generated Schema for WS_WebService_Para - DO NOT CHANGE
#		@author Banda Health (generated) 
#		@version Release 7.1 - $Id$
extend type Query {
	WS_WebService_ParaGet(page: Int, size: Int, sort: String, filter: String): WS_WebService_ParaConnection!
}

extend type Mutation {
	WS_WebService_ParaSave(entity: WS_WebService_ParaInput!): WS_WebService_Para!
	WS_WebService_ParaSaveMany(entities: [WS_WebService_ParaInput!]!): [WS_WebService_Para!]!
	WS_WebService_ParaDelete(uuids: [String!]!): Boolean!
}

type WS_WebService_ParaConnection {
	results: [WS_WebService_Para!]!
	pagingInfo: PagingInfo!
}

type WS_WebService_Para {
	# Client/Tenant for this installation.
	AD_Client: AD_Client!
	# Organizational entity within client
	AD_Org: AD_Org!
	# Constant value
	ConstantValue: String
	# Date this record was created
	Created: Date!
	# User who created this records
	CreatedBy: AD_User
	# The record is active in the system
	IsActive: Boolean!
	ParameterName: String
	ParameterType: AD_Ref_List!
	# Date this record was updated
	Updated: Date!
	# User who updated this records
	UpdatedBy: AD_User
	UUID: ID!
	WS_WebServiceType: WS_WebServiceType!
}

input WS_WebService_ParaInput {
	# Organizational entity within client
	AD_Org: ForeignEntityInput
	# Constant value
	ConstantValue: String
	# The record is active in the system
	IsActive: Boolean
	ParameterName: String
	ParameterType: AD_Ref_ListInput
	UUID: ID
	WS_WebServiceType: ForeignEntityInput
}
