-- Add new processes
INSERT INTO ad_process (ad_process_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, value, name, description, help, accesslevel, entitytype, procedurename, isreport, isdirectprint, ad_reportview_id, classname, statistic_count, statistic_seconds, ad_printformat_id, workflowvalue, ad_workflow_id, isbetafunctionality, showhelp, jasperreport, ad_form_id, copyfromprocess, ad_process_uu, ad_ctxhelp_id, executiontype, allowmultipleexecution) VALUES ((SELECT MAX(ad_process_id) + 1 FROM ad_process), 0, 0, 'Y', '2021-05-13 15:50:34.100000', 100, '2021-05-13 15:50:34.100000', 100, 'Cashier Patient Transactions', 'Cashier Patient Transactions', 'Generate list of Patient Transactions with the Cashier on it', null, '3', 'U', null, 'Y', 'N', null, null, 0, 0, null, null, null, 'N', 'Y', 'Cashier Transactions.jasper', null, 'N', 'b09d9a23-ad0f-4eff-a7c6-4c1e2309c3d1', null, null, 'P') ON CONFLICT DO NOTHING;
INSERT INTO ad_process (ad_process_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, value, name, description, help, accesslevel, entitytype, procedurename, isreport, isdirectprint, ad_reportview_id, classname, statistic_count, statistic_seconds, ad_printformat_id, workflowvalue, ad_workflow_id, isbetafunctionality, showhelp, jasperreport, ad_form_id, copyfromprocess, ad_process_uu, ad_ctxhelp_id, executiontype, allowmultipleexecution) VALUES ((SELECT MAX(ad_process_id) + 1 FROM ad_process), 0, 0, 'Y', '2021-05-13 15:55:24.292000', 100, '2021-05-13 15:55:24.292000', 100, 'Cashier Transaction Differences', 'Cashier Transaction Differences', 'Generate list of Transactions by Cashier with differences displayed', null, '3', 'U', null, 'Y', 'N', null, null, 0, 0, null, null, null, 'N', 'Y', 'Cashier Difference.jasper', null, 'N', '226cdf47-9cde-43e8-b7ef-87b28d7ef2e2', null, null, 'P') ON CONFLICT DO NOTHING;

-- Add new buttons to ensure the processes show up on the UI
INSERT INTO bh_dbrdbtngrp_btn (bh_dbrdbtngrp_btn_id, ad_client_id, ad_infowindow_id, ad_org_id, ad_window_id, bh_dbrdbtngrp_btn_uu, buttonclassname, buttonhelptext, buttontext, created, createdby, description, iconclassname, isactive, lineno, name, updated, updatedby, bh_dbrdbtngrp_id, ad_process_id, ad_form_id, included_role_id) VALUES ((SELECT MAX(bh_dbrdbtngrp_btn_id) + 1 FROM bh_dbrdbtngrp_btn), 0, null, 0, null, 'e4631bd7-34a2-4977-83fc-5856d52e99ca', 'button app big', null, 'Cashier Patient Transactions', '2021-05-13 15:57:56.741000', 100, null, null, 'Y', 0, 'Cashier Patient Transactions', '2021-05-13 15:57:56.741000', 100, (SELECT bh_dbrdbtngrp_id FROM bh_dbrdbtngrp WHERE bh_dbrdbtngrp_uu='9b44ce0e-3113-4690-ad0b-92b95b34c741'), (SELECT ad_process_id FROM ad_process WHERE ad_process_uu='b09d9a23-ad0f-4eff-a7c6-4c1e2309c3d1'), null, null) ON CONFLICT DO NOTHING;
INSERT INTO bh_dbrdbtngrp_btn (bh_dbrdbtngrp_btn_id, ad_client_id, ad_infowindow_id, ad_org_id, ad_window_id, bh_dbrdbtngrp_btn_uu, buttonclassname, buttonhelptext, buttontext, created, createdby, description, iconclassname, isactive, lineno, name, updated, updatedby, bh_dbrdbtngrp_id, ad_process_id, ad_form_id, included_role_id) VALUES ((SELECT MAX(bh_dbrdbtngrp_btn_id) + 1 FROM bh_dbrdbtngrp_btn), 0, null, 0, null, 'be1c1dc8-cfe0-4e59-b088-079cd701c4d1', 'button app big', null, 'Cashier Transaction Differences', '2021-05-13 15:57:36.253000', 100, null, null, 'Y', 0, 'Cashier Transaction Differences', '2021-05-13 15:57:36.253000', 100, (SELECT bh_dbrdbtngrp_id FROM bh_dbrdbtngrp WHERE bh_dbrdbtngrp_uu='9b44ce0e-3113-4690-ad0b-92b95b34c741'), (SELECT ad_process_id FROM ad_process WHERE ad_process_uu='226cdf47-9cde-43e8-b7ef-87b28d7ef2e2'), null, null) ON CONFLICT DO NOTHING;

-- ALl other data updates for process will happen in the 2-pack

SELECT register_migration_script('202105131545_GO-1530.sql') FROM dual;
