-- ADD bh_voided_reason TO C_Invoice
ALTER TABLE c_invoice 
  ADD IF NOT EXISTS bh_voided_reason_id numeric(10) DEFAULT NULL;
  
  -- ADD new c_order column to AD_Column
  INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:37:59.744000', '2021-06-30 17:37:59.744000', 100, 100, 'Voided Reason', null, null, 0, 'U', 'bh_voided_reason_id', (SELECT ad_table_id FROM ad_table WHERE ad_table_uu = '45ae7b81-2051-47ee-a5ac-278dac67b7cb'), 19, null, null, 22, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (SELECT ad_element_id FROM ad_element WHERE ad_element_uu = '9f1bb1b0-353c-4f5c-a034-e5faea969b35'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '321de5a1-9c73-489b-a9b8-a2fe6d6c3695', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
  
    -- ADD new c_invoice column to AD_Column
  INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-06-30 17:37:59.744000', '2021-06-30 17:37:59.744000', 100, 100, 'Voided Reason', null, null, 0, 'U', 'bh_voided_reason_id', (SELECT ad_table_id FROM ad_table WHERE ad_table_uu = '98b87058-b549-4bd2-90e5-b1caa61b558c'), 19, null, null, 22, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (SELECT ad_element_id FROM ad_element WHERE ad_element_uu = '9f1bb1b0-353c-4f5c-a034-e5faea969b35'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '8391b1e0-35fe-476a-a449-454c5ce7283c', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
  
SELECT register_migration_script('202108021155_GO-1739.sql') FROM dual;
