ALTER TABLE m_movement
 ADD IF NOT EXISTS BH_From_Warehouse_ID numeric(10) DEFAULT NULL;
 
ALTER TABLE m_movement 
 ADD IF NOT EXISTS BH_To_Warehouse_ID numeric(10) DEFAULT NULL;
 
 ALTER TABLE m_warehouse 
 ADD IF NOT EXISTS BH_DefaultWarehouse char default 'N'::bpchar;
 
 -- set default warehouses in existing clients
 UPDATE m_warehouse SET BH_DefaultWarehouse = 'Y' WHERE name != 'Standard' AND isactive = 'Y' AND ad_client_id > 999999;
 
 INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:31.093000', 100, '2021-10-13 16:36:31.093000', 100, 'BH_From_Warehouse_ID', 'U', 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', null, null, null, null, null, 'bfe459e4-4fe9-4ffa-ae5d-395379879d51', null) ON CONFLICT DO NOTHING;
 
 INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:39.633000', 100, '2021-10-13 16:36:39.633000', 100, 'BH_To_Warehouse_ID', 'U', 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', null, null, null, null, null, '483c2345-05f5-4d08-9927-f3520126fae8', null) ON CONFLICT DO NOTHING;
 
  INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT max(ad_element_id) + 1 FROM ad_element), 0, 0, 'Y', '2021-10-13 16:36:31.093000', 100, '2021-10-13 16:36:31.093000', 100, 'BH_DefaultWarehouse', 'U', 'Default Warehouse', 'Default Warehouse', 'Default Warehouse', null, null, null, null, null, 'a644ce55-ced1-4041-86fe-543adfc85609', null) ON CONFLICT DO NOTHING;
 
 INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-13 16:36:57.118000', '2021-10-13 16:36:57.118000', 100, 100, 'BH_From_Warehouse_ID', 'BH_From_Warehouse_ID', null, 0, 'U', 'BH_From_Warehouse_ID', 323, 13, null, null, 50, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = 'bfe459e4-4fe9-4ffa-ae5d-395379879d51'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '1ff928cc-2b78-490d-b8a0-4c246d9ed0e5', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
 
 INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-13 16:42:47.023000', '2021-10-13 16:42:47.023000', 100, 100, 'BH_To_Warehouse_ID', 'BH_To_Warehouse_ID', null, 0, 'U', 'BH_To_Warehouse_ID', 323, 13, null, null, 50, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = '483c2345-05f5-4d08-9927-f3520126fae8'), null, 'N', 'N', null, null, null, 'N', 'Y', null, 'e92cdafc-3691-4bc7-98bb-700ec86bccfb', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
 

  INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT max(ad_column_id) + 1 FROM ad_column), 0, 0, 'Y', '2021-10-18 18:30:27.701000', '2021-10-18 18:30:27.701000', 100, 100, 'BH_DefaultWarehouse', 'BH_DefaultWarehouse', null, 0, 'U', 'BH_DefaultWarehouse', 190, 20, null, null, 1, null, 'N', 'N', 'N', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = 'a644ce55-ced1-4041-86fe-543adfc85609'), null, 'N', 'N', null, null, null, 'N', 'Y', null, '0ccc40a4-6b68-4a7a-a28d-224cbfb9a898', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;
  
  INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT max(ad_field_id) + 1 FROM ad_field), 0, 0, 'Y', '2021-10-18 18:33:44.162000', 100, '2021-10-18 18:38:25.779000', 100, 'Default Warehouse', 'Default Warehouse', null, 'Y', (SELECT AD_TAB_ID FROM AD_Tab WHERE AD_TAB_UU = 'b6ec1b3e-e8d4-44e3-bb34-70062bea155c'), (SELECT AD_Column_ID FROM AD_Column where ad_column_uu = '0ccc40a4-6b68-4a7a-a28d-224cbfb9a898'), null, 'Y', null, 0, 'N', 140, 0, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, '4e2c2550-e94a-45ef-ab18-bd6bcb659f05', null, 140, 'Y', 2, 1, 1, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N') ON CONFLICT DO NOTHING;
  
-- create transfer inventory window
INSERT INTO adempiere.ad_window (ad_window_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, windowtype, issotrx, entitytype, processing, ad_image_id, ad_color_id, isdefault, winheight, winwidth, isbetafunctionality, ad_window_uu, titlelogic) VALUES ((SELECT MAX(ad_window_id) + 1 FROM ad_window), 0, 0, 'Y', '2021-10-20 10:35:13.822000', 100, '2021-10-20 10:35:13.822000', 100, 'Transfer Inventory', null, null, 'T', 'Y', 'U', 'N', null, null, 'N', 0, 0, 'N', 'd3c84cad-7306-464d-85da-7e629846f8c0', null) ON CONFLICT DO NOTHING;  

-- create transfer inventory header tab
INSERT INTO adempiere.ad_tab (ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab, parent_column_id, ad_tab_uu, ad_ctxhelp_id, treedisplayedon, maxqueryrecords) VALUES ((SELECT MAX(ad_tab_id) + 1 FROM ad_tab), 0, 0, 'Y', '2021-10-20 10:35:53.966000', 100, '2021-10-20 10:35:53.966000', 100, 'Transfer Inventory', null, null, (SELECT AD_TABLE_ID FROM AD_TABLE WHERE Ad_table_uu = '89b7adc4-6313-4088-9ed9-c13ae3098b7e'), (SELECT AD_WINDOW_ID FROM AD_Window WHERE AD_WINDOW_UU = 'd3c84cad-7306-464d-85da-7e629846f8c0'), 10, 0, 'Y', 'N', 'N', 'N', null, 'N', null, null, null, null, 'N', null, 'N', null, null, 'N', 'U', null, null, null, 'Y', 'N', null, 'a8a1d256-efc4-4674-acce-3415c3a49f39', null, 'B', 0) ON CONFLICT DO NOTHING;

-- home screen configurations
INSERT INTO adempiere.bh_dbrdbtngrp_btn (bh_dbrdbtngrp_btn_id, ad_client_id, ad_infowindow_id, ad_org_id, ad_window_id, bh_dbrdbtngrp_btn_uu, buttonclassname, buttonhelptext, buttontext, created, createdby, description, iconclassname, isactive, lineno, name, updated, updatedby, bh_dbrdbtngrp_id, ad_process_id, ad_form_id, included_role_id) VALUES ((SELECT MAX(bh_dbrdbtngrp_btn_id) + 1 FROM bh_dbrdbtngrp_btn), 0, null, 0, (SELECT ad_window_id FROM ad_window where ad_window_uu = 'd3c84cad-7306-464d-85da-7e629846f8c0'), '1da38275-67b8-4bb6-b409-db37b2decc9f', 'button app big', 'Transfer Inventory', 'Transfer Inventory', '2021-10-20 10:36:40.358000', 100, '/transferinventory', null, 'Y', 0, 'Transfer Inventory', '2021-10-20 10:36:40.358000', 100, (SELECT bh_dbrdbtngrp_id FROM bh_dbrdbtngrp WHERE bh_dbrdbtngrp_uu = '963fb728-5261-48ea-a462-d74ace913dea'), null, null, null) ON CONFLICT DO NOTHING;

-- give inventory/pharmacy write access
INSERT INTO adempiere.ad_window_access (ad_window_id, ad_role_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, isreadwrite, ad_window_access_uu, bh_candeactivate) VALUES ((SELECT ad_window_id FROM ad_window where ad_window_uu = 'd3c84cad-7306-464d-85da-7e629846f8c0'), (select ad_role_id FROM ad_role where ad_role_uu = 'ec17fee0-a53a-4dbb-b946-423ce14880eb'), 0, 0, 'Y', '2021-10-20 10:36:40.358000', 100, '2021-10-20 10:36:40.358000', 100, 'Y', '0bb84633-d507-43f3-95d4-3397a438b786', 'N') ON CONFLICT DO NOTHING;


-- warehouse access window
CREATE TABLE IF NOT EXISTS adempiere.bh_role_warehouseaccess (
    ad_client_id numeric(10,0) NOT NULL,
    ad_org_id numeric(10,0) NOT NULL,
    m_warehouse_id numeric(10,0) NOT NULL,
    bh_role_warehouseaccess_uu character varying(36) DEFAULT NULL::character varying,
    created timestamp without time zone DEFAULT statement_timestamp() NOT NULL,
    createdby numeric(10,0) NOT NULL,
    isactive character(1) DEFAULT 'Y'::bpchar NOT NULL,
    isreadonly character(1) NOT NULL,
    updated timestamp without time zone DEFAULT statement_timestamp() NOT NULL,
    updatedby numeric(10,0) NOT NULL,
    bh_role_warehouseaccess_id numeric(10,0) NOT NULL,
    ad_role_id numeric(10,0) DEFAULT NULL::numeric,
    CONSTRAINT bh_role_warehouseaccess_isactive_check CHECK ((isactive = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))),
    CONSTRAINT bh_role_warehouseaccess_isreadonly_check CHECK ((isreadonly = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))),
    CONSTRAINT bh_role_warehouseaccess_uu_idx UNIQUE (bh_role_warehouseaccess_uu),
    CONSTRAINT ad_functaccess_client FOREIGN KEY (ad_client_id) REFERENCES adempiere.ad_client(ad_client_id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ad_functaccessorg FOREIGN KEY (ad_org_id) REFERENCES adempiere.ad_org(ad_org_id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT adrole_bhrolewarehouseaccess FOREIGN KEY (ad_role_id) REFERENCES adempiere.ad_role(ad_role_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT mwarehouse_bhrolewarehouseacce FOREIGN KEY (m_warehouse_id) REFERENCES adempiere.m_warehouse(m_warehouse_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED    
);

INSERT INTO adempiere.ad_table (ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable, iscentrallymaintained, ad_table_uu, processing, databaseviewdrop, copycomponentsfromview) VALUES ((SELECT MAX(AD_Table_id)+1 FROM ad_table), 0, 0, 'Y', '2021-11-04 20:33:26.948000', 100, '2021-11-04 20:33:26.948000', 100, 'BH_Role_WarehouseAccess', null, null, 'BH_Role_WarehouseAccess', 'N', '6', 'U', 139, null, 0, 'N', 'Y', 'N', 'N', 'Y', 'L', null, 'N', 'Y', '6f7ae0d8-47d3-4b53-8702-2b60235fa7db', 'N', 'N', 'N')  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT MAX(ad_element_id) +1 FROM ad_element), 0, 0, 'Y', '2021-11-04 20:33:27.215000', 100, '2021-11-04 20:33:27.215000', 100, 'BH_Role_WarehouseAccess_UU', 'U', 'BH_Role_WarehouseAccess_UU', 'BH_Role_WarehouseAccess_UU', null, null, null, null, null, null, '368b1571-da29-45ad-b32f-1cd4474b9035', null)  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, ad_element_uu, placeholder) VALUES ((SELECT MAX(ad_element_id) +1 FROM ad_element), 0, 0, 'Y', '2021-11-04 20:33:27.902000', 100, '2021-11-04 20:33:27.902000', 100, 'BH_Role_WarehouseAccess_ID', 'U', 'BH_Role_WarehouseAccess_ID', 'BH_Role_WarehouseAccess_ID', null, null, null, null, null, null, 'ba9c69a9-f18f-4724-bcf1-0f118153d2ff', null)  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.039000', '2021-11-04 20:33:27.039000', 100, 100, 'Client', 'Client/Tenant for this installation.', 'A Client is a company or a legal entity. You cannot share data between Clients. Tenant is a synonym for Client.', 1, 'U', 'AD_Client_ID', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 19, null, 129, 22, '@AD_Client_ID@', 'N', 'N', 'Y', 'N', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 102, null, 'Y', 'N', null, null, null, 'N', 'Y', null, 'e5f74d71-b7da-4e7b-ab50-f391ab20b3c2', 'N', null, 'N', 'N', null, 'ad_functaccess_client', 'N', null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.114000', '2021-11-04 20:33:27.114000', 100, 100, 'Organization', 'Organizational entity within client', 'An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.', 1, 'U', 'AD_Org_ID', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 19, null, 104, 22, '@AD_Org_ID@', 'N', 'N', 'Y', 'N', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 113, null, 'Y', 'N', null, null, null, 'N', 'Y', null, 'f409c5cb-1192-4431-bc39-195e8886d15b', 'N', null, 'N', 'N', null, 'ad_functaccessorg', 'N', null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.159000', '2021-11-04 20:33:27.159000', 100, 100, 'Warehouse', 'Storage Warehouse and Service Point', 'The Warehouse identifies a unique Warehouse where products are stored or Services are provided.', 1, 'U', 'M_Warehouse_ID', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 19, null, null, 22, null, 'N', 'Y', 'Y', 'N', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 459, null, 'Y', 'N', null, null, null, 'N', 'Y', null, '0d71d4b7-ea6f-492d-8ebd-372fa8ffbb5e', 'Y', null, 'N', 'N', null, 'MWarehouse_BHRoleWarehouseAcce', 'C', null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.253000', '2021-11-04 20:33:27.253000', 100, 100, 'BH_Role_WarehouseAccess_UU', null, null, 1, 'U', 'BH_Role_WarehouseAccess_UU', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 10, null, null, 36, null, 'N', 'N', 'N', 'Y', null, 'N', null, 'N', 'N', null, null, null, null, 'N', (select ad_element_id from ad_element where ad_element_uu = '368b1571-da29-45ad-b32f-1cd4474b9035'), null, 'Y', 'N', null, null, null, 'N', 'Y', null, '8e280b62-9082-41ca-b613-e9ef7e6cd0a3', 'N', null, 'N', 'N', null, null, 'N', null, null, 'N')  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.368000', '2021-11-04 20:33:27.368000', 100, 100, 'Created', 'Date this record was created', 'The Created field indicates the date that this record was created.', 1, 'U', 'Created', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 16, null, null, 7, 'SYSDATE', 'N', 'N', 'Y', 'N', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 245, null, 'Y', 'N', null, null, null, 'N', 'Y', null, '66d99d50-1904-4cae-a832-7fd935203da4', 'N', null, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.500000', '2021-11-04 20:33:27.500000', 100, 100, 'Created By', 'User who created this records', 'The Created By field indicates the user who created this record.', 1, 'U', 'CreatedBy', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 30, 110, null, 22, null, 'N', 'N', 'Y', 'N', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 246, null, 'Y', 'N', null, null, null, 'N', 'Y', null, '7ffc6dae-ebe8-4706-aaa9-92358930eea6', 'N', null, 'N', 'N', null, null, 'D', null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.617000', '2021-11-04 20:33:27.617000', 100, 100, 'Active', 'The record is active in the system', 'There are two methods of making records unavailable in the system: One is to delete the record, the other is to de-activate the record. A de-activated record is not available for selection, but available for reports.
There are two reasons for de-activating and not deleting records:
(1) The system requires the record for audit purposes.
(2) The record is referenced by other records. E.g., you cannot delete a Business Partner, if there are invoices for this partner record existing. You de-activate the Business Partner and prevent that this record is used for future entries.', 1, 'U', 'IsActive', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 20, null, null, 1, 'Y', 'N', 'N', 'Y', 'Y', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 348, null, 'Y', 'N', null, null, null, 'N', 'Y', null, '113e05f9-1c9e-4c96-ac59-397640017956', 'N', null, 'N', 'N', null, null, 'N', null, null, 'N')  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.700000', '2021-11-04 20:33:27.700000', 100, 100, 'Read Only', 'Field is read only', 'The Read Only indicates that this field may only be Read.  It may not be updated.', 0, 'U', 'IsReadOnly', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 20, null, null, 1, null, 'N', 'N', 'Y', 'Y', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 405, null, 'Y', 'N', null, null, null, 'N', 'Y', null, '25784a48-215d-4278-8fa2-92700aacc820', 'Y', null, 'N', 'N', null, null, 'N', null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.763000', '2021-11-04 20:33:27.763000', 100, 100, 'Updated', 'Date this record was updated', 'The Updated field indicates the date that this record was updated.', 1, 'U', 'Updated', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 16, null, null, 7, 'SYSDATE', 'N', 'N', 'Y', 'N', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 607, null, 'Y', 'N', null, null, null, 'N', 'Y', null, '9c9cdf6c-62e2-49b0-93db-031ba9f4d034', 'N', null, 'N', 'N', null, null, 'N', null, null, 'N')  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.835000', '2021-11-04 20:33:27.835000', 100, 100, 'Updated By', 'User who updated this records', 'The Updated By field indicates the user who updated this record.', 1, 'U', 'UpdatedBy', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 30, 110, null, 22, null, 'N', 'N', 'Y', 'N', null, 'N', null, 'N', 'N', null, null, null, null, 'N', 608, null, 'Y', 'N', null, null, null, 'N', 'Y', null, 'ae3cce6a-7331-4b2b-a853-d0beb4d0a677', 'N', null, 'N', 'N', null, null, 'D', null, null, 'N')  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:27.956000', '2021-11-04 20:33:27.956000', 100, 100, 'BH_Role_WarehouseAccess_ID', null, null, 0, 'U', 'BH_Role_WarehouseAccess_ID', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 13, null, null, 22, null, 'N', 'N', 'Y', 'Y', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', (SELECT AD_Element_Id from ad_element where ad_element_uu = 'ba9c69a9-f18f-4724-bcf1-0f118153d2ff'), null, 'Y', 'N', null, null, null, 'N', 'Y', null, '4e433e2f-87b1-40d5-852e-0bb5f1daa696', 'Y', 0, 'N', 'N', null, null, 'N', null, null, 'N')  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_column (ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern, ad_column_uu, isallowcopy, seqnoselection, istoolbarbutton, issecure, ad_chart_id, fkconstraintname, fkconstrainttype, pa_dashboardcontent_id, placeholder, ishtml) VALUES ((SELECT MAX(ad_column_id)+1 FROM AD_COLUMN), 0, 0, 'Y', '2021-11-04 20:33:28.020000', '2021-11-04 20:33:28.020000', 100, 100, 'Role', 'Responsibility Role', 'The Role determines security and access a user who has this Role will have in the System.', 0, 'U', 'AD_Role_ID', (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 19, null, null, 22, null, 'N', 'Y', 'N', 'N', null, 'N', 0, 'N', 'N', null, null, null, null, 'N', 123, null, 'Y', 'N', null, null, null, 'N', 'Y', null, '4501f81e-473f-4a41-9b59-401c934c27ef', 'Y', 0, 'N', 'N', null, 'ADRole_BHRoleWarehouseAccess', 'C', null, null, 'N')  ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_tab (ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab, parent_column_id, ad_tab_uu, ad_ctxhelp_id, treedisplayedon, maxqueryrecords) VALUES ((SELECT MAX(AD_TAB_ID)+1 FROM AD_Tab), 0, 0, 'Y', '2021-11-04 20:33:28.101000', 100, '2021-11-04 20:33:28.101000', 100, 'Warehouse Access', null, null, (SELECT AD_Table_ID FROM AD_Table where ad_table_uu='6f7ae0d8-47d3-4b53-8702-2b60235fa7db'), 111, 120, 1, 'Y', 'N', 'N', 'N', (select ad_column_id from ad_column where ad_column_uu='0d71d4b7-ea6f-492d-8ebd-372fa8ffbb5e'), 'N', null, null, null, null, 'N', null, 'N', null, null, 'N', 'U', null, null, '@IsMasterRole@=N', 'Y', 'N', null, '50d5bf3d-3939-403d-9b4d-69af90b7d1e1', null, 'B', 0) ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT MAX(AD_Field_ID)+1 FROM AD_Field), 0, 0, 'Y', '2021-11-04 20:33:28.167000', 100, '2021-11-04 20:33:28.167000', 100, 'BH_Role_WarehouseAccess_UU', null, null, 'Y', (select ad_tab_id from ad_tab where ad_tab_uu='50d5bf3d-3939-403d-9b4d-69af90b7d1e1'), (select ad_column_id from ad_column where ad_column_uu = '8e280b62-9082-41ca-b613-e9ef7e6cd0a3'), null, 'N', null, 36, 'N', 0, null, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, '1e19a9bc-70ba-467f-b9ad-dfb2c2d2cf47', null, null, 'N', 1, 1, 2, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT MAX(AD_Field_ID)+1 FROM AD_Field), 0, 0, 'Y', '2021-11-04 20:33:28.248000', 100, '2021-11-04 20:33:28.248000', 100, 'Client', 'Client/Tenant for this installation.', 'A Client is a company or a legal entity. You cannot share data between Clients. Tenant is a synonym for Client.', 'Y', (select ad_tab_id from ad_tab where ad_tab_uu='50d5bf3d-3939-403d-9b4d-69af90b7d1e1'), (select ad_column_id from ad_column where ad_column_uu = 'e5f74d71-b7da-4e7b-ab50-f391ab20b3c2'), null, 'Y', null, 22, 'Y', 10, null, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, '5a06d1c0-d080-4803-9ac6-f903d1606b16', null, 10, 'Y', 1, 1, 2, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT MAX(AD_Field_ID)+1 FROM AD_Field), 0, 0, 'Y', '2021-11-04 20:33:28.311000', 100, '2021-11-04 20:33:28.311000', 100, 'Organization', 'Organizational entity within client', 'An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.', 'Y', (select ad_tab_id from ad_tab where ad_tab_uu='50d5bf3d-3939-403d-9b4d-69af90b7d1e1'), (select ad_column_id from ad_column where ad_column_uu = 'f409c5cb-1192-4431-bc39-195e8886d15b'), null, 'Y', null, 22, 'N', 20, null, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, '4955452d-c05a-4bd8-8922-c2bed5c591a7', 'Y', null, 'N', 4, 1, 2, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT MAX(AD_Field_ID)+1 FROM AD_Field), 0, 0, 'Y', '2021-11-04 20:33:28.372000', 100, '2021-11-04 20:33:28.372000', 100, 'Role', 'Responsibility Role', 'The Role determines security and access a user who has this Role will have in the System.', 'Y', (select ad_tab_id from ad_tab where ad_tab_uu='50d5bf3d-3939-403d-9b4d-69af90b7d1e1'), (select ad_column_id from ad_column where ad_column_uu = 'f4501f81e-473f-4a41-9b59-401c934c27ef'), null, 'Y', null, 0, 'Y', 30, null, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, 'f002d9d5-f8ca-4122-8596-c1bd13490c6b', null, 60, 'Y', 1, 1, 2, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT MAX(AD_Field_ID)+1 FROM AD_Field), 0, 0, 'Y', '2021-11-04 20:33:28.443000', 100, '2021-11-04 20:33:28.443000', 100, 'Warehouse', 'Storage Warehouse and Service Point', 'The Warehouse identifies a unique Warehouse where products are stored or Services are provided.', 'Y', (select ad_tab_id from ad_tab where ad_tab_uu='50d5bf3d-3939-403d-9b4d-69af90b7d1e1'), (select ad_column_id from ad_column where ad_column_uu = 'f0d71d4b7-ea6f-492d-8ebd-372fa8ffbb5e'), null, 'Y', null, 22, 'N', 40, 1, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, '587d4f01-6d36-478a-b9ab-84d57dee6c6e', null, 50, 'Y', 1, 1, 2, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N') ON CONFLICT DO NOTHING;

INSERT INTO adempiere.ad_field (ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass, ad_field_uu, isallowcopy, seqnogrid, isdisplayedgrid, xposition, numlines, columnspan, isquickentry, isupdateable, isalwaysupdateable, mandatorylogic, readonlylogic, istoolbarbutton, isadvancedfield, isdefaultfocus, vformat, ad_labelstyle_id, ad_fieldstyle_id, placeholder, isquickform) VALUES ((SELECT MAX(AD_Field_ID)+1 FROM AD_Field), 0, 0, 'Y', '2021-11-04 20:33:28.508000', 100, '2021-11-04 20:33:28.508000', 100, 'Active', 'The record is active in the system', 'There are two methods of making records unavailable in the system: One is to delete the record, the other is to de-activate the record. A de-activated record is not available for selection, but available for reports.
There are two reasons for de-activating and not deleting records:
(1) The system requires the record for audit purposes.
(2) The record is referenced by other records. E.g., you cannot delete a Business Partner, if there are invoices for this partner record existing. You de-activate the Business Partner and prevent that this record is used for future entries.', 'Y', (select ad_tab_id from ad_tab where ad_tab_uu='50d5bf3d-3939-403d-9b4d-69af90b7d1e1'), (select ad_column_id from ad_column where ad_column_uu = 'f113e05f9-1c9e-4c96-ac59-397640017956'), null, 'Y', null, 1, 'N', 50, null, 'N', 'N', 'N', 'N', 'U', null, null, null, null, null, null, null, null, '1151c117-a71f-46f2-8fef-8febb1133c98', null, 40, 'Y', 2, 1, 2, 'N', null, null, null, null, null, 'N', 'N', null, null, null, null, 'N') ON CONFLICT DO NOTHING;

SELECT register_migration_script('202110131559_GO-1806.sql') FROM dual;
