INSERT INTO ad_process (ad_process_id,
                        ad_client_id,
                        ad_org_id,
                        isactive,
                        created,
                        createdby,
                        updated,
                        updatedby,
                        value,
                        name,
                        description,
                        help,
                        accesslevel,
                        entitytype,
                        procedurename,
                        isreport,
                        isdirectprint,
                        ad_reportview_id,
                        classname,
                        statistic_count,
                        statistic_seconds,
                        ad_printformat_id,
                        workflowvalue,
                        ad_workflow_id,
                        isbetafunctionality,
                        isserverprocess,
                        showhelp,
                        jasperreport,
                        ad_form_id,
                        copyfromprocess,
                        ad_process_uu,
                        ad_ctxhelp_id,
                        executiontype,
                        allowmultipleexecution,
                        filenamepattern)
VALUES ((SELECT MAX(ad_process_id) + 1
         FROM ad_process),
        0,
        0,
        'Y',
        '2025-03-13 11:42:01.779000',
        100,
        '2025-03-13 11:44:09.571000',
        100,
        '10000000',
        'MoH706 Laboratory Test Summary',
        null,
        null,
        '3',
        'U',
        null,
        'Y',
        'N',
        null,
        null,
        0,
        0,
        null,
        null,
        null,
        'N',
        null,
        'Y',
        'moh-706/moh706Main.jasper',
        null,
        'N',
        '83378587-d80f-4c79-874b-5cdc64893b77',
        null,
        null,
        'P',
        null);

INSERT INTO ad_process_para (ad_process_para_id,
                             ad_client_id,
                             ad_org_id,
                             isactive,
                             created,
                             createdby,
                             updated,
                             updatedby,
                             name,
                             description,
                             help,
                             ad_process_id,
                             seqno,
                             ad_reference_id,
                             ad_reference_value_id,
                             ad_val_rule_id,
                             columnname,
                             iscentrallymaintained,
                             fieldlength,
                             ismandatory,
                             isrange,
                             defaultvalue,
                             defaultvalue2,
                             vformat,
                             valuemin,
                             valuemax,
                             ad_element_id,
                             entitytype,
                             readonlylogic,
                             displaylogic,
                             ad_process_para_uu,
                             isencrypted,
                             mandatorylogic,
                             placeholder,
                             placeholder2,
                             isautocomplete,
                             ad_fieldgroup_id,
                             query,
                             daterangeoption,
                             isshownegatebutton)
VALUES ((SELECT MAX(ad_process_para_id) + 1
         FROM ad_process_para),
        0,
        0,
        'Y',
        '2025-03-13 11:47:21.035000',
        100,
        '2025-03-13 11:47:21.035000',
        100,
        'End Date',
        null,
        null,
        (SELECT ad_process_id from ad_process where ad_process_uu = '83378587-d80f-4c79-874b-5cdc64893b77'),
        20,
        15,
        null,
        null,
        'End Date',
        'N',
        0,
        'N',
        'N',
        null,
        null,
        null,
        null,
        null,
        null,
        'U',
        null,
        null,
        '0b1174a0-effe-487a-8a39-060a7987ba25',
        'N',
        null,
        null,
        null,
        'N',
        null,
        null,
        'D',
        'N');

INSERT INTO ad_process_para (ad_process_para_id,
                             ad_client_id,
                             ad_org_id,
                             isactive,
                             created,
                             createdby,
                             updated,
                             updatedby,
                             name,
                             description,
                             help,
                             ad_process_id,
                             seqno,
                             ad_reference_id,
                             ad_reference_value_id,
                             ad_val_rule_id,
                             columnname,
                             iscentrallymaintained,
                             fieldlength,
                             ismandatory,
                             isrange,
                             defaultvalue,
                             defaultvalue2,
                             vformat,
                             valuemin,
                             valuemax,
                             ad_element_id,
                             entitytype,
                             readonlylogic,
                             displaylogic,
                             ad_process_para_uu,
                             isencrypted,
                             mandatorylogic,
                             placeholder,
                             placeholder2,
                             isautocomplete,
                             ad_fieldgroup_id,
                             query,
                             daterangeoption,
                             isshownegatebutton)
VALUES ((SELECT MAX(ad_process_para_id) + 1
         FROM ad_process_para),
        0,
        0,
        'Y',
        '2025-03-13 11:46:52.581000',
        100,
        '2025-03-13 11:46:52.581000',
        100,
        'Begin Date',
        null,
        null,
        (SELECT ad_process_id from ad_process where ad_process_uu = '83378587-d80f-4c79-874b-5cdc64893b77'),
        10,
        15,
        null,
        null,
        'Begin Date',
        'N',
        0,
        'N',
        'N',
        null,
        null,
        null,
        null,
        null,
        null,
        'U',
        null,
        null,
        '06ae7fbc-9063-4d24-b62d-03ffc861be9f',
        'N',
        null,
        null,
        null,
        'N',
        null,
        null,
        'D',
        'N');

-- Register the script and be done
SELECT register_migration_script('202503131149_GO-2867.sql')
FROM dual;